1.  (a) Positive association: mammals with longer gestation periods tend to live longer as well. (b) Association would still be positive. (c) No, they are not independent. See part (a).

1.  The graph below shows a ramp up period. There may also be a period of exponential growth at the start before the size of the petri dish becomes a factor in slowing growth.

    ```{r out.width="20%"}
    set.seed(2406)
    par(mar = c(1.5, 1.5, 0.5, 0.5), mgp = c(0.3, 0.7, 0),  mfrow = c(1,1), cex.lab = 1.5)
    curve(-1*dexp(x, rate = 4), lwd = 2,
          xlab = "time", ylab = "number of bacteria cells", axes = FALSE)
    box()
    ```

1.  (a) Population mean, $\mu_{2007} = 52$; sample mean, $\bar{x}_{2008} = 58$. (b) Population mean, $\mu_{2001} = 3.37$; sample mean, $\bar{x}_{2012} = 3.59$.

1.  Any 10 employees whose average number of days off is between the minimum and the mean number of days off for the entire workforce at this plant.

1.  (a) Dist B has a higher mean since $20 > 13$, and a higher standard deviation  since 20 is further from the rest of the data than 13. (b) Dist A has a higher mean since $-20 > -40$, and Dist B has a higher standard deviation since -40 is farther away from the rest of the data than -20. (c) Dist B has a higher mean since all values in this Dist Are higher than those in Dist A, but both distribution have the same standard deviation  since they are equally variable around their respective means. (d) Both distributions have the same mean since they're both centered at 300, but  Dist B has a higher standard deviation since the observations are farther from the mean than in Dist A.

1.  (a) About 30. (b) Since the distribution is right skewed the mean is higher than the median. (c) Q1: between 15 and 20, Q3: between 35 and 40, IQR: about 20. (d) Values that are considered to be unusually low or high lie more than 1.5$\times$IQR away from the quartiles. Upper fence: Q3 + 1.5 $\times$ IQR = $37.5 + 1.5 \times 20 = 67.5$; Lower fence: Q1 - 1.5 $\times$ IQR = $17.5 + 1.5 \times 20 =  -12.5$; The lowest AQI recorded is not lower than 5 and the highest AQI recorded is not higher than 65, which are both within the fences. Therefore none of the days in this sample would be considered to have an unusually low or high AQI.

1.  The histogram shows that the distribution is bimodal, which is not apparent in the box plot. The box plot makes it easy to identify more precise values of observations outside of the whiskers.

1.  (a) The distribution of number of pets per household is likely right skewed as there is a natural boundary at 0 and only a few people have many pets. Therefore the center would be best described by the median, and variability would be best described by the IQR. (b) The distribution of number of distance to work is likely right skewed as there is a natural boundary at 0 and only a few people live a very long distance from work. Therefore the center would be best described by the median, and variability would be best described by the IQR. (c) The distribution of heights of males is likely symmetric. Therefore the center would be best described by the mean, and variability would be best described by the standard deviation.

1.  (a) The median is a much better measure of the typical amount earned
    by these 42 people. The mean is much higher than the income of 40 of
    the 42 people. This is because the mean is an arithmetic average and
    gets affected by the two extreme observations. The median does not
    get effected as much since it is robust to outliers. (b) The IQR is
    a much better measure of variability in the amounts earned by nearly
    all of the 42 people. The standard deviation gets affected greatly
    by the two high salaries, but the IQR is robust to these extreme
    observations.

1.  (a) The distribution is unimodal and symmetric with a mean of about 25 minutes and a standard deviation of about 5 minutes. There does not appear to be any counties with unusually high or low mean travel times. Since the distribution is already unimodal and symmetric, a log transformation is not necessary. (b) Answers will vary. There are pockets of longer travel time around DC, Southeastern NY, Chicago, Minneapolis, Los Angeles, and many other big cities. There is also a large section of shorter average commute times that overlap with farmland in the Midwest. Many farmers' homes are adjacent to their farmland, so their commute would be brief, which may explain why the average commute time for these counties is relatively low.
