# Introduction to Linear Models {#intro-linear-models}


::: {.uptohere}
This chapter is currently under construction.
:::


::: {.chapterintro}
Chapter intro
:::


## Visual summaries of data: scatterplot, side-by-side boxplots, histogram, density plot, box plot (lead out with multivariate, follow with univariate)

## Describing distributions: correlation, central tendency, variability, skew, modality

## Num vs. num - SLR

- correlation
- Line fitting, residuals, and correlation
- Fitting a line by least squares regression
- Types of outliers in linear regression
	
	
## Chapter review {#chp3-review}

### Terms

We introduced the following terms in the chapter. 
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate. 
However you should be able to easily spot them as **bolded text**.

```{r eval = FALSE}
make_terms_table(terms_chp_3)
```

### Chapter exercises