# Multivariable and logistic models {#multi-logistic-models}

::: {.uptohere}
This chapter is currently under construction.
:::

::: {.chapterintro}
Chapter intro
:::

## Num vs. whatever - MLR

- Introduction to multiple regression

## Parallel slopes

## Hint at interaction, planes, and parallel planes but not quantify

- Visualization of higher-dimensional models (rgl demo)

## Logistic regression

- Binary vs. num/whatever
- Three scales interpretation (e.g. probability, odds, log-odds)
- “parallel” logistic curves? 

## Chapter review {#chp4-review}

### Terms

We introduced the following terms in the chapter. 
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate. 
However you should be able to easily spot them as **bolded text**.

```{r eval = FALSE}
make_terms_table(terms_chp_4)
```
