# Inference for numerical data {#inference-num}

```{block2, type="uptohere", echo=TRUE}
The content in this chapter is currently just placeholder. We will remove this banner once the chapter content has been updated and ready for review.
```

## One-sample means

- Bootstrap (for means, medians)
- t-distribution

## Paired data {#paired-data}

- Randomization 
- Bootstrap
- t-distribution

## Difference of two means

- Randomization 
- Bootstrap
- t-distribution

## Comparing many means with ANOVA (special topic, include simulation version)

- Randomization 
- t-distribution


## Chapter 7 review {#chp7-review}

### Terms

We introduced the following terms in the chapter. 
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate. 
However you should be able to easily spot them as **bolded text**.

```{r eval = FALSE}
make_terms_table(terms_chp_7)
```