# Inference for regression {#inference-reg}

```{block2, type="uptohere", echo=TRUE}
The content in this chapter is currently just placeholder. We will remove this banner once the chapter content has been updated and ready for review.
```

## Inference for linear regression

- Randomization
- Bootstrap for regression coefficients
- t-distribution for regression coefficients
- Model Comparison: Occam’s Razor and $R^2 > R^2_{adj}$

## Checking model assumptions using graphs

- L-I-N-E

## Inference for multiple regression

- residuals vs. fitted instead of residuals vs. x

## Inference for logistic regression

- t-dist only

## Chapter 8 review {#chp8-review}

### Terms

We introduced the following terms in the chapter. 
If you're not sure what some of these terms mean, we recommend you go back in the text and review their definitions.
We are purposefully presenting them in alphabetical order, instead of in order of appearance, so they will be a little more challenging to locate. 
However you should be able to easily spot them as **bolded text**.

```{r eval = FALSE}
make_terms_table(terms_chp_8)
```
