# Exercise solutions {#exercise-solutions}

::: {.section-exercise-solution}

## Chapter 1

### Case study: stents and strokes

```{r child="01/short-answers/01-01-case-study-short-answers.Rmd"}
```

### Data basics

```{r child="01/short-answers/01-02-data-basics-short-answers.Rmd"}
```

### Sampling principles and strategies

```{r child="01/short-answers/01-03-sampling-short-answers.Rmd"}
```

### Experiments

```{r child="01/short-answers/01-04-experiments-short-answers.Rmd"}
```

### Chapter review

```{r child="01/short-answers/01-05-chapter-review-short-answers.Rmd"}
```


## Chapter 2

### Exploring numerical data

```{r child="02/short-answers/02-01-numerical-data-short-answers.Rmd"}
```

### Exploring categorical data

```{r child="02/short-answers/02-02-categorical-data-short-answers.Rmd"}
```

### Effective data visualization

```{r child="02/short-answers/02-03-effective-dataviz-short-answers.Rmd", eval=FALSE}
```

### Case study: malaria vaccine

```{r child="02/short-answers/02-04-case-study-short-answers.Rmd"}
```

### Chapter review

```{r child="02/short-answers/02-05-chapter-review-short-answers.Rmd"}
```

::: 
