# Applications: Infer {#inference-applications}

## Case study: General Social Survey {#case-study-gss}

The data for the first part of the lab come from the General Social Survey, <https://gss.norc.org/About-The-GSS>

> The General Social Survey (GSS) is a nationally representative survey of adults in the United States conducted since 1972.
> The GSS collects data on contemporary American society in order tomonitor and explain trends in opinions, attitudes and behaviors.
> The GSS has adopted questions from earlier surveys which allows researchers to conduct comparisons for up to 80 years.

Consider the adults in the United States to be the population of interest.
The survey data is a representative sample that we can use to address questions about the population.

This case study will perform a series of hypothesis tests and confidence intervals using a particular package called **infer** in the R software.
The General Social Survey dataset is called `gss` and is available in the **infer** package.

### Confidence interval for proportion

### Two sample t-test

### Chi-squared analysis

## Interactive R tutorials {#inference-tutorials}

Navigate the concepts you've learned in this chapter in R using the following self-paced tutorials.
All you need is your browser to get started!

::: {.alltutorials}
[Tutorial 6: Inference for categorical responses](https://openintrostat.github.io/ims-tutorials/06-inference-for-categorical-responses/)
:::

::: {.singletutorial}
[Tutorial 6 - Lesson 1: Inference for a single proportion](https://openintro.shinyapps.io/ims-06-inference-for-categorical-responses-01/)
:::

::: {.singletutorial}
[Tutorial 6 - Lesson 2: Hypothesis tests to compare proportions](https://openintro.shinyapps.io/ims-06-inference-for-categorical-responses-02/)
:::

::: {.singletutorial}
[Tutorial 6 - Lesson 3: Chi-squared test of independence](https://openintro.shinyapps.io/ims-06-inference-for-categorical-responses-03/)
:::

::: {.singletutorial}
[Tutorial 6 - Lesson 4: Chi-squared goodness of fit Test](https://openintro.shinyapps.io/ims-06-inference-for-categorical-responses-04/)
:::

::: {.alltutorials}
[Tutorial 7: Inference for categorical responses](https://openintrostat.github.io/ims-tutorials/07-inference-for-numerical-responses/)
:::

::: {.singletutorial}
[Tutorial 7 - Lesson 1: Bootstrapping for estimating a parameter](https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-01/)
:::

::: {.singletutorial}
[Tutorial 7 - Lesson 2: Introducing the t-distribution](https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-02/)
:::

::: {.singletutorial}
[Tutorial 7 - Lesson 3: Inference for difference in two means](https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-03/)
:::

::: {.singletutorial}
[Tutorial 7 - Lesson 4: Comparing many means](https://openintro.shinyapps.io/ims-07-inference-for-numerical-responses-04/)
:::

You can also access the full list of tutorials supporting this book [here](https://openintrostat.github.io/ims-tutorials/).

## R labs {#inference-labs}

Further apply the concepts you've learned in this chapter in R with computational labs that walk you through a data analysis case study.

::: {.singlelab}
[Inference for categorical responses - Texting while driving](https://openintro.shinyapps.io/inf_for_categorical_data/)
:::

::: {.singlelab}
[Inference for numerical responses - Youth Risk Behavior Surveillance System](http://openintrostat.github.io/oilabs-tidy/07_inf_for_numerical_data/inf_for_numerical_data.html)
:::

::: {.alllabs}
[Full list of labs supporting OpenIntro::Introduction to Modern Statistics](http://openintrostat.github.io/oilabs-tidy/)
:::
