# Exercise solutions {#exercise-solutions}

```{r}
#| include: false
source("_common.R")
```

## Chapter 1 {#exercise-solutions-01 .unlisted}

::: exercises-solution
{{< include exercises/_01-sa-data-hello.qmd >}}
:::

## Chapter 2 {#exercise-solutions-02 .unlisted}

\vspace{-2mm}

::: exercises-solution
{{< include exercises/_02-sa-data-design.qmd >}}
:::

## Chapter 3 {#exercise-solutions-03 .unlisted}

Application chapter, no exercises.

## Chapter 4 {#exercise-solutions-04 .unlisted}

::: exercises-solution
{{< include exercises/_04-sa-explore-categorical.qmd >}}
:::

## Chapter 5 {#exercise-solutions-05 .unlisted}

::: exercises-solution
{{< include exercises/_05-sa-explore-numerical.qmd >}}
:::

## Chapter 6 {#exercise-solutions-06 .unlisted}

Application chapter, no exercises.

## Chapter 7 {#exercise-solutions-07 .unlisted}

::: exercises-solution
{{< include exercises/_07-sa-model-slr.qmd >}}
:::

## Chapter 8 {#exercise-solutions-08 .unlisted}

::: exercises-solution
{{< include exercises/_08-sa-model-mlr.qmd >}}
:::

## Chapter 9 {#exercise-solutions-09 .unlisted}

::: exercises-solution
{{< include exercises/_09-sa-model-logistic.qmd >}}
:::

## Chapter 10 {#exercise-solutions-10 .unlisted}

Application chapter, no exercises.

## Chapter 11 {#exercise-solutions-11 .unlisted}

::: exercises-solution
{{< include exercises/_11-sa-foundations-randomization.qmd >}}
:::

## Chapter 12 {#exercise-solutions-12 .unlisted}

::: exercises-solution
{{< include exercises/_12-sa-foundations-bootstrapping.qmd >}}
:::

## Chapter 13 {#exercise-solutions-13 .unlisted}

::: exercises-solution
{{< include exercises/_13-sa-foundations-mathematical.qmd >}}
:::

## Chapter 14 {#exercise-solutions-14 .unlisted}

::: exercises-solution
{{< include exercises/_14-sa-foundations-errors.qmd >}}
:::

## Chapter 15 {#exercise-solutions-15 .unlisted}

Application chapter, no exercises.

## Chapter 16 {#exercise-solutions-16 .unlisted}

::: exercises-solution
{{< include exercises/_16-sa-inference-one-prop.qmd >}}
:::

## Chapter 17 {#exercise-solutions-17 .unlisted}

::: exercises-solution
{{< include exercises/_17-sa-inference-two-props.qmd >}}
:::

## Chapter 18 {#exercise-solutions-18 .unlisted}

::: exercises-solution
{{< include exercises/_18-sa-inference-tables.qmd >}}
:::

## Chapter 19 {#exercise-solutions-19 .unlisted}

::: exercises-solution
{{< include exercises/_19-sa-inference-one-mean.qmd >}}
:::

## Chapter 20 {#exercise-solutions-20 .unlisted}

::: exercises-solution
{{< include exercises/_20-sa-inference-two-means.qmd >}}
:::

## Chapter 21 {#exercise-solutions-21 .unlisted}

::: exercises-solution
{{< include exercises/_21-sa-inference-paired-means.qmd >}}
:::

## Chapter 22 {#exercise-solutions-22 .unlisted}

::: exercises-solution
{{< include exercises/_22-sa-inference-many-means.qmd >}}
:::

## Chapter 23 {#exercise-solutions-23 .unlisted}

Application chapter, no exercises.

## Chapter 24 {#exercise-solutions-24 .unlisted}

::: exercises-solution
{{< include exercises/_24-sa-inf-model-slr.qmd >}}
:::

## Chapter 25 {#exercise-solutions-25 .unlisted}

::: exercises-solution
{{< include exercises/_25-sa-inf-model-mlr.qmd >}}
:::

## Chapter 26 {#exercise-solutions-26 .unlisted}

::: exercises-solution
{{< include exercises/_26-sa-inf-model-logistic.qmd >}}
:::
