# (PART) Appendix {.unnumbered}

# Exercise solutions {#exercise-solutions}

## Chapter 1

```{r sa-01, child = "exercises/01-sa-data-hello.Rmd"}
```

## Chapter 2

```{r sa-02, child = "exercises/02-sa-data-design.Rmd"}
```

## Chapter 4

```{r sa-04, child = "exercises/04-sa-explore-categorical.Rmd"}
```

## Chapter 5

```{r sa-05, child = "exercises/05-sa-explore-numerical.Rmd"}
```

## Chapter 6

```{r sa-06, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 8

```{r sa-08, child = "exercises/08-sa-model-slr.Rmd"}
```

## Chapter 9

```{r sa-09, child = "exercises/09-sa-model-mlr.Rmd"}
```

## Chapter 10

```{r sa-10, child = "exercises/10-sa-model-logistic.Rmd"}
```

## Chapter 12

```{r sa-12, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 13

```{r sa-13, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 14

```{r sa-14, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 15

```{r sa-15, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 17

```{r sa-17, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 18

```{r sa-18, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 19

```{r sa-19, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 20

```{r sa-20, child = "exercises/20-sa-inference-one-mean.Rmd"}
```

## Chapter 21

```{r sa-21, child = "exercises/20-sa-inference-one-mean.Rmd", eval = FALSE}
```

## Chapter 22

```{r sa-22, child = "exercises/22-sa-inference-paired-means.Rmd"}
```

## Chapter 23

```{r sa-23, child = "exercises/20-sa-inference-one-mean.Rmd"}
```

## Chapter 25

```{r sa-25, child = "exercises/20-sa-inference-one-mean.Rmd"}
```

## Chapter 26

```{r sa-26, child = "exercises/20-sa-inference-one-mean.Rmd"}
```

## Chapter 27

```{r sa-27, child = "exercises/20-sa-inference-one-mean.Rmd"}
```
