# Changes for the second edition {.unnumbered}

Welcome to the second edition of "Introduction to Modern Statistics"!
While the second edition does not represent a major change from the first edition, we have worked hard to improve content, to add exercises, and to update text and code to reflect changes in best practices (e.g., the book is now written in [Quarto](https://quarto.org/)).

A brief summary of the biggest changes follows:

* Twenty-five completely new exercises were added. Most of the new exercises are concatenated onto existing exercises so as to retain similar numbering across editions. However, a few exercises have been shuffled so as to produce both odd exercises (with solutions) and even exercises (without solutions) on the same topic.

* Multiple datasets were added or updated. For example, 
the [`pm25_2022_durham`](http://openintrostat.github.io/openintro/reference/pm25_2022_durham.html) data on air quality in Durham, NC in 2022 can be found in the [**openintro**](https://openintrostat.github.io/openintro/) R package.

* @sec-data-applications was re-written with an updated context and data example. Additionally, in @sec-data-applications, we explore Simpson's Paradox.

* Throughout the text and the exercises, "statistically significant" has been changed to "statistically discernible" so as to distance ourselves from the more colloquial use of the word "significant."
