# Exploratory data analysis {#sec-explore .unnumbered}

After obtaining a dataset, it is vitally important to understand the characteristics of the existing data. Sometimes the most effective way to grasp the data is through summary statistics or other numerical measures. Often, however, it is a picture that tells a thousand words. Knowing how to best convey the underlying meaning in a dataset is a hugely important aspect of communicating results.

- Categorical data is the focus of [Chapter -@sec-explore-categorical]. Both numerical and graphical summaries are presented as ways to convey information about categorical data.
- Numerical data is the focus of [Chapter -@sec-explore-numerical]. Both numerical and graphical summaries are presented as ways to convey information about numerical data.
- [Chapter -@sec-explore-applications] does a deep dive into important considerations when creating a visualization.

While our book is software agnostic, one of the best ways to become familiar with numerical and graphical summaries is to practice working with different datasets using statistical software. For example, if you are interested in using R, you might try working through some of the chapters in [R for Data Science](https://r4ds.hadley.nz/) (https://r4ds.hadley.nz), specifically the parts [Whole game](https://r4ds.hadley.nz/whole-game) and [Visualize](https://r4ds.hadley.nz/visualize).