<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>13&nbsp; Inference with mathematical models – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./foundations-errors.html" rel="next">
<link href="./foundations-bootstrapping.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-709f5aa5aa6a95674750e60a60b86f5a.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-790f3f5e7e2e01ab58e527b05f631cee.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations-of-inference.html">Foundations of inference</a></li><li class="breadcrumb-item"><a href="./foundations-mathematical.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#sec-CLTsection" id="toc-sec-CLTsection" class="nav-link active" data-scroll-target="#sec-CLTsection"><span class="header-section-number">13.1</span> Central Limit Theorem</a></li>
  <li>
<a href="#sec-normalDist" id="toc-sec-normalDist" class="nav-link" data-scroll-target="#sec-normalDist"><span class="header-section-number">13.2</span> Normal Distribution</a>
  <ul class="collapse">
<li><a href="#normal-distribution-model" id="toc-normal-distribution-model" class="nav-link" data-scroll-target="#normal-distribution-model"><span class="header-section-number">13.2.1</span> Normal distribution model</a></li>
  <li><a href="#standardizing-with-z-scores" id="toc-standardizing-with-z-scores" class="nav-link" data-scroll-target="#standardizing-with-z-scores"><span class="header-section-number">13.2.2</span> Standardizing with Z scores</a></li>
  <li><a href="#normal-probability-calculations" id="toc-normal-probability-calculations" class="nav-link" data-scroll-target="#normal-probability-calculations"><span class="header-section-number">13.2.3</span> Normal probability calculations</a></li>
  <li><a href="#normal-probability-examples" id="toc-normal-probability-examples" class="nav-link" data-scroll-target="#normal-probability-examples"><span class="header-section-number">13.2.4</span> Normal probability examples</a></li>
  </ul>
</li>
  <li>
<a href="#quantifying-the-variability-of-a-statistic" id="toc-quantifying-the-variability-of-a-statistic" class="nav-link" data-scroll-target="#quantifying-the-variability-of-a-statistic"><span class="header-section-number">13.3</span> Quantifying the variability of a statistic</a>
  <ul class="collapse">
<li><a href="#rule" id="toc-rule" class="nav-link" data-scroll-target="#rule"><span class="header-section-number">13.3.1</span> 68-95-99.7 rule</a></li>
  <li><a href="#sec-se" id="toc-sec-se" class="nav-link" data-scroll-target="#sec-se"><span class="header-section-number">13.3.2</span> Standard error</a></li>
  <li><a href="#sec-moe" id="toc-sec-moe" class="nav-link" data-scroll-target="#sec-moe"><span class="header-section-number">13.3.3</span> Margin of error</a></li>
  </ul>
</li>
  <li>
<a href="#sec-caseopp" id="toc-sec-caseopp" class="nav-link" data-scroll-target="#sec-caseopp"><span class="header-section-number">13.4</span> Case Study (test): Opportunity cost</a>
  <ul class="collapse">
<li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">13.4.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">13.4.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics" id="toc-observed-statistic-vs.-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics"><span class="header-section-number">13.4.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-casemed" id="toc-sec-casemed" class="nav-link" data-scroll-target="#sec-casemed"><span class="header-section-number">13.5</span> Case study (test): Medical consultant</a>
  <ul class="collapse">
<li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">13.5.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-1" id="toc-variability-of-the-statistic-1" class="nav-link" data-scroll-target="#variability-of-the-statistic-1"><span class="header-section-number">13.5.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics-1" id="toc-observed-statistic-vs.-null-statistics-1" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics-1"><span class="header-section-number">13.5.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  <li><a href="#conditions-for-applying-the-normal-model" id="toc-conditions-for-applying-the-normal-model" class="nav-link" data-scroll-target="#conditions-for-applying-the-normal-model"><span class="header-section-number">13.5.4</span> Conditions for applying the normal model</a></li>
  </ul>
</li>
  <li>
<a href="#sec-casestent" id="toc-sec-casestent" class="nav-link" data-scroll-target="#sec-casestent"><span class="header-section-number">13.6</span> Case study (interval): Stents</a>
  <ul class="collapse">
<li><a href="#observed-data-2" id="toc-observed-data-2" class="nav-link" data-scroll-target="#observed-data-2"><span class="header-section-number">13.6.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-2" id="toc-variability-of-the-statistic-2" class="nav-link" data-scroll-target="#variability-of-the-statistic-2"><span class="header-section-number">13.6.2</span> Variability of the statistic</a></li>
  <li><a href="#interpreting-confidence-intervals" id="toc-interpreting-confidence-intervals" class="nav-link" data-scroll-target="#interpreting-confidence-intervals"><span class="header-section-number">13.6.3</span> Interpreting confidence intervals</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp13-review" id="toc-sec-chp13-review" class="nav-link" data-scroll-target="#sec-chp13-review"><span class="header-section-number">13.7</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">13.7.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">13.7.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp13-exercises" id="toc-sec-chp13-exercises" class="nav-link" data-scroll-target="#sec-chp13-exercises"><span class="header-section-number">13.8</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/foundations-mathematical.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./foundations-of-inference.html">Foundations of inference</a></li><li class="breadcrumb-item"><a href="./foundations-mathematical.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-foundations-mathematical" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>In <a href="foundations-randomization.html" class="quarto-xref">Chapter&nbsp;<span>11</span></a> and <a href="foundations-bootstrapping.html" class="quarto-xref">Chapter&nbsp;<span>12</span></a> questions about population parameters were addressed using computational techniques. With randomization tests, the data were permuted assuming the null hypothesis. With bootstrapping, the data were resampled in order to measure the variability. In many cases (indeed, with sample proportions), the variability of the statistic can be described by the computational method (as in previous chapters) or by a mathematical formula (as in this chapter).</p>
<p>The normal distribution is presented here to describe the variability associated with sample proportions which are taken from either repeated samples or repeated experiments. The normal distribution is quite powerful in that it describes the variability of many different statistics, and we will encounter the normal distribution throughout the remainder of the book.</p>
<p>For now, however, focus is on the parallels between how data can provide insight about a research question either through computational methods or through mathematical models.</p>
</div>
<section id="sec-CLTsection" class="level2" data-number="13.1"><h2 data-number="13.1" class="anchored" data-anchor-id="sec-CLTsection">
<span class="header-section-number">13.1</span> Central Limit Theorem</h2>
<p>In recent chapters, we have encountered four case studies. While they differ in the settings, in their outcomes, and in the technique we have used to analyze the data, they all have something in common: the general shape of the distribution of the statistics (called the <strong>sampling distribution</strong>). You may have noticed that the distributions were symmetric and bell-shaped.</p>
<div class="important">
<p><strong>Sampling distribution.</strong></p>
<p>A sampling distribution is the distribution of all possible values of a <em>sample statistic</em> from samples of a given sample size from a given population. We can think about the sample distribution as describing how sample statistics (e.g., the sample proportion <span class="math inline">\(\hat{p}\)</span> or the sample mean <span class="math inline">\(\bar{x}\)</span>) varies from one study to another. A sampling distribution is contrasted with a data distribution which shows the variability of the <em>observed</em> data values. The data distribution can be visualized from the observations themselves. However, because a sampling distribution describes sample statistics computed from many studies, it cannot be visualized directly from a single dataset. Instead, we use either computational or mathematical structures to estimate the sampling distribution and hence to describe the expected variability of the sample statistic in repeated studies.</p>
</div>
<p><a href="#fig-FourCaseStudies" class="quarto-xref">Figure&nbsp;<span>13.1</span></a> shows the null distributions in each of the four case studies where we ran 10,000 simulations. Note that the <strong>null distribution</strong> is the sampling distribution of the statistic created under the setting where the null hypothesis is true. Therefore, the null distribution will always be centered at the value of the parameter given by the null hypothesis. In the case of the opportunity cost study, which originally had just 1,000 simulations, we have included an additional 9,000 simulations.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-FourCaseStudies" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four null hypothesis histograms for examples in the book including  opportunity cost, sex discrimination, medical consultant, and tappers  and listeners. Each histogram is centered at the null value of the  proportion which is 0, 0, 0.1, and 0.5, respectively. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-FourCaseStudies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-FourCaseStudies-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;13.1: The null distribution for each of the four case studies presented previously. Note that the center of each distribution is given by the value of the parameter set in the null hypothesis."><img src="foundations-mathematical_files/figure-html/fig-FourCaseStudies-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Four null hypothesis histograms for examples in the book including  opportunity cost, sex discrimination, medical consultant, and tappers  and listeners. Each histogram is centered at the null value of the  proportion which is 0, 0, 0.1, and 0.5, respectively. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-FourCaseStudies-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.1: The null distribution for each of the four case studies presented previously. Note that the center of each distribution is given by the value of the parameter set in the null hypothesis.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Describe the shape of the distributions and note anything that you find interesting.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>The case study for the medical consultant is the only distribution with any evident skew. As we observed in <a href="data-hello.html" class="quarto-xref">Chapter&nbsp;<span>1</span></a>, it’s common for distributions to be skewed or contain outliers. However, the null distributions we have so far encountered have all looked somewhat similar and, for the most part, symmetric. They all resemble a bell-shaped curve. The bell-shaped curve similarity is not a coincidence, but rather, is guaranteed by mathematical theory.</p>
<div class="important">
<p><strong>Central Limit Theorem for proportions.</strong></p>
<p>If we look at a proportion (or difference in proportions) and the scenario satisfies certain conditions, then the sample proportion (or difference in proportions) will appear to follow a bell-shaped curve called the <em>normal distribution</em>.</p>
</div>
<p>An example of a perfect normal distribution is shown in <a href="#fig-simpleNormal" class="quarto-xref">Figure&nbsp;<span>13.2</span></a>. Imagine laying a normal curve over each of the four null distributions in <a href="#fig-FourCaseStudies" class="quarto-xref">Figure&nbsp;<span>13.1</span></a>. While the mean (center) and standard deviation (width or spread) may change for each plot, the general shape remains roughly intact.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-simpleNormal" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A normal curve centered at 0 with a standard deviation of one.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-simpleNormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-simpleNormal-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;13.2: A normal curve."><img src="foundations-mathematical_files/figure-html/fig-simpleNormal-1.png" class="img-fluid figure-img" style="width:60.0%" alt="A normal curve centered at 0 with a standard deviation of one."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-simpleNormal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.2: A normal curve.
</figcaption></figure>
</div>
</div>
</div>
<p>Mathematical theory guarantees that if repeated samples are taken a sample proportion or a difference in sample proportions will follow something that resembles a normal distribution when certain conditions are met. (Note: we typically only take <strong>one</strong> sample, but the mathematical model lets us know what to expect if we <em>had</em> taken repeated samples.) These conditions fall into two general categories describing the independence between observations and the need to take a sufficiently large sample size.</p>
<ol type="1">
<li><p>Observations in the sample are <strong>independent</strong>. Independence is guaranteed when we take a random sample from a population. Independence can also be guaranteed if we randomly divide individuals into treatment and control groups.</p></li>
<li><p>The sample is <strong>large enough</strong>. The sample size cannot be too small. What qualifies as “small” differs from one context to the next, and we’ll provide suitable guidelines for proportions in <a href="inference-one-prop.html" class="quarto-xref">Chapter&nbsp;<span>16</span></a>.</p></li>
</ol>
<p>So far we have had no need for the normal distribution. We’ve been able to answer our questions somewhat easily using simulation techniques. However, soon this will change. Simulating data can be non-trivial. For example, some of the scenarios encountered in <a href="model-mlr.html" class="quarto-xref">Chapter&nbsp;<span>8</span></a> where we introduced regression models with multiple predictors would require complex simulations in order to make inferential conclusions. Instead, the normal distribution and other distributions like it offer a general framework for statistical inference that applies to a very large number of settings.</p>
<div class="important">
<p><strong>Technical Conditions.</strong></p>
<p>In order for the normal approximation to describe the sampling distribution of the sample proportion as it varies from sample to sample, two conditions must hold. If these conditions do not hold, it is unwise to use the normal distribution (and related concepts like Z scores, probabilities from the normal curve, etc.) for inferential analyses.</p>
<ol type="1">
<li><strong>Independent observations</strong></li>
<li>
<strong>Large enough sample:</strong> For proportions, at least 10 expected successes and 10 expected failures in the sample.</li>
</ol>
</div>
</section><section id="sec-normalDist" class="level2" data-number="13.2"><h2 data-number="13.2" class="anchored" data-anchor-id="sec-normalDist">
<span class="header-section-number">13.2</span> Normal Distribution</h2>
<p>Among all the distributions we see in statistics, one is overwhelmingly the most common. The symmetric, unimodal, bell curve is ubiquitous throughout statistics. It is so common that people know it as a variety of names including the <strong>normal curve</strong>, <strong>normal model</strong>, or <strong>normal distribution</strong>.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> Under certain conditions, sample proportions, sample means, and sample differences can be modeled using the normal distribution. Additionally, some variables such as SAT scores and heights of US adult males closely follow the normal distribution.</p>
<div class="important">
<p><strong>Normal distribution facts.</strong></p>
<p>Distributions of many variables are nearly normal, but none are exactly normal. Thus, the normal distribution, while not perfect for any single problem, is very useful for a variety of problems.</p>
</div>
<p>In this section, we will discuss the normal distribution in the context of data to become familiar with normal distribution techniques. In the following sections and beyond, we’ll move our discussion to focus on applying the normal distribution and other related distributions to model point estimates for hypothesis tests and for constructing confidence intervals.</p>
<section id="normal-distribution-model" class="level3" data-number="13.2.1"><h3 data-number="13.2.1" class="anchored" data-anchor-id="normal-distribution-model">
<span class="header-section-number">13.2.1</span> Normal distribution model</h3>
<p>The normal distribution always describes a symmetric, unimodal, bell-shaped curve. However, normal curves can look different depending on the details of the model. Specifically, the normal model can be adjusted using two parameters: mean and standard deviation. As you can probably guess, changing the mean shifts the bell curve to the left or right, while changing the standard deviation stretches or constricts the curve. <a href="#fig-twoSampleNormals-1" class="quarto-xref">Figure&nbsp;<span>13.3 (a)</span></a> shows the normal distribution with mean <span class="math inline">\(0\)</span> and standard deviation <span class="math inline">\(1\)</span> (which is commonly referred to as the <strong>standard normal distribution</strong>). A normal distribution with mean <span class="math inline">\(19\)</span> and standard deviation <span class="math inline">\(4\)</span> is shown on the right. <a href="#fig-twoSampleNormalsStacked" class="quarto-xref">Figure&nbsp;<span>13.4</span></a> shows the same two normal distributions on the same axis.</p>
<div id="fig-twoSampleNormals" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-twoSampleNormals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-twoSampleNormals" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-twoSampleNormals-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two normal curves. The first one has a mean at zero with a standard deviation of one and is called the standard normal distribution. The  second one has a mean at 19 with a standard deviation of four. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-twoSampleNormals-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-twoSampleNormals-1.png" class="lightbox" data-gallery="fig-twoSampleNormals" title="Figure&nbsp;13.3&nbsp;(a): Mean = 0, SD = 1"><img src="foundations-mathematical_files/figure-html/fig-twoSampleNormals-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-twoSampleNormals" alt="Two normal curves. The first one has a mean at zero with a standard deviation of one and is called the standard normal distribution. The  second one has a mean at 19 with a standard deviation of four. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-twoSampleNormals-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Mean = 0, SD = 1
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-twoSampleNormals" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-twoSampleNormals-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two normal curves. The first one has a mean at zero with a standard deviation of one and is called the standard normal distribution. The  second one has a mean at 19 with a standard deviation of four. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-twoSampleNormals-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-twoSampleNormals-2.png" class="lightbox" data-gallery="fig-twoSampleNormals" title="Figure&nbsp;13.3&nbsp;(b): Mean = 19, SD = 4"><img src="foundations-mathematical_files/figure-html/fig-twoSampleNormals-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-twoSampleNormals" alt="Two normal curves. The first one has a mean at zero with a standard deviation of one and is called the standard normal distribution. The  second one has a mean at 19 with a standard deviation of four. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-twoSampleNormals-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Mean = 19, SD = 4
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twoSampleNormals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.3: Two normal distributions with different centers and spreads.
</figcaption></figure>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-twoSampleNormalsStacked" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two normal curves plotted on the same axis. One is a standard normal curve with a mean at zero and a standard deviation of one. The other has a mean of 19 with a standard deviation of four. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-twoSampleNormalsStacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-twoSampleNormalsStacked-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;13.4: The two normal models shown in Figure&nbsp;fig-twoSampleNormals but plotted together on the same scale."><img src="foundations-mathematical_files/figure-html/fig-twoSampleNormalsStacked-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Two normal curves plotted on the same axis. One is a standard normal curve with a mean at zero and a standard deviation of one. The other has a mean of 19 with a standard deviation of four. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-twoSampleNormalsStacked-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.4: The two normal models shown in <a href="#fig-twoSampleNormals" class="quarto-xref">Figure&nbsp;<span>13.3</span></a> but plotted together on the same scale.
</figcaption></figure>
</div>
</div>
</div>
<p>If a normal distribution has mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma,\)</span> we may write the distribution as <span class="math inline">\(N(\mu, \sigma).\)</span> The two distributions in <a href="#fig-twoSampleNormalsStacked" class="quarto-xref">Figure&nbsp;<span>13.4</span></a> can be written as</p>
<p><span class="math display">\[ N(\mu = 0, \sigma = 1)\quad\text{and}\quad N(\mu = 19, \sigma = 4) \]</span></p>
<p>Because the mean and standard deviation describe a normal distribution exactly, they are called the distribution’s <strong>parameters</strong>.</p>
<div class="workedexample">
<p>Write down the short-hand for a normal distribution with the following parameters.</p>
<ol type="a">
<li>mean 5 and standard deviation 3</li>
<li>mean -100 and standard deviation 10</li>
<li>mean 2 and standard deviation 9</li>
</ol>
<hr>
<ol type="a">
<li><span class="math inline">\(N(\mu = 5,\sigma = 3)\)</span></li>
<li><span class="math inline">\(N(\mu = -100, \sigma = 10)\)</span></li>
<li><span class="math inline">\(N(\mu = 2, \sigma = 9)\)</span></li>
</ol>
</div>
</section><section id="standardizing-with-z-scores" class="level3" data-number="13.2.2"><h3 data-number="13.2.2" class="anchored" data-anchor-id="standardizing-with-z-scores">
<span class="header-section-number">13.2.2</span> Standardizing with Z scores</h3>
<div class="guidedpractice">
<p>SAT scores follow a nearly normal distribution with a mean of 1500 points and a standard deviation of 300 points. ACT scores also follow a nearly normal distribution with mean of 21 points and a standard deviation of 5 points. Suppose Nel scored 1800 points on their SAT and Sian scored 24 points on their ACT. Who performed better?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-satActNormals" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Nel's SAT score is plotted on a normal curve with a mean of 1500 and a standard deviation of 300. Sian's ACT score is plotted on a normal curve with a mean of 21 and a standard deviation of 5. Nel's score is relatively higher than Sian's score. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-satActNormals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-satActNormals-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;13.5: Nel’s and Sian’s scores shown with the distributions of SAT and ACT scores."><img src="foundations-mathematical_files/figure-html/fig-satActNormals-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Nel's SAT score is plotted on a normal curve with a mean of 1500 and a standard deviation of 300. Sian's ACT score is plotted on a normal curve with a mean of 21 and a standard deviation of 5. Nel's score is relatively higher than Sian's score. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-satActNormals-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.5: Nel’s and Sian’s scores shown with the distributions of SAT and ACT scores.
</figcaption></figure>
</div>
</div>
</div>
<p>The solution to the previous example relies on a standardization technique called a Z score, a method most commonly employed for nearly normal observations (but that may be used with any distribution). The <strong>Z score</strong> of an observation is defined as the number of standard deviations it falls above or below the mean. If the observation is one standard deviation above the mean, its Z score is 1. If it is 1.5 standard deviations <em>below</em> the mean, then its Z score is -1.5. If <span class="math inline">\(x\)</span> is an observation from a distribution <span class="math inline">\(N(\mu, \sigma),\)</span> we define the Z score mathematically as</p>
<p><span class="math display">\[ Z = \frac{x-\mu}{\sigma} \]</span></p>
<p>Using <span class="math inline">\(\mu_{SAT}=1500,\)</span> <span class="math inline">\(\sigma_{SAT}=300,\)</span> and <span class="math inline">\(x_{Nel}=1800,\)</span> we find Nel’s Z score:</p>
<p><span class="math display">\[ Z_{Nel} = \frac{x_{Nel} - \mu_{SAT}}{\sigma_{SAT}} = \frac{1800-1500}{300} = 1 \]</span></p>
<div class="important">
<p><strong>The Z score.</strong></p>
<p>The Z score of an observation is the number of standard deviations it falls above or below the mean. We compute the Z score for an observation <span class="math inline">\(x\)</span> that follows a distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span> using</p>
<p><span class="math display">\[Z = \frac{x-\mu}{\sigma}\]</span></p>
<p>If the observation <span class="math inline">\(x\)</span> comes from a <em>normal</em> distribution centered at <span class="math inline">\(\mu\)</span> with standard deviation of <span class="math inline">\(\sigma\)</span>, then the Z score will be distributed according to a <em>normal</em> distribution with a center of 0 and a standard deviation of 1. That is, the normality remains when transforming from <span class="math inline">\(x\)</span> to <span class="math inline">\(Z\)</span> with a shift in both the center as well as the spread.</p>
</div>
<div class="guidedpractice">
<p>Use Sian’s ACT score, 24, along with the ACT mean and standard deviation to compute their Z score.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</div>
<p>Observations above the mean always have positive Z scores while those below the mean have negative Z scores. If an observation is equal to the mean (e.g., SAT score of 1500), then the Z score is <span class="math inline">\(0.\)</span></p>
<div class="workedexample">
<p>Let <span class="math inline">\(X\)</span> represent a random variable from <span class="math inline">\(N(\mu=3, \sigma=2),\)</span> and suppose we observe <span class="math inline">\(x=5.19.\)</span> Find the Z score of <span class="math inline">\(x.\)</span> Then, use the Z score to determine how many standard deviations above or below the mean <span class="math inline">\(x\)</span> falls.</p>
<hr>
<p>Its Z score is given by <span class="math inline">\(Z = \frac{x-\mu}{\sigma} = \frac{5.19 - 3}{2} = 2.19/2 = 1.095.\)</span> The observation <span class="math inline">\(x\)</span> is 1.095 standard deviations <em>above</em> the mean. We know it must be above the mean since <span class="math inline">\(Z\)</span> is positive.</p>
</div>
<div class="guidedpractice">
<p>Head lengths of brushtail possums follow a nearly normal distribution with mean 92.6 mm and standard deviation 3.6 mm. Compute the Z scores for possums with head lengths of 95.4 mm and 85.8 mm.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
<p>We can use Z scores to roughly identify which observations are more unusual than others. One observation <span class="math inline">\(x_1\)</span> is said to be more unusual than another observation <span class="math inline">\(x_2\)</span> if the absolute value of its Z score is larger than the absolute value of the other observation’s Z score: <span class="math inline">\(|Z_1| &gt; |Z_2|.\)</span> This technique is especially insightful when a distribution is symmetric.</p>
<div class="guidedpractice">
<p>Which of the two brushtail possum observations in the previous guided practice is more <em>unusual</em>?<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
</div>
</section><section id="normal-probability-calculations" class="level3" data-number="13.2.3"><h3 data-number="13.2.3" class="anchored" data-anchor-id="normal-probability-calculations">
<span class="header-section-number">13.2.3</span> Normal probability calculations</h3>
<div class="workedexample">
<p>Nel from the SAT Guided Practice earned a score of 1800 on their SAT with a corresponding <span class="math inline">\(Z=1.\)</span> They would like to know what percentile they fall in among all SAT test-takers.</p>
<hr>
<p>Nel’s <strong>percentile</strong> is the percentage of people who earned a lower SAT score than Nel. We shade the area representing those individuals in <a href="#fig-satBelow1800" class="quarto-xref">Figure&nbsp;<span>13.6</span></a>. The total area under the normal curve is always equal to 1, and the proportion of people who scored below Nel on the SAT is equal to the <em>area</em> shaded in <a href="#fig-satBelow1800" class="quarto-xref">Figure&nbsp;<span>13.6</span></a>: 0.8413. In other words, Nel is in the <span class="math inline">\(84^{th}\)</span> percentile of SAT takers.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-satBelow1800" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Nel's SAT score of 1800 is plotted on a normal curve with mean of 1500 and standard deviation of 300. The scores lower than Nel's are shaded in blue and represent roughly 84% of the distribution. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-satBelow1800-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-satBelow1800-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;13.6: The normal model for SAT scores, shading the area of those individuals who scored below Nel."><img src="foundations-mathematical_files/figure-html/fig-satBelow1800-1.png" class="img-fluid figure-img" style="width:60.0%" alt="Nel's SAT score of 1800 is plotted on a normal curve with mean of 1500 and standard deviation of 300. The scores lower than Nel's are shaded in blue and represent roughly 84% of the distribution. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-satBelow1800-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.6: The normal model for SAT scores, shading the area of those individuals who scored below Nel.
</figcaption></figure>
</div>
</div>
</div>
<p>We can use the normal model to find percentiles or probabilities. A <strong>normal probability table</strong>, which lists Z scores and corresponding percentiles, can be used to identify a percentile based on the Z score (and vice versa). Statistical software can also be used.</p>
<p>Normal probabilities are most commonly found using statistical software which we will show here using R. We use the software to identify the percentile corresponding to any particular Z score. For instance, the percentile of <span class="math inline">\(Z=0.43\)</span> is 0.6664, or the <span class="math inline">\(66.64^{th}\)</span> percentile. The <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> function is available in default R and will provide the percentile associated with any cutoff on a normal curve. The <code>normTail()</code> function is available in the <a href="http://openintrostat.github.io/openintro/"><strong>openintro</strong></a> R package and will draw the associated normal distribution curve.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">pnorm</a></span><span class="op">(</span><span class="fl">0.43</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.666</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">openintro</span><span class="fu">::</span><span class="fu"><a href="https://openintrostat.github.io/openintro/reference/normTail.html">normTail</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fl">0</span>, s <span class="op">=</span> <span class="fl">1</span>, L <span class="op">=</span> <span class="fl">0.43</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="foundations-mathematical_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>We can also find the Z score associated with a percentile. For example, to identify Z for the <span class="math inline">\(80^{th}\)</span> percentile, we use <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> which identifies the <strong>quantile</strong> for a given percentage. The quantile represents the cutoff value. (To remember the function <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> as providing a cutoff, notice that both <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code> and “cutoff” start with the sound “kuh”. To remember the <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> function as providing a probability from a given cutoff, notice that both <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> and probability start with the sound “puh”.) We determine the Z score for the <span class="math inline">\(80^{th}\)</span> percentile using <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>: 0.84.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.80</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.842</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">openintro</span><span class="fu">::</span><span class="fu"><a href="https://openintrostat.github.io/openintro/reference/normTail.html">normTail</a></span><span class="op">(</span>m <span class="op">=</span> <span class="fl">0</span>, s <span class="op">=</span> <span class="fl">1</span>, L <span class="op">=</span> <span class="fl">0.842</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="foundations-mathematical_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Determine the proportion of SAT test takers who scored better than Nel on the SAT.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a></p>
</div>
</section><section id="normal-probability-examples" class="level3" data-number="13.2.4"><h3 data-number="13.2.4" class="anchored" data-anchor-id="normal-probability-examples">
<span class="header-section-number">13.2.4</span> Normal probability examples</h3>
<p>Cumulative SAT scores are approximated well by a normal model, <span class="math inline">\(N(\mu=1500, \sigma=300).\)</span></p>
<div class="workedexample">
<p>Shannon is a randomly selected SAT taker, and nothing is known about Shannon’s SAT aptitude. What is the probability that Shannon scores at least 1630 on their SATs?</p>
<hr>
<p>First, always draw and label a picture of the normal distribution. (Drawings need not be exact to be useful.) We are interested in the chance they score above 1630, so we shade the upper tail. See the normal curve below.</p>
<p>The <span class="math inline">\(x\)</span>-axis identifies the mean and the values at 2 standard deviations above and below the mean. The simplest way to find the shaded area under the curve makes use of the Z score of the cutoff value. With <span class="math inline">\(\mu=1500,\)</span> <span class="math inline">\(\sigma=300,\)</span> and the cutoff value <span class="math inline">\(x=1630,\)</span> the Z score is computed as</p>
<p><span class="math display">\[ Z = \frac{x - \mu}{\sigma} = \frac{1630 - 1500}{300} = \frac{130}{300} = 0.43 \]</span></p>
<p>We use software to find the percentile of <span class="math inline">\(Z=0.43,\)</span> which yields 0.6664. However, the percentile describes those who had a Z score <em>lower</em> than 0.43. To find the area <em>above</em> <span class="math inline">\(Z=0.43,\)</span> we compute one minus the area of the lower tail, as seen below.</p>
<p>The probability Shannon scores at least 1630 on the SAT is 0.3336. This calculation is visualized in <a href="#fig-subtractingArea" class="quarto-xref">Figure&nbsp;<span>13.7</span></a>.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-subtractingArea" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Three normal curves visualizing that probabilities can be calculated using arithmetic on areas. The area above 1630 can be calculated by taking the total area of one and subtracting the area below 1630 (which is 0.6664). The resulting value is 0.3336. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-subtractingArea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-subtractingArea-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;13.7: Visual calculation of the probability that Shannon scores at least 1630 on the SAT."><img src="foundations-mathematical_files/figure-html/fig-subtractingArea-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Three normal curves visualizing that probabilities can be calculated using arithmetic on areas. The area above 1630 can be calculated by taking the total area of one and subtracting the area below 1630 (which is 0.6664). The resulting value is 0.3336. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-subtractingArea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.7: Visual calculation of the probability that Shannon scores at least 1630 on the SAT.
</figcaption></figure>
</div>
</div>
</div>
<div class="tip">
<p><strong>Always draw a picture first, and find the Z score second.</strong></p>
<p>For any normal probability situation, <em>always always always</em> draw and label the normal curve and shade the area of interest first. The picture will provide an estimate of the probability.</p>
<p>After drawing a figure to represent the situation, identify the Z score for the observation of interest.</p>
</div>
<div class="guidedpractice">
<p>If the probability of Shannon scoring at least 1630 is 0.3336, then what is the probability they score less than 1630? Draw the normal curve representing this exercise, shading the lower region instead of the upper one.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a></p>
</div>
<div class="workedexample">
<p>Edward earned a 1400 on their SAT. What is their percentile?</p>
<hr>
<p>First, a picture is needed. Edward’s percentile is the proportion of people who do not get as high as a 1400. These are the scores to the left of 1400, as shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/edward-percentile-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="foundations-mathematical_files/figure-html/edward-percentile-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%" alt="A normal curve with a mean of 1500 and a standard deviation of 300. Values less than 1400 are shaded blue in the lower part of the curve. The shaded part is roughly 37 percent of the graph. "></a></p>
</figure>
</div>
</div>
</div>
<p>The mean <span class="math inline">\(\mu=1500,\)</span> the standard deviation <span class="math inline">\(\sigma=300,\)</span> and the cutoff for the tail area <span class="math inline">\(x=1400\)</span> are used to compute the Z score:</p>
<p><span class="math display">\[ Z = \frac{x - \mu}{\sigma} = \frac{1400 - 1500}{300} = -0.33\]</span></p>
<p>Statistical software can be used to find the proportion of the <span class="math inline">\(N(0,1)\)</span> curve to the left of <span class="math inline">\(-0.33\)</span> which is 0.3707. Edward is at the <span class="math inline">\(37^{th}\)</span> percentile.</p>
</div>
<div class="workedexample">
<p>Use the results of the previous example to compute the proportion of SAT takers who did better than Edward. Also draw a new picture.</p>
<hr>
<p>If Edward did better than 37% of SAT takers, then about 63% must have done better than them, as shown below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/edward-percentile-better-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="foundations-mathematical_files/figure-html/edward-percentile-better-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%" alt="A normal curve with a mean of 1500 and a standard deviation of 300. Values greater than 1400 are shaded blue in the upper part of the curve. The shaded part is roughly 63 percent of the graph."></a></p>
</figure>
</div>
</div>
</div>
</div>
<div class="tip">
<p><strong>Areas to the right.</strong></p>
<p>Most statistical software, as well as normal probability tables in most books, give the area to the left. If you would like the area to the right, first find the area to the left and then subtract the amount from one.</p>
</div>
<div class="guidedpractice">
<p>Stuart earned an SAT score of 2100. Draw a picture for each part. (a) What is their percentile? (b) What percent of SAT takers did better than Stuart?<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a></p>
</div>
<p>Based on a sample of 100 men,<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> the heights of adults who identify as male, between the ages 20 and 62 in the US is nearly normal with mean 70.0” and standard deviation 3.3”.</p>
<div class="workedexample">
<p>Kamron is 5’7” (67 inches) and Adrian is 6’4” (76 inches). (a) What is Kamron’s height percentile? (b) What is Adrian’s height percentile? Also draw one picture for each part.</p>
<hr>
<p>Numerical answers, calculated using statistical software (e.g., <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> in R): (a) 18.17th percentile. (b) 96.55th percentile.</p>
</div>
<p>The last several problems have focused on finding the probability or percentile for a particular observation. What if you would like to know the observation corresponding to a particular percentile?</p>
<div class="workedexample">
<p>Yousef’s height is at the <span class="math inline">\(40^{th}\)</span> percentile. How tall are they?</p>
<hr>
<p>As always, first draw the picture.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="foundations-mathematical_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>In this case, the lower tail probability is known (0.40), which can be shaded on the diagram. We want to find the observation that corresponds to the known probability of 0.4. We can find the observation in two different ways: using the height curve seen above or using the Z score associated with the standard normal curve centered at zero with a standard deviation of one.</p>
<p>If you have access to software (like R, code seen below) that allows you to specify the mean and standard deviation of the normal curve, you can calculate the observed value on the curve (i.e., Yousef’s height) directly.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 69.2</code></pre>
</div>
</div>
<p>Yousef is 69.2 inches tall. That is, Yousef is about 5’9” (this is notation for 5-feet, 9-inches).</p>
<p>Without access to flexible software, you will need the information given by a standard normal curve (a normal curve centered at zero with a standard deviation of one). First, determine the Z score associated with the <span class="math inline">\(40^{th}\)</span> percentile.</p>
<p>Because the percentile is below 50%, we know <span class="math inline">\(Z\)</span> will be negative. Statistical software provides the <span class="math inline">\(Z\)</span> value to be <span class="math inline">\(-0.25.\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.4</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.253</code></pre>
</div>
</div>
<p>Knowing <span class="math inline">\(Z_{Yousef}=-0.25\)</span> and the population parameters <span class="math inline">\(\mu=70\)</span> and <span class="math inline">\(\sigma=3.3\)</span> inches, the Z score formula can be set up to determine Yousef’s unknown height, labeled <span class="math inline">\(x_{Yousef}\)</span>:</p>
<p><span class="math display">\[ -0.253 = Z_{Yousef} = \frac{x_{Yousef} - \mu}{\sigma} = \frac{x_{Yousef} - 70}{3.3} \]</span></p>
<p>Solving for <span class="math inline">\(x_{Yousef}\)</span> yields the height 69.2 inches. Again, Yousef is about 5’9”.</p>
</div>
<div class="workedexample">
<p>What is the adult male height at the <span class="math inline">\(82^{nd}\)</span> percentile?</p>
<hr>
<p>In order to practice using Z scores, we will use the standard normal curve to solve the problem.</p>
<p>Again, we draw the figure first.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/height82Perc-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="foundations-mathematical_files/figure-html/height82Perc-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>And calculate the Z value associated with the <span class="math inline">\(82^{nd}\)</span> percentile:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">qnorm</a></span><span class="op">(</span><span class="fl">0.82</span>, mean <span class="op">=</span> <span class="fl">0</span>, sd <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.915</code></pre>
</div>
</div>
<p>Next, we want to find the Z score at the <span class="math inline">\(82^{nd}\)</span> percentile, which will be a positive value (because the percentile is bigger than 50%). Using <code><a href="https://rdrr.io/r/stats/Normal.html">qnorm()</a></code>, the <span class="math inline">\(82^{nd}\)</span> percentile corresponds to <span class="math inline">\(Z=0.92.\)</span> Finally, the height <span class="math inline">\(x\)</span> is found using the Z score formula with the known mean <span class="math inline">\(\mu,\)</span> standard deviation <span class="math inline">\(\sigma,\)</span> and Z score <span class="math inline">\(Z=0.92\)</span>:</p>
<p><span class="math display">\[ 0.92 = Z = \frac{x-\mu}{\sigma} = \frac{x - 70}{3.3} \]</span></p>
<p>This yields 73.04 inches or about 6’1” as the height at the <span class="math inline">\(82^{nd}\)</span> percentile.</p>
</div>
<div class="guidedpractice">
<p>Using Z scores, answer the following questions.</p>
<ol type="a">
<li>What is the <span class="math inline">\(95^{th}\)</span> percentile for SAT scores?<br>
</li>
<li>What is the <span class="math inline">\(97.5^{th}\)</span> percentile of the male heights? As always with normal probability problems, first draw a picture.<a href="#fn11" class="footnote-ref" id="fnref11" role="doc-noteref"><sup>11</sup></a>
</li>
</ol>
</div>
<div class="guidedpractice">
<p>Using Z scores, answer the following questions.</p>
<ol type="a">
<li>What is the probability that a randomly selected male adult is at least 6’2” (74 inches)?<br>
</li>
<li>What is the probability that a male adult is shorter than 5’9” (69 inches)?<a href="#fn12" class="footnote-ref" id="fnref12" role="doc-noteref"><sup>12</sup></a>
</li>
</ol>
</div>
<div class="workedexample">
<p>What is the probability that a randomly selected adult male is between 5’9” and 6’2”?</p>
<hr>
<p>These heights correspond to 69 inches and 74 inches. First, draw the figure. The area of interest is no longer an upper or lower tail.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/unnamed-chunk-18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="foundations-mathematical_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>The total area under the curve is 1. If we find the area of the two tails that are not shaded (from the previous Guided Practice, these areas are <span class="math inline">\(0.3821\)</span> and <span class="math inline">\(0.1131\)</span>), then we can find the middle area:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/unnamed-chunk-19-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="foundations-mathematical_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>That is, the probability of being between 5’9” and 6’2” is 0.5048.</p>
</div>
<div class="guidedpractice">
<p>Find the percent of SAT takers who earn between 1500 and 2000.<a href="#fn13" class="footnote-ref" id="fnref13" role="doc-noteref"><sup>13</sup></a></p>
</div>
<div class="guidedpractice">
<p>What percent of adult males are between 5’5” and 5’7”?<a href="#fn14" class="footnote-ref" id="fnref14" role="doc-noteref"><sup>14</sup></a></p>
</div>
</section></section><section id="quantifying-the-variability-of-a-statistic" class="level2" data-number="13.3"><h2 data-number="13.3" class="anchored" data-anchor-id="quantifying-the-variability-of-a-statistic">
<span class="header-section-number">13.3</span> Quantifying the variability of a statistic</h2>
<p>As seen in later chapters, it turns out that many of the statistics used to summarize data (e.g., the sample proportion, the sample mean, differences in two sample proportions, differences in two sample means, the sample slope from a linear model, etc.) vary according to the normal distribution seen above. The mathematical models are derived from the normal theory, but even the computational methods (and the intuitive thinking behind both approaches) use the general bell-shaped variability seen in most of the distributions constructed so far.</p>
<section id="rule" class="level3" data-number="13.3.1"><h3 data-number="13.3.1" class="anchored" data-anchor-id="rule">
<span class="header-section-number">13.3.1</span> 68-95-99.7 rule</h3>
<p>Here, we present a useful general rule for the probability of falling within 1, 2, and 3 standard deviations of the mean in the normal distribution. The rule will be useful in a wide range of practical settings, especially when trying to make a quick estimate without a calculator or Z table.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-er6895997" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A normal curve showing the area within one standard deviation of the mean (which is 0.68), the area within two standard deviations of the mean (which is 0.95), and the are within three standard deviations of the mean (which is 0.997). ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-er6895997-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-er6895997-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figure&nbsp;13.8: Probabilities for falling within 1, 2, and 3 standard deviations of the mean in a normal distribution."><img src="foundations-mathematical_files/figure-html/fig-er6895997-1.png" class="img-fluid figure-img" style="width:60.0%" alt="A normal curve showing the area within one standard deviation of the mean (which is 0.68), the area within two standard deviations of the mean (which is 0.95), and the are within three standard deviations of the mean (which is 0.997). "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-er6895997-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.8: Probabilities for falling within 1, 2, and 3 standard deviations of the mean in a normal distribution.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Use <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> (or a Z table) to confirm that about 68%, 95%, and 99.7% of observations fall within 1, 2, and 3, standard deviations of the mean in the normal distribution, respectively. For instance, first find the area that falls between <span class="math inline">\(Z=-1\)</span> and <span class="math inline">\(Z=1,\)</span> which should have an area of about 0.68. Similarly there should be an area of about 0.95 between <span class="math inline">\(Z=-2\)</span> and <span class="math inline">\(Z=2.\)</span><a href="#fn15" class="footnote-ref" id="fnref15" role="doc-noteref"><sup>15</sup></a></p>
</div>
<p>It is possible for a normal random variable to fall 4, 5, or even more standard deviations from the mean. However, these occurrences are very rare if the data are nearly normal. The probability of being further than 4 standard deviations from the mean is about 1-in-30,000. For 5 and 6 standard deviations, it is about 1-in-3.5 million and 1-in-1 billion, respectively.</p>
<div class="guidedpractice">
<p>SAT scores closely follow the normal model with mean <span class="math inline">\(\mu = 1500\)</span> and standard deviation <span class="math inline">\(\sigma = 300.\)</span> About what percent of test takers score 900 to 2100? What percent score between 1500 and 2100 ?<a href="#fn16" class="footnote-ref" id="fnref16" role="doc-noteref"><sup>16</sup></a></p>
</div>
</section><section id="sec-se" class="level3" data-number="13.3.2"><h3 data-number="13.3.2" class="anchored" data-anchor-id="sec-se">
<span class="header-section-number">13.3.2</span> Standard error</h3>
<p>Point estimates vary from sample to sample, and we quantify this variability with what is called the <strong>standard error (SE)</strong>. The standard error is equal to the standard deviation associated with the statistic. So, for example, to quantify the variability of a point estimate from one sample to the next, the variability is called the standard error of the point estimate. Almost always, the standard error is itself an estimate, calculated from the sample of data.</p>
<p>The way we determine the standard error varies from one situation to the next. However, typically it is determined using a formula based on the Central Limit Theorem.</p>
</section><section id="sec-moe" class="level3" data-number="13.3.3"><h3 data-number="13.3.3" class="anchored" data-anchor-id="sec-moe">
<span class="header-section-number">13.3.3</span> Margin of error</h3>
<p>Very related to the standard error is the <strong>margin of error</strong>. The margin of error describes how far away observations are from their mean.<br>
For example, to describe where most (i.e., 95%) observations lie, we say that the margin of error is approximately <span class="math inline">\(2 \times SE\)</span>. That is, 95% of the observations are within two margins of error of the mean.</p>
<div class="important">
<p><strong>Margin of error for sample proportions.</strong></p>
<p>The distance given by <span class="math inline">\(z^\star \times SE\)</span> is called the <strong>margin of error</strong>.</p>
<p><span class="math inline">\(z^\star\)</span> is the cutoff value found on the normal distribution. The most common value of <span class="math inline">\(z^\star\)</span> is 1.96 (often approximated to be 2) indicating that the margin of error describes the variability associated with 95% of the sampled statistics.</p>
</div>
<p>Notice that if the spread of the observations goes from some lower bound to some upper bound, a rough approximation of the SE is to divide the range by 4. That is, if you notice the sample proportions go from 0.1 to 0.4, the SE can be approximated to be 0.075.</p>
</section></section><section id="sec-caseopp" class="level2" data-number="13.4"><h2 data-number="13.4" class="anchored" data-anchor-id="sec-caseopp">
<span class="header-section-number">13.4</span> Case Study (test): Opportunity cost</h2>
<p>The approach for using the normal model in the context of inference is very similar to the practice of applying the model to individual observations that are nearly normal. We will replace null distributions we previously obtained using the randomization or simulation techniques and verify the results once again using the normal model. When the sample size is sufficiently large, the normal approximation generally provides us with the same conclusions as the simulation model.</p>
<section id="observed-data" class="level3" data-number="13.4.1"><h3 data-number="13.4.1" class="anchored" data-anchor-id="observed-data">
<span class="header-section-number">13.4.1</span> Observed data</h3>
<p>In <a href="foundations-randomization.html#sec-caseStudyOpportunityCost" class="quarto-xref"><span>Section 11.2</span></a> we were introduced to the opportunity cost study, which found that students became thriftier when they were reminded that not spending money now means the money can be spent on other things in the future. Let’s re-analyze the data in the context of the normal distribution and compare the results.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/opportunity_cost.html"><code>opportunity_cost</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
</section><section id="variability-of-the-statistic" class="level3" data-number="13.4.2"><h3 data-number="13.4.2" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">13.4.2</span> Variability of the statistic</h3>
<p><a href="#fig-OpportunityCostDiffs-w-normal" class="quarto-xref">Figure&nbsp;<span>13.9</span></a> summarizes the null distribution as determined using the randomization method. The best fitting normal distribution for the null distribution has a mean of 0. We can calculate the standard error of this distribution by borrowing a formula that we will become familiar with in <a href="inference-two-props.html" class="quarto-xref">Chapter&nbsp;<span>17</span></a>, but for now let’s just take the value <span class="math inline">\(SE = 0.078\)</span> as a given. Recall that the point estimate of the difference was 0.20, as shown in <a href="#fig-OpportunityCostDiffs-w-normal" class="quarto-xref">Figure&nbsp;<span>13.9</span></a>. Next, we’ll use the normal distribution approach to compute the p-value.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-OpportunityCostDiffs-w-normal" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Normal curve overlaid on the histogram of the simulated differences in sample proportions in the opportunity cost study. The theoretical normal distribution fits the histogram quite well. The observed difference in sample proportions of 0.2 is in the tail of both the normal curve and the histogram. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-OpportunityCostDiffs-w-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-OpportunityCostDiffs-w-normal-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;13.9: Null distribution of differences with an overlaid normal curve for the opportunity cost study. 10,000 simulations were run for this figure."><img src="foundations-mathematical_files/figure-html/fig-OpportunityCostDiffs-w-normal-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Normal curve overlaid on the histogram of the simulated differences in sample proportions in the opportunity cost study. The theoretical normal distribution fits the histogram quite well. The observed difference in sample proportions of 0.2 is in the tail of both the normal curve and the histogram. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-OpportunityCostDiffs-w-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.9: Null distribution of differences with an overlaid normal curve for the opportunity cost study. 10,000 simulations were run for this figure.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="observed-statistic-vs.-null-statistics" class="level3" data-number="13.4.3"><h3 data-number="13.4.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics">
<span class="header-section-number">13.4.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>As we learned in <a href="#sec-normalDist" class="quarto-xref"><span>Section 13.2</span></a>, it is helpful to draw and shade a picture of the normal distribution so we know precisely what we want to calculate. Here we want to find the area of the tail beyond 0.2, representing the p-value.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/OpportunityCostDiffs_normal_only-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19"><img src="foundations-mathematical_files/figure-html/OpportunityCostDiffs_normal_only-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Next, we can calculate the Z score using the observed difference, 0.20, and the two model parameters. The standard error, <span class="math inline">\(SE = 0.078,\)</span> is the equivalent of the model’s standard deviation.</p>
<p><span class="math display">\[Z = \frac{\text{observed difference} - 0}{SE} = \frac{0.20 - 0}{0.078} = 2.56\]</span></p>
<p>We can either use statistical software or look up <span class="math inline">\(Z = 2.56\)</span> in the normal probability table to determine the right tail area: 0.0052, which is about the same as what we got for the right tail using the randomization approach (0.006). Using this area as the p-value, we see that the p-value is less than 0.05, we conclude that the treatment did indeed impact students’ spending.</p>
<div class="important">
<p><strong>Z score in a hypothesis test.</strong></p>
<p>In the context of a hypothesis test, the Z score for a point estimate is</p>
<p><span class="math display">\[Z = \frac{\text{point estimate} - \text{null value}}{SE}\]</span></p>
<p>The standard error in this case is the equivalent of the standard deviation of the point estimate, and the null value comes from the claim made in the null hypothesis.</p>
</div>
<p>We have confirmed that the randomization approach we used earlier and the normal distribution approach provide almost identical p-values and conclusions in the opportunity cost case study. Next, let’s turn our attention to the medical consultant case study.</p>
</section></section><section id="sec-casemed" class="level2" data-number="13.5"><h2 data-number="13.5" class="anchored" data-anchor-id="sec-casemed">
<span class="header-section-number">13.5</span> Case study (test): Medical consultant</h2>
<section id="observed-data-1" class="level3" data-number="13.5.1"><h3 data-number="13.5.1" class="anchored" data-anchor-id="observed-data-1">
<span class="header-section-number">13.5.1</span> Observed data</h3>
<p>In <a href="foundations-bootstrapping.html#sec-case-study-med-consult" class="quarto-xref"><span>Section 12.1</span></a> we learned about a medical consultant who reported that only 3 of their 62 clients who underwent a liver transplant had complications, which is less than the more common complication rate of 0.10. In that work, we did not model a null scenario, but we will discuss a simulation method for a one proportion null distribution in <a href="inference-one-prop.html#sec-one-prop-null-boot" class="quarto-xref"><span>Section 16.1</span></a>, such a distribution is provided in <a href="#fig-MedConsNullSim-w-normal" class="quarto-xref">Figure&nbsp;<span>13.10</span></a>. We have added the best-fitting normal curve to the figure, which has a mean of 0.10. Borrowing a formula that we’ll encounter in <a href="inference-one-prop.html" class="quarto-xref">Chapter&nbsp;<span>16</span></a>, the standard error of this distribution was also computed: <span class="math inline">\(SE = 0.038.\)</span></p>
</section><section id="variability-of-the-statistic-1" class="level3" data-number="13.5.2"><h3 data-number="13.5.2" class="anchored" data-anchor-id="variability-of-the-statistic-1">
<span class="header-section-number">13.5.2</span> Variability of the statistic</h3>
<p>Before we begin, we want to point out a simple detail that is easy to overlook: the null distribution we generated from the simulation is slightly skewed, and the histogram is not particularly smooth. In fact, the normal distribution only sort-of fits this model.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-MedConsNullSim-w-normal" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Normal curve overlaid on the histogram of the simulated sample proportions in the medical consultant study. The theoretical normal distribution does not fit the histogram as well as in @fig-OpportunityCostDiffs-w-normal due to the skewness of the distribution of the sample proportions. The observed sample proportion of 0.0484 is towards the tail in both the normal curve and the histogram, but it is not an extreme value. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-MedConsNullSim-w-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-MedConsNullSim-w-normal-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="Figure&nbsp;13.10: The null distribution for the sample proportion, created from 10,000 simulated studies from the medical consultant, along with the best-fitting normal model."><img src="foundations-mathematical_files/figure-html/fig-MedConsNullSim-w-normal-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Normal curve overlaid on the histogram of the simulated sample proportions in the medical consultant study. The theoretical normal distribution does not fit the histogram as well as in @fig-OpportunityCostDiffs-w-normal due to the skewness of the distribution of the sample proportions. The observed sample proportion of 0.0484 is towards the tail in both the normal curve and the histogram, but it is not an extreme value. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-MedConsNullSim-w-normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.10: The null distribution for the sample proportion, created from 10,000 simulated studies from the medical consultant, along with the best-fitting normal model.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="observed-statistic-vs.-null-statistics-1" class="level3" data-number="13.5.3"><h3 data-number="13.5.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics-1">
<span class="header-section-number">13.5.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>As always, we’ll draw a picture before finding the normal probabilities. Below is a normal distribution centered at 0.10 with a standard error of 0.038.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="foundations-mathematical_files/figure-html/MedConsNullSim-normal-only-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21"><img src="foundations-mathematical_files/figure-html/MedConsNullSim-normal-only-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Next, we can calculate the Z score using the observed complication rate, <span class="math inline">\(\hat{p} = 0.048\)</span> along with the mean and standard deviation of the normal model. Here again, we use the standard error for the standard deviation.</p>
<p><span class="math display">\[Z = \frac{\hat{p} - p_0}{SE_{\hat{p}}} = \frac{0.048 - 0.10}{0.038} = -1.37\]</span></p>
<p>Identifying <span class="math inline">\(Z = -1.37\)</span> using statistical software or in the normal probability table, we can determine that the left tail area is 0.0853 which is the estimated p-value for the hypothesis test. There is a small problem: the p-value of 0.0853 is almost 30% smaller than the simulation p-value of 0.1222 which will be calculated in <a href="inference-one-prop.html#sec-one-prop-null-boot" class="quarto-xref"><span>Section 16.1</span></a>.</p>
<p>The discrepancy is explained by the normal model’s poor representation of the null distribution in <a href="#fig-MedConsNullSim-w-normal" class="quarto-xref">Figure&nbsp;<span>13.10</span></a>. As noted earlier, the null distribution from the simulations is not very smooth, and the distribution itself is slightly skewed. That’s the bad news. The good news is that we can foresee these problems using some simple checks. We’ll learn more about these checks in the following chapters.</p>
<p>In <a href="#sec-CLTsection" class="quarto-xref"><span>Section 13.1</span></a> we noted that the two common requirements to apply the Central Limit Theorem are (1) the observations in the sample must be independent, and (2) the sample must be sufficiently large. The guidelines for this particular situation – which we will learn in <a href="inference-one-prop.html" class="quarto-xref">Chapter&nbsp;<span>16</span></a> – would have alerted us that the normal model was a poor approximation.</p>
</section><section id="conditions-for-applying-the-normal-model" class="level3" data-number="13.5.4"><h3 data-number="13.5.4" class="anchored" data-anchor-id="conditions-for-applying-the-normal-model">
<span class="header-section-number">13.5.4</span> Conditions for applying the normal model</h3>
<p>The success story in this section was the application of the normal model in the context of the opportunity cost data. However, the biggest lesson comes from the less successful attempt to use the normal approximation in the medical consultant case study.</p>
<p>Statistical techniques are like a carpenter’s tools. When used responsibly, they can produce amazing and precise results. However, if the tools are applied irresponsibly or under inappropriate conditions, they will produce unreliable results. For this reason, with every statistical method that we introduce in future chapters, we will carefully outline conditions when the method can reasonably be used. These conditions should be checked in each application of the technique.</p>
<p>After covering the introductory topics in this course, advanced study may lead to working with complex models which, for example, bring together many variables with different variability structure. Working with data that come from normal populations makes higher-order models easier to estimate and interpret. There are times when simulation, randomization, or bootstrapping are unwieldy in either structure or computational demand. Normality can often lead to excellent approximations of the data using straightforward modeling techniques.</p>
</section></section><section id="sec-casestent" class="level2" data-number="13.6"><h2 data-number="13.6" class="anchored" data-anchor-id="sec-casestent">
<span class="header-section-number">13.6</span> Case study (interval): Stents</h2>
<p>A point estimate is our best guess for the value of the parameter, so it makes sense to build the confidence interval around that value. The standard error, which is a measure of the uncertainty associated with the point estimate, provides a guide for how large we should make the confidence interval. The 68-95-99.7 rule tells us that, in general, 95% of observations are within 2 standard errors of the mean. Here, we use the value 1.96 to be slightly more precise.</p>
<div class="important">
<p><strong>Constructing a 95% confidence interval.</strong></p>
<p>When the sampling distribution of a point estimate can reasonably be modeled as normal, the point estimate we observe will be within 1.96 standard errors of the true value of interest about 95% of the time. Thus, a <strong>95% confidence interval</strong> for such a point estimate can be constructed:</p>
<p><span class="math display">\[\text{point estimate} \pm 1.96 \times SE\]</span></p>
<p>We can be <strong>95% confident</strong> this interval captures the true value.</p>
</div>
<div class="guidedpractice">
<p>Compute the area between -1.96 and 1.96 for a normal distribution with mean 0 and standard deviation 1.<a href="#fn17" class="footnote-ref" id="fnref17" role="doc-noteref"><sup>17</sup></a></p>
</div>
<div class="workedexample">
<p>The point estimate in the opportunity cost study was that 20% fewer students would buy a video if they were reminded that money not spent now could be spent later on something else. This point estimate can reasonably be modeled with a normal distribution with a standard error of <span class="math inline">\(SE = 0.078.\)</span> Construct a 95% confidence interval for the point estimate.</p>
<hr>
<p>Since we’re told the point estimate can be modeled with a normal distribution:</p>
<p><span class="math display">\[\text{point estimate} \pm 1.96 \times SE = 0.20 \pm 1.96 \times 0.078 = (0.047, 0.353)\]</span></p>
<p>We are 95% confident that the video purchase rate resulting from the treatment is between 4.7% and 35.3% lower than in the control group. Since this confidence interval does not contain 0, it is consistent with our earlier hypothesis test where we rejected the notion of “no difference”.</p>
<p>Note that we have used SE = 0.078 from the last section. However, it would more generally be appropriate to recompute the SE slightly differently for this confidence interval using sample proportions. Don’t worry about this detail for now since the two resulting standard errors are, in this case, almost identical.</p>
</div>
<section id="observed-data-2" class="level3" data-number="13.6.1"><h3 data-number="13.6.1" class="anchored" data-anchor-id="observed-data-2">
<span class="header-section-number">13.6.1</span> Observed data</h3>
<p>Consider an experiment that examined whether implanting a stent in the brain of a patient at risk for a stroke helps reduce the risk of a stroke. The results from the first 30 days of this study, which included 451 patients, are summarized in <a href="#tbl-stentStudyResultsCIsection" class="quarto-xref">Table&nbsp;<span>13.1</span></a>. These results are surprising! The point estimate suggests that patients who received stents may have a <em>higher</em> risk of stroke: <span class="math inline">\(p_{trmt} - p_{ctrl} = 0.090.\)</span></p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-stentStudyResultsCIsection" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stentStudyResultsCIsection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.1: Descriptive statistics for 30-day results for the stent study.
</figcaption><div aria-describedby="tbl-stentStudyResultsCIsection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No event</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Stroke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">control</td>
<td style="text-align: right; width: 7em;">214</td>
<td style="text-align: right; width: 7em;">13</td>
<td style="text-align: right; width: 7em;">227</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">treatment</td>
<td style="text-align: right; width: 7em;">191</td>
<td style="text-align: right; width: 7em;">33</td>
<td style="text-align: right; width: 7em;">224</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 7em;">405</td>
<td style="text-align: right; width: 7em;">46</td>
<td style="text-align: right; width: 7em;">451</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/stent30.html"><code>stent30</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
</section><section id="variability-of-the-statistic-2" class="level3" data-number="13.6.2"><h3 data-number="13.6.2" class="anchored" data-anchor-id="variability-of-the-statistic-2">
<span class="header-section-number">13.6.2</span> Variability of the statistic</h3>
<div class="workedexample">
<p>Consider the stent study and results. The conditions necessary to ensure the point estimate <span class="math inline">\(p_{trmt} - p_{ctrl} = 0.090\)</span> is nearly normal have been verified for you, and the estimate’s standard error is <span class="math inline">\(SE = 0.028.\)</span> Construct a 95% confidence interval for the change in 30-day stroke rates from usage of the stent.</p>
<hr>
<p>The conditions for applying the normal model have already been verified, so we can proceed to the construction of the confidence interval:</p>
<p><span class="math display">\[\text{point estimate} \pm 1.96 \times SE = 0.090 \pm 1.96 \times 0.028 = (0.035, 0.145)\]</span></p>
<p>We are 95% confident that implanting a stent in a stroke patient’s brain increased the risk of stroke within 30 days by a rate of 0.035 to 0.145. This confidence interval can also be used in a way analogous to a hypothesis test: since the interval does not contain 0 (is completely above 0), it means the data provide convincing evidence that the stent used in the study changed the risk of stroke within 30 days.</p>
</div>
<p>As with hypothesis tests, confidence intervals are imperfect. About 1-in-20 properly constructed 95% confidence intervals will fail to capture the parameter of interest, simply due to natural variability in the observed data. <a href="#fig-95PercentConfidenceInterval" class="quarto-xref">Figure&nbsp;<span>13.11</span></a> shows 25 confidence intervals for a proportion that were constructed from 25 different datasets that all came from the same population where the true proportion was <span class="math inline">\(p = 0.3.\)</span> However, 1 of these 25 confidence intervals happened not to include the true value. The interval which does not capture <span class="math inline">\(p=0.3\)</span> is not due to bad science. Instead, it is due to natural variability, and we should <em>expect</em> some of our intervals to miss the parameter of interest. Indeed, over a lifetime of creating 95% intervals, you should expect 5% of your reported intervals to miss the parameter of interest (unfortunately, you will not ever know which of your reported intervals captured the parameter and which missed the parameter).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-95PercentConfidenceInterval" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A series of 25 horizontal lines are drawn, representing each of 25 different samples. Each vertical line starts at the value of the lower bound of the confidence interval and ends at the value of the upper bound of the confidence interval which was created from that particular sample. In the center of the line is a solid dot at the observed proportion of successes for that particular sample. A dashed vertical line runs through the horizontal lines at p = 0.3 (which is the true value of the population proportion). 24 of the 25 horizontal lines cross the vertical line at 0.3, but one of the horizontal lines is completely lower than 0.3. The line that does not cross 0.3 is colored red because the confidence interval from that particular sample would not have captured the true population proportion.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-95PercentConfidenceInterval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="foundations-mathematical_files/figure-html/fig-95PercentConfidenceInterval-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="Figure&nbsp;13.11: Twenty-five samples of size n=300 were collected from a population with p = 0.30. For each sample, a confidence interval was created to try to capture the true proportion p. However, 1 of these 25 intervals did not capture p = 0.30."><img src="foundations-mathematical_files/figure-html/fig-95PercentConfidenceInterval-1.png" class="img-fluid figure-img" style="width:90.0%" alt="A series of 25 horizontal lines are drawn, representing each of 25 different samples. Each vertical line starts at the value of the lower bound of the confidence interval and ends at the value of the upper bound of the confidence interval which was created from that particular sample. In the center of the line is a solid dot at the observed proportion of successes for that particular sample. A dashed vertical line runs through the horizontal lines at p = 0.3 (which is the true value of the population proportion). 24 of the 25 horizontal lines cross the vertical line at 0.3, but one of the horizontal lines is completely lower than 0.3. The line that does not cross 0.3 is colored red because the confidence interval from that particular sample would not have captured the true population proportion."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-95PercentConfidenceInterval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13.11: Twenty-five samples of size <span class="math inline">\(n=300\)</span> were collected from a population with <span class="math inline">\(p = 0.30.\)</span> For each sample, a confidence interval was created to try to capture the true proportion <span class="math inline">\(p.\)</span> However, 1 of these 25 intervals did not capture <span class="math inline">\(p = 0.30.\)</span>
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>In <a href="#fig-95PercentConfidenceInterval" class="quarto-xref">Figure&nbsp;<span>13.11</span></a>, one interval does not contain the true proportion, <span class="math inline">\(p = 0.3.\)</span> Does this imply that there was a problem with the datasets that were selected?<a href="#fn18" class="footnote-ref" id="fnref18" role="doc-noteref"><sup>18</sup></a></p>
</div>
</section><section id="interpreting-confidence-intervals" class="level3" data-number="13.6.3"><h3 data-number="13.6.3" class="anchored" data-anchor-id="interpreting-confidence-intervals">
<span class="header-section-number">13.6.3</span> Interpreting confidence intervals</h3>
<p>A careful eye might have observed the somewhat awkward language used to describe confidence intervals.</p>
<div class="important">
<p><strong>Correct confidence interval interpretation.</strong></p>
<p>We are XX% confident that the population parameter is between <em>lower</em> and <em>upper</em> (where <em>lower</em> and <em>upper</em> are both numerical values).</p>
<p><strong>Incorrect</strong> language might try to describe the confidence interval as capturing the population parameter with a certain probability.</p>
<p>This is one of the most common errors: while it might be useful to think of it as a probability, the confidence level only quantifies how plausible it is that the parameter is in the interval.</p>
</div>
<p>Another especially important consideration of confidence intervals is that they <em>only try to capture the population parameter</em>. Our intervals say nothing about the confidence of capturing individual observations, a proportion of the observations, or about capturing point estimates. Confidence intervals provide an interval estimate for and attempt to capture <strong>population parameters</strong>.</p>
<p></p>
</section></section><section id="sec-chp13-review" class="level2" data-number="13.7"><h2 data-number="13.7" class="anchored" data-anchor-id="sec-chp13-review">
<span class="header-section-number">13.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="13.7.1"><h3 data-number="13.7.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">13.7.1</span> Summary</h3>
<p>We can summarise the process of using the normal model as follows:</p>
<ul>
<li>
<strong>Frame the research question.</strong> The mathematical model can be applied to both the hypothesis testing and the confidence interval framework. Make sure that your research question is being addressed by the most appropriate inference procedure.</li>
<li>
<strong>Collect data with an observational study or experiment.</strong> To address the research question, collect data on the variables of interest. Note that your data may be a random sample from a population or may be part of a randomized experiment.</li>
<li>
<strong>Model the randomness of the statistic.</strong> In many cases, the normal distribution will be an excellent model for the randomness associated with the statistic of interest. The Central Limit Theorem tells us that if the sample size is large enough, sample averages (which can be calculated as either a proportion or a sample mean) will be approximately normally distributed when describing how the statistics change from sample to sample.</li>
<li>
<strong>Calculate the variability of the statistic.</strong> Using formulas, come up with the standard deviation (or more typically, an estimate of the standard deviation called the standard error) of the statistic. The SE of the statistic will give information on how far the observed statistic is from the null hypothesized value (if performing a hypothesis test) or from the unknown population parameter (if creating a confidence interval).</li>
<li>
<strong>Use the normal distribution to quantify the variability.</strong> The normal distribution will provide a probability which measures how likely it is for your observed and hypothesized (or observed and unknown) parameter to differ by the amount measured. The unusualness (or not) of the discrepancy will form the conclusion to the research question.</li>
<li>
<strong>Form a conclusion.</strong> Using the p-value or the confidence interval from the analysis, report on the research question of interest. Also, be sure to write the conclusion in plain language so casual readers can understand the results.</li>
</ul>
<p><a href="#tbl-chp13-summary" class="quarto-xref">Table&nbsp;<span>13.2</span></a> is another look at the mathematical model approach to inference.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-chp13-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-chp13-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.2: Summary of mathematical models as an inferential statistical method.
</figcaption><div aria-describedby="tbl-chp13-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Question</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Answer</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">What does it do?</td>
<td style="text-align: left;">Uses theory (primarily the Central Limit Theorem) to describe the hypothetical variability resulting from either repeated randomized experiments or random samples</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">What is the random process described?</td>
<td style="text-align: left;">Randomized experiment or random sampling</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">What other random processes can be approximated?</td>
<td style="text-align: left;">Can also be used to describe random sampling in an observational model or random allocation in an experiment</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">What is it best for?</td>
<td style="text-align: left;">Quick analyses through, for example, calculating a Z score</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">What physical object represents the simulation process?</td>
<td style="text-align: left;">Not applicable</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="terms" class="level3" data-number="13.7.2"><h3 data-number="13.7.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">13.7.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-13" class="quarto-xref">Table&nbsp;<span>13.3</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-13" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13.3: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-13-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">95% confidence interval</td>
<td style="text-align: left; width: 12em;">normal distribution</td>
<td style="text-align: left; width: 12em;">percentile</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">95% confident</td>
<td style="text-align: left; width: 12em;">normal model</td>
<td style="text-align: left; width: 12em;">sampling distribution</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 12em;">Central Limit Theorem</td>
<td style="text-align: left; width: 12em;">normal probability table</td>
<td style="text-align: left; width: 12em;">standard error</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">margin of error</td>
<td style="text-align: left; width: 12em;">null distribution</td>
<td style="text-align: left; width: 12em;">standard normal distribution</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 12em;">normal curve</td>
<td style="text-align: left; width: 12em;">parameter</td>
<td style="text-align: left; width: 12em;">Z score</td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp13-exercises" class="level2" data-number="13.8"><h2 data-number="13.8" class="anchored" data-anchor-id="sec-chp13-exercises">
<span class="header-section-number">13.8</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-13" class="quarto-xref">Appendix&nbsp;<span>A.13</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<p><strong>Area under the curve, Part I.</strong> What percent of a standard normal distribution <span class="math inline">\(N(\mu=0, \sigma=1)\)</span> is found in each region denoted by a <span class="math inline">\(Z\)</span> inequality below? Be sure to draw a graph. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p><span class="math inline">\(Z &lt; -1.35\)</span></p></li>
<li><p><span class="math inline">\(Z &gt; 1.48\)</span></p></li>
<li><p><span class="math inline">\(-0.4 &lt; Z &lt; 1.5\)</span></p></li>
<li><p><span class="math inline">\(|Z| &gt; 2\)</span></p></li>
</ol>
</li>
</ol>
<ol start="2" type="1">
<li>
<p><strong>Area under the curve, Part II.</strong> What percent of a standard normal distribution <span class="math inline">\(N(\mu=0, \sigma=1)\)</span> is found in each region denoted by a <span class="math inline">\(Z\)</span> inequality below? Be sure to draw a graph. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p><span class="math inline">\(Z &gt; -1.13\)</span></p></li>
<li><p><span class="math inline">\(Z &lt; 0.18\)</span></p></li>
<li><p><span class="math inline">\(Z &gt; 8\)</span></p></li>
<li><p><span class="math inline">\(|Z| &lt; 0.5\)</span></p></li>
</ol>
</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>GRE scores, Z scores.</strong> Sophia who took the Graduate Record Examination (GRE) scored 160 on the Verbal Reasoning section and 157 on the Quantitative Reasoning section. The mean score for Verbal Reasoning section for all test takers was 151 with a standard deviation of 7, and the mean score for the Quantitative Reasoning was 153 with a standard deviation of 7.67. Suppose that both distributions are nearly normal. Use the information to compute each of the following. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p>Write down the short-hand for each of the two normal distributions.</p></li>
<li><p>What is Sophia’s Z score on the Verbal Reasoning section? On the Quantitative Reasoning section? Draw a standard normal distribution curve and mark the two Z scores.</p></li>
<li><p>What do the Z scores tell you?</p></li>
<li><p>Relative to others, which section did Sophia do better on?</p></li>
<li><p>Find her percentile scores for each of the two exams.</p></li>
<li><p>What percent of the test takers did better than her on the Verbal Reasoning section? On the Quantitative Reasoning section?</p></li>
<li><p>Explain why simply comparing raw scores from the two sections could lead to an incorrect conclusion as to which section a student did better on.</p></li>
<li><p>If the distributions of the scores on these exams are not nearly normal, would your answers to parts (b) - (f) change? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="4" type="1">
<li>
<p><strong>Triathlon times, Z scores.</strong> In triathlons, it is common for racers to be placed into age and gender groups. Two friends, Leo and Mary, both completed the Hermosa Beach Triathlon, where Leo competed in the “Men, Ages 30 - 34” group and Mary competed in the “Women, Ages 25 - 29” group. Leo completed the race in 1:22:28 (4948 seconds), while Mary completed the race in 1:31:53 (5513 seconds). We can see that Leo finished faster, but they are curious about how they did within their respective groups. Can you help them? Below is some information on the performance of their groups. Use the information to compute each of the following. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ul>
<li><p>The finishing times of the “Men, Ages 30 - 34” group has a mean of 4313 seconds with a standard deviation of 583 seconds.</p></li>
<li><p>The finishing times of the “Women, Ages 25 - 29” group has a mean of 5261 seconds with a standard deviation of 807 seconds.</p></li>
<li><p>The distributions of finishing times for both groups are approximately Normal.<br>
Remember: a better performance corresponds to a faster finish.</p></li>
</ul>
<ol type="a">
<li><p>Write down the short-hand for the two normal distributions.</p></li>
<li><p>What are the Z scores for each of Leo’s and Mary’s finishing times? What do the Z scores tell you?</p></li>
<li><p>Did Leo or Mary rank better in their respective group? Explain your reasoning.</p></li>
<li><p>What percent of the triathletes did Leo finish faster than in his group?</p></li>
<li><p>What percent of the triathletes did Mary finish faster than in her group?</p></li>
<li><p>If the distributions of finishing times are not nearly normal, would your answers to parts (b) – (e) change? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="5" type="1">
<li>
<p><strong>GRE scores, cutoffs.</strong> Consider the previous two distributions for GRE scores: <span class="math inline">\(N(\mu=151, \sigma=7)\)</span> for the Verbal Reasoning part of the exam and <span class="math inline">\(N(\mu=153, \sigma=7.67)\)</span> for the Quantitative Reasoning part. Use the information to compute each of the following. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p>The score of a student who scored in the <span class="math inline">\(80^{th}\)</span> percentile on the Quantitative Reasoning section.</p></li>
<li><p>The score of a student who scored worse than 70% of test takers in the Verbal Reasoning section.</p></li>
</ol>
</li>
</ol>
<ol start="6" type="1">
<li>
<p><strong>Triathlon times, cutoffs.</strong> Recall the two different distributions for triathlon times: <span class="math inline">\(N(\mu=4313, \sigma=583)\)</span> for “Men, Ages 30 - 34” and <span class="math inline">\(N(\mu=5261, \sigma=807)\)</span> for the “Women, Ages 25 - 29” group. Times are listed in seconds. Use this information to compute each of the following. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p>The cutoff time for the fastest 5% of athletes in the men’s group, i.e., those who took the shortest 5% of time to finish.</p></li>
<li><p>The cutoff time for the slowest 10% of athletes in the women’s group.</p></li>
</ol>
</li>
</ol>
<ol start="7" type="1">
<li>
<p><strong>LA weather, Fahrenheit.</strong> The average daily high temperature in June in LA is 77<span class="math inline">\(^\circ\)</span> F with a standard deviation of 5<span class="math inline">\(^\circ\)</span> F. Suppose that the temperatures in June closely follow a normal distribution. Use the information to compute each of the following. In the text above, we used R to calculate normal probabilities. You might choose to use a different source, such as a <a href="https://openintro.shinyapps.io/dist_calc/">Shiny App</a> or a normal table.</p>
<ol type="a">
<li><p>What is the probability of observing an 83<span class="math inline">\(^\circ\)</span> F temperature or higher in LA during a randomly chosen day in June?</p></li>
<li><p>How cool are the coldest 10% of the days (days with lowest high temperature) during June in LA?</p></li>
</ol>
</li>
</ol>
<ol start="8" type="1">
<li>
<p><strong>CAPM.</strong> The Capital Asset Pricing Model (CAPM) is a financial model that assumes returns on a portfolio are normally distributed. Suppose a portfolio has an average annual return of 14.7% (i.e., an average gain of 14.7%) with a standard deviation of 33%. A return of 0% means the value of the portfolio doesn’t change, a negative return means that the portfolio loses money, and a positive return means that the portfolio gains money.</p>
<ol type="a">
<li><p>What percent of years does this portfolio lose money, i.e., have a return less than 0%?</p></li>
<li><p>What is the cutoff for the highest 15% of annual returns with this portfolio?</p></li>
</ol>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>LA weather, Celsius.</strong> Recall the set-up that average daily high temperature in June in LA is 77<span class="math inline">\(^\circ\)</span> F with a standard deviation of 5<span class="math inline">\(^\circ\)</span> F, and it can be assumed that the high temperatures follow a normal distribution. We use the following equation to convert <span class="math inline">\(^\circ\)</span>F (Fahrenheit) to <span class="math inline">\(^\circ\)</span>C (Celsius): <span class="math inline">\(C = (F - 32) \times \frac{5}{9}.\)</span></p>
<ol type="a">
<li><p>Write the probability model for the distribution of temperature in <span class="math inline">\(^\circ\)</span>C in June in LA.</p></li>
<li><p>What is the probability of observing a 28<span class="math inline">\(^\circ\)</span> C (which roughly corresponds to 83<span class="math inline">\(^\circ\)</span> F) temperature or higher in June in LA? Calculate using the <span class="math inline">\(^\circ\)</span>C model from part (a).</p></li>
<li><p>Did you get the same answer or different answers in part (b) of this question and part (a) of the previous question on the LA weather? Are you surprised? Explain.</p></li>
<li><p>Estimate the IQR of the temperatures (in <span class="math inline">\(^\circ\)</span>C) in June in LA.</p></li>
</ol>
</li>
</ol>
<ol start="10" type="1">
<li>
<p><strong>Find the SD.</strong> Find the standard deviation of the distribution in the following situations.</p>
<ol type="a">
<li><p>MENSA is an organization whose members have IQs in the top 2% of the population. IQs are normally distributed with mean 100, and the minimum IQ score required for admission to MENSA is 132.</p></li>
<li><p>Cholesterol levels for women aged 20 to 34 follow an approximately normal distribution with mean 185 milligrams per deciliter (mg/dl). Women with cholesterol levels above 220 mg/dl are considered to have high cholesterol and about 18.5% of women fall into this category.</p></li>
</ol>
</li>
</ol>
<ol start="11" type="1">
<li>
<p><strong>Chronic illness.</strong> In 2013, the Pew Research Foundation reported that “45% of U.S. adults report that they live with one or more chronic conditions”. However, this value was based on a sample, so it may not be a perfect estimate for the population parameter of interest on its own. The study reported a standard error of about 1.2%, and a normal model may reasonably be used in this setting.</p>
<ol type="a">
<li><p>Create a 95% confidence interval for the proportion of U.S. adults who live with one or more chronic conditions. Also interpret the confidence interval in the context of the study. <span class="citation" data-cites="data:pewdiagnosis:2013">(<a href="references.html#ref-data:pewdiagnosis:2013" role="doc-biblioref">Pew Research Center 2013</a>)</span></p></li>
<li>
<p>Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.</p>
<ol type="i">
<li><p>We can say with certainty that the confidence interval from part (a) contains the true percentage of U.S. adults who suffer from a chronic illness.</p></li>
<li><p>If we repeated this study 1,000 times and constructed a 95% confidence interval for each study, then approximately 950 of those confidence intervals would contain the true fraction of U.S. adults who suffer from chronic illnesses.</p></li>
<li><p>The poll provides statistically discernible evidence (at the <span class="math inline">\(\alpha = 0.05\)</span> level) that the percentage of U.S. adults who suffer from chronic illnesses is below 50%.</p></li>
<li><p>Since the standard error is 1.2%, only 1.2% of people in the study communicated uncertainty about their answer.</p></li>
</ol>
</li>
</ol>
</li>
</ol>
<ol start="12" type="1">
<li>
<p><strong>Social media users and news, mathematical model.</strong> A poll conducted in 2022 found that 50% of U.S. adults (i.e., a proportion of 0.5) get news from social media sometimes or often. The standard error for this estimate was 0.5% (i.e., 0.005), and a normal distribution may be used to model the sample proportion. <span class="citation" data-cites="data:socialmedianews:2022">(<a href="references.html#ref-data:socialmedianews:2022" role="doc-biblioref">Pew Research Center 2022</a>)</span></p>
<ol type="a">
<li><p>Construct a 99% confidence interval for the fraction of U.S. adults who get news on social media sometimes or often, and interpret the confidence interval in context.</p></li>
<li>
<p>Identify each of the following statements as true or false. Provide an explanation to justify each of your answers.</p>
<ol type="i">
<li><p>The data provide statistically discernible evidence that more than half of U.S. adults users get news through social media sometimes or often. Use a discernibility level of <span class="math inline">\(\alpha = 0.01\)</span>.</p></li>
<li><p>Since the standard error is 0.5%, we can conclude that 99.5% of all U.S. adults users were included in the study.</p></li>
<li><p>If we want to reduce the standard error of the estimate, we should collect less data.</p></li>
<li><p>If we construct a 90% confidence interval for the percentage of U.S. adults who get news through social media sometimes or often, the resulting confidence interval will be wider than a corresponding 99% confidence interval.</p></li>
</ol>
</li>
</ol>
</li>
</ol>
<ol start="13" type="1">
<li>
<p><strong>Interpreting a Z score from a sample proportion.</strong> Suppose that you conduct a hypothesis test about a population proportion and calculate the Z score to be 0.47. Which of the following is the best interpretation of this value? For the problems which are not a good interpretation, indicate the statistical idea being described.<a href="#fn19" class="footnote-ref" id="fnref19" role="doc-noteref"><sup>19</sup></a></p>
<ol type="a">
<li><p>The probability is 0.47 that the null hypothesis is true.</p></li>
<li><p>If the null hypothesis were true, the probability would be 0.47 of obtaining a sample proportion as far as observed from the hypothesized value of the population proportion.</p></li>
<li><p>The sample proportion is 0.47 standard errors greater than the hypothesized value of the population proportion.</p></li>
<li><p>The sample proportion is equal to 0.47 times the standard error.</p></li>
<li><p>The sample proportion is 0.47 away from the hypothesized value of the population.</p></li>
<li><p>The sample proportion is 0.47.</p></li>
</ol>
</li>
</ol>
<ol start="14" type="1">
<li>
<p><strong>Mental health.</strong> The General Social Survey asked the question: “For how many days during the past 30 days was your mental health, which includes stress, depression, and problems with emotions, not good?” Based on responses from 1,151 US residents, the survey reported a 95% confidence interval of 3.40 to 4.24 days in 2010.</p>
<ol type="a">
<li><p>Interpret this interval in context of the data.</p></li>
<li><p>What does “95% confident” mean? Explain in the context of the application.</p></li>
<li><p>Suppose the researchers think a 99% confidence level would be more appropriate for this interval. Will this new interval be smaller or wider than the 95% confidence interval?</p></li>
<li><p>If a new survey were to be done with 500 Americans, do you think the standard error of the estimate be larger, smaller, or about the same.</p></li>
</ol>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Repeated water samples.</strong> A nonprofit wants to understand the fraction of households that have elevated levels of lead in their drinking water. They expect at least 5% of homes will have elevated levels of lead, but not more than about 30%. They randomly sample 800 homes and work with the owners to retrieve water samples, and they compute the fraction of these homes with elevated lead levels. They repeat this 1,000 times and build a distribution of sample proportions.</p>
<ol type="a">
<li><p>What is this distribution called?</p></li>
<li><p>Would you expect the shape of this distribution to be symmetric, right skewed, or left skewed? Explain your reasoning.</p></li>
<li><p>What is the name of the variability of this distribution.</p></li>
<li><p>Suppose the researchers’ budget is reduced, and they are only able to collect 250 observations per sample, but they can still collect 1,000 samples. They build a new distribution of sample proportions. How will the variability of this new distribution compare to the variability of the distribution when each sample contained 800 observations?</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>Repeated student samples.</strong> Of all freshman at a large college, 16% made the dean’s list in the current year. As part of a class project, students randomly sample 40 students and check if those students made the list. They repeat this 1,000 times and build a distribution of sample proportions.</p>
<ol type="a">
<li><p>What is this distribution called?</p></li>
<li><p>Would you expect the shape of this distribution to be symmetric, right skewed, or left skewed? Explain your reasoning.</p></li>
<li><p>What is the name of the variability of this distribution?</p></li>
<li><p>Suppose the students decide to sample again, this time collecting 90 students per sample, and they again collect 1,000 samples. They build a new distribution of sample proportions. How will the variability of this new distribution compare to the variability of the distribution when each sample contained 40 observations?</p></li>
</ol>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-data:pewdiagnosis:2013" class="csl-entry" role="listitem">
Pew Research Center. 2013. <span>“The Diagnosis Difference.”</span> <a href="https://www.openintro.org/go?id=textbook-pew-2013-diagnosis-difference">https://www.openintro.org/go?id=textbook-pew-2013-diagnosis-difference</a>.
</div>
<div id="ref-data:socialmedianews:2022" class="csl-entry" role="listitem">
———. 2022. <span>“News Consumption Across Digital Platforms.”</span> <a href="https://www.pewresearch.org/journalism/fact-sheet/news-platform-fact-sheet/pj_2022-09-20_news-platforms_0-03b/">https://www.pewresearch.org/journalism/fact-sheet/news-platform-fact-sheet/pj_2022-09-20_news-platforms_0-03b/</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>In general, the distributions are reasonably symmetric. The case study for the medical consultant is the only distribution with any evident skew (the distribution is skewed right).<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>It is also introduced as the Gaussian distribution after Frederic Gauss, the first person to formalize its mathematical expression.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>We use the standard deviation as a guide. Nel is 1 standard deviation above average on the SAT: <span class="math inline">\(1500 + 300 = 1800.\)</span> Sian is 0.6 standard deviations above the mean on the ACT: <span class="math inline">\(21+0.6 \times 5 = 24.\)</span> In <a href="#fig-satActNormals" class="quarto-xref">Figure&nbsp;<span>13.5</span></a>, we can see that Nel did better compared to other test takers than Sian did, so their score was better.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><span class="math inline">\(Z_{Sian} = \frac{x_{Sian} - \mu_{ACT}}{\sigma_{ACT}} = \frac{24 - 21}{5} = 0.6\)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>For <span class="math inline">\(x_1=95.4\)</span> mm: <span class="math inline">\(Z_1 = \frac{x_1 - \mu}{\sigma} = \frac{95.4 - 92.6}{3.6} = 0.78.\)</span> For <span class="math inline">\(x_2=85.8\)</span> mm: <span class="math inline">\(Z_2 = \frac{85.8 - 92.6}{3.6} = -1.89.\)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Because the <em>absolute value</em> of Z score for the second observation is larger than that of the first, the second observation has a more unusual head length.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>If 84% had lower scores than Nel, the number of people who had better scores must be 16%. (Generally ties are ignored when the normal model, or any other continuous distribution, is used.)<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>We found the probability to be 0.6664. A picture for this exercise is represented by the shaded area below “0.6664”.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>Numerical answers: (a) 0.9772. (b) 0.0228.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>This sample was taken from the USDA Food Commodity Intake Database.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn11"><p>Remember: draw a picture first, then find the Z score. (We leave the pictures to you.) The Z score can be found by using the percentiles and the normal probability table. (a) We look for 0.95 in the probability portion (middle part) of the normal probability table, which leads us to row 1.6 and (about) column 0.05, i.e., <span class="math inline">\(Z_{95}=1.65.\)</span> Knowing <span class="math inline">\(Z_{95}=1.65,\)</span> <span class="math inline">\(\mu = 1500,\)</span> and <span class="math inline">\(\sigma = 300,\)</span> we setup the Z score formula: <span class="math inline">\(1.65 = \frac{x_{95} - 1500}{300}.\)</span> We solve for <span class="math inline">\(x_{95}\)</span>: <span class="math inline">\(x_{95} = 1995.\)</span> (b) Similarly, we find <span class="math inline">\(Z_{97.5} = 1.96,\)</span> again setup the Z score formula for the heights, and calculate <span class="math inline">\(x_{97.5} = 76.5.\)</span><a href="#fnref11" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn12"><p>Numerical answers: (a) 0.1131. (b) 0.3821.<a href="#fnref12" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn13"><p>This is an abbreviated solution. (Be sure to draw a figure!) First find the percent who get below 1500 and the percent that get above 2000: <span class="math inline">\(Z_{1500} = 0.00 \to 0.5000\)</span> (area below), <span class="math inline">\(Z_{2000} = 1.67 \to 0.0475\)</span> (area above). Final answer: <span class="math inline">\(1.0000-0.5000 - 0.0475 = 0.4525.\)</span><a href="#fnref13" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn14"><p>5’5” is 65 inches. 5’7” is 67 inches. Numerical solution: <span class="math inline">\(1.000 - 0.0649 - 0.8183 = 0.1168,\)</span> i.e., 11.68%.<a href="#fnref14" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn15"><p>First draw the pictures. To find the area between <span class="math inline">\(Z=-1\)</span> and <span class="math inline">\(Z=1,\)</span> use <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code> or the normal probability table to determine the areas below <span class="math inline">\(Z=-1\)</span> and above <span class="math inline">\(Z=1.\)</span> Next verify the area between <span class="math inline">\(Z=-1\)</span> and <span class="math inline">\(Z=1\)</span> is about 0.68. Repeat this for <span class="math inline">\(Z=-2\)</span> to <span class="math inline">\(Z=2\)</span> and for <span class="math inline">\(Z=-3\)</span> to <span class="math inline">\(Z=3.\)</span><a href="#fnref15" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn16"><p>900 and 2100 represent two standard deviations above and below the mean, which means about 95% of test takers will score between 900 and 2100. Since the normal model is symmetric, then half of the test takers from part (a) (<span class="math inline">\(\frac{95\%}{2} = 47.5\%\)</span> of all test takers) will score 900 to 1500 while 47.5% score between 1500 and 2100.<a href="#fnref16" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn17"><p>We will leave it to you to draw a picture. The Z scores are <span class="math inline">\(Z_{left} = -1.96\)</span> and <span class="math inline">\(Z_{right} = 1.96.\)</span> The area between these two Z scores is <span class="math inline">\(0.9750 - 0.0250 = 0.9500.\)</span> This is where “1.96” comes from in the 95% confidence interval formula.<a href="#fnref17" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn18"><p>No. Just as some observations occur more than 1.96 standard deviations from the mean, some point estimates will be more than 1.96 standard errors from the parameter. A confidence interval only provides a plausible range of values for a parameter. While we might say other values are implausible based on the data, this does not mean they are impossible.<a href="#fnref18" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn19"><p>This exercise was inspired by discussion on Dr.&nbsp;Allan Rossman’s blog <a href="https://askgoodquestions.blog/">Ask Good Questions</a>.<a href="#fnref19" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./foundations-bootstrapping.html" class="pagination-link" aria-label="Confidence intervals with bootstrapping">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./foundations-errors.html" class="pagination-link" aria-label="Decision Errors">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/foundations-mathematical.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>