---
title: "HW Chp6"
author: "Jo Hardin"
date: "3/19/2021"
output: html_document
---

## Inv 4.1 Which samples of size 3 are "more extreme" than what we observed?

(a) 53, 56, 64
(b) 55, 55, 56
(c) 55, 55, 64
(d) 55, 56, 64

## Look at Jessica's book, how does she frame her thought questions? Add questions like that to the begining of each case study.

## Problem 1 (MDSR)

A categorical variable is XXX.
Show scatter plot with continuous x and y.
how can you differentiate the points based on the categorical variable?

## Problem 2 (MDSR - exactly copied): Find two graphs published in a newspaper or on the internet in the last two years.

Identify a graphical display that you find compelling.
What aspects of the display work well, and how do these relate to the principles established in this chapter?
Include a screen shot of the display along with your solution.

Identify a graphical display that you find less than compelling.
What aspects of the display don't work well?
Are there ways that the display might be improved?
Include a screen shot of the display along with your solution.

## Problem 3: WGOITG

<https://www.nytimes.com/column/whats-going-on-in-this-graph>

## Problem 4: steal some of Ben's viz links? All are too hard.

<http://mdsr-book.github.io/exercises.html#exercise_25>

## Problem 4: WEB Du Bois (please, please, let's include!) can we get the liscences???

<https://github.com/ajstarks/dubois-data-portraits/tree/master/challenge>

-   What do the colors tell us?
-   What do the labels add?

faceted bar plots in challenge 2: <https://github.com/ajstarks/dubois-data-portraits/tree/master/challenge/challenge02>
