--- 
title: "Introduction to Statistics with Randomization and Simulation"
author: "Mine Çetinkaya-Rundel, Johanna Hardin, David Diez, others..."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is ISRS2!"
header-includes:
- \usepackage{subfig}
---

# Welcome {-}

<!--
This book may be downloaded as a free PDF at [openintro.org](http://www.openintro.org).
-->

**change again**

We hope readers will take away three ideas from this book in addition to forming a foundation of statistical thinking and methods.

1. Statistics is an applied field with a wide range of practical applications.
2. You don't have to be a math guru to learn from interesting, real data.
3. Data are messy, and statistical tools are imperfect. However, when you understand the strengths and weaknesses of these tools, you can use them to learn interesting things about the~world.

**IMPORTANT NOTE:** This book is currently in active development, and is planned for launch in late 2020 as the 2nd edition of OpenIntro Statistics - Introduction to Statistics with Randomization and Simulation. The 1st edition of the book can be accessed at [openintro.org/book/isrs/](https://www.openintro.org/book/isrs/).

## Textbook overview {-}

1. **Introduction to data.** Data structures, variables, summaries, graphics, and basic data collection techniques.
2. **Exploratory data analysis.** Data visualization and summarisation.
3. **Correlation and regression.** Visualising relationships between many variables and descriptive summaries for quantifying the relationship between two variables.
4. **Multiple regression.** Descriptive summaries for quantifying the relationship between two variables.
5. **Foundations for inference.** Case studies are used to introduce the ideas of statistical inference with randomization and simulations. 
6. **Inference for categorical data.** Inference for proportions using simulation and randomization techniques as well as the normal and chi-square distributions.
7. **Inference for numerical data.** Inference for one or two sample means using simulation and randomization techniques as well as the normal and F distributions.
8. **Inference for regression.** Extending inference techniques presented thus-far to regression settings.
7. **Appendix: Probability.** An introduction to probability is provided as an optional reference. Exercises and additional probability content may be found in Chapter~3 of OpenIntro Statistics at [openintro.org/book/os](https://www.openintro.org/book/os/).

## Examples, exercises, and additional appendices {-}

Examples and guided practice exercises throughout the textbook may be identified by their distinctive bullets:

[MCR-TODO: Need to update language below]

<!--
\begin{example}{Large filled bullets signal the start of an example.}
Full solutions to examples are provided and often include an accompanying table or figure.
 \end{example}

\begin{exercise}
Large empty bullets signal to readers that an exercise has been inserted into the text for additional practice and guidance. Solutions for all guided practice exercises are provided in footnotes.\footnote{Full solutions are located down here in the footnote!}
\end{exercise}

Exercises at the end of each chapter are useful for practice or homework assignments. Many of these questions have multiple parts, and solutions to odd-numbered exercises can be found in Appendix~\ref{eoceSolutions}. %These end-of-chapter exercises are also available online in a public question bank at \textbf{openintro.org}, and the available selection is constantly growing based on teacher contributions. Numbered citations in end-of-chapter exercises may be found in Appendix~B.

Probability tables for the normal, $t$, and chi-square distributions are in Appendix~\ref{distributionTables}, and PDF copies of these tables are also available from \href{http://www.openintro.org}{\color{black}\textbf{openintro.org}}.

-->

## OpenIntro, online resources, and getting involved {-}

OpenIntro is an organization focused on developing free and affordable education materials.

We encourage anyone learning or teaching statistics to visit [openintro.org] (http://www.openintro.org) and get involved. We also provide many free online resources, including free course software. Students can test their knowledge with practice quizzes for each chapter or try an application of concepts learned using real data. 

Data sets for this textbook are available on the website and through a companion R package, [**openintro**](http://openintrostat.github.io/openintro-r-package/).^[Mine Çetinkaya-Rundel, David Diez, Andrew Bray, Albert Kim, Ben Baumer, Chester Ismay and Christopher Barr (2019). openintro: Data Sets and Supplemental Functions from 'OpenIntro' Textbooks and Labs. R package version 2.0.1. https://github.com/OpenIntroStat/openintro-r-package.] All of these resources are free, and we want to be clear that anyone is welcome to use these online tools and resources with or without this textbook as a companion.

We value your feedback. If there is a part of the project you especially like or think needs improvement, we want to hear from you. You may find our contact form at [openintro.org](https://www.openintro.org/form/?f=contact).

## Acknowledgements {-}

[MCR-TODO: Will need to update language and people mentioned here.]

This project would not be possible without the dedication and volunteer hours of all those involved. No one has received any monetary compensation from this project, and we hope you will join us in extending a *thank you* to all those who volunteer with OpenIntro.

The authors would especially like to thank Andrew Bray and Meenal Patel for their involvement and contributions to this textbook. We are also grateful to Andrew Bray, Ben Baumer, and David Laffie for providing us with valuable feedback based on their experiences while teaching with this textbook, and to the many teachers, students, and other readers who have helped improve OpenIntro resources through their feedback.

The authors would like to specially thank George Cobb of Mount Holyoke College and Chris Malone of Winona State University. George has spent a good part of his career supporting the use of nonparametric techniques in introductory statistics, and Chris was helpful in discussing practical considerations for the ordering of inference used in this textbook. Thank you, George and Chris!

