<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>24&nbsp; Inference for linear regression with a single predictor – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inf-model-mlr.html" rel="next">
<link href="./inferential-modeling.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c115713b74ff8bcd8ed35270603a4893.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b48b13b17e828e7fee5d86eb98a32420.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c115713b74ff8bcd8ed35270603a4893.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-790f3f5e7e2e01ab58e527b05f631cee.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inferential-modeling.html">Inferential modeling</a></li><li class="breadcrumb-item"><a href="./inf-model-slr.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#case-study-sandwich-store" id="toc-case-study-sandwich-store" class="nav-link active" data-scroll-target="#case-study-sandwich-store"><span class="header-section-number">24.1</span> Case study: Sandwich store</a>
  <ul class="collapse">
<li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">24.1.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">24.1.2</span> Variability of the statistic</a></li>
  </ul>
</li>
  <li>
<a href="#sec-randslope" id="toc-sec-randslope" class="nav-link" data-scroll-target="#sec-randslope"><span class="header-section-number">24.2</span> Randomization test for the slope</a>
  <ul class="collapse">
<li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">24.2.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-1" id="toc-variability-of-the-statistic-1" class="nav-link" data-scroll-target="#variability-of-the-statistic-1"><span class="header-section-number">24.2.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics" id="toc-observed-statistic-vs.-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics"><span class="header-section-number">24.2.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-bootbeta1" id="toc-sec-bootbeta1" class="nav-link" data-scroll-target="#sec-bootbeta1"><span class="header-section-number">24.3</span> Bootstrap confidence interval for the slope</a>
  <ul class="collapse">
<li><a href="#observed-data-2" id="toc-observed-data-2" class="nav-link" data-scroll-target="#observed-data-2"><span class="header-section-number">24.3.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-2" id="toc-variability-of-the-statistic-2" class="nav-link" data-scroll-target="#variability-of-the-statistic-2"><span class="header-section-number">24.3.2</span> Variability of the statistic</a></li>
  </ul>
</li>
  <li>
<a href="#sec-mathslope" id="toc-sec-mathslope" class="nav-link" data-scroll-target="#sec-mathslope"><span class="header-section-number">24.4</span> Mathematical model for testing the slope</a>
  <ul class="collapse">
<li><a href="#observed-data-3" id="toc-observed-data-3" class="nav-link" data-scroll-target="#observed-data-3"><span class="header-section-number">24.4.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-3" id="toc-variability-of-the-statistic-3" class="nav-link" data-scroll-target="#variability-of-the-statistic-3"><span class="header-section-number">24.4.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics-1" id="toc-observed-statistic-vs.-null-statistics-1" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics-1"><span class="header-section-number">24.4.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li><a href="#mathematical-model-interval-for-the-slope" id="toc-mathematical-model-interval-for-the-slope" class="nav-link" data-scroll-target="#mathematical-model-interval-for-the-slope"><span class="header-section-number">24.5</span> Mathematical model, interval for the slope</a></li>
  <li>
<a href="#sec-tech-cond-linmod" id="toc-sec-tech-cond-linmod" class="nav-link" data-scroll-target="#sec-tech-cond-linmod"><span class="header-section-number">24.6</span> Checking model conditions</a>
  <ul class="collapse">
<li><a href="#what-are-the-technical-conditions-for-the-mathematical-model" id="toc-what-are-the-technical-conditions-for-the-mathematical-model" class="nav-link" data-scroll-target="#what-are-the-technical-conditions-for-the-mathematical-model"><span class="header-section-number">24.6.1</span> What are the technical conditions for the mathematical model?</a></li>
  <li><a href="#why-do-we-need-technical-conditions" id="toc-why-do-we-need-technical-conditions" class="nav-link" data-scroll-target="#why-do-we-need-technical-conditions"><span class="header-section-number">24.6.2</span> Why do we need technical conditions?</a></li>
  <li><a href="#what-if-all-the-technical-conditions-are-met" id="toc-what-if-all-the-technical-conditions-are-met" class="nav-link" data-scroll-target="#what-if-all-the-technical-conditions-are-met"><span class="header-section-number">24.6.3</span> What if all the technical conditions are met?</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp24-review" id="toc-sec-chp24-review" class="nav-link" data-scroll-target="#sec-chp24-review"><span class="header-section-number">24.7</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">24.7.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">24.7.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp24-exercises" id="toc-sec-chp24-exercises" class="nav-link" data-scroll-target="#sec-chp24-exercises"><span class="header-section-number">24.8</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inf-model-slr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./inferential-modeling.html">Inferential modeling</a></li><li class="breadcrumb-item"><a href="./inf-model-slr.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-inf-model-slr" class="quarto-section-identifier"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>We now bring together ideas of inferential analyses with the descriptive models seen in <a href="model-slr.html" class="quarto-xref">Chapter&nbsp;<span>7</span></a>. In particular, we will use the least squares regression line to test whether there is a relationship between two continuous variables. Additionally, we will build confidence intervals which quantify the slope of the linear regression line. The setting is now focused on predicting a numeric response variable (for linear models) or a binary response variable (for logistic models), we continue to ask questions about the variability of the model from sample to sample. The sampling variability will inform the conclusions about the population that can be drawn.</p>
<p>Many of the inferential ideas are remarkably similar to those covered in previous chapters. The technical conditions for linear models are typically assessed graphically, although independence of observations continues to be of utmost importance.</p>
<p>We encourage the reader to think broadly about the models at hand without putting too much dependence on the exact p-values that are reported from the statistical software. Inference on models with multiple explanatory variables can suffer from data snooping which results in false positive claims. We provide some guidance and hope the reader will further their statistical learning after working through the material in this text.</p>
</div>
<section id="case-study-sandwich-store" class="level2" data-number="24.1"><h2 data-number="24.1" class="anchored" data-anchor-id="case-study-sandwich-store">
<span class="header-section-number">24.1</span> Case study: Sandwich store</h2>
<section id="observed-data" class="level3" data-number="24.1.1"><h3 data-number="24.1.1" class="anchored" data-anchor-id="observed-data">
<span class="header-section-number">24.1.1</span> Observed data</h3>
<p>We start the chapter with a hypothetical example describing the linear relationship between dollars spent advertising for a chain sandwich restaurant and monthly revenue. The hypothetical example serves the purpose of illustrating how a linear model varies from sample to sample. Because we have made up the example and the data (and the entire population), we can take many many samples from the population to visualize the variability. Note that in real life, we always have exactly one sample (that is, one dataset), and through the inference process, we imagine what might have happened had we taken a different sample. The change from sample to sample leads to an understanding of how the single observed dataset is different from the population of values, which is typically the fundamental goal of inference.</p>
<p>Consider the following hypothetical population of all of the sandwich stores of a particular chain seen in <a href="#fig-sandpop" class="quarto-xref">Figure&nbsp;<span>24.1</span></a>. In this made-up world, the CEO actually has all the relevant data, which is why they can plot it here. The CEO is omniscient and can write down the population model which describes the true population relationship between the advertising dollars and revenue. There appears to be a linear relationship between advertising dollars and revenue (both in $1,000).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sandpop" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatterplot with advertising amount on the x-axis and revenue on the y-axis.  A linear model is superimposed. The points show a reasonably strong and positive linear trend.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sandpop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-sandpop-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;24.1: Revenue as a linear model of advertising dollars for a population of sandwich stores, in thousands of dollars."><img src="inf-model-slr_files/figure-html/fig-sandpop-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Scatterplot with advertising amount on the x-axis and revenue on the y-axis.  A linear model is superimposed. The points show a reasonably strong and positive linear trend."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sandpop-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.1: Revenue as a linear model of advertising dollars for a population of sandwich stores, in thousands of dollars.
</figcaption></figure>
</div>
</div>
</div>
<p>You may remember from <a href="model-slr.html" class="quarto-xref"><span>Chapter 7</span></a> that the population model is: <span class="math display">\[y = \beta_0 + \beta_1 x + \varepsilon.\]</span></p>
<p>Again, the omniscient CEO (with the full population information) can write down the true population model as: <span class="math display">\[\texttt{expected revenue} = 11.23 + 4.8 \times \texttt{advertising}.\]</span></p>
</section><section id="variability-of-the-statistic" class="level3" data-number="24.1.2"><h3 data-number="24.1.2" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">24.1.2</span> Variability of the statistic</h3>
<p>Unfortunately, in our scenario, the CEO is not willing to part with the full set of data, but they will allow potential franchise buyers to see a small sample of the data in order to help the potential buyer decide whether set up a new franchise. The CEO is willing to give each potential franchise buyer a random sample of data from 20 stores.</p>
<p>As with any numerical characteristic which describes a subset of the population, the estimated slope of a sample will vary from sample to sample. Consider the linear model which describes revenue (in $1,000) based on advertising dollars (in $1,000).</p>
<p>The least squares regression model uses the data to find a sample linear fit: <span class="math display">\[\hat{y} = b_0 + b_1 x.\]</span></p>
<p>Two random samples of 20 stores shows different least squares regression lines in <a href="#fig-sand-samp-1" class="quarto-xref">Figure&nbsp;<span>24.2 (a)</span></a> and <a href="#fig-sand-samp-2" class="quarto-xref">Figure&nbsp;<span>24.2 (b)</span></a>, depending on which observations are selected. Both trends are similar to those seen in <a href="#fig-sandpop" class="quarto-xref">Figure&nbsp;<span>24.1</span></a>, which describes the population.</p>
<div id="fig-sand-samp" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sand-samp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sand-samp" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-sand-samp-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="For two random samples of 20 stores, scatterplots with advertising amount on  the x-axis and revenue on the y-axis. Linear models are superimposed.  The points in each plot show reasonably strong and positive linear trends. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sand-samp-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-sand-samp-1.png" class="lightbox" data-gallery="fig-sand-samp" title="Figure&nbsp;24.2&nbsp;(a): First sample."><img src="inf-model-slr_files/figure-html/fig-sand-samp-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-sand-samp" alt="For two random samples of 20 stores, scatterplots with advertising amount on  the x-axis and revenue on the y-axis. Linear models are superimposed.  The points in each plot show reasonably strong and positive linear trends. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sand-samp-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) First sample.
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-sand-samp" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-sand-samp-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="For two random samples of 20 stores, scatterplots with advertising amount on  the x-axis and revenue on the y-axis. Linear models are superimposed.  The points in each plot show reasonably strong and positive linear trends. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-sand-samp-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-sand-samp-2.png" class="lightbox" data-gallery="fig-sand-samp" title="Figure&nbsp;24.2&nbsp;(b): Second sample."><img src="inf-model-slr_files/figure-html/fig-sand-samp-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-sand-samp" alt="For two random samples of 20 stores, scatterplots with advertising amount on  the x-axis and revenue on the y-axis. Linear models are superimposed.  The points in each plot show reasonably strong and positive linear trends. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-sand-samp-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Second sample.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sand-samp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.2: Two random samples of 20 stores from the entire population. A linear trend between advertising and revenue is observed in both.
</figcaption></figure>
</div>
<p><a href="#fig-sand-samp12" class="quarto-xref">Figure&nbsp;<span>24.3</span></a> shows the two samples and the least squares regressions from <a href="#fig-sand-samp" class="quarto-xref">Figure&nbsp;<span>24.2</span></a> on the same plot. We can see that the two lines are different. That is, there is <strong>variability</strong> in the regression line from sample to sample. The concept of the sampling variability is something you’ve seen before, but in this lesson, you will focus on the variability of the line often measured through the variability of a single statistic: <strong>the slope of the line</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sand-samp12" class="quarto-float quarto-figure quarto-figure-center anchored" alt="For two different random samples, superimposed onto the same plot,  scatterplot with advertising amount on the x-axis and revenue on the y-axis.  Two linear models are plotted to demonstrate that the lines are very similar,  yet they are not the same. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sand-samp12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-sand-samp12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;24.3: The linear models from the two random samples are quite similar, but not exactly the same."><img src="inf-model-slr_files/figure-html/fig-sand-samp12-1.png" class="img-fluid figure-img" style="width:90.0%" alt="For two different random samples, superimposed onto the same plot,  scatterplot with advertising amount on the x-axis and revenue on the y-axis.  Two linear models are plotted to demonstrate that the lines are very similar,  yet they are not the same. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sand-samp12-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.3: The linear models from the two random samples are quite similar, but not exactly the same.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-slopes" class="quarto-xref">Figure&nbsp;<span>24.4</span></a> shows least squares lines fit to many more random samples of 20 from the population.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-slopes" class="quarto-float quarto-figure quarto-figure-center anchored" alt="An x-y coordinate system with least squares regression lines from many  random samples of size 20 (no points are plotted). The lines vary around the  true population line. On the x-axis is advertising amount; on the y-axis  is revenue. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-slopes-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;24.4: If repeated samples of size 20 are taken from the entire population, each linear model will be slightly different. The red line provides the linear fit to the entire population."><img src="inf-model-slr_files/figure-html/fig-slopes-1.png" class="img-fluid figure-img" style="width:90.0%" alt="An x-y coordinate system with least squares regression lines from many  random samples of size 20 (no points are plotted). The lines vary around the  true population line. On the x-axis is advertising amount; on the y-axis  is revenue. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-slopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.4: If repeated samples of size 20 are taken from the entire population, each linear model will be slightly different. The red line provides the linear fit to the entire population.
</figcaption></figure>
</div>
</div>
</div>
<p>You might notice in <a href="#fig-slopes" class="quarto-xref">Figure&nbsp;<span>24.4</span></a> that the <span class="math inline">\(\hat{y}\)</span> values given by the lines are much more consistent in the middle of the dataset than at the ends. The reason is that the data itself anchors the lines in such a way that the line must pass through the center of the data cloud. The effect of the fan-shaped lines is that predicted revenue for advertising close to $4,000 will be much more precise than the revenue predictions made for $1,000 or $7,000 of advertising.</p>
<p>The distribution of slopes (for samples of size <span class="math inline">\(n=20\)</span>) can be seen in <a href="#fig-sand20lm" class="quarto-xref">Figure&nbsp;<span>24.5</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sand20lm" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of the slope values from many random samples of size 20.  The slope estimates vary from about 2.1 to 8. The histogram is reasonably bell-shaped.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sand20lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-sand20lm-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;24.5: Variability of slope estimates from many different samples of stores, each of size 20."><img src="inf-model-slr_files/figure-html/fig-sand20lm-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of the slope values from many random samples of size 20.  The slope estimates vary from about 2.1 to 8. The histogram is reasonably bell-shaped."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sand20lm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.5: Variability of slope estimates from many different samples of stores, each of size 20.
</figcaption></figure>
</div>
</div>
</div>
<p>Recall, the example described in this introduction is hypothetical. That is, we created an entire population in order to demonstrate how the slope of a line would vary from sample to sample. The tools in this textbook are designed to evaluate only one single sample of data. With actual studies, we do not have repeated samples, so we are not able to use repeated samples to visualize the variability in slopes. We have seen variability in samples throughout this text, so it should not come as a surprise that different samples will produce different linear models. However, it is nice to visually consider the linear models produced by different slopes. Additionally, as with measuring the variability of previous statistics (e.g., <span class="math inline">\(\overline{X}_1 - \overline{X}_2\)</span> or <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span>), the histogram of the sample statistics can provide information related to inferential considerations.</p>
<p>In the following sections, the distribution (i.e., histogram) of <span class="math inline">\(b_1\)</span> (the estimated slope coefficient) will be constructed in the same three ways that, by now, may be familiar to you. First (in <a href="#sec-randslope" class="quarto-xref"><span>Section 24.2</span></a>), the distribution of <span class="math inline">\(b_1\)</span> when <span class="math inline">\(\beta_1 = 0\)</span> is constructed by randomizing (permuting) the response variable. Next (in <a href="#sec-bootbeta1" class="quarto-xref"><span>Section 24.3</span></a>), we can bootstrap the data by taking random samples of size <span class="math inline">\(n\)</span> from the original dataset. And last (in <a href="#sec-mathslope" class="quarto-xref"><span>Section 24.4</span></a>), we use mathematical tools to describe the variability using the <span class="math inline">\(t\)</span>-distribution that was first encountered in <a href="inference-one-mean.html#sec-one-mean-math" class="quarto-xref"><span>Section 19.2</span></a>.</p>
</section></section><section id="sec-randslope" class="level2" data-number="24.2"><h2 data-number="24.2" class="anchored" data-anchor-id="sec-randslope">
<span class="header-section-number">24.2</span> Randomization test for the slope</h2>
<p></p>
<p>Consider data on 100 randomly selected births gathered originally from the US Department of Health and Human Services. Some of the variables are plotted in <a href="#fig-babyweight" class="quarto-xref">Figure&nbsp;<span>24.6</span></a>.</p>
<p>The scientific research interest at hand will be in determining the linear relationship between weight of baby at birth (in lbs) and number of weeks of gestation. The dataset is quite rich and deserves exploring, but for this example, we will focus only on the weight of the baby.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package. We will work with a random sample of 100 observations from these data.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-babyweight" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four different scatterplots, all with weight of baby on the y-axis.  On the x-axis are weight gained by mother, mother's age, number of hospital  visits, and weeks gestation. Weeks gestation and weight of baby show the  strongest linear relationship (which is positive).">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-babyweight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-babyweight-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;24.6: Weight of baby at birth (in lbs) as plotted by four other birth variables (mother’s weight gain, mother’s age, number of hospital visits, and weeks gestation)."><img src="inf-model-slr_files/figure-html/fig-babyweight-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Four different scatterplots, all with weight of baby on the y-axis.  On the x-axis are weight gained by mother, mother's age, number of hospital  visits, and weeks gestation. Weeks gestation and weight of baby show the  strongest linear relationship (which is positive)."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-babyweight-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.6: Weight of baby at birth (in lbs) as plotted by four other birth variables (mother’s weight gain, mother’s age, number of hospital visits, and weeks gestation).
</figcaption></figure>
</div>
</div>
</div>
<p>As you have seen previously, statistical inference typically relies on setting a null hypothesis which is hoped to be subsequently rejected. In the linear model setting, we might hope to have a linear relationship between <code>weeks</code> and <code>weight</code> in settings where <code>weeks</code> gestation is known and <code>weight</code> of baby needs to be predicted.</p>
<p>The relevant hypotheses for the linear model setting can be written in terms of the population slope parameter. Here the population refers to a larger population of births in the US.</p>
<ul>
<li>
<span class="math inline">\(H_0: \beta_1= 0\)</span>, there is no linear relationship between <code>weight</code> and <code>weeks</code>.</li>
<li>
<span class="math inline">\(H_A: \beta_1 \ne 0\)</span>, there is some linear relationship between <code>weight</code> and <code>weeks</code>.</li>
</ul>
<p>Recall that for the randomization test, we permute one variable to eliminate any existing relationship between the variables. That is, we set the null hypothesis to be true, and we measure the natural variability in the data due to sampling but <strong>not</strong> due to variables being correlated. <a href="#fig-permweightScatter-1" class="quarto-xref">Figure&nbsp;<span>24.7 (a)</span></a> shows the observed data and <a href="#fig-permweightScatter-2" class="quarto-xref">Figure&nbsp;<span>24.7 (b)</span></a> shows one permutation of the <code>weight</code> variable. The careful observer can see that each of the observed values for <code>weight</code> (and for <code>weeks</code>) exist in both the original data plot as well as the permuted <code>weight</code> plot, but the <code>weight</code> and <code>weeks</code> gestation are no longer matched for a given birth. That is, each <code>weight</code> value is randomly assigned to a new <code>weeks</code> gestation.</p>
<p>By repeatedly permuting the response variable, any pattern in the linear model that is observed is due only to random chance (and not an underlying relationship). The randomization test compares the slopes calculated from the permuted response variable with the observed slope. If the observed slope is inconsistent with the slopes from permuting, we can conclude that there is some underlying relationship (and that the slope is not merely due to random chance).</p>
<div id="fig-permweightScatter" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-permweightScatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-permweightScatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-permweightScatter-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with length of gestation on the x-axis and weight  of baby on the y-axis. The left panel is the original data. The right panel  is data where the weight of the baby has been permuted across the observations. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-permweightScatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-permweightScatter-1.png" class="lightbox" data-gallery="fig-permweightScatter" title="Figure&nbsp;24.7&nbsp;(a): Original data."><img src="inf-model-slr_files/figure-html/fig-permweightScatter-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-permweightScatter" alt="Two scatterplots, both with length of gestation on the x-axis and weight  of baby on the y-axis. The left panel is the original data. The right panel  is data where the weight of the baby has been permuted across the observations. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-permweightScatter-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original data.
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-permweightScatter" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-permweightScatter-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with length of gestation on the x-axis and weight  of baby on the y-axis. The left panel is the original data. The right panel  is data where the weight of the baby has been permuted across the observations. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-permweightScatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-permweightScatter-2.png" class="lightbox" data-gallery="fig-permweightScatter" title="Figure&nbsp;24.7&nbsp;(b): Permuted data."><img src="inf-model-slr_files/figure-html/fig-permweightScatter-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-permweightScatter" alt="Two scatterplots, both with length of gestation on the x-axis and weight  of baby on the y-axis. The left panel is the original data. The right panel  is data where the weight of the baby has been permuted across the observations. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-permweightScatter-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Permuted data.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permweightScatter-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.7: Permutation removes the linear relationship between <code>weight</code> and <code>weeks</code>. Repeated permutations allow for quantifying the variability in the slope under the condition that there is no linear relationship (i.e., that the null hypothesis is true).
</figcaption></figure>
</div>
<section id="observed-data-1" class="level3" data-number="24.2.1"><h3 data-number="24.2.1" class="anchored" data-anchor-id="observed-data-1">
<span class="header-section-number">24.2.1</span> Observed data</h3>
<p>We will continue to use the births data to investigate the linear relationship between <code>weight</code> and <code>weeks</code> gestation. Note that the least squares model (see <a href="model-slr.html" class="quarto-xref"><span>Chapter 7</span></a>) describing the relationship is given in <a href="#tbl-ls-births" class="quarto-xref">Table&nbsp;<span>24.1</span></a>. The columns in <a href="#tbl-ls-births" class="quarto-xref">Table&nbsp;<span>24.1</span></a> are further described in <a href="#sec-mathslope" class="quarto-xref"><span>Section 24.4</span></a>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-ls-births" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ls-births-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.1: The least squares estimates of the intercept and slope are given in the estimate column. The observed slope is 0.335.
</figcaption><div aria-describedby="tbl-ls-births-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-5.72</td>
<td style="text-align: right; width: 5em;">1.61</td>
<td style="text-align: right; width: 5em;">-3.54</td>
<td style="text-align: right; width: 5em;">6e-04</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">weeks</td>
<td style="text-align: right; width: 5em;">0.34</td>
<td style="text-align: right; width: 5em;">0.04</td>
<td style="text-align: right; width: 5em;">8.07</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="variability-of-the-statistic-1" class="level3" data-number="24.2.2"><h3 data-number="24.2.2" class="anchored" data-anchor-id="variability-of-the-statistic-1">
<span class="header-section-number">24.2.2</span> Variability of the statistic</h3>
<p>After permuting the data, the least squares estimate of the line can be computed. Repeated permutations and slope calculations describe the variability in the line (i.e., in the slope) due only to the natural variability and not due to a relationship between <code>weight</code> and <code>weeks</code> gestation. <a href="#fig-permweekslm" class="quarto-xref">Figure&nbsp;<span>24.8</span></a> shows two different permutations of <code>weight</code> and the resulting linear models.</p>
<div id="fig-permweekslm" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-permweekslm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-permweekslm" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-permweekslm-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with length of gestation on the x-axis and  weight of baby on the y-axis. Each plot includes data where the weight of  the baby has been permuted across the observations. The two different  permutations produce slightly different least squares regression lines. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-permweekslm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-permweekslm-1.png" class="lightbox" data-gallery="fig-permweekslm" title="Figure&nbsp;24.8&nbsp;(a): First permutation."><img src="inf-model-slr_files/figure-html/fig-permweekslm-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-permweekslm" alt="Two scatterplots, both with length of gestation on the x-axis and  weight of baby on the y-axis. Each plot includes data where the weight of  the baby has been permuted across the observations. The two different  permutations produce slightly different least squares regression lines. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-permweekslm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) First permutation.
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-permweekslm" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-permweekslm-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with length of gestation on the x-axis and  weight of baby on the y-axis. Each plot includes data where the weight of  the baby has been permuted across the observations. The two different  permutations produce slightly different least squares regression lines. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-permweekslm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-permweekslm-2.png" class="lightbox" data-gallery="fig-permweekslm" title="Figure&nbsp;24.8&nbsp;(b): Second permutation."><img src="inf-model-slr_files/figure-html/fig-permweekslm-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-permweekslm" alt="Two scatterplots, both with length of gestation on the x-axis and  weight of baby on the y-axis. Each plot includes data where the weight of  the baby has been permuted across the observations. The two different  permutations produce slightly different least squares regression lines. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-permweekslm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Second permutation.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permweekslm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.8: Two permutations of <code>weight</code> with slightly different least squares regression lines.
</figcaption></figure>
</div>
<p>As you can see, sometimes the slope of the permuted data is positive, sometimes it is negative. Because the randomization happens under the condition of no underlying relationship (because the response variable is completely mixed with the explanatory variable), we expect to see the center of the randomized slope distribution to be zero.</p>
</section><section id="observed-statistic-vs.-null-statistics" class="level3" data-number="24.2.3"><h3 data-number="24.2.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics">
<span class="header-section-number">24.2.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<div class="cell">
<div class="cell-output-display">
<div id="fig-nulldistBirths" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of slopes describing the linear model from permuted weight  regressed on weeks gestation. The permuted slopes range from -0.15 to +0.15  and are nowhere near the observed slope value of 0.335. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-nulldistBirths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-nulldistBirths-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;24.9: Histogram of slopes given different permutations of the weight variable. The vertical red line is at the observed value of the slope, 0.335."><img src="inf-model-slr_files/figure-html/fig-nulldistBirths-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of slopes describing the linear model from permuted weight  regressed on weeks gestation. The permuted slopes range from -0.15 to +0.15  and are nowhere near the observed slope value of 0.335. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nulldistBirths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.9: Histogram of slopes given different permutations of the <code>weight</code> variable. The vertical red line is at the observed value of the slope, 0.335.
</figcaption></figure>
</div>
</div>
</div>
<p>As we can see from <a href="#fig-nulldistBirths" class="quarto-xref">Figure&nbsp;<span>24.9</span></a>, a slope estimate as extreme as the observed slope estimate (the red line) never happened in many repeated permutations of the <code>weight</code> variable. That is, if indeed there were no linear relationship between <code>weight</code> and <code>weeks</code>, the natural variability of the slopes would produce estimates between approximately -0.15 and +0.15. We reject the null hypothesis. Therefore, we believe that the slope observed on the original data is not just due to natural variability and indeed, there is a linear relationship between <code>weight</code> of baby and <code>weeks</code> gestation for births in the US.</p>
</section></section><section id="sec-bootbeta1" class="level2" data-number="24.3"><h2 data-number="24.3" class="anchored" data-anchor-id="sec-bootbeta1">
<span class="header-section-number">24.3</span> Bootstrap confidence interval for the slope</h2>
<p></p>
<p>As we have seen in previous chapters, we can use bootstrapping to estimate the sampling distribution of the statistic of interest (here, the slope) without the null assumption of no relationship (which was the condition in the randomization test). Because interest is now in creating a CI, there is no null hypothesis, so there won’t be any reason to permute either of the variables.</p>
<section id="observed-data-2" class="level3" data-number="24.3.1"><h3 data-number="24.3.1" class="anchored" data-anchor-id="observed-data-2">
<span class="header-section-number">24.3.1</span> Observed data</h3>
<p>Returning to the births data, we may want to consider the relationship between <code>mage</code> (mother’s age) and <code>weight</code>. Is <code>mage</code> a good predictor of <code>weight</code>? And if so, what is the relationship? That is, what is the slope that models average <code>weight</code> of baby as a function of <code>mage</code> (mother’s age)? The linear model regressing <code>weight</code> on <code>mage</code> is provided in <a href="#tbl-ls-births-mage" class="quarto-xref">Table&nbsp;<span>24.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-magePlot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatterplot with mother's age on the x-axis and baby's weight on the  y-axis. A linear model is superimposed. The points show a weak positive  linear trend. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-magePlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-magePlot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;24.10: Using the original data, the weight of baby as a linear model of mother’s age. Notice that the relationship between mother’s age and weight of baby is not as strong as the relationship we saw previously between weeks gestation and weight of baby."><img src="inf-model-slr_files/figure-html/fig-magePlot-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Scatterplot with mother's age on the x-axis and baby's weight on the  y-axis. A linear model is superimposed. The points show a weak positive  linear trend. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-magePlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.10: Using the original data, the weight of baby as a linear model of mother’s age. Notice that the relationship between mother’s age and weight of baby is not as strong as the relationship we saw previously between weeks gestation and weight of baby.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell" data-tbl-pos="H">
<div id="tbl-ls-births-mage" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ls-births-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.2: The least squares estimates of the intercept and slope are given in the estimate column. The observed slope is 0.036.
</figcaption><div aria-describedby="tbl-ls-births-mage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">6.23</td>
<td style="text-align: right; width: 5em;">0.71</td>
<td style="text-align: right; width: 5em;">8.79</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">mage</td>
<td style="text-align: right; width: 5em;">0.04</td>
<td style="text-align: right; width: 5em;">0.02</td>
<td style="text-align: right; width: 5em;">1.50</td>
<td style="text-align: right; width: 5em;">0.1362</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="variability-of-the-statistic-2" class="level3" data-number="24.3.2"><h3 data-number="24.3.2" class="anchored" data-anchor-id="variability-of-the-statistic-2">
<span class="header-section-number">24.3.2</span> Variability of the statistic</h3>
<p>Because the focus here is <em>not</em> on a null distribution, we sample with replacement <span class="math inline">\(n = 100\)</span> observations from the original dataset. Recall that with bootstrapping the resample always has the same number of observations as the original dataset in order to mimic the process of taking a sample from the population. When sampling in the linear model case, consider each observation to be a single dot. If the dot is resampled, both the <code>weight</code> and the <code>mage</code> measurement are observed. The measurements are linked to the dot (i.e., to the birth in the sample).</p>
<div id="fig-birth2BS" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-birth2BS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birth2BS" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birth2BS-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with mother's age on the x-axis and baby's weight  on the y-axis. The left plot is the original data. The right plot is the  bootstrapped data. Comparing the bootstrapped points to the original points,  we can see that some observations were sampled more than once, and some  observations were not selected for the bootstrap sample at all. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-birth2BS-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-birth2BS-1.png" class="lightbox" data-gallery="fig-birth2BS" title="Figure&nbsp;24.11&nbsp;(a): Original data."><img src="inf-model-slr_files/figure-html/fig-birth2BS-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-birth2BS" alt="Two scatterplots, both with mother's age on the x-axis and baby's weight  on the y-axis. The left plot is the original data. The right plot is the  bootstrapped data. Comparing the bootstrapped points to the original points,  we can see that some observations were sampled more than once, and some  observations were not selected for the bootstrap sample at all. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birth2BS-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Original data.
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-birth2BS" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-birth2BS-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two scatterplots, both with mother's age on the x-axis and baby's weight  on the y-axis. The left plot is the original data. The right plot is the  bootstrapped data. Comparing the bootstrapped points to the original points,  we can see that some observations were sampled more than once, and some  observations were not selected for the bootstrap sample at all. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-birth2BS-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-birth2BS-2.png" class="lightbox" data-gallery="fig-birth2BS" title="Figure&nbsp;24.11&nbsp;(b): Bootstrapped data."><img src="inf-model-slr_files/figure-html/fig-birth2BS-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-birth2BS" alt="Two scatterplots, both with mother's age on the x-axis and baby's weight  on the y-axis. The left plot is the original data. The right plot is the  bootstrapped data. Comparing the bootstrapped points to the original points,  we can see that some observations were sampled more than once, and some  observations were not selected for the bootstrap sample at all. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-birth2BS-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Bootstrapped data.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-birth2BS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.11: Original and one bootstrap sample of the births data. It is difficult to differentiate between the two plots, as (within a single bootstrap sample) the observations which have been resampled twice are plotted as points on top of one another. The red circles represent points in the original data which were not included in the bootstrap sample. The blue circles represent a data point that was repeatedly resampled (and is therefore darker) in the bootstrap sample. The green circles represent a particular structure to the data which is observed in both the original and bootstrap samples.
</figcaption></figure>
</div>
<p><a href="#fig-birth2BS-1" class="quarto-xref">Figure&nbsp;<span>24.11 (a)</span></a> shows the original data as compared with a single bootstrap sample in <a href="#fig-birth2BS-2" class="quarto-xref">Figure&nbsp;<span>24.11 (b)</span></a>, resulting in (slightly) different linear models. The red circles represent points in the original data which were not included in the bootstrap sample. The blue circles represent a point that was repeatedly resampled (and is therefore darker) in the bootstrap sample. The green circles represent a particular structure to the data which is observed in both the original and bootstrap samples. By repeatedly resampling, we can see dozens of bootstrapped slopes on the same plot in <a href="#fig-birthBS" class="quarto-xref">Figure&nbsp;<span>24.12</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-birthBS" class="quarto-float quarto-figure quarto-figure-center anchored" alt="An x-y coordinate system with least squares regression lines from many  bootstrap samples (no points are plotted). The lines vary around the observed  population line. On the x-axis is mother's age; on the y-axis is baby's weight.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-birthBS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-birthBS-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="Figure&nbsp;24.12: Repeated bootstrap resamples of size 100 are taken from the original data. Each of the bootstrapped linear models is slightly different."><img src="inf-model-slr_files/figure-html/fig-birthBS-1.png" class="img-fluid figure-img" style="width:90.0%" alt="An x-y coordinate system with least squares regression lines from many  bootstrap samples (no points are plotted). The lines vary around the observed  population line. On the x-axis is mother's age; on the y-axis is baby's weight."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-birthBS-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.12: Repeated bootstrap resamples of size 100 are taken from the original data. Each of the bootstrapped linear models is slightly different.
</figcaption></figure>
</div>
</div>
</div>
<p>Recall that in order to create a confidence interval for the slope, we need to find the range of values that the statistic (here the slope) takes on from different bootstrap samples. <a href="#fig-mageBSslopes" class="quarto-xref">Figure&nbsp;<span>24.13</span></a> is a histogram of the relevant bootstrapped slopes. We can see that a 95% bootstrap percentile interval for the true population slope is given by (-0.01, 0.081). We are 95% confident that for the model describing the population of births, predicting weight of baby from mother’s age, a one unit increase in <code>mage</code> (in years) is associated with an increase in predicted average baby <code>weight</code> of between -0.01 and 0.081 pounds. Notice that the CI contains zero, so the true relationship <em>might</em> be null!</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mageBSslopes" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of the slopes computed from many bootstrapped samples.  The bootstrap samples range from -0.05 (with the 2.5 percentile at -0.01) to  +0.1 (with the 97.5 percentile at 0.081). The bootstrapped slopes form a  histogram that is reasonably symmetric and bell-shaped.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-mageBSslopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-mageBSslopes-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="Figure&nbsp;24.13: The original births data on baby’s weight and mother’s age is bootstrapped 1,000 times. The histogram provides a sense for the variability of the slope of the linear model from sample to sample."><img src="inf-model-slr_files/figure-html/fig-mageBSslopes-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of the slopes computed from many bootstrapped samples.  The bootstrap samples range from -0.05 (with the 2.5 percentile at -0.01) to  +0.1 (with the 97.5 percentile at 0.081). The bootstrapped slopes form a  histogram that is reasonably symmetric and bell-shaped."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mageBSslopes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.13: The original births data on baby’s weight and mother’s age is bootstrapped 1,000 times. The histogram provides a sense for the variability of the slope of the linear model from sample to sample.
</figcaption></figure>
</div>
</div>
</div>
<div class="workedexample">
<p>Using <a href="#fig-mageBSslopes" class="quarto-xref">Figure&nbsp;<span>24.13</span></a>, calculate the bootstrap estimate for the standard error of the slope. Using the bootstrap standard error, find a 95% bootstrap SE confidence interval for the true population slope, and interpret the interval in context.</p>
<hr>
<p>Notice that most of the bootstrapped slopes fall between -0.01 and +0.08 (a range of 0.09). Using the empirical rule (that with bell-shaped distributions, most observations are within two standard errors of the center), the standard error of the slopes is approximately 0.0225. The critical value for a 95% confidence interval is <span class="math inline">\(z^\star = 1.96\)</span> which leads to a confidence interval of <span class="math inline">\(b_1 \pm 1.96 \cdot SE \rightarrow 0.036 \pm 1.96 \cdot 0.0225 \rightarrow (-0.0081, 0.0801).\)</span> The bootstrap SE confidence interval is almost identical to the bootstrap percentile interval. In context, we are 95% confident that for the model describing the population of births, predicting weight of baby from mother’s age, a one unit increase in <code>mage</code> (in years) is associated with an increase in predicted average baby <code>weight</code> of between -0.0081 and 0.0801 pounds.</p>
</div>
</section></section><section id="sec-mathslope" class="level2" data-number="24.4"><h2 data-number="24.4" class="anchored" data-anchor-id="sec-mathslope">
<span class="header-section-number">24.4</span> Mathematical model for testing the slope</h2>
<p>When certain technical conditions apply, it is convenient to use mathematical approximations to test and estimate the slope parameter. The approximations will build on the t-distribution which was described in <a href="inference-one-mean.html" class="quarto-xref"><span>Chapter 19</span></a>. The mathematical model is often correct and is usually easy to implement computationally. The validity of the technical conditions will be considered in detail in <a href="#sec-tech-cond-linmod" class="quarto-xref"><span>Section 24.6</span></a>.</p>
<p>In this section, we discuss uncertainty in the estimates of the slope and y-intercept for a regression line. Just as we identified standard errors for point estimates in previous chapters, we start by discussing standard errors for the slope and y-intercept estimates.</p>
<section id="observed-data-3" class="level3" data-number="24.4.1"><h3 data-number="24.4.1" class="anchored" data-anchor-id="observed-data-3">
<span class="header-section-number">24.4.1</span> Observed data</h3>
<p><strong>Midterm elections and unemployment</strong></p>
<p>Elections for members of the United States House of Representatives occur every two years, coinciding every four years with the U.S. Presidential election. The set of House elections occurring during the middle of a Presidential term are called midterm elections. In America’s two-party system (the vast majority of House members through history have been either Republicans or Democrats), one political theory suggests the higher the unemployment rate, the worse the President’s party will do in the midterm elections. In 2020 there were 232 Democrats, 198 Republicans, and 1 Libertarian in the House.</p>
<p>To assess the validity of the claim related to unemployment and voting patterns, we can compile historical data and look for a connection. We consider every midterm election from 1898 to 2018, with the exception of the elections during the Great Depression. The House of Representatives is made up of 435 voting members.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/midterms_house.html"><code>midterms_house</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p><a href="#fig-unemploymentAndChangeInHouse" class="quarto-xref">Figure&nbsp;<span>24.14</span></a> shows these data and the least-squares regression line:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\texttt{percent change in House seats for President's party}  \\
&amp;\qquad\qquad= -7.36 - 0.89 \times \texttt{(unemployment rate)}
\end{aligned}
\]</span></p>
<p>We consider the percent change in the number of seats of the President’s party (e.g., percent change in the number of seats for Republicans in 2018) against the unemployment rate.</p>
<p>Examining the data, there are no clear deviations from linearity or substantial outliers (see <a href="model-slr.html#sec-resids" class="quarto-xref"><span>Section 7.1.3</span></a> for a discussion on using residuals to visualize how well a linear model fits the data). While the data are collected sequentially, a separate analysis was used to check for any apparent correlation between successive observations; no such correlation was found.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-unemploymentAndChangeInHouse" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatterplot with percent unemployed on the x-axis and percent change in  House seats for the President's party on the y-axis. Each point represents a  different President's midterm and is colored according to their political party  (Democrat or Republican). The relationship is moderate and negative. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-unemploymentAndChangeInHouse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-unemploymentAndChangeInHouse-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="Figure&nbsp;24.14: The percent change in House seats for the President’s party in each election from 1898 to 2010 plotted against the unemployment rate. The two points for the Great Depression have been removed, and a least squares regression line has been fit to the data."><img src="inf-model-slr_files/figure-html/fig-unemploymentAndChangeInHouse-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Scatterplot with percent unemployed on the x-axis and percent change in  House seats for the President's party on the y-axis. Each point represents a  different President's midterm and is colored according to their political party  (Democrat or Republican). The relationship is moderate and negative. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-unemploymentAndChangeInHouse-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.14: The percent change in House seats for the President’s party in each election from 1898 to 2010 plotted against the unemployment rate. The two points for the Great Depression have been removed, and a least squares regression line has been fit to the data.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>The data for the Great Depression (1934 and 1938) were removed because the unemployment rate was 21% and 18%, respectively. Do you agree that they should be removed for this investigation? Why or why not?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>There is a negative slope in the line shown in <a href="#fig-unemploymentAndChangeInHouse" class="quarto-xref">Figure&nbsp;<span>24.14</span></a>. However, this slope (and the y-intercept) are only estimates of the parameter values. We might wonder, is this convincing evidence that the “true” linear model has a negative slope? That is, do the data provide strong evidence that the political theory is accurate, where the unemployment rate is a useful predictor of the midterm election? We can frame this investigation into a statistical hypothesis test:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = 0\)</span>. The true linear model has slope zero.</li>
<li>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\beta_1 \neq 0\)</span>. The true linear model has a slope different than zero. The unemployment is predictive of whether the President’s party wins or loses seats in the House of Representatives.</li>
</ul>
<p>We would reject <span class="math inline">\(H_0\)</span> in favor of <span class="math inline">\(H_A\)</span> if the data provide strong evidence that the true slope parameter is different than zero. To assess the hypotheses, we identify a standard error for the estimate, compute an appropriate test statistic, and identify the p-value.</p>
</section><section id="variability-of-the-statistic-3" class="level3" data-number="24.4.2"><h3 data-number="24.4.2" class="anchored" data-anchor-id="variability-of-the-statistic-3">
<span class="header-section-number">24.4.2</span> Variability of the statistic</h3>
<p>Just like other point estimates we have seen before, we can compute a standard error and test statistic for <span class="math inline">\(b_1\)</span>. We will generally label the test statistic using a <span class="math inline">\(T\)</span>, since it follows the <span class="math inline">\(t\)</span>-distribution.</p>
<p></p>
<p>We will rely on statistical software to compute the standard error and leave the explanation of how this standard error is determined to a second or third statistics course. <a href="#tbl-midtermUnempRegTable" class="quarto-xref">Table&nbsp;<span>24.3</span></a> shows software output for the least squares regression line in <a href="#fig-unemploymentAndChangeInHouse" class="quarto-xref">Figure&nbsp;<span>24.14</span></a>. The row labeled <code>unemp</code> includes all relevant information about the slope estimate (i.e., the coefficient of the unemployment variable, the related SE, the T statistic, and the corresponding p-value).</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-midtermUnempRegTable" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-midtermUnempRegTable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.3: Output from statistical software for the regression line modeling the midterm election losses for the President’s party as a response to unemployment.
</figcaption><div aria-describedby="tbl-midtermUnempRegTable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-7.36</td>
<td style="text-align: right; width: 5em;">5.16</td>
<td style="text-align: right; width: 5em;">-1.43</td>
<td style="text-align: right; width: 5em;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">unemp</td>
<td style="text-align: right; width: 5em;">-0.89</td>
<td style="text-align: right; width: 5em;">0.83</td>
<td style="text-align: right; width: 5em;">-1.07</td>
<td style="text-align: right; width: 5em;">0.30</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="workedexample">
<p>What do the first and second columns of <a href="#tbl-midtermUnempRegTable" class="quarto-xref">Table&nbsp;<span>24.3</span></a> represent?</p>
<hr>
<p>The entries in the first column represent the least squares estimates, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(b_1\)</span>, and the values in the second column correspond to the standard errors of each estimate. Using the estimates, we could write the equation for the least square regression line as</p>
<p><span class="math display">\[ \hat{y} = -7.36 - 0.89 x \]</span></p>
<p>where <span class="math inline">\(\hat{y}\)</span> in this case represents the predicted change in the number of seats for the president’s party, and <span class="math inline">\(x\)</span> represents the unemployment rate.</p>
</div>
<p>We previously used a <span class="math inline">\(t\)</span>-test statistic for hypothesis testing in the context of numerical data. Regression is very similar. In the hypotheses we consider, the null value for the slope is 0, so we can compute the test statistic using the T score formula:</p>
<p><span class="math display">\[
T \ = \ \frac{\text{estimate} - \text{null value}}{\text{SE}} = \ \frac{-0.89 - 0}{0.835} = \ -1.07
\]</span></p>
<p>The T score we calculated corresponds to the third column of <a href="#tbl-midtermUnempRegTable" class="quarto-xref">Table&nbsp;<span>24.3</span></a>.</p>
<div class="workedexample">
<p>Use <a href="#tbl-midtermUnempRegTable" class="quarto-xref">Table&nbsp;<span>24.3</span></a> to determine the p-value for the hypothesis test.</p>
<hr>
<p>The last column of the table gives the p-value for the two-sided hypothesis test for the coefficient of the unemployment rate 0.2961. That is, the data do not provide convincing evidence that a higher unemployment rate has any correspondence with smaller or larger losses for the President’s party in the House of Representatives in midterm elections. If there was no linear relationship between the two variables (i.e., if <span class="math inline">\(\beta_1 = 0)\)</span>, then we would expect to see linear models as or more extreme that the observed model roughly 30% of the time.</p>
</div>
</section><section id="observed-statistic-vs.-null-statistics-1" class="level3" data-number="24.4.3"><h3 data-number="24.4.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics-1">
<span class="header-section-number">24.4.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>As the final step in a mathematical hypothesis test for the slope, we use the information provided to make a conclusion about whether the data could have come from a population where the true slope was zero (i.e., <span class="math inline">\(\beta_1 = 0\)</span>). Before evaluating the formal hypothesis claim, sometimes it is important to check your intuition. Based on everything we have seen in the examples above describing the variability of a line from sample to sample, ask yourself if the linear relationship given by the data could have come from a population in which the slope was truly zero.</p>
<div class="workedexample">
<p>Examine <a href="model-slr.html#fig-elmhurstScatterWLine" class="quarto-xref">Figure&nbsp;<span>7.13</span></a>, which relates the Elmhurst College aid and student family income. Are you convinced that the slope is discernibly different from zero? That is, do you think a formal hypothesis test would reject the claim that the true slope of the line should be zero?</p>
<hr>
<p>While the relationship between the variables is not perfect, there is an evident decreasing trend in the data. Such a distinct trend suggests that the hypothesis test will reject the null claim that the slope is zero.</p>
</div>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/elmhurst.html"><code>elmhurst</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p>The tools in this section help you go beyond a visual interpretation of the linear relationship toward a formal mathematical claim about whether the slope estimate is meaningfully different from 0 to suggest that the true population slope is different from 0.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-rOutputForIncomeAidLSRLineInInferenceSection" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rOutputForIncomeAidLSRLineInInferenceSection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.4: Summary of least squares fit for the Elmhurst College data, where we are predicting the gift aid by the university based on the family income of students.
</figcaption><div aria-describedby="tbl-rOutputForIncomeAidLSRLineInInferenceSection-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">24319.33</td>
<td style="text-align: right; width: 5em;">1291.45</td>
<td style="text-align: right; width: 5em;">18.83</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">family_income</td>
<td style="text-align: right; width: 5em;">-0.04</td>
<td style="text-align: right; width: 5em;">0.01</td>
<td style="text-align: right; width: 5em;">-3.98</td>
<td style="text-align: right; width: 5em;">2e-04</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="guidedpractice">
<p><a href="#tbl-rOutputForIncomeAidLSRLineInInferenceSection" class="quarto-xref">Table&nbsp;<span>24.4</span></a> shows statistical software output from fitting the least squares regression line shown in <a href="model-slr.html#fig-elmhurstScatterWLine" class="quarto-xref">Figure&nbsp;<span>7.13</span></a>. Use the output to formally evaluate the following hypotheses.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: The true coefficient for family income is zero.</li>
<li>
<span class="math inline">\(H_A\)</span>: The true coefficient for family income is not zero.</li>
</ul>
</div>
<div class="important">
<p><strong>Inference for regression.</strong></p>
<p>We usually rely on statistical software to identify point estimates, standard errors, test statistics, and p-values in practice. However, be aware that software will not generally check whether the method is appropriate, meaning we must still verify conditions are met. See <a href="#sec-tech-cond-linmod" class="quarto-xref"><span>Section 24.6</span></a>.</p>
</div>
</section></section><section id="mathematical-model-interval-for-the-slope" class="level2" data-number="24.5"><h2 data-number="24.5" class="anchored" data-anchor-id="mathematical-model-interval-for-the-slope">
<span class="header-section-number">24.5</span> Mathematical model, interval for the slope</h2>
<p>Similar to how we can conduct a hypothesis test for a model coefficient using regression output, we can also construct confidence intervals for the slope and intercept coefficients.</p>
<div class="important">
<p><strong>Confidence intervals for coefficients.</strong></p>
<p>Confidence intervals for model coefficients (e.g., the intercept or the slope) can be computed using the <span class="math inline">\(t\)</span>-distribution:</p>
<p><span class="math display">\[ b_i \ \pm\ t_{df}^{\star} \times SE_{b_{i}} \]</span></p>
<p>where <span class="math inline">\(t_{df}^{\star}\)</span> is the appropriate <span class="math inline">\(t^{\star}\)</span> cutoff corresponding to the confidence level with the model’s degrees of freedom, <span class="math inline">\(df = n - 2\)</span>.</p>
</div>
<div class="workedexample">
<p>Compute the 95% confidence interval for the coefficient using the regression output from <a href="#tbl-rOutputForIncomeAidLSRLineInInferenceSection" class="quarto-xref">Table&nbsp;<span>24.4</span></a>.</p>
<hr>
<p>The point estimate is -0.0431 and the standard error is <span class="math inline">\(SE = 0.0108\)</span>. When constructing a confidence interval for a model coefficient, we generally use a <span class="math inline">\(t\)</span>-distribution. The degrees of freedom for the distribution are noted in the regression output, <span class="math inline">\(df = 48\)</span>, allowing us to identify <span class="math inline">\(t_{48}^{\star} = 2.01\)</span> for use in the confidence interval.</p>
<p>We can now construct the confidence interval in the usual way:</p>
<p><span class="math display">\[
\begin{aligned}
\text{point estimate} &amp;\pm t_{48}^{\star} \times SE \\
-0.0431 &amp;\pm 2.01 \times 0.0108 \\
(-0.0648 &amp;, -0.0214)
\end{aligned}
\]</span></p>
<p>We are 95% confident that for an additional one unit (i.e., $1000 increase) in family income, the university’s gift aid is predicted to decrease on average by $21.40 to $64.80.</p>
</div>
<p>On the topic of intervals in this book, we have focused exclusively on confidence intervals for model parameters. However, there are other types of intervals that may be of interest (and are outside the scope of this book), including prediction intervals for a response value and confidence intervals for a mean response value in the context of regression.</p>
</section><section id="sec-tech-cond-linmod" class="level2" data-number="24.6"><h2 data-number="24.6" class="anchored" data-anchor-id="sec-tech-cond-linmod">
<span class="header-section-number">24.6</span> Checking model conditions</h2>
<p></p>
<p>In the previous sections, we used randomization and bootstrapping to perform inference when the mathematical model was not valid due to violations of the technical conditions. In this section, we’ll provide details for when the mathematical model is appropriate and a discussion of technical conditions needed for the randomization and bootstrapping procedures. Recall from <a href="model-slr.html#sec-resids" class="quarto-xref"><span>Section 7.1.3</span></a> that residual plots can be used to visualize how well a linear model fits the data.</p>
<section id="what-are-the-technical-conditions-for-the-mathematical-model" class="level3" data-number="24.6.1"><h3 data-number="24.6.1" class="anchored" data-anchor-id="what-are-the-technical-conditions-for-the-mathematical-model">
<span class="header-section-number">24.6.1</span> What are the technical conditions for the mathematical model?</h3>
<p>When fitting a least squares line, we generally require the following:</p>
<ul>
<li><p><strong>Linearity.</strong> The data should show a linear trend. If there is a nonlinear trend (e.g., first panel of <a href="#fig-whatCanGoWrongWithLinearModel" class="quarto-xref">Figure&nbsp;<span>24.15</span></a>) an advanced regression method from another book or later course should be applied.</p></li>
<li><p><strong>Independent observations.</strong> Be cautious about applying regression to data that are sequential observations in time such as a stock price each day. Such data may have an underlying structure that should be considered in a different type of model and analysis. An example of a dataset where successive observations are not independent is shown in the fourth panel of <a href="#fig-whatCanGoWrongWithLinearModel" class="quarto-xref">Figure&nbsp;<span>24.15</span></a>. There are also other instances where correlations within the data are important, which is further discussed in <a href="inf-model-mlr.html" class="quarto-xref"><span>Chapter 25</span></a>.</p></li>
<li><p><strong>Nearly normal residuals.</strong> Generally, the residuals should be nearly normal. When this condition is found to be unreasonable, it is often because of outliers or concerns about influential points, which we’ll talk about more in <a href="model-slr.html#sec-outliers-in-regression" class="quarto-xref"><span>Section 7.3</span></a>. An example of a residual that would be potentially concerning is shown in the second panel of <a href="#fig-whatCanGoWrongWithLinearModel" class="quarto-xref">Figure&nbsp;<span>24.15</span></a>, where one observation is clearly much further from the regression line than the others. Outliers should be treated extremely carefully. Do not automatically remove an outlier if it truly belongs in the dataset. However, be honest about its impact on the analysis. A strategy for dealing with outliers is to present two analyses: one with the outlier and one without the outlier. Additionally, a type of violation of normality happens when the positive residuals are smaller in magnitude than the negative residuals (or vice versa). That is, when the residuals are not symmetrically distributed around the line <span class="math inline">\(y=0.\)</span></p></li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div id="fig-whatCanGoWrongWithLinearModel" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A grid of 2 by 4 scatterplots with fabricated data. The top row of plots  contains original x-y data plots with a least squares regression line. The  bottom row of plots is a series of residual plot with predicted value on the  x-axis and residual on the y-axis. The first column of plots gives an example  of points that have a quadratic relationship instead of a linear relationship.  The second column of plots gives an example where a single outlying point  does not fit the linear model. The third column of points gives an example  where the points have increasing variability as the value of x increases.  The last column of points gives an example where the points are correlated  with one another, possibly as part of a time series. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-whatCanGoWrongWithLinearModel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inf-model-slr_files/figure-html/fig-whatCanGoWrongWithLinearModel-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="Figure&nbsp;24.15: Four examples showing when the methods in this chapter are insufficient to apply a linear model to the data. The top set of graphs represents the x and y relationship. The bottom set of graphs is a residual plot. First panel – linearity fails. Second panel – there are outliers, most especially one point that is very far away from the line. Third panel – the variability of the errors is related to the value of x. Fourth panel – a time series dataset is shown, where successive observations are highly correlated."><img src="inf-model-slr_files/figure-html/fig-whatCanGoWrongWithLinearModel-1.png" class="img-fluid figure-img" style="width:100.0%" alt="A grid of 2 by 4 scatterplots with fabricated data. The top row of plots  contains original x-y data plots with a least squares regression line. The  bottom row of plots is a series of residual plot with predicted value on the  x-axis and residual on the y-axis. The first column of plots gives an example  of points that have a quadratic relationship instead of a linear relationship.  The second column of plots gives an example where a single outlying point  does not fit the linear model. The third column of points gives an example  where the points have increasing variability as the value of x increases.  The last column of points gives an example where the points are correlated  with one another, possibly as part of a time series. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-whatCanGoWrongWithLinearModel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;24.15: Four examples showing when the methods in this chapter are insufficient to apply a linear model to the data. The top set of graphs represents the <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> relationship. The bottom set of graphs is a residual plot. First panel – linearity fails. Second panel – there are outliers, most especially one point that is very far away from the line. Third panel – the variability of the errors is related to the value of <span class="math inline">\(x\)</span>. Fourth panel – a time series dataset is shown, where successive observations are highly correlated.
</figcaption></figure>
</div>
</div>
</div>
<ul>
<li>
<strong>Constant or equal variability.</strong> The variability of points around the least squares line remains roughly constant. An example of non-constant variability is shown in the third panel of <a href="#fig-whatCanGoWrongWithLinearModel" class="quarto-xref">Figure&nbsp;<span>24.15</span></a>, which represents the most common pattern observed when this condition fails: the variability of <span class="math inline">\(y\)</span> is larger when <span class="math inline">\(x\)</span> is larger.</li>
</ul>
<div class="guidedpractice">
<p>Should we have concerns about applying least squares regression to the Elmhurst data in <a href="model-slr.html#fig-elmhurstScatterW2Lines" class="quarto-xref">Figure&nbsp;<span>7.14</span></a>?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<p>The technical conditions are often remembered using the <strong>LINE</strong> mnemonic. The linearity, normality, and equality of variance conditions usually can be assessed through residual plots, as seen in <a href="#fig-whatCanGoWrongWithLinearModel" class="quarto-xref">Figure&nbsp;<span>24.15</span></a>. A careful consideration of the experimental design should be undertaken to confirm that the observed values are indeed independent.</p>
<ul>
<li>L: <strong>linear</strong> model</li>
<li>I: <strong>independent</strong> observations</li>
<li>N: points are <strong>normally</strong> distributed around the line</li>
<li>E: <strong>equal</strong> variability around the line for all values of the explanatory variable</li>
</ul></section><section id="why-do-we-need-technical-conditions" class="level3" data-number="24.6.2"><h3 data-number="24.6.2" class="anchored" data-anchor-id="why-do-we-need-technical-conditions">
<span class="header-section-number">24.6.2</span> Why do we need technical conditions?</h3>
<p>As with other inferential techniques we have covered in this text, if the technical conditions above do not hold, then it is not possible to make concluding claims about the population. That is, without the technical conditions, the T score will not have the assumed t-distribution. That said, it is almost always impossible to check the conditions precisely, so we look for large deviations from the conditions. If there are large deviations, we will be unable to trust the calculated p-value or the endpoints of the resulting confidence interval.</p>
<p><strong>The model based on linearity</strong></p>
<p>The linearity condition is among the most important if your goal is to understand a linear model between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span>. For example, the value of the slope will not be at all meaningful if the true relationship between <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> is quadratic, as in <a href="model-slr.html#fig-notGoodAtAllForALinearModel" class="quarto-xref">Figure&nbsp;<span>7.3</span></a>. Not only should we be cautious about the inference, but the model <em>itself</em> is also not an accurate portrayal of the relationship between the variables. However, an extended discussion on the different methods for modeling functional forms other than linear is outside the scope of this text.</p>
<p><strong>The importance of independence</strong></p>
<p>The technical condition describing the independence of the observations is often the most crucial but also the most difficult to diagnose. It is also extremely difficult to gather a dataset which is a true random sample from the population of interest. A true randomized experiment from a fixed set of individuals is much easier to implement, and indeed, randomized experiments are done in most medical studies these days.</p>
<p>Dependent observations can bias results in ways that produce fundamentally flawed analyses. That is, if you hang out at the gym measuring height and weight, your linear model is surely not a representation of all students at your university. At best it is a model describing students who use the gym, but also who are willing to talk to you, that use the gym at the times you were there measuring, etc.</p>
<p>In lieu of trying to answer whether your observations are a true random sample, you might instead focus on whether you believe your observations are representative of a population of interest. Humans are notoriously bad at implementing random procedures, so you should be wary of any process that used human intuition to balance the data with respect to, for example, the demographics of the individuals in the sample.</p>
<p><strong>Some thoughts on normality</strong></p>
<p>The normality condition requires that points vary symmetrically around the line, spreading out in a bell-shaped fashion. You should consider the “bell” of the normal distribution as sitting on top of the line (coming off the paper in a 3-D sense) so as to indicate that the points are dense close to the line and disperse gradually as they get farther from the line.</p>
<p>The normality condition is less important than linearity or independence for a few reasons. First, the linear model fit with least squares will still be an unbiased estimate of the true population model. However, the distribution of the estimate will be unknown. Fortunately the Central Limit Theorem (described in <a href="inference-one-mean.html#sec-one-mean-math" class="quarto-xref"><span>Section 19.2</span></a>) tells us that most of the analyses (e.g., SEs, p-values, confidence intervals) done using the mathematical model (with the <span class="math inline">\(t\)</span>-distribution) will still hold (even if the data are not normally distributed around the line) as long as the sample size is large enough. One analysis method that <em>does</em> require normality, regardless of sample size, is creating intervals which predict the response of individual outcomes at a given <span class="math inline">\(x\)</span> value, using the linear model. One additional reason to worry slightly less about normality is that neither the randomization test nor the bootstrapping procedures require the data to be normal around the line.</p>
<p><strong>Equal variability for prediction in particular</strong></p>
<p>As with normality, the equal variability condition (that points are spread out in similar ways around the line for all values of <span class="math inline">\(x\)</span>) will not cause problems for the estimate of the linear model. That said, the <strong>inference</strong> on the model (e.g., computing p-values) will be incorrect if the variability around the line is extremely heterogeneous. Data that exhibit non-equal variance across the range of x-values will have the potential to seriously mis-estimate the variability of the slope which will have consequences for the inference results (i.e., hypothesis tests and confidence intervals).</p>
<p>In many cases, the inference results for both a randomization test or a bootstrap confidence interval are also robust to the equal variability condition, so they provide the analyst a set of methods to use when the data are heteroskedastic (that is, exhibit unequal variability around the regression line). Although randomization tests and bootstrapping allow us to analyze data using fewer conditions, some technical conditions are required for all methods described in this text (e.g., independent observation). When the equal variability condition is violated and a mathematical analysis (e.g., p-value from T score) is needed, there are other existing methods (outside the scope of this text) which can handle the unequal variance (e.g., weighted least squares analysis).</p>
</section><section id="what-if-all-the-technical-conditions-are-met" class="level3" data-number="24.6.3"><h3 data-number="24.6.3" class="anchored" data-anchor-id="what-if-all-the-technical-conditions-are-met">
<span class="header-section-number">24.6.3</span> What if all the technical conditions are met?</h3>
<p>When the technical conditions are met, the least squares regression model and inference is provided by virtually all statistical software. In addition to being ubiquitous, however, an additional advantage to the least squares regression model (and related inference) is that the linear model has important extensions (which are not trivial to implement with bootstrapping and randomization tests). In particular, random effects models, repeated measures, and interaction are all linear model extensions which require the above technical conditions. When the technical conditions hold, the extensions to the linear model can provide important insight into the data and research question at hand. We will discuss some of the extended modeling and associated inference in <a href="inf-model-mlr.html" class="quarto-xref"><span>Chapter 25</span></a> and <a href="inf-model-logistic.html" class="quarto-xref"><span>Chapter 26</span></a>. Many of the techniques used to deal with technical condition violations are outside the scope of this text, but they are taught in universities in the very next class after this one. If you are working with linear models or are curious to learn more, we recommend that you continue learning about statistical methods applicable to a larger class of datasets.</p>
</section></section><section id="sec-chp24-review" class="level2" data-number="24.7"><h2 data-number="24.7" class="anchored" data-anchor-id="sec-chp24-review">
<span class="header-section-number">24.7</span> Chapter review</h2>
<section id="summary" class="level3" data-number="24.7.1"><h3 data-number="24.7.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">24.7.1</span> Summary</h3>
<p>Recall that early in the text we presented graphical techniques which communicated relationships across multiple variables. We also used modeling to formalize the relationships. Many chapters were dedicated to inferential methods which allowed claims about the population to be made based on samples of data. Not only did we present the mathematical model for each of the inferential techniques, but when appropriate, we also presented bootstrapping and permutation methods.</p>
<p>In <a href="#sec-inf-model-slr" class="quarto-xref"><span>Chapter 24</span></a> we brought all of those ideas together by considering inferential claims on linear models through randomization tests, bootstrapping, and mathematical modeling. We continue to emphasize the importance of experimental design in making conclusions about research claims. In particular, recall that variability can come from different sources (e.g., random sampling vs.&nbsp;random allocation, see <a href="data-design.html#fig-randsampValloc" class="quarto-xref">Figure&nbsp;<span>2.8</span></a>).</p>
</section><section id="terms" class="level3" data-number="24.7.2"><h3 data-number="24.7.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">24.7.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-24" class="quarto-xref">Table&nbsp;<span>24.5</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-24" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-24-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;24.5: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-24-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">bootstrap CI for the slope</td>
<td style="text-align: left; width: 12em;">randomization test for the slope</td>
<td style="text-align: left; width: 12em;">technical conditions linear regression</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">inference with single predictor regression</td>
<td style="text-align: left; width: 12em;">t-distribution for slope</td>
<td style="text-align: left; width: 12em;">variability of the slope</td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp24-exercises" class="level2" data-number="24.8"><h2 data-number="24.8" class="anchored" data-anchor-id="sec-chp24-exercises">
<span class="header-section-number">24.8</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-24" class="quarto-xref">Appendix&nbsp;<span>A.24</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<p><strong>Body measurements, randomization test.</strong> Researchers studying anthropometry collected body and skeletal diameter measurements, as well as age, weight, height and sex for 507 physically active individuals. A linear model is built to predict height based on shoulder girth (circumference of shoulders measured over deltoid muscles), both measured in centimeters.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="citation" data-cites="Heinz:2003">(<a href="references.html#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span> Shown below are the linear model output for predicting height from shoulder girth and the histogram of slopes from 1,000 randomized datasets (1,000 times, <code>hgt</code> was permuted and regressed against <code>sho_gi</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</p>
<div class="quarto-layout-panel" data-layout="[0.6, 0.4]">
<div class="quarto-layout-row">
<div id="table" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 3em;">105.832</td>
<td style="text-align: right; width: 3em;">3.27</td>
<td style="text-align: right; width: 3em;">32.3</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">sho_gi</td>
<td style="text-align: right; width: 3em;">0.604</td>
<td style="text-align: right; width: 3em;">0.03</td>
<td style="text-align: right; width: 3em;">20.0</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20"><img src="inf-model-slr_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model predicting height from shoulder girth is differen than 0.</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like shoulder girth and height).</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion from the mathematical model? Explain your reasoning.</p></li>
</ol>
</li>
<li>
<p><strong>Baby’s weight and father’s age, randomization test.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <span class="citation" data-cites="data:births14">(<a href="references.html#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span> Shown below are the linear model output for predicting baby’s weight (in pounds) from father’s age (in years) and the histogram of slopes from 1000 randomized datasets (1000 times, <code>weight</code> was permuted and regressed against <code>fage</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</p>
<div class="quarto-layout-panel" data-layout="[0.6, 0.4]">
<div class="quarto-layout-row">
<div id="table" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 3em;">7.101</td>
<td style="text-align: right; width: 3em;">0.199</td>
<td style="text-align: right; width: 3em;">35.674</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 3em;">0.005</td>
<td style="text-align: right; width: 3em;">0.006</td>
<td style="text-align: right; width: 3em;">0.757</td>
<td style="text-align: right; width: 3em;">0.4495</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21"><img src="inf-model-slr_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model for predicting baby’s weight from father’s age is different than 0?</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like father’s age and weight of baby). What does the conclusion of your test say about whether the father’s age is a useful predictor of baby’s weight?</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion from the mathematical model? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>Body measurements, mathematical test.</strong> The scatterplot and least squares summary below show the relationship between weight measured in kilograms and height measured in centimeters of 507 physically active individuals. <span class="citation" data-cites="Heinz:2003">(<a href="references.html#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></p>
<div class="quarto-layout-panel" data-layout="[0.4, 0.6]">
<div class="quarto-layout-row">
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22"><img src="inf-model-slr_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="output" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 4em;">-105.01</td>
<td style="text-align: right; width: 4em;">7.54</td>
<td style="text-align: right; width: 3em;">-13.9</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em; font-family: monospace;">hgt</td>
<td style="text-align: right; width: 4em;">1.02</td>
<td style="text-align: right; width: 4em;">0.04</td>
<td style="text-align: right; width: 3em;">23.1</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>Describe the relationship between height and weight.</p></li>
<li><p>Write the equation of the regression line. Interpret the slope and intercept in context.</p></li>
<li><p>Do the data provide convincing evidence that the true slope parameter is different than 0? State the null and alternative hypotheses, report the p-value (using a mathematical model), and state your conclusion.</p></li>
<li><p>The correlation coefficient for height and weight is 0.72. Calculate <span class="math inline">\(R^2\)</span> and interpret it in context.</p></li>
</ol>
</li>
</ol>
<ol start="4" type="1">
<li>
<p><strong>Baby’s weight and father’s age, mathematical test.</strong> Is the father’s age useful in predicting the baby’s weight? The scatterplot and least squares summary below show the relationship between baby’s weight (measured in pounds) and father’s age for a random sample of babies. <span class="citation" data-cites="data:births14">(<a href="references.html#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span></p>
<div class="quarto-layout-panel" data-layout="[0.4, 0.6]">
<div class="quarto-layout-row">
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23"><img src="inf-model-slr_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
<div id="output" class="quarto-layout-cell" style="flex-basis: 60.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 4em;">7.1042</td>
<td style="text-align: right; width: 4em;">0.1936</td>
<td style="text-align: right; width: 3em;">36.698</td>
<td style="text-align: right; width: 3em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 4em;">0.0047</td>
<td style="text-align: right; width: 4em;">0.0061</td>
<td style="text-align: right; width: 3em;">0.779</td>
<td style="text-align: right; width: 3em;">0.4359</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
<ol type="a">
<li><p>What is the predicted weight of a baby whose father is 30 years old?</p></li>
<li><p>Do the data provide convincing evidence that the model for predicting baby weights from father’s age has a slope different than 0? State the null and alternative hypotheses, report the p-value (using a mathematical model), and state your conclusion.</p></li>
<li><p>Based on your conclusion, is father’s age a useful predictor of baby’s weight?</p></li>
</ol>
</li>
</ol>
<ol start="5" type="1">
<li>
<p><strong>Body measurements, bootstrap percentile interval.</strong> In order to estimate the slope of the model predicting height based on shoulder girth (circumference of shoulders measured over deltoid muscles), 1,000 bootstrap samples are taken from a dataset of body measurements from 507 people. A linear model predicting height based on shoulder girth is fit to each bootstrap sample, and the slope is estimated. A histogram of these slopes is shown below. <span class="citation" data-cites="Heinz:2003">(<a href="references.html#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24"><img src="inf-model-slr_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap percentile method and the histogram above, find a 98% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="6" type="1">
<li>
<p><strong>Baby’s weight and father’s age, bootstrap percentile interval.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby. Below is the bootstrap distribution of the slope statistic from 1,000 different bootstrap samples of the data. <span class="citation" data-cites="data:births14">(<a href="references.html#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-19-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25"><img src="inf-model-slr_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap percentile method and the histogram above, find a 95% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="7" type="1">
<li>
<p><strong>Body measurements, standard error bootstrap interval.</strong> A linear model is built to predict height based on shoulder girth (circumference of shoulders measured over deltoid muscles), both measured in centimeters. <span class="citation" data-cites="Heinz:2003">(<a href="references.html#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span> Shown below are the linear model output for predicting height from shoulder girth and the bootstrap distribution of the slope statistic from 1,000 different bootstrap samples of the data.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">105.832</td>
<td style="text-align: right; width: 5em;">3.27</td>
<td style="text-align: right; width: 5em;">32.3</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">sho_gi</td>
<td style="text-align: right; width: 5em;">0.604</td>
<td style="text-align: right; width: 5em;">0.03</td>
<td style="text-align: right; width: 5em;">20.0</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 98% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-21-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26"><img src="inf-model-slr_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</li>
</ol>
<ol start="8" type="1">
<li>
<p><strong>Baby’s weight and father’s age, standard error bootstrap interval.</strong> US Department of Health and Human Services, Centers for Disease Control and Prevention collect information on births recorded in the country. The data used here are a random sample of 1000 births from 2014. Here, we study the relationship between the father’s age and the weight of the baby. <span class="citation" data-cites="data:births14">(<a href="references.html#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span> Shown below are the linear model output for predicting baby’s weight (in pounds) from father’s age (in years) and the the bootstrap distribution of the slope statistic from 1000 different bootstrap samples of the data.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">7.101</td>
<td style="text-align: right; width: 5em;">0.199</td>
<td style="text-align: right; width: 5em;">35.674</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">fage</td>
<td style="text-align: right; width: 5em;">0.005</td>
<td style="text-align: right; width: 5em;">0.006</td>
<td style="text-align: right; width: 5em;">0.757</td>
<td style="text-align: right; width: 5em;">0.4495</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 95% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-23-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27"><img src="inf-model-slr_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>Body measurements, conditions.</strong> The scatterplot below shows the residuals (on the y-axis) from the linear model of weight vs.&nbsp;height from a dataset of body measurements from 507 physically active individuals. The x-axis is the height of the individuals, in cm. <span class="citation" data-cites="Heinz:2003">(<a href="references.html#ref-Heinz:2003" role="doc-biblioref">Heinz et al. 2003</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-24-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28"><img src="inf-model-slr_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>For these data, <span class="math inline">\(R^2\)</span> is 51.84%. What is the value of the correlation coefficient? How can you tell if it is positive or negative? (Hint: you may need to look at a previous exercise.)</p></li>
<li><p>Examine the residual plot. What do you observe? Is a simple least squares fit appropriate for these data? Which of the LINE conditions are met or not met?</p></li>
</ol>
</li>
</ol>
<ol start="10" type="1">
<li>
<p><strong>Baby’s weight and father’s age, conditions.</strong> The scatterplot below shows the residuals (on the y-axis) from the linear model of baby’s weight (measured in pounds) vs.&nbsp;father’s age for a random sample of babies. Father’s age is on the x-axis. <span class="citation" data-cites="data:births14">(<a href="references.html#ref-data:births14" role="doc-biblioref">ICPSR 2014</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-25-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-29"><img src="inf-model-slr_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>For these data, <span class="math inline">\(R^2\)</span> is 0.09%. What is the value of the correlation coefficient? How can you tell if it is positive or negative? (Hint: you may need to look at a previous exercise.)</p></li>
<li><p>Examine the residual plot. What do you observe? Is a simple least squares fit appropriate for these data? Which of the LINE conditions are met or not met?</p></li>
</ol>
</li>
</ol>
<ol start="11" type="1">
<li>
<p><strong>Murders and poverty, randomization test.</strong> The following regression output is for predicting annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas. Shown below are the linear model output for predicting annual murders per million from percentage living in poverty for metropolitan areas and the histogram of slopes from 1000 randomized datasets (1000 times, <code>annual_murders_per_mil</code> was permuted and regressed against <code>perc_pov</code>). The red vertical line is drawn at the observed slope value which was produced in the linear model output.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.90</td>
<td style="text-align: right; width: 5em;">7.79</td>
<td style="text-align: right; width: 5em;">-3.84</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.56</td>
<td style="text-align: right; width: 5em;">0.39</td>
<td style="text-align: right; width: 5em;">6.56</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="quarto-layout-panel" data-layout="[0.48, -0.02, 0.5]">
<div class="quarto-layout-row">
<div id="questions" class="quarto-layout-cell" style="flex-basis: 48.0%;justify-content: flex-start;">
<ol type="a">
<li><p>What are the null and alternative hypotheses for evaluating whether the slope of the model for predicting annual murder rate from poverty percentage is different than 0?</p></li>
<li><p>Using the histogram which describes the distribution of slopes when the null hypothesis is true, find the p-value and conclude the hypothesis test in the context of the problem (use words like murder rate and poverty).</p></li>
<li><p>Is the conclusion based on the histogram of randomized slopes consistent with the conclusion which would have been obtained using the mathematical model? Explain your reasoning.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-27-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-30"><img src="inf-model-slr_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</li>
<li>
<p><strong>Murders and poverty, mathematical test.</strong> The table below shows the output of a linear model annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.90</td>
<td style="text-align: right; width: 5em;">7.79</td>
<td style="text-align: right; width: 5em;">-3.84</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.56</td>
<td style="text-align: right; width: 5em;">0.39</td>
<td style="text-align: right; width: 5em;">6.56</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>What are the hypotheses for evaluating whether the slope of the model predicting annual murder rate from poverty percentage is different than 0?</p></li>
<li><p>State the conclusion of the hypothesis test from part (a) in context. What does this say about whether poverty percentage is a useful predictor of annual murder rate?</p></li>
<li><p>Calculate a 95% confidence interval for the slope of poverty percentage, and interpret it in context.</p></li>
<li><p>Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="13" type="1">
<li>
<p><strong>Murders and poverty, bootstrap percentile interval.</strong> Data on annual murders per million (<code>annual_murders_per_mil</code>) and percentage living in poverty (<code>perc_pov</code>) is collected from a random sample of 20 metropolitan areas. Using these data we want to estimate the slope of the model predicting <code>annual_murders_per_mil</code> from <code>perc_pov</code>. We take 1,000 bootstrap samples of the data and fit a linear model predicting <code>annual_murders_per_mil</code> from <code>perc_pov</code> to each bootstrap sample. A histogram of these slopes is shown below.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-29-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-31"><img src="inf-model-slr_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the percentile bootstrap method and the histogram above, find a 90% confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</li>
<li>
<p><strong>Murders and poverty, standard error bootstrap interval.</strong> A linear model is built to predict annual murders per million (<code>annual_murders_per_mil</code>) from percentage living in poverty (<code>perc_pov</code>) in a random sample of 20 metropolitan areas. Shown below are the standard linear model output for predicting annual murders per million from percentage living in poverty for metropolitan areas and the bootstrap distribution of the slope statistic from 1000 different bootstrap samples of the data.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-29.90</td>
<td style="text-align: right; width: 5em;">7.79</td>
<td style="text-align: right; width: 5em;">-3.84</td>
<td style="text-align: right; width: 5em;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">perc_pov</td>
<td style="text-align: right; width: 5em;">2.56</td>
<td style="text-align: right; width: 5em;">0.39</td>
<td style="text-align: right; width: 5em;">6.56</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-30-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-32"><img src="inf-model-slr_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the histogram, approximate the standard error of the slope statistic (that is, quantify the variability of the slope statistic from sample to sample).</p></li>
<li><p>Find a 90% bootstrap SE confidence interval for the slope parameter.</p></li>
<li><p>Interpret the confidence interval in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Murders and poverty, conditions.</strong> The scatterplot below shows the annual murders per million vs.&nbsp;percentage living in poverty in a random sample of 20 metropolitan areas. The second figure plots residuals on the y-axis and percent living in poverty on the x-axis.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inf-model-slr_files/figure-html/unnamed-chunk-31-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-33"><img src="inf-model-slr_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inf-model-slr_files/figure-html/unnamed-chunk-31-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-34"><img src="inf-model-slr_files/figure-html/unnamed-chunk-31-2.png" class="img-fluid"></a></p>
</div>
</div>
</div>
<ol type="a">
<li><p>For these data, <span class="math inline">\(R^2\)</span> is 70.56%. What is the value of the correlation coefficient? How can you tell if it is positive or negative?</p></li>
<li><p>Examine the residual plot. What do you observe? Is a simple least squares fit appropriate for the data? Which of the LINE conditions are met or not met?</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>I heart cats.</strong> Researchers collected data on heart and body weights of 144 domestic adult cats. The table below shows the output of a linear model predicting heart weight (measured in grams) from body weight (measured in kilograms) of these cats.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-0.357</td>
<td style="text-align: right; width: 5em;">0.692</td>
<td style="text-align: right; width: 5em;">-0.515</td>
<td style="text-align: right; width: 5em;">0.6072</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">Bwt</td>
<td style="text-align: right; width: 5em;">4.034</td>
<td style="text-align: right; width: 5em;">0.250</td>
<td style="text-align: right; width: 5em;">16.119</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>What are the hypotheses for evaluating whether body weight is positively associated with heart weight in cats?</p></li>
<li><p>State the conclusion of the hypothesis test from part (a) in context.</p></li>
<li><p>Calculate a 95% confidence interval for the slope of body weight, and interpret it in context.</p></li>
<li><p>Do your results from the hypothesis test and the confidence interval agree? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="17" type="1">
<li>
<p><strong>Beer and blood alcohol content.</strong> Many people believe that weight, drinking habits, and many other factors are much more important in predicting blood alcohol content (BAC) than simply considering the number of drinks a person consumed. Here we examine data from sixteen student volunteers at Ohio State University who each drank a randomly assigned number of cans of beer. These students were evenly divided between men and women, and they differed in weight and drinking habits. Thirty minutes later, a police officer measured their blood alcohol content (BAC) in grams of alcohol per deciliter of blood. The scatterplot and regression table summarize the findings. <a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <span class="citation" data-cites="Malkevitc+Lesser:2008">(<a href="references.html#ref-Malkevitc+Lesser:2008" role="doc-biblioref">Malkevitch and Lesser 2008</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-33-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-35"><img src="inf-model-slr_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">estimate</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">std.error</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">statistic</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">p.value</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em; font-family: monospace;">(Intercept)</td>
<td style="text-align: right; width: 5em;">-0.0127</td>
<td style="text-align: right; width: 5em;">0.0126</td>
<td style="text-align: right; width: 5em;">-1.00</td>
<td style="text-align: right; width: 5em;">0.332</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em; font-family: monospace;">beers</td>
<td style="text-align: right; width: 5em;">0.0180</td>
<td style="text-align: right; width: 5em;">0.0024</td>
<td style="text-align: right; width: 5em;">7.48</td>
<td style="text-align: right; width: 5em;">&lt;0.0001</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>Describe the relationship between the number of cans of beer and BAC.</p></li>
<li><p>Write the equation of the regression line. Interpret the slope and intercept in context.</p></li>
<li><p>Do the data provide convincing evidence that drinking more cans of beer is associated with an increase in blood alcohol? State the null and alternative hypotheses, report the p-value, and state your conclusion.</p></li>
<li><p>The correlation coefficient for number of cans of beer and BAC is 0.89. Calculate <span class="math inline">\(R^2\)</span> and interpret it in context.</p></li>
<li><p>Suppose we visit a bar in our own town, ask people how many drinks they have had, and also measure their BAC. Would the relationship between number of drinks and BAC would be as strong as the relationship found in the Ohio State study? Why?</p></li>
</ol>
</li>
</ol>
<ol start="18" type="1">
<li>
<p><strong>Urban homeowners, conditions.</strong> The scatterplot below shows the percent of families who own their home vs.&nbsp;the percent of the population living in urban areas. <span class="citation" data-cites="data:urbanOwner">(<a href="references.html#ref-data:urbanOwner" role="doc-biblioref">US Census Bureau 2010</a>)</span> There are 52 observations, each corresponding to a state in the US. Puerto Rico and District of Columbia are also included. The second figure plots residuals on the y-axis and percent of the population living in urban areas on the x-axis.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inf-model-slr_files/figure-html/unnamed-chunk-34-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-36"><img src="inf-model-slr_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inf-model-slr_files/figure-html/unnamed-chunk-34-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-37"><img src="inf-model-slr_files/figure-html/unnamed-chunk-34-2.png" class="img-fluid"></a></p>
</div>
</div>
</div>
<ol type="a">
<li><p>For these data, <span class="math inline">\(R^2\)</span> is 29.16%. What is the value of the correlation coefficient? How can you tell if it is positive or negative?</p></li>
<li><p>Examine the residual plot. What do you observe? Is a simple least squares fit appropriate for the data? Which of the LINE conditions are met or not met?</p></li>
</ol>
</li>
</ol>
<ol start="19" type="1">
<li>
<p><strong>I heart cats, LINE conditions.</strong> Researchers collected data on heart and body weights of 144 domestic adult cats. The figure below shows the output of the predicted values and residuals generated from a linear model predicting heart weight (measured in grams) from body weight (measured in kilograms) of these cats.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-35-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-38"><img src="inf-model-slr_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Examine the residual plot. Notice that for the small predicted values the residuals have a smaller magnitude than the larger residuals seen with the larger predicted values. The change in magnitude of the residuals across the predicted values is an indication of violation of which LINE technical condition?</p></li>
<li><p>If the LINE condtion described in part (a) is violated, might it lead to an incorrect conclusion about the model (i.e., the least squares regression line itself), the inference of the model (i.e., the p-value associated with the least squares regression line), neither, or both? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="20" type="1">
<li>
<p><strong>Beer and blood alcohol content, LINE conditions.</strong> The figure below shows the output of the predicted values and residuals generated from a linear model predicting the blood alcohol content (BAC) from number of cans of beer drunk by sixteen student volunteers at Ohio State University.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> <span class="citation" data-cites="Malkevitc+Lesser:2008">(<a href="references.html#ref-Malkevitc+Lesser:2008" role="doc-biblioref">Malkevitch and Lesser 2008</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inf-model-slr_files/figure-html/unnamed-chunk-36-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-39"><img src="inf-model-slr_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Examine the residual plot. Notice that it is difficult to identify any convincing patterns for or against violation of the LINE technical conditions. What is it about the residual plot that makes it difficult to assess the LINE technical conditions?</p></li>
<li><p>Is there anything about the residual plot which would make you hesitate about using the linear model for inference about all students? Is there anything about the experimental design of the study which would make you hesitate about using the linear model for inference about all students?</p></li>
</ol>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Heinz:2003" class="csl-entry" role="listitem">
Heinz, G., L. J. Peterson, R. W. Johnson, and C. J. Kerk. 2003. <span>“Exploring Relationships in Body Dimensions.”</span> <em>Journal of Statistics Education</em> 11 (2). <a href="http://www.openintro.org/redirect.php?go=textbook-body_dim_2003">http://www.openintro.org/redirect.php?go=textbook-body_dim_2003</a>.
</div>
<div id="ref-data:births14" class="csl-entry" role="listitem">
ICPSR. 2014. <span>“United States Department of Health and Human Services. Centers for Disease Control and Prevention. National Center for Health Statistics. Natality Detail File, 2014 United States. Inter-University Consortium for Political and Social Research, 2016-10-07.”</span> <a href="https://doi.org/10.3886/ICPSR36461.v1">https://doi.org/10.3886/ICPSR36461.v1</a>.
</div>
<div id="ref-Malkevitc+Lesser:2008" class="csl-entry" role="listitem">
Malkevitch, J., and L. M. Lesser. 2008. <em>For All Practical Purposes: Mathematical Literacy in Today’s World</em>. WH Freeman &amp; Co.
</div>
<div id="ref-data:urbanOwner" class="csl-entry" role="listitem">
US Census Bureau. 2010. <span>“2010 Census Urban and Rural Classification and Urban Area Criteria Housing Characteristics.”</span> <a href="http://www.openintro.org/redirect.php?go=textbook-housing_char_2010">http://www.openintro.org/redirect.php?go=textbook-housing_char_2010</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The answer to this question relies on the idea that statistical data analysis is somewhat of an art. That is, in many situations, there is no “right” answer. As you do more and more analyses on your own, you will come to recognize the nuanced understanding which is needed for a particular dataset. In terms of the Great Depression, we will provide two contrasting considerations. Each of these points would have very high leverage on any least-squares regression line, and years with such high unemployment may not help us understand what would happen in other years where the unemployment is only modestly high. On the other hand, the Depression years are exceptional cases, and we would be discarding important information if we exclude them from a final analysis.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We look in the second row corresponding to the family income variable. We see the point estimate of the slope of the line is -0.0431, the standard error of this estimate is 0.0108, and the <span class="math inline">\(t\)</span>-test statistic is <span class="math inline">\(T = -3.98\)</span>. The p-value corresponds exactly to the two-sided test we are interested in: 0.0002. The p-value is so small that we reject the null hypothesis and conclude that family income and financial aid at Elmhurst College for freshman entering in the year 2011 are negatively correlated and the true slope parameter is indeed less than 0, just as we believed in our analysis of <a href="model-slr.html#fig-elmhurstScatterWLine" class="quarto-xref">Figure&nbsp;<span>7.13</span></a>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The trend appears to be linear, the data fall around the line with no obvious outliers, the variance is roughly constant. The data do not come from a time series or other obvious violation to independence. Least squares regression can be applied to these data.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <a href="http://openintrostat.github.io/openintro/reference/bdims.html"><code>bdims</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The <a href="https://stat.ethz.ch/R-manual/R-patched/library/MASS/html/cats.html"><code>cats</code></a> data used in this exercise can be found in the <a href="https://cran.r-project.org/web/packages/MASS/index.html"><strong>MASS</strong></a> R package.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The <a href="http://openintrostat.github.io/openintro/reference/bac.html"><code>bac</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The <a href="http://openintrostat.github.io/openintro/reference/bac.html"><code>bac</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./inferential-modeling.html" class="pagination-link" aria-label="Inferential modeling">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Inferential modeling</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inf-model-mlr.html" class="pagination-link" aria-label="Inference for linear regression with multiple predictors">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inf-model-slr.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>