<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.23">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>21&nbsp; Inference for comparing paired means – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference-many-means.html" rel="next">
<link href="./inference-two-means.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bbc06d6f6ef3926df35ba59865d9f801.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-378f0d7aee85f7ba334b728025a30d77.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bbc06d6f6ef3926df35ba59865d9f801.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-860897ce047b349f0abcbac7c46aa68b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-67a1a0d0d1c355d6091f60efc95b4fa8.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-860897ce047b349f0abcbac7c46aa68b.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-paired-means.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#randomization-test-for-the-mean-paired-difference" id="toc-randomization-test-for-the-mean-paired-difference" class="nav-link active" data-scroll-target="#randomization-test-for-the-mean-paired-difference"><span class="header-section-number">21.1</span> Randomization test for the mean paired difference</a>
  <ul class="collapse">
<li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">21.1.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">21.1.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics" id="toc-observed-statistic-vs.-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics"><span class="header-section-number">21.1.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#bootstrap-confidence-interval-for-the-mean-paired-difference" id="toc-bootstrap-confidence-interval-for-the-mean-paired-difference" class="nav-link" data-scroll-target="#bootstrap-confidence-interval-for-the-mean-paired-difference"><span class="header-section-number">21.2</span> Bootstrap confidence interval for the mean paired difference</a>
  <ul class="collapse">
<li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">21.2.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-1" id="toc-variability-of-the-statistic-1" class="nav-link" data-scroll-target="#variability-of-the-statistic-1"><span class="header-section-number">21.2.2</span> Variability of the statistic</a></li>
  </ul>
</li>
  <li>
<a href="#sec-mathpaired" id="toc-sec-mathpaired" class="nav-link" data-scroll-target="#sec-mathpaired"><span class="header-section-number">21.3</span> Mathematical model for the mean paired difference</a>
  <ul class="collapse">
<li><a href="#observed-data-2" id="toc-observed-data-2" class="nav-link" data-scroll-target="#observed-data-2"><span class="header-section-number">21.3.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-2" id="toc-variability-of-the-statistic-2" class="nav-link" data-scroll-target="#variability-of-the-statistic-2"><span class="header-section-number">21.3.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics-1" id="toc-observed-statistic-vs.-null-statistics-1" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics-1"><span class="header-section-number">21.3.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp21-review" id="toc-sec-chp21-review" class="nav-link" data-scroll-target="#sec-chp21-review"><span class="header-section-number">21.4</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">21.4.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">21.4.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp21-exercises" id="toc-sec-chp21-exercises" class="nav-link" data-scroll-target="#sec-chp21-exercises"><span class="header-section-number">21.5</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-paired-means.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-paired-means.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-inference-paired-means" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>In <a href="inference-two-means.html" class="quarto-xref">Chapter&nbsp;<span>20</span></a> analysis was done to compare the average population value across two different groups. Recall that one of the important conditions in doing a two-sample analysis is that the two groups are independent. Here, independence across groups means that knowledge of the observations in one group does not change what we would expect to happen in the other group. But what happens if the groups are <strong>dependent</strong>? Sometimes dependency is not something that can be addressed through a statistical method. However, a particular dependency, <strong>pairing</strong>, can be modeled quite effectively using many of the same tools we have already covered in this text.</p>
</div>
<p>Paired data represent a particular type of experimental structure where the analysis is somewhat akin to a one-sample analysis (see <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a>) but has other features that resemble a two-sample analysis (see <a href="inference-two-means.html" class="quarto-xref">Chapter&nbsp;<span>20</span></a>). As with a two-sample analysis, quantitative measurements are made on each of two different levels of the explanatory variable. However, because the observational unit is <strong>paired</strong> across the two groups, the two measurements are subtracted such that only the difference is retained. <a href="#tbl-pairedexamples" class="quarto-xref">Table&nbsp;<span>21.1</span></a> presents some examples of studies where paired designs were implemented.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-pairedexamples" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pairedexamples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.1: Examples of studies where a paired design is used to measure the difference in the measurement over two conditions.
</figcaption><div aria-describedby="tbl-pairedexamples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Observational unit</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Comparison groups</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Measurement</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Value of interest</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 8em;">Car</td>
<td style="text-align: left; width: 8em;">Smooth Turn vs Quick Spin</td>
<td style="text-align: left; width: 8em;">amount of tire tread after 1,000 miles</td>
<td style="text-align: left;">difference in tread</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 8em;">Textbook</td>
<td style="text-align: left; width: 8em;">UCLA vs Amazon</td>
<td style="text-align: left; width: 8em;">price of new text</td>
<td style="text-align: left;">difference in price</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 8em;">Individual person</td>
<td style="text-align: left; width: 8em;">Pre-course vs Post-course</td>
<td style="text-align: left; width: 8em;">exam score</td>
<td style="text-align: left;">difference in score</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="important">
<p><strong>Paired data.</strong></p>
<p></p>
<p>Two sets of observations are <em>paired</em> if each observation in one set has a special correspondence or connection with exactly one observation in the other dataset.</p>
</div>
<p>It is worth noting that if mathematical modeling is chosen as the analysis tool, paired data inference on the difference in measurements will be identical to the one-sample mathematical techniques described in <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a>. However, recall from <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a> that with pure one-sample data, the computational tools for hypothesis testing are not easy to implement and were not presented (although the bootstrap was presented as a computational approach for constructing a one sample confidence interval). With paired data, the randomization test fits nicely with the structure of the experiment and is presented here.</p>
<section id="randomization-test-for-the-mean-paired-difference" class="level2" data-number="21.1"><h2 data-number="21.1" class="anchored" data-anchor-id="randomization-test-for-the-mean-paired-difference">
<span class="header-section-number">21.1</span> Randomization test for the mean paired difference</h2>
<p>Consider an experiment done to measure whether tire brand Smooth Turn or tire brand Quick Spin has longer tread wear (in cm). That is, after 1,000 miles on a car, which brand of tires has more tread, on average?</p>
<section id="observed-data" class="level3" data-number="21.1.1"><h3 data-number="21.1.1" class="anchored" data-anchor-id="observed-data">
<span class="header-section-number">21.1.1</span> Observed data</h3>
<p>The observed data represent 25 tread measurements (in cm) taken on 25 tires of Smooth Turn and 25 tires of Quick Spin. The study used a total of 25 cars, so on each car, one tire was of Smooth Turn and one was of Quick Spin. The mean tread for the Quick Spin tires was 0.308 cm and the mean tread for the Smooth Turn tires was 0.310 cm. <a href="#fig-tiredata" class="quarto-xref">Figure&nbsp;<span>21.1</span></a> presents the observed data, calculations on tread remaining (in cm).</p>
<p>The Smooth Turn manufacturer looks at the box plots and says:</p>
<blockquote class="blockquote">
<p><em>Clearly the tread on Smooth Turn tires is higher, on average, than the tread on Quick Spin tires after 1,000 miles of driving.</em></p>
</blockquote>
<p>The Quick Spin manufacturer is skeptical and retorts:</p>
<blockquote class="blockquote">
<p><em>But with only 25 cars, it seems that the variability in road conditions (sometimes one tire hits a pothole, etc.) could be what leads to the small difference in average tread amount.</em></p>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tiredata" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Box plots of the amount of tire tread for each of the two brands of tires with data values superimposed over the box plots. Each superimposed dot represents a car that drove with both types of tires. A grey line connects each car across the two box plots indicating that Smooth Turn has more tire wear than Quick Spin.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredata-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;21.1: Box plots of the tire tread data (in cm) and the brand of tire from which the original measurements came."><img src="inference-paired-means_files/figure-html/fig-tiredata-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Box plots of the amount of tire tread for each of the two brands of tires with data values superimposed over the box plots. Each superimposed dot represents a car that drove with both types of tires. A grey line connects each car across the two box plots indicating that Smooth Turn has more tire wear than Quick Spin."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.1: Box plots of the tire tread data (in cm) and the brand of tire from which the original measurements came.
</figcaption></figure>
</div>
</div>
</div>
<p>We’d like to be able to systematically distinguish between what the Smooth Turn manufacturer sees in the plot and what the Quick Spin manufacturer sees in the plot. Fortunately for us, we have an excellent way to simulate the natural variability (from road conditions, etc.) that can lead to tires being worn at different rates.</p>
</section><section id="variability-of-the-statistic" class="level3" data-number="21.1.2"><h3 data-number="21.1.2" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">21.1.2</span> Variability of the statistic</h3>
<p>A randomization test will identify whether the differences seen in the box plot of the original data in <a href="#fig-tiredata" class="quarto-xref">Figure&nbsp;<span>21.1</span></a> could have happened just by chance variability. As before, we will simulate the variability in the study under the assumption that the null hypothesis is true. In this study, the null hypothesis is that average tire tread wear is the same across Smooth Turn and Quick Spin tires.</p>
<ul>
<li>
<span class="math inline">\(H_0: \mu_{diff} = 0,\)</span> the average tread wear is the same for the two tire brands.</li>
<li>
<span class="math inline">\(H_A: \mu_{diff} \ne 0,\)</span> the average tread wear is different across the two tire brands.</li>
</ul>
<p>When observations are paired, the randomization process randomly assigns the tire brand to each of the observed tread values. Note that in the randomization test for the two-sample mean setting (see <a href="inference-two-means.html#sec-rand2mean" class="quarto-xref"><span>Section 20.1</span></a>) the explanatory variable was <em>also</em> randomly assigned to the responses. The change in the paired setting, however, is that the assignment happens <em>within</em> an observational unit (here, a car). Remember, if the null hypothesis is true, it will not matter which brand is put on which tire because the overall tread wear will be the same across pairs.</p>
<p><a href="#fig-tiredata4" class="quarto-xref">Figure&nbsp;<span>21.2</span></a> and <a href="#fig-tiredata5" class="quarto-xref">Figure&nbsp;<span>21.3</span></a> show that the random assignment of group (tire brand) happens within a single car. That is, every single car will still have one tire of each type. In the first randomization, it just so happens that the 4th car’s tire brands were swapped and the 5th car’s tire brands were not swapped.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tiredata4" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line plot connecting the tread for the 4th car in the dataset. The first plot is the original data and the second plot is the permuted data where the groups happened to get permuted randomly. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredata4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredata4-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;21.2: The 4th car: the tire brand was randomly permuted, and in the randomization calculation, the measurements (in cm) ended up in different groups."><img src="inference-paired-means_files/figure-html/fig-tiredata4-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Line plot connecting the tread for the 4th car in the dataset. The first plot is the original data and the second plot is the permuted data where the groups happened to get permuted randomly. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredata4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.2: The 4th car: the tire brand was randomly permuted, and in the randomization calculation, the measurements (in cm) ended up in different groups.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tiredata5" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line plot connecting the tread for the 5th car in the dataset. The first plot is the original data and the second plot is the permuted data where the groups happened to stay connected to the original measurements. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredata5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredata5-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;21.3: The 5th car: the tire brand was randomly permuted to stay the same! In the randomization calculation, the measurements (in cm) ended up in the original groups."><img src="inference-paired-means_files/figure-html/fig-tiredata5-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Line plot connecting the tread for the 5th car in the dataset. The first plot is the original data and the second plot is the permuted data where the groups happened to stay connected to the original measurements. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredata5-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.3: The 5th car: the tire brand was randomly permuted to stay the same! In the randomization calculation, the measurements (in cm) ended up in the original groups.
</figcaption></figure>
</div>
</div>
</div>
<p>We can put the shuffled assignments for all the cars into one plot as seen in <a href="#fig-tiredataPerm-2" class="quarto-xref">Figure&nbsp;<span>21.4 (b)</span></a>.</p>
<div id="fig-tiredataPerm" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredataPerm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tiredataPerm" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tiredataPerm-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line plot connecting the tread for the all of the cars in the dataset. The first plot is the original data and the second plot is the permuted data where some of the brands are connect to the original tread measurements and some of the brands have been swapped across the two tread measurements, within a car. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-tiredataPerm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredataPerm-1.png" class="lightbox" data-gallery="fig-tiredataPerm" title="Figure&nbsp;21.4&nbsp;(a): Brand of tire is the original brand."><img src="inference-paired-means_files/figure-html/fig-tiredataPerm-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-tiredataPerm" alt="Line plot connecting the tread for the all of the cars in the dataset. The first plot is the original data and the second plot is the permuted data where some of the brands are connect to the original tread measurements and some of the brands have been swapped across the two tread measurements, within a car. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tiredataPerm-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Brand of tire is the original brand.
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tiredataPerm" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tiredataPerm-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Line plot connecting the tread for the all of the cars in the dataset. The first plot is the original data and the second plot is the permuted data where some of the brands are connect to the original tread measurements and some of the brands have been swapped across the two tread measurements, within a car. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-tiredataPerm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredataPerm-2.png" class="lightbox" data-gallery="fig-tiredataPerm" title="Figure&nbsp;21.4&nbsp;(b): Brand of tire is the shuffled brand assignment."><img src="inference-paired-means_files/figure-html/fig-tiredataPerm-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-tiredataPerm" alt="Line plot connecting the tread for the all of the cars in the dataset. The first plot is the original data and the second plot is the permuted data where some of the brands are connect to the original tread measurements and some of the brands have been swapped across the two tread measurements, within a car. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tiredataPerm-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Brand of tire is the shuffled brand assignment.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredataPerm-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.4: Tire tread (in cm) by brand, original and shuffled. As evidenced by the colors, some of the cars kept their original tire assignments and some cars swapped the tire assignments.
</figcaption></figure>
</div>
<p>The next step in the randomization test is to sort the brands so that the assigned brand value on the x-axis aligns with the assigned group from the randomization. <a href="#fig-tiredataPermSort-1" class="quarto-xref">Figure&nbsp;<span>21.5 (a)</span></a> shows the same randomized groups, as seen in <a href="#fig-tiredataPerm-2" class="quarto-xref">Figure&nbsp;<span>21.4 (b)</span></a> previously. However, <a href="#fig-tiredataPermSort-2" class="quarto-xref">Figure&nbsp;<span>21.5 (b)</span></a> sorts the randomized groups so that we can measure the variability <em>across</em> groups as compared to the variability <em>within</em> groups.</p>
<div id="fig-tiredataPermSort" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredataPermSort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tiredataPermSort" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tiredataPermSort-1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatterplot of tread on the y axis and tire brand on the x axis. The left panel has the observed tread values matched to the original tire brand for the x axis location. The observations are colored based on the permuted tire brand assigned in the randomization. The right panel has the tread values matched to the permuted tire brand, so some observations have swapped orientation. The observations are also colored by the permuted tire brand assigned in the randomization. In the right panel, the two tire brands seem equivalent with respect to tire wear. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-tiredataPermSort-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredataPermSort-1.png" class="lightbox" data-gallery="fig-tiredataPermSort" title="Figure&nbsp;21.5&nbsp;(a): Randomized brand assignment"><img src="inference-paired-means_files/figure-html/fig-tiredataPermSort-1.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-tiredataPermSort" alt="Scatterplot of tread on the y axis and tire brand on the x axis. The left panel has the observed tread values matched to the original tire brand for the x axis location. The observations are colored based on the permuted tire brand assigned in the randomization. The right panel has the tread values matched to the permuted tire brand, so some observations have swapped orientation. The observations are also colored by the permuted tire brand assigned in the randomization. In the right panel, the two tire brands seem equivalent with respect to tire wear. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tiredataPermSort-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Randomized brand assignment
</figcaption></figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-tiredataPermSort" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-tiredataPermSort-2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Scatterplot of tread on the y axis and tire brand on the x axis. The left panel has the observed tread values matched to the original tire brand for the x axis location. The observations are colored based on the permuted tire brand assigned in the randomization. The right panel has the tread values matched to the permuted tire brand, so some observations have swapped orientation. The observations are also colored by the permuted tire brand assigned in the randomization. In the right panel, the two tire brands seem equivalent with respect to tire wear. ">
<figure class="quarto-float quarto-subfloat-fig figure"><div aria-describedby="fig-tiredataPermSort-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredataPermSort-2.png" class="lightbox" data-gallery="fig-tiredataPermSort" title="Figure&nbsp;21.5&nbsp;(b): Randomized brand assignment sorted by brand."><img src="inference-paired-means_files/figure-html/fig-tiredataPermSort-2.png" class="img-fluid figure-img" style="width:100.0%" data-ref-parent="fig-tiredataPermSort" alt="Scatterplot of tread on the y axis and tire brand on the x axis. The left panel has the observed tread values matched to the original tire brand for the x axis location. The observations are colored based on the permuted tire brand assigned in the randomization. The right panel has the tread values matched to the permuted tire brand, so some observations have swapped orientation. The observations are also colored by the permuted tire brand assigned in the randomization. In the right panel, the two tire brands seem equivalent with respect to tire wear. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-tiredataPermSort-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Randomized brand assignment sorted by brand.
</figcaption></figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredataPermSort-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.5: Tire tread (in cm) by brand.
</figcaption></figure>
</div>
<p><a href="#fig-tiredatarand1" class="quarto-xref">Figure&nbsp;<span>21.6</span></a> presents a second randomization of the data. Notice that the two observations from the same car are linked with a grey line; some of the tread values have been randomly assigned to the other tire brand, while some are still connected to their original tire brands.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tiredatarand1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Box plots and scatterplot with tire brand on the x-axis and treat on the y-axis. The points are assigned to the x-axis brand given by the permutation, but the plot differs from previous figures in that it is a second permutation of the brands. Again, the two permuted brands seem equivalent with respect to tire wear.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredatarand1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredatarand1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;21.6: A second randomization where the brand is randomly swapped (or not) across the two tread wear measurements (in cm) from the same car."><img src="inference-paired-means_files/figure-html/fig-tiredatarand1-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Box plots and scatterplot with tire brand on the x-axis and treat on the y-axis. The points are assigned to the x-axis brand given by the permutation, but the plot differs from previous figures in that it is a second permutation of the brands. Again, the two permuted brands seem equivalent with respect to tire wear."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredatarand1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.6: A second randomization where the brand is randomly swapped (or not) across the two tread wear measurements (in cm) from the same car.
</figcaption></figure>
</div>
</div>
</div>
<p><a href="#fig-tiredatarand2" class="quarto-xref">Figure&nbsp;<span>21.7</span></a> presents yet another randomization of the data. Again, the same observations are linked by a grey line, and some of the tread values have been randomly assigned to the opposite tire brand than they were originally (while some are still connected to their original tire brands).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-tiredatarand2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Box plots and scatterplot with tire brand on the x-axis and treat on the y-axis. The points are assigned to the x-axis brand given by the permutation, but the plot differs from previous figures in that it is a second permutation of the brands. The additional permutation demonstrates that the box plots continue to change for each permutation yet the tire tread is equivalent across the permuted groups.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-tiredatarand2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-tiredatarand2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;21.7: An additional randomization where the brand is randomly swapped (or not) across the two tread wear measurements (in cm) from the same car."><img src="inference-paired-means_files/figure-html/fig-tiredatarand2-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Box plots and scatterplot with tire brand on the x-axis and treat on the y-axis. The points are assigned to the x-axis brand given by the permutation, but the plot differs from previous figures in that it is a second permutation of the brands. The additional permutation demonstrates that the box plots continue to change for each permutation yet the tire tread is equivalent across the permuted groups."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tiredatarand2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.7: An additional randomization where the brand is randomly swapped (or not) across the two tread wear measurements (in cm) from the same car.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="observed-statistic-vs.-null-statistics" class="level3" data-number="21.1.3"><h3 data-number="21.1.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics">
<span class="header-section-number">21.1.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>By repeating the randomization process, we can create a distribution of the average of the differences in tire treads, as seen in <a href="#fig-pair-randomize" class="quarto-xref">Figure&nbsp;<span>21.8</span></a>. As expected (because the differences were generated under the null hypothesis), the center of the histogram is zero. A line has been drawn at the observed difference which is well outside the majority of the null differences simulated from natural variability by mixing up which the tire received Smooth Turn and which received Quick Spin. Because the observed statistic is so far away from the natural variability of the randomized differences, we are convinced that there is a difference between Smooth Turn and Quick Spin. Our conclusion is that the extra amount of average tire tread in Smooth Turn is due to more than just natural variability: we reject <span class="math inline">\(H_0\)</span> and conclude that <span class="math inline">\(\mu_{ST} \ne \mu_{QS}.\)</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pair-randomize" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of the average difference in tire wear, Quick Spin minus Smooth Turn over 1000 different permutations. The histogram is centered at 0 and spreads to approximately -0.0025 and 0.0025. A red line at approximately 0.002 indicates the observed difference in average trend from the original data.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pair-randomize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-pair-randomize-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;21.8: Histogram of 1,000 mean differences with tire brand randomly assigned across the two tread measurements (in cm) per pair."><img src="inference-paired-means_files/figure-html/fig-pair-randomize-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of the average difference in tire wear, Quick Spin minus Smooth Turn over 1000 different permutations. The histogram is centered at 0 and spreads to approximately -0.0025 and 0.0025. A red line at approximately 0.002 indicates the observed difference in average trend from the original data."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pair-randomize-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.8: Histogram of 1,000 mean differences with tire brand randomly assigned across the two tread measurements (in cm) per pair.
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="bootstrap-confidence-interval-for-the-mean-paired-difference" class="level2" data-number="21.2"><h2 data-number="21.2" class="anchored" data-anchor-id="bootstrap-confidence-interval-for-the-mean-paired-difference">
<span class="header-section-number">21.2</span> Bootstrap confidence interval for the mean paired difference</h2>
<p>For both the bootstrap and the mathematical models applied to paired data, the analysis is virtually identical to the one-sample approach given in <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a>. The key to working with paired data (for bootstrapping and mathematical approaches) is to consider the measurement of interest to be the difference in measured values across the pair of observations.</p>
<p></p>
<section id="observed-data-1" class="level3" data-number="21.2.1"><h3 data-number="21.2.1" class="anchored" data-anchor-id="observed-data-1">
<span class="header-section-number">21.2.1</span> Observed data</h3>
<p>In an earlier edition of this textbook, we found that Amazon prices were, on average, lower than those of the UCLA Bookstore for UCLA courses in 2010. It’s been several years, and many stores have adapted to the online market, so we wondered, how is the UCLA Bookstore doing today?</p>
<p>We sampled 201 UCLA courses. Of those, 68 required books could be found on Amazon. A portion of the dataset from these courses is shown in <a href="#tbl-textbooksDF" class="quarto-xref">Table&nbsp;<span>21.2</span></a>, where prices are in US dollars.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/ucla_textbooks_f18.html"><code>ucla_textbooks_f18</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<div class="cell" data-tbl-pos="H">
<div id="tbl-textbooksDF" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-textbooksDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.2: Four cases from the <code>ucla_textbooks_f18</code> dataset.
</figcaption><div aria-describedby="tbl-textbooksDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">subject</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">course_num</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">bookstore_new</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">amazon_new</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">price_diff</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">American Indian Studies</td>
<td style="text-align: left;">M10</td>
<td style="text-align: right;">48.0</td>
<td style="text-align: right;">47.5</td>
<td style="text-align: right;">0.52</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anthropology</td>
<td style="text-align: left;">2</td>
<td style="text-align: right;">14.3</td>
<td style="text-align: right;">13.6</td>
<td style="text-align: right;">0.71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arts and Architecture</td>
<td style="text-align: left;">10</td>
<td style="text-align: right;">13.5</td>
<td style="text-align: right;">12.5</td>
<td style="text-align: right;">0.97</td>
</tr>
<tr class="even">
<td style="text-align: left;">Asian</td>
<td style="text-align: left;">M60W</td>
<td style="text-align: right;">49.3</td>
<td style="text-align: right;">55.0</td>
<td style="text-align: right;">-5.69</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p></p>
<p>Each textbook has two corresponding prices in the dataset: one for the UCLA Bookstore and one for Amazon. When two sets of observations have this special correspondence, they are said to be <strong>paired</strong>.</p>
</section><section id="variability-of-the-statistic-1" class="level3" data-number="21.2.2"><h3 data-number="21.2.2" class="anchored" data-anchor-id="variability-of-the-statistic-1">
<span class="header-section-number">21.2.2</span> Variability of the statistic</h3>
<p>Following the example of bootstrapping the one-sample statistic, the observed <em>differences</em> can be bootstrapped in order to understand the variability of the average difference from sample to sample. Remember, the differences act as a single value to bootstrap. That is, the original dataset would include the list of 68 price differences, and each resample will also include 68 price differences (some repeated through the bootstrap resampling process). The bootstrap procedure for paired differences is quite similar to the procedure applied to the one-sample statistic case in <a href="inference-one-mean.html#sec-boot1mean" class="quarto-xref"><span>Section 19.1</span></a>.</p>
<p>In <a href="#fig-pairboot" class="quarto-xref">Figure&nbsp;<span>21.9</span></a>, two 99% confidence intervals for the difference in the cost of a new book at the UCLA bookstore compared with Amazon have been calculated. The bootstrap percentile confidence interval is computed using the 0.5 percentile and 99.5 percentile bootstrapped differences and is found to be ($0.25, $7.87).</p>
<div class="guidedpractice">
<p>Using the histogram of bootstrapped difference in means, estimate the standard error of the mean of the sample differences, <span class="math inline">\(\bar{x}_{diff}.\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>The bootstrap SE interval is found by computing the SE of the bootstrapped differences <span class="math inline">\((SE_{\overline{x}_{diff}} = \$1.64)\)</span> and the normal multiplier of <span class="math inline">\(z^{\star} = 2.58.\)</span> The averaged difference is <span class="math inline">\(\bar{x} = \$3.58.\)</span> The 99% confidence interval is: <span class="math inline">\(\$3.58 \pm 2.58 \times \$ 1.64 = (\$-0.65, \$7.81).\)</span></p>
<p>The confidence intervals seem to indicate that the UCLA bookstore price is, on average, higher than the Amazon price, as the majority of the confidence interval is positive. However, if the analysis required a strong degree of certainty (e.g., 99% confidence), and the bootstrap SE interval was most appropriate (given a second course in statistics the nuances of the methods can be investigated), the results of which book seller is higher is not well determined (because the bootstrap SE interval overlaps zero). That is, the 99% bootstrap SE interval gives potential for UCLA bookstore to be lower, on average, than Amazon (because of the possible negative values for the true mean difference in price).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-pairboot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram showing the distribution of the average bootstrapped difference of price, UCLA minus Amazon. The center of the distribution is given at approximately $3.75. Two bootstrap intervals are given. The percentile interval is approximately $0.25 to $8.50. The SE interval is approximately -$0.50 to $7.75.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-pairboot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-pairboot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;21.9: Bootstrap distribution for the average difference in new book price at the UCLA bookstore versus Amazon. 99% confidence intervals are superimposed using blue dashed (bootstrap percentile interval) and red dotted (bootstrap SE interval) lines."><img src="inference-paired-means_files/figure-html/fig-pairboot-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram showing the distribution of the average bootstrapped difference of price, UCLA minus Amazon. The center of the distribution is given at approximately $3.75. Two bootstrap intervals are given. The percentile interval is approximately $0.25 to $8.50. The SE interval is approximately -$0.50 to $7.75."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pairboot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.9: Bootstrap distribution for the average difference in new book price at the UCLA bookstore versus Amazon. 99% confidence intervals are superimposed using blue dashed (bootstrap percentile interval) and red dotted (bootstrap SE interval) lines.
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="sec-mathpaired" class="level2" data-number="21.3"><h2 data-number="21.3" class="anchored" data-anchor-id="sec-mathpaired">
<span class="header-section-number">21.3</span> Mathematical model for the mean paired difference</h2>
<p>Thinking about the differences as a single observation on an observational unit changes the paired setting into the one-sample setting. The mathematical model for the one-sample case is covered in <a href="inference-one-mean.html#sec-one-mean-math" class="quarto-xref"><span>Section 19.2</span></a>.</p>
<section id="observed-data-2" class="level3" data-number="21.3.1"><h3 data-number="21.3.1" class="anchored" data-anchor-id="observed-data-2">
<span class="header-section-number">21.3.1</span> Observed data</h3>
<div class="quarto-layout-panel" data-layout="[0.55, -0.05, 0.4]">
<div class="quarto-layout-row">
<div id="text" class="quarto-layout-cell" style="flex-basis: 55.0%;justify-content: flex-start;">
<p>To analyze paired data, it is often useful to look at the difference in outcomes of each pair of observations. In the textbook data, we look at the differences in prices, which is represented as the <code>price_difference</code> variable in the dataset. Here the differences are taken as</p>
<p><span class="math display">\[\text{UCLA Bookstore price} - \text{Amazon price}\]</span></p>
<p>It is important that we always subtract using a consistent order; here Amazon prices are always subtracted from UCLA prices. The first difference shown in <a href="#tbl-textbooksDF" class="quarto-xref">Table&nbsp;<span>21.2</span></a> is computed as <span class="math inline">\(47.97 - 47.45 = 0.52.\)</span> Similarly, the second difference is computed as <span class="math inline">\(14.26 - 13.55 = 0.71,\)</span> and the third is <span class="math inline">\(13.50 - 12.53 = 0.97.\)</span> A histogram of the differences is shown in <a href="#fig-diffInTextbookPricesF18" class="quarto-xref">Figure&nbsp;<span>21.10</span></a>.</p>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 40.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div id="fig-diffInTextbookPricesF18" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of the differences in prices for each book samples, UCLA minus Amazon. The prices differences range from -$10 to $80 with a strong right skew. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-diffInTextbookPricesF18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-paired-means_files/figure-html/fig-diffInTextbookPricesF18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;21.10: Histogram of the differences in prices for each book sampled."><img src="inference-paired-means_files/figure-html/fig-diffInTextbookPricesF18-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Histogram of the differences in prices for each book samples, UCLA minus Amazon. The prices differences range from -$10 to $80 with a strong right skew. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diffInTextbookPricesF18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;21.10: Histogram of the differences in prices for each book sampled.
</figcaption></figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section><section id="variability-of-the-statistic-2" class="level3" data-number="21.3.2"><h3 data-number="21.3.2" class="anchored" data-anchor-id="variability-of-the-statistic-2">
<span class="header-section-number">21.3.2</span> Variability of the statistic</h3>
<p>To analyze a paired dataset, we simply analyze the differences. <a href="#tbl-textbooksSummaryStats" class="quarto-xref">Table&nbsp;<span>21.3</span></a> provides the data summaries from the textbook data. Note that instead of reporting the prices separately for UCLA and Amazon, the summary statistics are given by the mean of the differences, the standard deviation of the differences, and the total number of pairs (i.e., differences). The parameter of interest is also a single value, <span class="math inline">\(\mu_{diff},\)</span> so we can use the same <span class="math inline">\(t\)</span>-distribution techniques we applied in <a href="inference-one-mean.html#sec-one-mean-math" class="quarto-xref"><span>Section 19.2</span></a> directly onto the observed differences.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-textbooksSummaryStats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-textbooksSummaryStats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.3: Summary statistics for the 68 price differences.
</figcaption><div aria-describedby="tbl-textbooksSummaryStats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
</tr></thead>
<tbody><tr class="odd">
<td style="text-align: center; width: 8em;">68</td>
<td style="text-align: center; width: 8em;">3.58</td>
<td style="text-align: center; width: 8em;">13.4</td>
</tr></tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="workedexample">
<p>Set up a hypothesis test to determine whether, on average, there is a difference between Amazon’s price for a book and the UCLA bookstore’s price. Also, check the conditions for whether we can move forward with the test using the <span class="math inline">\(t\)</span>-distribution.</p>
<hr>
<p>We are considering two scenarios:</p>
<ul>
<li><p><span class="math inline">\(H_0:\)</span> <span class="math inline">\(\mu_{diff} = 0.\)</span> There is no difference in the average textbook prices.</p></li>
<li><p><span class="math inline">\(H_A:\)</span> <span class="math inline">\(\mu_{diff} \neq 0.\)</span> There is a difference in average prices.</p></li>
</ul>
<p>Next, we check the independence and normality conditions. This is a simple random sample, so assuming the textbooks are independent seems reasonable. While there are some outliers, <span class="math inline">\(n = 68\)</span> and none of the outliers are particularly extreme, so the normality of <span class="math inline">\(\bar{x}\)</span> is satisfied. With these conditions satisfied, we can move forward with the <span class="math inline">\(t\)</span>-distribution.</p>
</div>
</section><section id="observed-statistic-vs.-null-statistics-1" class="level3" data-number="21.3.3"><h3 data-number="21.3.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics-1">
<span class="header-section-number">21.3.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>As mentioned previously, the methods applied to a difference will be identical to the one-sample techniques. Therefore, the full hypothesis test framework is presented as guided practices.</p>
<div class="important">
<p><strong>The test statistic for assessing a paired mean is a T.</strong></p>
<p></p>
<p>The T score is a ratio of how the sample mean difference varies from zero as compared to how the observations vary.</p>
<p><span class="math display">\[T = \frac{\bar{x}_{diff} - 0 }{s_{diff}/\sqrt{n_{diff}}}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, T has a t-distribution with <span class="math inline">\(df = n_{diff} - 1.\)</span></p>
<p>Conditions:</p>
<ul>
<li>Independently sampled pairs.</li>
<li>Large samples and no extreme outliers.</li>
</ul>
</div>
<div class="workedexample">
<p>Complete the hypothesis test started in the previous Example.</p>
<hr>
<p>To compute the test compute the standard error associated with <span class="math inline">\(\bar{x}_{diff}\)</span> using the standard deviation of the differences <span class="math inline">\((s_{diff} = 13.42)\)</span> and the number of differences <span class="math inline">\((n_{diff} = 68):\)</span></p>
<p><span class="math display">\[SE_{\bar{x}_{diff}} = \frac{s_{diff}}{\sqrt{n_{diff}}} = \frac{13.42}{\sqrt{68}} = 1.63\]</span></p>
<p>The test statistic is the T score of <span class="math inline">\(\bar{x}_{diff}\)</span> under the null hypothess that the true mean difference is 0:</p>
<p><span class="math display">\[T = \frac{\bar{x}_{diff} - 0}{SE_{\bar{x}_{diff}}} = \frac{3.58 - 0}{1.63} = 2.20\]</span></p>
<p>To visualize the p-value, the sampling distribution of <span class="math inline">\(\bar{x}_{diff}\)</span> is drawn as though <span class="math inline">\(H_0\)</span> is true, and the p-value is represented by the two shaded tails in the figure below. The degrees of freedom is <span class="math inline">\(df = 68 - 1 = 67.\)</span> Using statistical software, we find the one-tail area of 0.0156.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/textbooksF18HTTails-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="inference-paired-means_files/figure-html/textbooksF18HTTails-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Doubling this area gives the p-value: 0.0312. Because the p-value is less than 0.05, we reject the null hypothesis. The data provide evidence that Amazon prices are different, on average, than the UCLA Bookstore prices for UCLA courses.</p>
</div>
<p>Recall that the margin of error is defined by the standard error. The margin of error for <span class="math inline">\(\bar{x}_{diff}\)</span> can be directly obtained from <span class="math inline">\(SE(\bar{x}_{diff}).\)</span></p>
<div class="important">
<p><strong>Margin of error for</strong> <span class="math inline">\(\bar{x}_{diff}.\)</span></p>
<p>The margin of error is <span class="math inline">\(t^\star_{df} \times s_{diff}/\sqrt{n_{diff}}\)</span> where <span class="math inline">\(t^\star_{df}\)</span> is calculated from a specified percentile on the t-distribution with <em>df</em> degrees of freedom.</p>
</div>
<p></p>
<div class="workedexample">
<p>Create a 95% confidence interval for the average price difference between books at the UCLA bookstore and books on Amazon.</p>
<hr>
<p>Conditions have already been verified and the standard error computed in a previous Example.<br>
To find the confidence interval, identify <span class="math inline">\(t^{\star}_{67}\)</span> using statistical software or the <span class="math inline">\(t\)</span>-table <span class="math inline">\((t^{\star}_{67} = 2.00),\)</span> and plug it, the point estimate, and the standard error into the confidence interval formula:</p>
<p><span class="math display">\[
\begin{aligned}
\text{point estimate} \ &amp;\pm \ t^{\star}_{67} \ \times \ SE \\
3.58 \ &amp;\pm \ 2.00 \ \times \ 1.63 \\
(0.32 \ &amp;, \ 6.84)
\end{aligned}
\]</span></p>
<p>We are 95% confident that the UCLA Bookstore is, on average, between $0.32 and $6.84 more expensive than Amazon for UCLA course books.</p>
</div>
<div class="guidedpractice">
<p>We have convincing evidence that Amazon is, on average, less expensive. How should this conclusion affect UCLA student buying habits? Should UCLA students always buy their books on Amazon?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
<p>A small note on the power of the paired t-test (recall the discussion of power in <a href="foundations-errors.html#sec-pow" class="quarto-xref"><span>Section 14.4</span></a>). It turns out that the paired t-test given here is often more powerful than the independent t-test discussed in <a href="inference-two-means.html#sec-math2samp" class="quarto-xref"><span>Section 20.3</span></a>. That said, depending on how the data are collected, we don’t always have mechanism for pairing the data and reducing the inherent variability across observations.</p>
</section></section><section id="sec-chp21-review" class="level2" data-number="21.4"><h2 data-number="21.4" class="anchored" data-anchor-id="sec-chp21-review">
<span class="header-section-number">21.4</span> Chapter review</h2>
<section id="summary" class="level3" data-number="21.4.1"><h3 data-number="21.4.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">21.4.1</span> Summary</h3>
<p>Like the two independent sample procedures in <a href="inference-two-means.html" class="quarto-xref">Chapter&nbsp;<span>20</span></a>, the paired difference analysis can be done using a t-distribution. The randomization test applied to the paired differences is slightly different, however. Note that when randomizing under the paired setting, each null statistic is created by randomly assigning the group to a numerical outcome <strong>within</strong> the individual observational unit. The procedure for creating a confidence interval for the paired difference is almost identical to the confidence intervals created in <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a> for a single mean.</p>
</section><section id="terms" class="level3" data-number="21.4.2"><h3 data-number="21.4.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">21.4.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-21" class="quarto-xref">Table&nbsp;<span>21.4</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-21" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.4: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">bootstrap CI paired difference</td>
<td style="text-align: left; width: 12em;">paired difference CI</td>
<td style="text-align: left; width: 12em;">T score paired difference</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">paired data</td>
<td style="text-align: left; width: 12em;">paired difference t-test</td>
<td style="text-align: left; width: 12em;"></td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp21-exercises" class="level2" data-number="21.5"><h2 data-number="21.5" class="anchored" data-anchor-id="sec-chp21-exercises">
<span class="header-section-number">21.5</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-21" class="quarto-xref">Appendix&nbsp;<span>A.21</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<strong>Air quality.</strong> Air quality measurements were collected in a random sample of 25 country capitals in 2013, and then again in the same cities in 2014. We would like to use these data to compare average air quality between the two years. Should we use a paired or non-paired test? Explain your reasoning.</li>
</ol>
<ol start="2" type="1">
<li>
<p><strong>True / False: paired.</strong> Determine if the following statements are true or false. If false, explain.</p>
<ol type="a">
<li><p>In a paired analysis we first take the difference of each pair of observations, and then we do inference on these differences.</p></li>
<li><p>Two datasets of different sizes cannot be analyzed as paired data.</p></li>
<li><p>Consider two sets of data that are paired with each other. Each observation in one dataset has a natural correspondence with exactly one observation from the other dataset.</p></li>
<li><p>Consider two sets of data that are paired with each other. Each observation in one dataset is subtracted from the average of the other dataset’s observations.</p></li>
</ol>
</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>Paired or not? I.</strong> In each of the following scenarios, determine if the data are paired.</p>
<ol type="a">
<li><p>Compare pre- (beginning of semester) and post-test (end of semester) scores of students.</p></li>
<li><p>Assess gender-related salary gap by comparing salaries of randomly sampled men and women.</p></li>
<li><p>Compare artery thicknesses at the beginning of a study and after 2 years of taking Vitamin E for the same group of patients.</p></li>
<li><p>Assess effectiveness of a diet regimen by comparing the before and after weights of subjects.</p></li>
</ol>
</li>
</ol>
<ol start="4" type="1">
<li>
<p><strong>Paired or not? II.</strong> In each of the following scenarios, determine if the data are paired.</p>
<ol type="a">
<li><p>We would like to know if Intel’s stock and Southwest Airlines’ stock have similar rates of return. To find out, we take a random sample of 50 days, and record Intel’s and Southwest’s stock on those same days.</p></li>
<li><p>We randomly sample 50 items from Target stores and note the price for each. Then we visit Walmart and collect the price for each of those same 50 items.</p></li>
<li><p>A school board would like to determine whether there is a difference in average SAT scores for students at one high school versus another high school in the district. To check, they take a simple random sample of 100 students from each high school.</p></li>
</ol>
</li>
</ol>
<ol start="5" type="1">
<li>
<strong>Sample size and pairing.</strong> Determine if the following statement is true or false, and if false, explain your reasoning: If comparing means of two groups with equal sample sizes, always use a paired test.</li>
</ol>
<ol start="6" type="1">
<li>
<p><strong>High School and Beyond, randomization test.</strong> The National Center of Education Statistics conducted a survey of high school seniors, collecting test data on reading, writing, and several other subjects. Here we examine a simple random sample of 200 students from this survey.</p>
<p>Side-by-side box plots of reading and writing scores as well as a histogram of the differences in scores are shown below. Also provided below is a histogram of randomized averages of paired differences of scores (read - write), with the observed difference (<span class="math inline">\(\bar{x}_{read-write} = -0.545\)</span>) marked with a red vertical line. The randomization distribution was produced by doing the following 1000 times: for each student, the two scores were randomly assigned to either read or write, and the average was taken across all students in the sample.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-6-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="inference-paired-means_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Is there a clear difference in the average reading and writing scores?</p></li>
<li><p>Are the reading and writing scores of each student independent of each other?</p></li>
<li><p>Create hypotheses appropriate for the following research question: is there an evident difference in the average scores of students in the reading and writing exam?</p></li>
<li><p>Is the average of the observed difference in scores <span class="math inline">\((\bar{x}_{read-write} = -0.545)\)</span> consistent with the distribution of randomized average differences? Explain.</p></li>
<li><p>Do these data provide convincing evidence of a difference between the average scores on the two exams? Estimate the p-value from the randomization test, and conclude the hypothesis test using words like “score on reading test” and “score on writing test.”</p></li>
</ol>
</li>
</ol>
<ol start="7" type="1">
<li>
<p><strong>Global warming, randomization test.</strong> Let’s consider a limited set of climate data, examining temperature differences in 1950 vs 2022. We sampled 26 locations in the US from the National Oceanic and Atmospheric Administration’s (NOAA) historical data, where the data was available for both years of interest. <span class="citation" data-cites="webpage:noaa19482018">(<a href="references.html#ref-webpage:noaa19482018" role="doc-biblioref">NOAA 2023</a>)</span> The data are not a random sample, but they are selected to be a representative sample across the land area of the lower 48 United States. Using the hottest day of the year as a measure can make the results susceptible to outliers. Instead, to get a sense for how hot a year was, we calculate the 90<span class="math inline">\(^{th}\)</span> percentile; that is, we find the maximum temperature on the day that was hotter than 90% of the days that year. We want to know: is the 90<span class="math inline">\(^{th}\)</span> percentile high temperature greater in 2022 or in 1950? The difference in 90<span class="math inline">\(^{th}\)</span> percentile high temperature (high temperature for 2022 - high temperature for 1950) was calculated for each of the 26 locations. The average of the 26 differences was 2.52<span class="math inline">\(^\circ\)</span>F with a standard deviation of 2.95<span class="math inline">\(^\circ\)</span>F. We are interested in determining whether these data provide strong evidence that the 90<span class="math inline">\(^{th}\)</span> percentile high temperature is higher in 2022 than in 1950.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.45, -0.05, 0.45]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="question" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Create hypotheses appropriate for the following research question: is there an evident difference in the 90<span class="math inline">\(^{th}\)</span> percentile high temp across the two years (1950 and 2022)?<br></p></li>
<li><p>Is the average of the observed difference in scores <span class="math inline">\((\bar{x}_{2022-1950} = 2.53\)</span>^<span class="math inline">\(F)\)</span> consistent with the distribution of randomized average differences? Explain.</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="inference-paired-means_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:98.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="3" type="a">
<li>Do these data provide convincing evidence of a difference between the 90<span class="math inline">\(^{th}\)</span> percentile high temperature? Estimate the p-value from the randomization test, and conclude the hypothesis test using words like “90<span class="math inline">\(^{th}\)</span> percentile high temperature in 1950” and “90<span class="math inline">\(^{th}\)</span> percentile high temperature in 2022.”</li>
</ol>
</li>
</ol>
<ol start="8" type="1">
<li>
<p><strong>High School and Beyond, bootstrap interval.</strong> We considered the differences between the reading and writing scores of a random sample of 200 students who took the High School and Beyond Survey. The mean and standard deviation of the differences are <span class="math inline">\(\bar{x}_{read-write} = -0.545\)</span> and <span class="math inline">\(s_{read-write}\)</span> = 8.887 points. The bootstrap distribution below was produced by bootstrapping from the sample of differences in reading and writing scores 1,000 times.</p>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.45, -0.05, 0.45]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="question" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Find an approximate 95% bootstrap percentile confidence interval for the true average difference in scores (read - write).<br></p></li>
<li><p>Find an approximate 95% bootstrap SE confidence interval for the true average difference in scores (read - write).</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="inference-paired-means_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:98.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="3" type="a">
<li><p>Interpret both confidence intervals using words like “population” and “score”.</p></li>
<li><p>From the confidence intervals calculated above, does it appear that there is a discernible difference in reading and writing scores, on average?</p></li>
</ol>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>Global warming, bootstrap interval.</strong> We considered the change in the 90<span class="math inline">\(^{th}\)</span> percentile high temperature in 1950 versus 2022 at 26 sampled locations from the NOAA database. <span class="citation" data-cites="webpage:noaa19482018">(<a href="references.html#ref-webpage:noaa19482018" role="doc-biblioref">NOAA 2023</a>)</span> The mean and standard deviation of the reported differences are 2.53<span class="math inline">\(^\circ\)</span>F and 2.95<span class="math inline">\(^\circ\)</span>F.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-9-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="inference-paired-means_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Calculate a 90% bootstrap percentile confidence interval for the average difference of 90<span class="math inline">\(^{th}\)</span> percentile high temperature between 1950 and 2022.</p></li>
<li><p>Calculate a 90% bootstrap SE confidence interval for the average difference of 90<span class="math inline">\(^{th}\)</span> percentile high temperature between 1950 and 2022.</p></li>
<li><p>Interpret both intervals in context.</p></li>
<li><p>Do the confidence intervals provide convincing evidence that there were hotter high temperatures in 2022 than in 1950 at NOAA stations? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="10" type="1">
<li>
<p><strong>High School and Beyond, mathematical test.</strong> We considered the differences between the reading and writing scores of a random sample of 200 students who took the High School and Beyond Survey.</p>
<ol type="a">
<li><p>Create hypotheses appropriate for the following research question: is there an evident difference in the average scores of students in the reading and writing exam?</p></li>
<li><p>Check the conditions required to complete this test.</p></li>
<li><p>The average observed difference in scores is <span class="math inline">\(\bar{x}_{read-write} = -0.545\)</span>, and the standard deviation of the differences is <span class="math inline">\(s_{read-write} = 8.887\)</span> points. Do these data provide convincing evidence of a difference between the average scores on the two exams?</p></li>
<li><p>What type of error might we have made? Explain what the error means in the context of the application.</p></li>
<li><p>Based on the results of this hypothesis test, would you expect a confidence interval for the average difference between the reading and writing scores to include 0? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="11" type="1">
<li>
<p><strong>Global warming, mathematical test.</strong> We considered the change in the 90<span class="math inline">\(^{th}\)</span> percentile high temperature in 1950 versus 2022 at 26 sampled locations from the NOAA database. <span class="citation" data-cites="webpage:noaa19482018">(<a href="references.html#ref-webpage:noaa19482018" role="doc-biblioref">NOAA 2023</a>)</span> The mean and standard deviation of the reported differences are 2.53<span class="math inline">\(^\circ\)</span>F and 2.95<span class="math inline">\(^\circ\)</span>F.</p>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.45, -0.05, 0.45]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="question" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<ol type="a">
<li><p>Is there a relationship between the observations collected in 1950 and 2022? Or are the observations in the two groups independent? Explain your reasoning.<br></p></li>
<li><p>Write hypotheses for this research in symbols and in words.<br></p></li>
<li><p>Check the conditions required to complete this test.<br></p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="plot" class="quarto-layout-cell" style="flex-basis: 45.0%;justify-content: flex-start;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="inference-paired-means_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:98.0%"></a></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
<ol start="4" type="a">
<li><p>Calculate the test statistic and find the p-value.</p></li>
<li><p>Use <span class="math inline">\(\alpha = 0.05\)</span> to evaluate the test, and interpret your conclusion in context.</p></li>
<li><p>What type of error might we have made? Explain in context what the error means.</p></li>
<li><p>Based on the results of this hypothesis test, would you expect a confidence interval for the average difference between the 90<span class="math inline">\(^{th}\)</span> percentile high temperture from 1950 to 2022 to include 0? Explain your reasoning.</p></li>
</ol>
</li>
<li>
<p><strong>High school and beyond, mathematical interval.</strong> We considered the differences between the reading and writing scores of a random sample of 200 students who took the High School and Beyond Survey. The mean and standard deviation of the differences are <span class="math inline">\(\bar{x}_{read-write} = -0.545\)</span> and <span class="math inline">\(s_{read-write}\)</span> = 8.887 points.</p>
<ol type="a">
<li><p>Calculate a 95% confidence interval for the average difference between the reading and writing scores of all students.</p></li>
<li><p>Interpret this interval in context.</p></li>
<li><p>Does the confidence interval provide convincing evidence that there is a real difference in the average scores? Explain.</p></li>
</ol>
</li>
<li>
<p><strong>Global warming, mathematical interval.</strong> We considered the change in the 90<span class="math inline">\(^{th}\)</span> percentile high temperature in 1950 versus 2022 at 26 sampled locations from the NOAA database. <span class="citation" data-cites="webpage:noaa19482018">(<a href="references.html#ref-webpage:noaa19482018" role="doc-biblioref">NOAA 2023</a>)</span> The mean and standard deviation of the reported differences are 2.53<span class="math inline">\(^\circ\)</span>F and 2.95<span class="math inline">\(^\circ\)</span>F.</p>
<ol type="a">
<li><p>Calculate a 90% confidence interval for the average difference of 90<span class="math inline">\(^{th}\)</span> percentile high temperature between 1950 and 2022. We’ve already checked the conditions for you.</p></li>
<li><p>Interpret the interval in context.</p></li>
<li><p>Does the confidence interval provide convincing evidence that there were hotter high temperatures in 2022 than in 1950 at NOAA stations? Explain your reasoning.</p></li>
</ol>
</li>
<li>
<p><strong>Possible paired randomized differences.</strong> Two observations were collected on each of five people. Which of the following could be a possible randomization of the paired differences given in the table below? If the set of values could not be a randomized set of differences, indicate why not.</p>
<div class="quarto-layout-panel" data-layout="[-0.05, 0.35, -0.02, 0.58]">
<div class="quarto-layout-row">
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 5.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="question" class="quarto-layout-cell" style="flex-basis: 35.0%;justify-content: flex-start;">
<ol type="a">
<li><p>-2, 1, 1, 11, -2</p></li>
<li><p>-4, 11, -2, 0, 1</p></li>
<li><p>-2, 2, -11, 11, -2, 2, 0, 1, -1</p></li>
<li><p>0, -1, 2, -4, 11</p></li>
<li><p>4, -11, 2, 0, -1</p></li>
</ol>
</div>
<div class="quarto-figure-spacer quarto-layout-cell" style="flex-basis: 2.0%;justify-content: flex-start;">
<p>&nbsp;</p>
</div>
<div id="table" class="quarto-layout-cell" style="flex-basis: 58.0%;justify-content: center;">
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
People
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Observation 1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observation 2</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Difference</td>
<td style="text-align: right;">-4</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Study environment.</strong> In order to test the effects of listening to music while studying versus studying in silence, students agree to be randomized to two treatments (i.e., study with music or study in silence). There are two exams during the semester, so the researchers can either randomize the students to have one exam with music and one with silence (randomly selecting which exam corresponds to which study environment) or the researchers can randomize the students to one study habit for both exams.</p>
<p>The researchers are interested in estimating the true population difference of exam score for those who listen to music while studying as compared to those who study in silence.</p>
<ol type="a">
<li><p>Describe the experiment which is consistent with a paired designed experiment. How is the treatment assigned, and how are the data collected such that the observations are paired?</p></li>
<li><p>Describe the experiment which is consistent with an indpenedent samples experiment. How is the treatment assigned, and how are the data collected such that the observations are independent?</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>Friday the 13th, traffic.</strong> In the early 1990’s, researchers in the UK collected data on traffic flow on Friday the 13th with the goal of addressing issues of how superstitions regarding Friday the 13th affect human behavior and and whether Friday the 13th is an unlucky day. The histograms below show the distributions of numbers of cars passing by a specific intersection on Friday the 6th and Friday the 13th for many such date pairs. Also provided are some sample statistics, where the difference is the number of cars on the 6th minus the number of cars on the 13th.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> <span class="citation" data-cites="Scanlon:1993">(<a href="references.html#ref-Scanlon:1993" role="doc-biblioref">Scanlon et al. 1993</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19"><img src="inference-paired-means_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">sixth</td>
<td style="text-align: right; width: 5em;">10</td>
<td style="text-align: right; width: 5em;">128,385</td>
<td style="text-align: right; width: 5em;">7,259</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">thirteenth</td>
<td style="text-align: right; width: 5em;">10</td>
<td style="text-align: right; width: 5em;">126,550</td>
<td style="text-align: right; width: 5em;">7,664</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">diff</td>
<td style="text-align: right; width: 5em;">10</td>
<td style="text-align: right; width: 5em;">1,836</td>
<td style="text-align: right; width: 5em;">1,176</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>Are there any underlying structures in these data that should be considered in an analysis? Explain.</p></li>
<li><p>What are the hypotheses for evaluating whether the number of people out on Friday the 6<span class="math inline">\(^{\text{th}}\)</span> is different than the number out on Friday the 13<span class="math inline">\(^{\text{th}}\)</span>?</p></li>
<li><p>Check conditions to carry out the hypothesis test from part (b) using mathematical models.</p></li>
<li><p>Calculate the test statistic and the p-value.</p></li>
<li><p>What is the conclusion of the hypothesis test?</p></li>
<li><p>Interpret the p-value in this context.</p></li>
<li><p>What type of error might have been made in the conclusion of your test? Explain.</p></li>
</ol>
</li>
</ol>
<ol start="17" type="1">
<li>
<p><strong>Friday the 13th, accidents.</strong> In the early 1990’s, researchers in the UK collected data the number of traffic accident related emergency room (ER) admissions on Friday the 13th with the goal of addressing issues of how superstitions regarding Friday the 13th affect human behavior and and whether Friday the 13th is an unlucky day. The histograms below show the distributions of numbers of ER admissions at specific emergency rooms on Friday the 6th and Friday the 13th for many such date pairs. Also provided are some sample statistics, where the difference is the ER admissions on the 6th minus the ER admissions on the 13th.<span class="citation" data-cites="Scanlon:1993">(<a href="references.html#ref-Scanlon:1993" role="doc-biblioref">Scanlon et al. 1993</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-paired-means_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20"><img src="inference-paired-means_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:100.0%"></a></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">sixth</td>
<td style="text-align: right; width: 5em;">6</td>
<td style="text-align: right; width: 5em;">8</td>
<td style="text-align: right; width: 5em;">3</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">thirteenth</td>
<td style="text-align: right; width: 5em;">6</td>
<td style="text-align: right; width: 5em;">11</td>
<td style="text-align: right; width: 5em;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">diff</td>
<td style="text-align: right; width: 5em;">6</td>
<td style="text-align: right; width: 5em;">-3</td>
<td style="text-align: right; width: 5em;">3</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>Conduct a hypothesis test using mathematical models to evaluate if there is a difference between the average numbers of traffic accident related emergency room admissions between Friday the 6<span class="math inline">\(^{\text{th}}\)</span> and Friday the 13<span class="math inline">\(^{\text{th}}\)</span>.</p></li>
<li><p>Calculate a 95% confidence interval using mathematical models for the difference between the average numbers of traffic accident related emergency room admissions between Friday the 6<span class="math inline">\(^{\text{th}}\)</span> and Friday the 13<span class="math inline">\(^{\text{th}}\)</span>.</p></li>
<li><p>The conclusion of the original study states, “Friday 13th is unlucky for some. The risk of hospital admission as a result of a transport accident may be increased by as much as 52%. Staying at home is recommended.” Do you agree with this statement? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="18" type="1">
<li>
<p><strong>Forest management.</strong> Forest rangers wanted to better understand the rate of growth for younger trees in the park. They took measurements of a random sample of 50 young trees in 2009 and again measured those same trees in 2019. The data below summarize their measurements, where the heights are in feet.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Year</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">2009</td>
<td style="text-align: center; width: 5em;">12.0</td>
<td style="text-align: center; width: 5em;">3.5</td>
<td style="text-align: center; width: 5em;">50</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">2019</td>
<td style="text-align: center; width: 5em;">24.5</td>
<td style="text-align: center; width: 5em;">9.5</td>
<td style="text-align: center; width: 5em;">50</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">Difference</td>
<td style="text-align: center; width: 5em;">12.5</td>
<td style="text-align: center; width: 5em;">7.2</td>
<td style="text-align: center; width: 5em;">50</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Construct a 99% confidence interval for the average growth of (what had been) younger trees in the park over 2009-2019.</p>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-webpage:noaa19482018" class="csl-entry" role="listitem">
NOAA. 2023. <span>“Climate Data Online.”</span> <a href="http://www.openintro.org/redirect.php?go=textbook-noaa_1948_2018">http://www.openintro.org/redirect.php?go=textbook-noaa_1948_2018</a>.
</div>
<div id="ref-Scanlon:1993" class="csl-entry" role="listitem">
Scanlon, T. J., R. N. Luben, F. L. Scanlon, and N. Singleton. 1993. <span>“Is Friday the 13th Bad for Your Health?”</span> <em>British Medical Journal</em> 307: 1584–86. <a href="https://doi.org/10.1136/bmj.307.6919.1584">https://doi.org/10.1136/bmj.307.6919.1584</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The bootstrapped differences in sample means vary roughly from 0.7 to 7.5, a range of $6.80. Although the bootstrap distribution is not symmetric, we use the empirical rule (that with bell-shaped distributions, most observations are within two standard errors of the center), the standard error of the mean differences is approximately $1.70. You might note that the standard error calculation given in <a href="#sec-mathpaired" class="quarto-xref"><span>Section 21.3</span></a> is <span class="math inline">\(SE(\bar{x}_{diff}) = \sqrt{s^2_{diff}/n_{diff}} = \sqrt{13.4^2/68} = \$1.62\)</span> (values from <a href="#sec-mathpaired" class="quarto-xref"><span>Section 21.3</span></a>), very close to the bootstrap approximation.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The average price difference is only mildly useful for this question. Examine the distribution shown in <a href="#fig-diffInTextbookPricesF18" class="quarto-xref">Figure&nbsp;<span>21.10</span></a>. There are certainly a handful of cases where Amazon prices are far below the UCLA Bookstore’s, which suggests it is worth checking Amazon (and probably other online sites) before purchasing. However, in many cases the Amazon price is above what the UCLA Bookstore charges, and most of the time the price isn’t that different. Ultimately, if getting a book immediately from the bookstore is notably more convenient, e.g., to get started on reading or homework, it’s likely a good idea to go with the UCLA Bookstore unless the price difference on a specific book happens to be quite large. For reference, this is a very different result from what we (the authors) had seen in a similar dataset from 2010. At that time, Amazon prices were almost uniformly lower than those of the UCLA Bookstore’s and by a large margin, making the case to use Amazon over the UCLA Bookstore quite compelling at that time. Now we frequently check multiple websites to find the best price.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The <a href="http://openintrostat.github.io/openintro/reference/hsb2.html"><code>hsb2</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <a href="http://openintrostat.github.io/openintro/reference/us_temperature.html"><code>us_temperature</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>The <a href="http://openintrostat.github.io/openintro/reference/friday.html"><code>friday</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./inference-two-means.html" class="pagination-link" aria-label="Inference for comparing two independent means">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference-many-means.html" class="pagination-link" aria-label="Inference for comparing many means">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-paired-means.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>