<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>18&nbsp; Inference for two-way tables – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference-one-mean.html" rel="next">
<link href="./inference-two-props.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c115713b74ff8bcd8ed35270603a4893.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b48b13b17e828e7fee5d86eb98a32420.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-c115713b74ff8bcd8ed35270603a4893.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-790f3f5e7e2e01ab58e527b05f631cee.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-tables.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#randomization-test-of-independence" id="toc-randomization-test-of-independence" class="nav-link active" data-scroll-target="#randomization-test-of-independence"><span class="header-section-number">18.1</span> Randomization test of independence</a>
  <ul class="collapse">
<li><a href="#expected-counts-in-two-way-tables" id="toc-expected-counts-in-two-way-tables" class="nav-link" data-scroll-target="#expected-counts-in-two-way-tables"><span class="header-section-number">18.1.1</span> Expected counts in two-way tables</a></li>
  <li><a href="#the-observed-chi-squared-statistic" id="toc-the-observed-chi-squared-statistic" class="nav-link" data-scroll-target="#the-observed-chi-squared-statistic"><span class="header-section-number">18.1.2</span> The observed chi-squared statistic</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">18.1.3</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-chi-squared-statistics" id="toc-observed-statistic-vs.-null-chi-squared-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-chi-squared-statistics"><span class="header-section-number">18.1.4</span> Observed statistic vs.&nbsp;null chi-squared statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-mathchisq" id="toc-sec-mathchisq" class="nav-link" data-scroll-target="#sec-mathchisq"><span class="header-section-number">18.2</span> Mathematical model for test of independence</a>
  <ul class="collapse">
<li><a href="#the-chi-squared-test-of-independence" id="toc-the-chi-squared-test-of-independence" class="nav-link" data-scroll-target="#the-chi-squared-test-of-independence"><span class="header-section-number">18.2.1</span> The chi-squared test of independence</a></li>
  <li><a href="#variability-of-the-chi-squared-statistic" id="toc-variability-of-the-chi-squared-statistic" class="nav-link" data-scroll-target="#variability-of-the-chi-squared-statistic"><span class="header-section-number">18.2.2</span> Variability of the chi-squared statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-chi-squared-statistics-1" id="toc-observed-statistic-vs.-null-chi-squared-statistics-1" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-chi-squared-statistics-1"><span class="header-section-number">18.2.3</span> Observed statistic vs.&nbsp;null chi-squared statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp18-review" id="toc-sec-chp18-review" class="nav-link" data-scroll-target="#sec-chp18-review"><span class="header-section-number">18.3</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">18.3.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">18.3.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp18-exercises" id="toc-sec-chp18-exercises" class="nav-link" data-scroll-target="#sec-chp18-exercises"><span class="header-section-number">18.4</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-tables.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-tables.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-inference-tables" class="quarto-section-identifier"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>In <a href="inference-two-props.html" class="quarto-xref">Chapter&nbsp;<span>17</span></a> our focus was on the difference in proportions, a statistic calculated from finding the success proportions (from the binary response variable) measured across two groups (the binary explanatory variable). As we will see in the examples below, sometimes the explanatory or response variables have more than two possible options. In that setting, a difference across two groups is not sufficient, and the proportion of “success” is not well defined if there are 3 or 4 or more possible response levels. The primary way to summarize categorical data where the explanatory and response variables both have 2 or more levels is through a two-way table as in <a href="#tbl-ipod-ask-data-summary" class="quarto-xref">Table&nbsp;<span>18.1</span></a>.</p>
<p>Note that with two-way tables, there is not an obvious single parameter of interest. Instead, research questions usually focus on how the proportions of the response variable changes (or not) across the different levels of the explanatory variable. Because there is not a population parameter to estimate, bootstrapping to find the standard error of the estimate is not meaningful. As such, for two-way tables, we will focus on the randomization test and corresponding mathematical approximation (and not bootstrapping).</p>
</div>
<section id="randomization-test-of-independence" class="level2" data-number="18.1"><h2 data-number="18.1" class="anchored" data-anchor-id="randomization-test-of-independence">
<span class="header-section-number">18.1</span> Randomization test of independence</h2>
<p>We all buy used products – cars, computers, textbooks, and so on – and we sometimes assume the sellers of those products will be forthright about any underlying problems with what they’re selling. This is not something we should take for granted. Researchers recruited 219 participants in a study where they would sell a used iPod<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> that was known to have frozen twice in the past. The participants were incentivized to get as much money as they could for the iPod since they would receive a 5% cut of the sale on top of $10 for participating. The researchers wanted to understand what types of questions would elicit the seller to disclose the freezing issue.</p>
<p>Unbeknownst to the participants who were the sellers in the study, the buyers were collaborating with the researchers to evaluate the influence of different questions on the likelihood of getting the sellers to disclose the past issues with the iPod. The scripted buyers started with “Okay, I guess I’m supposed to go first. So you’ve had the iPod for 2 years …” and ended with one of three questions:</p>
<ul>
<li>General: What can you tell me about it?</li>
<li>Positive Assumption: It does not have any problems, does it?</li>
<li>Negative Assumption: What problems does it have?</li>
</ul>
<p>The question is the treatment given to the sellers, and the response is whether the question prompted them to disclose the freezing issue with the iPod. The results are shown in <a href="#tbl-ipod-ask-data-summary" class="quarto-xref">Table&nbsp;<span>18.1</span></a>, and the data suggest that asking the, <em>What problems does it have?</em>, was the most effective at getting the seller to disclose the past freezing issues. However, you should also be asking yourself: could we see these results due to chance alone if there really is no difference in the question asked, or is this in fact evidence that some questions are more effective for getting at the truth?</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-ipod-ask-data-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipod-ask-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.1: Summary of the iPod study, where a question was posed to the study participant who acted.
</figcaption><div aria-describedby="tbl-ipod-ask-data-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Question</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Disclose problem</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hide problem</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">General</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Positive assumption</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Negative assumption</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">37</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">158</td>
<td style="text-align: right;">219</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/ask.html"><code>ask</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p>The hypothesis test for the iPod experiment is really about assessing whether there is convincing evidence that there was a difference in the success rates that each question had on getting the participant to disclose the problem with the iPod. In other words, the goal is to check whether the buyer’s question was independent of whether the seller disclosed a problem.</p>
<section id="expected-counts-in-two-way-tables" class="level3" data-number="18.1.1"><h3 data-number="18.1.1" class="anchored" data-anchor-id="expected-counts-in-two-way-tables">
<span class="header-section-number">18.1.1</span> Expected counts in two-way tables</h3>
<p>While we would not expect the number of disclosures to be exactly the same across the three question classes, the rate of disclosure seems substantially different across the three groups. In order to investigate whether the differences in rates is due to natural variability in people’s honesty or due to a treatment effect (i.e., the question causing the differences), we need to compute estimated counts for each cell in a two-way table.</p>
<div class="workedexample">
<p>From the experiment, we can compute the proportion of all sellers who disclosed the freezing problem as <span class="math inline">\(61/219 = 0.2785.\)</span> If there really is no difference among the questions and 27.85% of sellers were going to disclose the freezing problem no matter the question they were asked, how many of the 73 people in the <code>General</code> group would we have expected to disclose the freezing problem?</p>
<hr>
<p>We would predict that <span class="math inline">\(0.2785 \times 73 = 20.33\)</span> sellers would disclose the problem. Obviously we observed fewer than this, though it is not yet clear if that is due to chance variation or whether that is because the questions vary in how effective they are at getting to the truth.</p>
</div>
<div class="guidedpractice">
<p>If the questions were actually equally effective, meaning about 27.85% of respondents would disclose the freezing issue regardless of what question they were asked, about how many sellers would we expect to <em>hide</em> the freezing problem from the Positive Assumption group?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
<p>We can compute the expected number of sellers who we would expect to disclose or hide the freezing issue for all groups, if the questions had no impact on what they disclosed, using the same strategies employed in the previous Example and Guided Practice to compute expected counts. These expected counts were used to construct <a href="#tbl-ipod-ask-data-summary-expected" class="quarto-xref">Table&nbsp;<span>18.2</span></a>, which is the same as <a href="#tbl-ipod-ask-data-summary" class="quarto-xref">Table&nbsp;<span>18.1</span></a>, except now the expected counts have been added in parentheses.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-ipod-ask-data-summary-expected" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipod-ask-data-summary-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.2: The observed counts and the expected counts for the iPod experiment.
</figcaption><div aria-describedby="tbl-ipod-ask-data-summary-expected-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Disclose problem
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Hide problem
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Total
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">General</td>
<td style="text-align: right;">2</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(20.33)</td>
<td style="text-align: right;">71</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(52.67)</td>
<td style="text-align: right; width: 5em;">73</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Positive assumption</td>
<td style="text-align: right;">23</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(20.33)</td>
<td style="text-align: right;">50</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(52.67)</td>
<td style="text-align: right; width: 5em;">73</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Negative assumption</td>
<td style="text-align: right;">36</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(20.33)</td>
<td style="text-align: right;">37</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;">(52.67)</td>
<td style="text-align: right; width: 5em;">73</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Total</td>
<td style="text-align: right;">61</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;"></td>
<td style="text-align: right;">158</td>
<td style="text-align: left; font-style: italic; color: rgba(86, 155, 189, 255) !important;"></td>
<td style="text-align: right; width: 5em;">219</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The examples and exercises above provided some help in computing expected counts. In general, expected counts for a two-way table may be computed using the row totals, column totals, and the table total. For instance, if there was no difference between the groups, then about 27.85% of each row should be in the first column:</p>
<p><span class="math display">\[
\begin{aligned}
0.2785\times (\text{row 1 total}) &amp;= 20.33 \\
0.2785\times (\text{row 2 total}) &amp;= 20.33 \\
0.2785\times (\text{row 3 total}) &amp;= 20.33
\end{aligned}
\]</span></p>
<p>Looking back to how 0.2785 was computed – as the fraction of sellers who disclosed the freezing issue <span class="math inline">\((61/219)\)</span> – these three expected counts could have been computed as</p>
<p><span class="math display">\[
\begin{aligned}
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 1 total)} &amp;= 20.33 \\
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 2 total)} &amp;= 20.33 \\
\left(\frac{\text{row 1 total}}{\text{table total}}\right)
    \text{(column 3 total)} &amp;= 20.33
\end{aligned}
\]</span></p>
<p>This leads us to a general formula for computing expected counts in a two-way table when we would like to test whether there is strong evidence of an association between the column variable and row variable.</p>
<div class="important">
<p><strong>Computing expected counts in a two-way table.</strong></p>
<p></p>
<p>To calculate the expected count for the <span class="math inline">\(i^{th}\)</span> row and <span class="math inline">\(j^{th}\)</span> column, compute</p>
<p><span class="math display">\[\text{Expected Count}_{\text{row }i,\text{ col }j} = \frac{(\text{row $i$ total}) \times (\text{column $j$ total})}{\text{table total}}\]</span></p>
</div>
</section><section id="the-observed-chi-squared-statistic" class="level3" data-number="18.1.2"><h3 data-number="18.1.2" class="anchored" data-anchor-id="the-observed-chi-squared-statistic">
<span class="header-section-number">18.1.2</span> The observed chi-squared statistic</h3>
<p>The chi-squared test statistic for a two-way table is found by finding the ratio of how far the observed counts are from the expected counts, as compared to the expected counts, for every cell in the table. For each table count, compute:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{General formula} &amp;&amp;
    \frac{(\text{observed count } - \text{expected count})^2}
        {\text{expected count}} \\
&amp;\text{Row 1, Col 1} &amp;&amp;
    \frac{(2 - 20.33)^2}{20.33} = 16.53 \\
&amp;\text{Row 2, Col 1} &amp;&amp;
    \frac{(23 - 20.33)^2}{20.33} = 0.35 \\
&amp; \hspace{9mm}\vdots &amp;&amp;
    \hspace{13mm}\vdots \\
&amp;\text{Row 3, Col 2} &amp;&amp;
    \frac{(37 - 52.67)^2}{52.67} = 4.66
\end{aligned}
\]</span></p>
<p>Adding the computed value for each cell gives the chi-squared test statistic <span class="math inline">\(X^2:\)</span></p>
<p><span class="math display">\[X^2 = 16.53 + 0.35 + \dots + 4.66 = 40.13\]</span></p>
<p>Is 40.13 a big number? That is, does it indicate that the observed and expected values are really different? Or is 40.13 a value of the statistic that we would expect to see just due to natural variability? Previously, we applied the randomization test to the setting where the research question investigated a difference in proportions. The same idea of shuffling the data under the null hypothesis can be used in the setting of the two-way table.</p>
</section><section id="variability-of-the-statistic" class="level3" data-number="18.1.3"><h3 data-number="18.1.3" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">18.1.3</span> Variability of the statistic</h3>
<p>Assuming that the individuals would disclose or hide the problems <strong>regardless</strong> of the question they are given (i.e., that the null hypothesis is true), we can randomize the data by reassigning the 61 disclosed problems and 158 hidden problems to the three groups at random. <a href="#tbl-ipod-ask-data-summary-rand" class="quarto-xref">Table&nbsp;<span>18.3</span></a> shows a possible randomization of the observed data under the condition that the null hypothesis is true (in contrast to the original observed data in <a href="#tbl-ipod-ask-data-summary" class="quarto-xref">Table&nbsp;<span>18.1</span></a>).</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-ipod-ask-data-summary-rand" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-ipod-ask-data-summary-rand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.3: Summary of the iPod study.
</figcaption><div aria-describedby="tbl-ipod-ask-data-summary-rand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Question</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Disclose problem</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Hide problem</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">General</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">44</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Positive assumption</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">58</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Negative assumption</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">56</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">61</td>
<td style="text-align: right;">158</td>
<td style="text-align: right;">219</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As before, the randomized data is used to find a single value for the test statistic (here a chi-squared statistic). The chi-squared statistic for the randomized two-way table is found by comparing the observed and expected counts for each cell in the <em>randomized</em> table. For each cell, compute:</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\text{General formula} &amp;&amp;
    \frac{(\text{observed count } - \text{expected count})^2}
        {\text{expected count}} \\
&amp;\text{Row 1, Col 1} &amp;&amp;
    \frac{(29 - 20.33)^2}{20.33} = 3.7 \\
&amp;\text{Row 2, Col 1} &amp;&amp;
    \frac{(15 - 20.33)^2}{20.33} = 1.4 \\
&amp; \hspace{9mm}\vdots &amp;&amp;
    \hspace{13mm}\vdots \\
&amp;\text{Row 3, Col 2} &amp;&amp;
    \frac{(56 - 52.67)^2}{52.67} = 0.211
\end{aligned}
\]</span></p>
<p>Adding the computed value for each cell gives the chi-squared test statistic <span class="math inline">\(X^2:\)</span> </p>
<p><span class="math display">\[X^2 = 3.7 + 1.4 + \dots + 0.211 = 8\]</span></p>
</section><section id="observed-statistic-vs.-null-chi-squared-statistics" class="level3" data-number="18.1.4"><h3 data-number="18.1.4" class="anchored" data-anchor-id="observed-statistic-vs.-null-chi-squared-statistics">
<span class="header-section-number">18.1.4</span> Observed statistic vs.&nbsp;null chi-squared statistics</h3>
<p>As before, one randomization will not be sufficient for understanding if the observed data are particularly different from the expected chi-squared statistics when <span class="math inline">\(H_0\)</span> is true. To investigate whether 40.13 is large enough to indicate the observed and expected counts are substantially different, we need to understand the variability in the values of the chi-squared statistic we would expect to see if the null hypothesis was true. <a href="#fig-ipodRandDotPlot" class="quarto-xref">Figure&nbsp;<span>18.1</span></a> plots 1,000 chi-squared statistics generated under the null hypothesis. We can see that the observed value is so far from the null statistics that the simulated p-value is zero. That is, the probability of seeing the observed statistic when the null hypothesis is true is virtually zero. In this case we can conclude that the decision of whether to disclose the iPod’s problem is changed by the question asked. We use the causal language of “changed” because the study was an experiment. Note that with a chi-squared test, we only know that the two variables (<code>question_class</code> and <code>response</code>) are related (i.e., not independent). We are not able to claim which type of question causes which type of response.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ipodRandDotPlot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A histogram of chi-squared statisics from 1,000 simulations produced under the null hypothesis, where the question is independent of the response. The observed statistic of 40.13 is marked by the red line. None of the 1,000 simulations had a chi-squared value of at least 40.13. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ipodRandDotPlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-tables_files/figure-html/fig-ipodRandDotPlot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;18.1: A histogram of chi-squared statisics from 1,000 simulations produced under the null hypothesis, H_0, where the question is independent of the response. The observed statistic of 40.13 is marked by the red line. None of the 1,000 simulations had a chi-squared value of at least 40.13. In fact, none of the simulated chi-squared statistics came anywhere close to the observed statistic!"><img src="inference-tables_files/figure-html/fig-ipodRandDotPlot-1.png" class="img-fluid figure-img" style="width:90.0%" alt="A histogram of chi-squared statisics from 1,000 simulations produced under the null hypothesis, where the question is independent of the response. The observed statistic of 40.13 is marked by the red line. None of the 1,000 simulations had a chi-squared value of at least 40.13. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ipodRandDotPlot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.1: A histogram of chi-squared statisics from 1,000 simulations produced under the null hypothesis, <span class="math inline">\(H_0,\)</span> where the question is independent of the response. The observed statistic of 40.13 is marked by the red line. None of the 1,000 simulations had a chi-squared value of at least 40.13. In fact, none of the simulated chi-squared statistics came anywhere close to the observed statistic!
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="sec-mathchisq" class="level2" data-number="18.2"><h2 data-number="18.2" class="anchored" data-anchor-id="sec-mathchisq">
<span class="header-section-number">18.2</span> Mathematical model for test of independence</h2>
<section id="the-chi-squared-test-of-independence" class="level3" data-number="18.2.1"><h3 data-number="18.2.1" class="anchored" data-anchor-id="the-chi-squared-test-of-independence">
<span class="header-section-number">18.2.1</span> The chi-squared test of independence</h3>
<p>Previously, in <a href="inference-two-props.html#sec-math-2prop" class="quarto-xref"><span>Section 17.3</span></a>, we applied the Central Limit Theorem to the sampling variability of <span class="math inline">\(\hat{p}_1 - \hat{p}_2.\)</span> The result was that we could use the normal distribution (e.g., <span class="math inline">\(z^*\)</span> values (see <a href="inference-one-prop.html#fig-choosingZForCI" class="quarto-xref">Figure&nbsp;<span>16.2</span></a>) and p-values from <span class="math inline">\(Z\)</span> scores) to complete the mathematical inferential procedure. The chi-squared test statistic has a different mathematical distribution called the Chi-squared distribution. The important specification to make in describing the chi-squared distribution is something called degrees of freedom. The degrees of freedom change the shape of the chi-squared distribution to fit the problem at hand. <a href="#fig-chisqDistDF" class="quarto-xref">Figure&nbsp;<span>18.2</span></a> visualizes different chi-squared distributions corresponding to different degrees of freedom.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-chisqDistDF" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The chi-squared distribution for differing degrees of freedom. The larger the degrees of freedom, the longer the right tail extends. The smaller the degrees of freedom, the more peaked the mode on the left becomes. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-chisqDistDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-tables_files/figure-html/fig-chisqDistDF-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;18.2: The chi-squared distribution for differing degrees of freedom. The larger the degrees of freedom, the longer the right tail extends. The smaller the degrees of freedom, the more peaked the mode on the left becomes."><img src="inference-tables_files/figure-html/fig-chisqDistDF-1.png" class="img-fluid figure-img" style="width:90.0%" alt="The chi-squared distribution for differing degrees of freedom. The larger the degrees of freedom, the longer the right tail extends. The smaller the degrees of freedom, the more peaked the mode on the left becomes. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-chisqDistDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.2: The chi-squared distribution for differing degrees of freedom. The larger the degrees of freedom, the longer the right tail extends. The smaller the degrees of freedom, the more peaked the mode on the left becomes.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="variability-of-the-chi-squared-statistic" class="level3" data-number="18.2.2"><h3 data-number="18.2.2" class="anchored" data-anchor-id="variability-of-the-chi-squared-statistic">
<span class="header-section-number">18.2.2</span> Variability of the chi-squared statistic</h3>
<p>As it turns out, the chi-squared test statistic follows a <strong>Chi-squared distribution</strong> when the null hypothesis is true. For two way tables, the degrees of freedom is equal to: <span class="math inline">\(df = \text{(number of rows minus 1)}\times \text{(number of columns minus 1)}\)</span>. In our example, the degrees of freedom parameter is <span class="math inline">\(df = (2-1)\times (3-1) = 2\)</span>.</p>
</section><section id="observed-statistic-vs.-null-chi-squared-statistics-1" class="level3" data-number="18.2.3"><h3 data-number="18.2.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-chi-squared-statistics-1">
<span class="header-section-number">18.2.3</span> Observed statistic vs.&nbsp;null chi-squared statistics</h3>
<div class="important">
<p><strong>The test statistic for assessing the independence between two categorical variables is a</strong> <span class="math inline">\(X^2.\)</span></p>
<p>The <span class="math inline">\(X^2\)</span> statistic is a ratio of how the observed counts vary from the expected counts as compared to the expected counts (which are a measure of how large the sample size is).</p>
<p><span class="math display">\[X^2 = \sum_{i,j} \frac{(\text{observed count} - \text{expected count})^2}{\text{expected count}}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, <span class="math inline">\(X^2\)</span> has a Chi-squared distribution with <span class="math inline">\(df = (r-1) \times (c-1).\)</span></p>
<p>Conditions:</p>
<ul>
<li>Independent observations</li>
<li>Large samples: 5 expected counts in each cell</li>
</ul>
</div>
<p>To bring it back to the example, we can safely assume that the observations are independent, as the question groups were randomly assigned. Additionally, there are over 5 expected counts in each cell, so the conditions for using the Chi-square distribution are met. If the null hypothesis is true (i.e., the questions had no impact on the sellers in the experiment), then the test statistic <span class="math inline">\(X^2 = 40.13\)</span> is expected to follow a Chi-squared distribution with 2 degrees of freedom. Using this information, we can compute the p-value for the test, which is depicted in <a href="#fig-iPodChiSqTail" class="quarto-xref">Figure&nbsp;<span>18.3</span></a>.</p>
<div class="important">
<p><strong>Computing degrees of freedom for a two-way table.</strong></p>
<p> When applying the chi-squared test to a two-way table, we use <span class="math inline">\(df = (R-1)\times (C-1)\)</span> where <span class="math inline">\(R\)</span> is the number of rows in the table and <span class="math inline">\(C\)</span> is the number of columns.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-iPodChiSqTail" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Chi-square distribution (with df = 2) curve, shaded for p-value for  X2 = 40.13. The p-value is so small that it is not visible on the plot. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-iPodChiSqTail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-tables_files/figure-html/fig-iPodChiSqTail-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;18.3: Visualization of the p-value for X^2 = 40.13 when df = 2."><img src="inference-tables_files/figure-html/fig-iPodChiSqTail-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Chi-square distribution (with df = 2) curve, shaded for p-value for  X2 = 40.13. The p-value is so small that it is not visible on the plot. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iPodChiSqTail-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;18.3: Visualization of the p-value for <span class="math inline">\(X^2 = 40.13\)</span> when <span class="math inline">\(df = 2\)</span>.
</figcaption></figure>
</div>
</div>
</div>
<p>The software R can be used to find the p-value with the function <code><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq()</a></code>. Just like <code><a href="https://rdrr.io/r/stats/Normal.html">pnorm()</a></code>, <code><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq()</a></code> always gives the area to the left of the cutoff value. Because, in this example, the p-value is represented by the area to the right of 40.13, we subtract the output of <code><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq()</a></code> from 1.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fl">1</span> <span class="op">-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Chisquare.html">pchisq</a></span><span class="op">(</span><span class="fl">40.13</span>, df <span class="op">=</span> <span class="fl">2</span><span class="op">)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.93e-09</code></pre>
</div>
</div>
<div class="workedexample">
<p>Find the p-value and draw a conclusion about whether the question affects the sellers likelihood of reporting the freezing problem.</p>
<hr>
<p>Using a computer, we can compute a very precise value for the tail area above <span class="math inline">\(X^2 = 40.13\)</span> for a chi-squared distribution with 2 degrees of freedom: 0.000000002.</p>
<p>Using a discernibility level of <span class="math inline">\(\alpha=0.05,\)</span> the null hypothesis is rejected since the p-value is smaller. That is, the data provide convincing evidence that the question asked did affect a seller’s likelihood to tell the truth about problems with the iPod.</p>
</div>
<div class="workedexample">
<p><a href="#tbl-diabetes2ExpMetRosiLifestyleSummary" class="quarto-xref">Table&nbsp;<span>18.4</span></a> summarizes the results of an experiment evaluating three treatments for Type 2 Diabetes in patients aged 10-17 who were being treated with metformin. The three treatments considered were continued treatment with metformin (<code>met</code>), treatment with metformin combined with rosiglitazone (<code>rosi</code>), or a <code>lifestyle</code> intervention program. Each patient had a primary outcome, which was either lacked glycemic control (failure) or did not lack that control (success). What are appropriate hypotheses for this test?</p>
<hr>
<ul>
<li>
<span class="math inline">\(H_0:\)</span> There is no difference in the effectiveness of the three treatments.</li>
<li>
<span class="math inline">\(H_A:\)</span> There is some difference in effectiveness between the three treatments, e.g., perhaps the <code>rosi</code> treatment performed better than <code>lifestyle</code>.</li>
</ul>
</div>
<div class="cell" data-tbl-pos="H">
<div id="tbl-diabetes2ExpMetRosiLifestyleSummary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-diabetes2ExpMetRosiLifestyleSummary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.4: Results for the Type 2 Diabetes study.
</figcaption><div aria-describedby="tbl-diabetes2ExpMetRosiLifestyleSummary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Treatment</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Failure</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Success</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">lifestyle</td>
<td style="text-align: right; width: 5em;">109</td>
<td style="text-align: right; width: 5em;">125</td>
<td style="text-align: right; width: 5em;">234</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">met</td>
<td style="text-align: right; width: 5em;">120</td>
<td style="text-align: right; width: 5em;">112</td>
<td style="text-align: right; width: 5em;">232</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">rosi</td>
<td style="text-align: right; width: 5em;">90</td>
<td style="text-align: right; width: 5em;">143</td>
<td style="text-align: right; width: 5em;">233</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">Total</td>
<td style="text-align: right; width: 5em;">319</td>
<td style="text-align: right; width: 5em;">380</td>
<td style="text-align: right; width: 5em;">699</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/diabetes2.html"><code>diabetes2</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p>Typically we will use a computer to do the computational work of finding the chi-squared statistic. However, it is always good to have a sense for what the computer is doing, and in particular, calculating the values which would be expected if the null hypothesis is true can help to understand the null hypothesis claim. Additionally, comparing the expected and observed values by eye often gives the researcher some insight into why or why not the null hypothesis for a given test is rejected or not.</p>
<div class="guidedpractice">
<p>A chi-squared test for a two-way table may be used to test the hypotheses in the diabetes Example above. To get a sense for the statistic used in the chi-squared test, first compute the expected values for each of the six table cells.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<p>Note, when analyzing 2-by-2 contingency tables (that is, when both variables only have two possible options), one guideline is to use the two-proportion methods introduced in <a href="inference-two-props.html" class="quarto-xref">Chapter&nbsp;<span>17</span></a>.</p>
</section></section><section id="sec-chp18-review" class="level2" data-number="18.3"><h2 data-number="18.3" class="anchored" data-anchor-id="sec-chp18-review">
<span class="header-section-number">18.3</span> Chapter review</h2>
<section id="summary" class="level3" data-number="18.3.1"><h3 data-number="18.3.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">18.3.1</span> Summary</h3>
<p>In this chapter we extended the randomization / bootstrap / mathematical model paradigm to research questions involving categorical variables. We continued working with one population proportion as well as the difference in populations proportions, but the test of independence allowed for hypothesis testing on categorical variables with more than two levels. We note that the normal model was an excellent mathematical approximation to the sampling distribution of sample proportions (or differences in sample proportions), but that the questions with categorical variables with more than 2 levels required a new mathematical model, the chi-squared distribution. As seen in <a href="foundations-randomization.html" class="quarto-xref">Chapter&nbsp;<span>11</span></a>, <a href="foundations-bootstrapping.html" class="quarto-xref">Chapter&nbsp;<span>12</span></a> and <a href="foundations-mathematical.html" class="quarto-xref">Chapter&nbsp;<span>13</span></a>, almost all the research questions can be approached using computational methods (e.g., randomization tests or bootstrapping) or using mathematical models. We continue to emphasize the importance of experimental design in making conclusions about research claims. In particular, recall that variability can come from different sources (e.g., random sampling vs.&nbsp;random allocation, see <a href="data-design.html#fig-randsampValloc" class="quarto-xref">Figure&nbsp;<span>2.8</span></a>).</p>
</section><section id="terms" class="level3" data-number="18.3.2"><h3 data-number="18.3.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">18.3.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-18" class="quarto-xref">Table&nbsp;<span>18.5</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-18" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;18.5: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">Chi-squared distribution</td>
<td style="text-align: left; width: 12em;">expected counts</td>
<td style="text-align: left; width: 12em;"></td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">chi-squared statistic</td>
<td style="text-align: left; width: 12em;">independence</td>
<td style="text-align: left; width: 12em;"></td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp18-exercises" class="level2" data-number="18.4"><h2 data-number="18.4" class="anchored" data-anchor-id="sec-chp18-exercises">
<span class="header-section-number">18.4</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-18" class="quarto-xref">Appendix&nbsp;<span>A.18</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<p><strong>Quitters.</strong> Does being part of a support group affect the ability of people to quit smoking? A county health department enrolled 300 smokers in a randomized experiment. 150 participants were randomly assigned to a group that used a nicotine patch and met weekly with a support group; the other 150 received the patch and did not meet with a support group. At the end of the study, 40 of the participants in the patch plus support group had quit smoking while only 30 smokers had quit in the other group.</p>
<ol type="a">
<li><p>Create a two-way table presenting the results of this study.</p></li>
<li>
<p>Answer each of the following questions under the null hypothesis that being part of a support group does not affect the ability of people to quit smoking, and indicate whether the expected values are higher or lower than the observed values.</p>
<ol type="i">
<li><p>How many subjects in the “patch + support” group would you expect to quit?</p></li>
<li><p>How many subjects in the “patch only” group would you expect to not quit?</p></li>
</ol>
</li>
</ol>
</li>
</ol>
<ol start="2" type="1">
<li>
<p><strong>Act on climate change.</strong> The table below summarizes results from a Pew Research poll which asked respondents whether they have personally taken action to help address climate change within the last year and their generation. The differences in each generational group may be due to chance. Complete the following computations under the null hypothesis of independence between an individual’s generation and whether they have personally taken action to help address climate change within the last year. <span class="citation" data-cites="pewclimatechange2021">(<a href="references.html#ref-pewclimatechange2021" role="doc-biblioref">Pew Research Center 2021</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Response
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Generation</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Took action</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Didn't take action</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Gen Z</td>
<td style="text-align: right; width: 8em;">292</td>
<td style="text-align: right; width: 8em;">620</td>
<td style="text-align: right; width: 8em;">912</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Millenial</td>
<td style="text-align: right; width: 8em;">885</td>
<td style="text-align: right; width: 8em;">2,275</td>
<td style="text-align: right; width: 8em;">3,160</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Gen X</td>
<td style="text-align: right; width: 8em;">809</td>
<td style="text-align: right; width: 8em;">2,709</td>
<td style="text-align: right; width: 8em;">3,518</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Boomer &amp; older</td>
<td style="text-align: right; width: 8em;">1,276</td>
<td style="text-align: right; width: 8em;">4,798</td>
<td style="text-align: right; width: 8em;">6,074</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 8em;">3,262</td>
<td style="text-align: right; width: 8em;">10,402</td>
<td style="text-align: right; width: 8em;">13,664</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If there is no relationship between age and action,</p>
<ol type="a">
<li><p>how many Gen Z’ers would you expect to have personally taken action to help address climate change within the last year?</p></li>
<li><p>how many Millenials would you expect to have personally taken action to help address climate change within the last year?</p></li>
<li><p>how many Gen X’ers would you expect to have personally taken action to help address climate change within the last year?</p></li>
<li><p>how many Boomers and older would you expect to have personally taken action to help address climate change within the last year?</p></li>
</ol>
</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>Lizard habitats, data.</strong> In order to assess whether habitat conditions are related to the sunlight choices a lizard makes for resting, Western fence lizard (<em>Sceloporus occidentalis</em>) were observed across three different microhabitats.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> <span class="citation" data-cites="Adolph:1990 Asbury:2007">(<a href="references.html#ref-Adolph:1990" role="doc-biblioref">Adolph 1990</a>; <a href="references.html#ref-Asbury:2007" role="doc-biblioref">Asbury and Adolph 2007</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
sunlight
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sun</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">partial</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shade</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3em;">desert</td>
<td style="text-align: right; width: 3em;">16</td>
<td style="text-align: right; width: 3em;">32</td>
<td style="text-align: right; width: 3em;">71</td>
<td style="text-align: right; width: 3em;">119</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">mountain</td>
<td style="text-align: right; width: 3em;">56</td>
<td style="text-align: right; width: 3em;">36</td>
<td style="text-align: right; width: 3em;">15</td>
<td style="text-align: right; width: 3em;">107</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3em;">valley</td>
<td style="text-align: right; width: 3em;">42</td>
<td style="text-align: right; width: 3em;">40</td>
<td style="text-align: right; width: 3em;">24</td>
<td style="text-align: right; width: 3em;">106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">Total</td>
<td style="text-align: right; width: 3em;">114</td>
<td style="text-align: right; width: 3em;">108</td>
<td style="text-align: right; width: 3em;">110</td>
<td style="text-align: right; width: 3em;">332</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>If the variables describing the habitat and the amount of sunlight are independent, what proporiton of lizards (total) would be expected in each of the three sunlight categories?</p></li>
<li><p>Given the proportions of each sunlight condition, how many lizards of each type would you expect to see in the sun? in the partial sun? in the shade?</p></li>
<li><p>Compare the observed (original data) and expected (part b.) tables. From a first glance, does it seem as though the habitat and choice of sunlight may be associated?</p></li>
<li><p>Regardless of your answer to part (c), is it possible to tell from looking only at the expected and observed counts whether the two variables are associated?</p></li>
</ol>
</li>
</ol>
<ol start="4" type="1">
<li>
<p><strong>Disaggregating Asian American tobacco use, data.</strong> Understanding cultural differences in tobacco use across different demographic groups can lead to improved health care education and treatment. A recent study disaggregated tobacco use across Asian American ethnic groups including Asian-Indian (n = 4,373), Chinese (n = 4,736), and Filipino (n = 4,912), in comparison to non-Hispanic Whites (n = 275,025). The number of current smokers in each group was reported as Asian-Indian (n = 223), Chinese (n = 279), Filipino (n = 609), and non-Hispanic Whites (n = 50,880). <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span></p>
<p>In order to assess whether there is a difference in current smoking rates across three Asian American ethnic groups, the observed data is compared to the data that would be expected if there were no association between the variables.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smoking
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">don't smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Asian-Indian</td>
<td style="text-align: right; width: 7em;">4,150</td>
<td style="text-align: right; width: 7em;">223</td>
<td style="text-align: right; width: 7em;">4,373</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Chinese</td>
<td style="text-align: right; width: 7em;">4,457</td>
<td style="text-align: right; width: 7em;">279</td>
<td style="text-align: right; width: 7em;">4,736</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Filipino</td>
<td style="text-align: right; width: 7em;">4,303</td>
<td style="text-align: right; width: 7em;">609</td>
<td style="text-align: right; width: 7em;">4,912</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 7em;">12,910</td>
<td style="text-align: right; width: 7em;">1,111</td>
<td style="text-align: right; width: 7em;">14,021</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>If the variables on ethnicity and smoking status are independent, estimate the proporiton of individuals (total) who smoke?</p></li>
<li><p>Given the overall proportion who smoke, how many of each Asian American ethnicity would you expect to smoke?</p></li>
<li><p>Compare the observed and expected counts. From a first glance, does it seem as though the Asian American ethnicity and choice of smoking may be associated?</p></li>
<li><p>Regardless of your answer to part (c), is it possible to tell from looking only at the expected and observed counts whether the two variables are associated?</p></li>
</ol>
</li>
</ol>
<ol start="5" type="1">
<li>
<p><strong>Lizard habitats, randomize once.</strong> In order to assess whether habitat conditions are related to the sunlight choices a lizard makes for resting, Western fence lizard (<em>Sceloporus occidentalis</em>) were observed across three different microhabitats. <span class="citation" data-cites="Adolph:1990 Asbury:2007">(<a href="references.html#ref-Adolph:1990" role="doc-biblioref">Adolph 1990</a>; <a href="references.html#ref-Asbury:2007" role="doc-biblioref">Asbury and Adolph 2007</a>)</span> Then, the data were randomized once, where sunlight preference was randomly assigned to the lizards across different sites. The original data are shown on the left and the results of the randomization is shown on the right.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Original data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
sunlight
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sun</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">partial</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shade</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3em;">desert</td>
<td style="text-align: right; width: 3em;">16</td>
<td style="text-align: right; width: 3em;">32</td>
<td style="text-align: right; width: 3em;">71</td>
<td style="text-align: right; width: 3em;">119</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">mountain</td>
<td style="text-align: right; width: 3em;">56</td>
<td style="text-align: right; width: 3em;">36</td>
<td style="text-align: right; width: 3em;">15</td>
<td style="text-align: right; width: 3em;">107</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3em;">valley</td>
<td style="text-align: right; width: 3em;">42</td>
<td style="text-align: right; width: 3em;">40</td>
<td style="text-align: right; width: 3em;">24</td>
<td style="text-align: right; width: 3em;">106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">Total</td>
<td style="text-align: right; width: 3em;">114</td>
<td style="text-align: right; width: 3em;">108</td>
<td style="text-align: right; width: 3em;">110</td>
<td style="text-align: right; width: 3em;">332</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Randomized data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
sunlight
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sun</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">partial</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shade</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 3em;">desert</td>
<td style="text-align: right; width: 3em;">44</td>
<td style="text-align: right; width: 3em;">42</td>
<td style="text-align: right; width: 3em;">33</td>
<td style="text-align: right; width: 3em;">119</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">mountain</td>
<td style="text-align: right; width: 3em;">39</td>
<td style="text-align: right; width: 3em;">31</td>
<td style="text-align: right; width: 3em;">37</td>
<td style="text-align: right; width: 3em;">107</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 3em;">valley</td>
<td style="text-align: right; width: 3em;">31</td>
<td style="text-align: right; width: 3em;">35</td>
<td style="text-align: right; width: 3em;">40</td>
<td style="text-align: right; width: 3em;">106</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 3em;">Total</td>
<td style="text-align: right; width: 3em;">114</td>
<td style="text-align: right; width: 3em;">108</td>
<td style="text-align: right; width: 3em;">110</td>
<td style="text-align: right; width: 3em;">332</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Recall that the Chi-squared statistic <span class="math inline">\((X^2)\)</span> measures the difference between the expected and observed counts. Without calculating the actual statistic, report on whether the original data or the randomized data will have a larger Chi-squared statistic. Explain your choice.</p>
</li>
</ol>
<ol start="6" type="1">
<li>
<p><strong>Disaggregating Asian American tobacco use, randomize once.</strong> In a study that aims to disaggregate tobacco use across Asian American ethnic groups (Asian-Indian, Chinese, and Filipino, in comparison to non-Hispanic Whites), respondents were asked whether they smoke tobacco or not. <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span> Then, the data were randomized once, where smoking status was randomly assigned to the participants across different ethnicities. The original data are shown on the left and the results of the randomization is shown on the right.</p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Original data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smoking
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">don't smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Asian-Indian</td>
<td style="text-align: right; width: 3em;">4,150</td>
<td style="text-align: right; width: 3em;">223</td>
<td style="text-align: right; width: 3em;">4,373</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Chinese</td>
<td style="text-align: right; width: 3em;">4,457</td>
<td style="text-align: right; width: 3em;">279</td>
<td style="text-align: right; width: 3em;">4,736</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Filipino</td>
<td style="text-align: right; width: 3em;">4,303</td>
<td style="text-align: right; width: 3em;">609</td>
<td style="text-align: right; width: 3em;">4,912</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 3em;">12,910</td>
<td style="text-align: right; width: 3em;">1,111</td>
<td style="text-align: right; width: 3em;">14,021</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Randomized data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smoking
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">don't smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Asian-Indian</td>
<td style="text-align: right; width: 3em;">4,015</td>
<td style="text-align: right; width: 3em;">358</td>
<td style="text-align: right; width: 3em;">4,373</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Chinese</td>
<td style="text-align: right; width: 3em;">4,385</td>
<td style="text-align: right; width: 3em;">351</td>
<td style="text-align: right; width: 3em;">4,736</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Filipino</td>
<td style="text-align: right; width: 3em;">4,510</td>
<td style="text-align: right; width: 3em;">402</td>
<td style="text-align: right; width: 3em;">4,912</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 3em;">12,910</td>
<td style="text-align: right; width: 3em;">1,111</td>
<td style="text-align: right; width: 3em;">14,021</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Recall that the Chi-squared statistic <span class="math inline">\((X^2)\)</span> measures the difference between the expected and observed counts. Without calculating the actual statistic, report on whether the original data or the randomized data will have a larger Chi-squared statistic. Explain your choice.</p>
</li>
</ol>
<ol start="7" type="1">
<li>
<p><strong>Lizard habitats, randomization test.</strong> In order to assess whether habitat conditions are related to the sunlight choices a lizard makes for resting, Western fence lizard (<em>Sceloporus occidentalis</em>) were observed across three different microhabitats. <span class="citation" data-cites="Adolph:1990 Asbury:2007">(<a href="references.html#ref-Adolph:1990" role="doc-biblioref">Adolph 1990</a>; <a href="references.html#ref-Asbury:2007" role="doc-biblioref">Asbury and Adolph 2007</a>)</span> The original data were randomized 1,000 times (sunlight variable randomly assigned to the observations across different habitats), and the histogram of the Chi-squared statistic on each randomization is displayed.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-tables_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="inference-tables_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>The histogram above describes the Chi-squared statistics for 1,000 different randomization datasets. When randomizing the data, is the imposed structure that the variables are independent or that the variables are associated? Explain.</p></li>
<li><p>What is the range of plausible values for the randomized Chi-squared statistic?</p></li>
<li><p>The observed Chi-squared statistic is 68.8 (marked in red on plot). Does the observed value provide evidence against the null hypothesis? To answer the question, state the null and alternative hypotheses, approximate the p-value, and conclude the test in the context of the problem.</p></li>
</ol>
</li>
<li>
<p><strong>Disaggregating Asian American tobacco use, randomization test.</strong> Understanding cultural differences in tobacco use across different demographic groups can lead to improved health care education and treatment. A recent study disaggregated tobacco use across Asian American ethnic groups including Asian-Indian (n = 4373), Chinese (n = 4736), and Filipino (n = 4912), in comparison to non-Hispanic Whites (n = 275,025). The number of current smokers in each group was reported as Asian-Indian (n = 223), Chinese (n = 279), Filipino (n = 609), and non-Hispanic Whites (n = 50,880). <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span> The original data were randomized 1000 times (smoking status randomly assigned to the observations across ethnicities), and the histogram of the Chi-squared statistic on each randomization is displayed.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-tables_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="inference-tables_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>The histogram above describes the Chi-squared statistics for 1000 different randomization datasets. When randomizing the data, is the imposed structure that the variables are independent or that the variables are associated? Explain.</p></li>
<li><p>What is the range of plausible values for the randomized Chi-squared statistic?</p></li>
<li><p>The observed Chi-squared statistic is 209.42 (marked in red on plot). Does the observed value provide evidence against the null hypothesis? To answer the question, state the null and alternative hypotheses, approximate the p-value, and conclude the test in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>Lizard habitats, larger data.</strong> In order to assess whether habitat conditions are related to the sunlight choices a lizard makes for resting, Western fence lizard (<em>Sceloporus occidentalis</em>) were observed across three different microhabitats. <span class="citation" data-cites="Adolph:1990 Asbury:2007">(<a href="references.html#ref-Adolph:1990" role="doc-biblioref">Adolph 1990</a>; <a href="references.html#ref-Asbury:2007" role="doc-biblioref">Asbury and Adolph 2007</a>)</span></p>
<p>Consider the situation where the dataset is 5 times <em>larger</em> than the original data (but have the same proportional representation in each category). The distribution of lizards in each of the sites resting in the sun, partial sun, and shade are as follows.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Larger data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="3" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
sunlight
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">site</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sun</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">partial</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">shade</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">desert</td>
<td style="text-align: right; width: 5em;">80</td>
<td style="text-align: right; width: 5em;">160</td>
<td style="text-align: right; width: 5em;">355</td>
<td style="text-align: right; width: 5em;">595</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">mountain</td>
<td style="text-align: right; width: 5em;">280</td>
<td style="text-align: right; width: 5em;">180</td>
<td style="text-align: right; width: 5em;">75</td>
<td style="text-align: right; width: 5em;">535</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">valley</td>
<td style="text-align: right; width: 5em;">210</td>
<td style="text-align: right; width: 5em;">200</td>
<td style="text-align: right; width: 5em;">120</td>
<td style="text-align: right; width: 5em;">530</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">Total</td>
<td style="text-align: right; width: 5em;">570</td>
<td style="text-align: right; width: 5em;">540</td>
<td style="text-align: right; width: 5em;">550</td>
<td style="text-align: right; width: 5em;">1,660</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The larger dataset was randomized 1,000 times (sunlight preference randomly assigned to the observations across sites), and the histogram of the Chi-squared statistic on each randomization is displayed.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-tables_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="inference-tables_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>The histogram above describes the Chi-squared statistics for 1,000 different randomization of the larger dataset. When randomizing the data, is the imposed structure that the variables are independent or that the variables are associated? Explain.</p></li>
<li><p>What is the (approximate) range of plausible values for the randomized Chi-squared statistic?</p></li>
<li><p>The observed Chi-squared statistic is 343.865 (and seen in red on the graph). Does the observed value provide evidence against the null hypothesis? To answer the question, state the null and alternative hypotheses, approximate the p-value, and conclude the test in the context of the problem.</p></li>
<li><p>If the alternative hypothesis is true, how does the sample size effect the ability to reject the null hypothesis? (<em>Hint:</em> Consider the original data as compared with the larger dataset that have the same proportional values.)</p></li>
</ol>
</li>
</ol>
<ol start="10" type="1">
<li>
<p><strong>Disaggregating Asian American tobacco use, smaller data.</strong> Understanding cultural differences in tobacco use across different demographic groups can lead to improved health care education and treatment. A recent study disaggregated tobacco use across Asian American ethnic groups <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span>.</p>
<p>Consider the situation where the dataset is 50 times <em>smaller</em> than the original data (but have the same proportional representation in each category). The distribution of smokers in each of the ethnicity groups in the smaller data are as follows.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th colspan="4" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smaller data
</div></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Smoking
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">ethnicity</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">don't smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">smoke</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Asian-Indian</td>
<td style="text-align: right; width: 5em;">83</td>
<td style="text-align: right; width: 5em;">4</td>
<td style="text-align: right; width: 5em;">87</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Chinese</td>
<td style="text-align: right; width: 5em;">89</td>
<td style="text-align: right; width: 5em;">6</td>
<td style="text-align: right; width: 5em;">95</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Filipino</td>
<td style="text-align: right; width: 5em;">86</td>
<td style="text-align: right; width: 5em;">12</td>
<td style="text-align: right; width: 5em;">98</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: right; width: 5em;">258</td>
<td style="text-align: right; width: 5em;">22</td>
<td style="text-align: right; width: 5em;">280</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The smaller dataset was randomized 1,000 times (smoking status randomly assigned to the observations across ethnicities), and the histogram of the Chi-squared statistic on each randomization is displayed.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-tables_files/figure-html/unnamed-chunk-17-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="inference-tables_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>The histogram above describes the Chi-squared statistics for 1,000 different randomization of the smaller dataset. When randomizing the data, is the imposed structure that the variables are independent or that the variables are associated? Explain.</p></li>
<li><p>What is the (approximate) range of plausible values for the randomized Chi-squared statistic?</p></li>
<li><p>The observed Chi-squared statistic is 4.19 (and seen in red on the graph). Does the observed value provide evidence against the null hypothesis? To answer the question, state the null and alternative hypotheses, approximate the p-value, and conclude the test in the context of the problem.</p></li>
<li><p>If the alternative hypothesis is true, how does the sample size effect the ability to reject the null hypothesis? (<em>Hint:</em> Consider the original data as compared with the smaller dataset that have the same proportional values.)</p></li>
</ol>
</li>
</ol>
<ol start="11" type="1">
<li>
<p><strong>True / False, I.</strong> Determine if the statements below are true or false. For each false statement, suggest an alternative wording to make it a true statement.</p>
<ol type="a">
<li><p>The Chi-square distribution, just like the normal distribution, has two parameters, mean and standard deviation.</p></li>
<li><p>The Chi-square distribution is always right skewed, regardless of the value of the degrees of freedom parameter.</p></li>
<li><p>The Chi-square statistic is always greater than or equal to 0.</p></li>
<li><p>As the degrees of freedom increases, the shape of the Chi-square distribution becomes more skewed.</p></li>
</ol>
</li>
</ol>
<ol start="12" type="1">
<li>
<p><strong>True / False, II.</strong> Determine if the statements below are true or false. For each false statement, suggest an alternative wording to make it a true statement.</p>
<ol type="a">
<li><p>As the degrees of freedom increases, the mean of the Chi-square distribution increases.</p></li>
<li><p>If you found <span class="math inline">\(\chi^2 = 10\)</span> with <span class="math inline">\(df = 5\)</span> you would fail to reject <span class="math inline">\(H_0\)</span> at the 5% discernibility level.</p></li>
<li><p>When finding the p-value of a Chi-square test, we always shade the tail areas in both tails.</p></li>
<li><p>As the degrees of freedom increases, the variability of the Chi-square distribution decreases.</p></li>
</ol>
</li>
</ol>
<ol start="13" type="1">
<li>
<p><strong>Sleep deprived transportation workers.</strong> The National Sleep Foundation conducted a survey on the sleep habits of randomly sampled transportation workers and randomly sampled non-transportation workers that serve as a “control” for comparison. <span class="citation" data-cites="data:sleepTransport">(<a href="references.html#ref-data:sleepTransport" role="doc-biblioref">National Sleep Foundation 2012</a>)</span> The results of the survey are shown below. Conduct a hypothesis test to evaluate if these data provide evidence of an association between sleep levels and profession.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Profession</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Less than 6 hours</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">6 to 8 hours</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">More than 8 hours</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">Non-transportation workers</td>
<td style="text-align: right; width: 5em;">35</td>
<td style="text-align: right; width: 5em;">193</td>
<td style="text-align: right; width: 5em;">64</td>
<td style="text-align: right; width: 5em;">292</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Transportation workers</td>
<td style="text-align: right; width: 5em;">104</td>
<td style="text-align: right; width: 5em;">499</td>
<td style="text-align: right; width: 5em;">192</td>
<td style="text-align: right; width: 5em;">795</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Total</td>
<td style="text-align: right; width: 5em;">139</td>
<td style="text-align: right; width: 5em;">692</td>
<td style="text-align: right; width: 5em;">256</td>
<td style="text-align: right; width: 5em;">1,087</td>
</tr>
</tbody>
</table>
</div>
</div>
</li>
</ol>
<ol start="14" type="1">
<li>
<p><strong>Parasitic worm.</strong> Lymphatic filariasis is a disease caused by a parasitic worm. Complications of the disease can lead to extreme swelling and other complications. Here we consider results from a randomized experiment that compared three different drug treatment options to clear people of the this parasite, which people are working to eliminate entirely. The results for the second year of the study are given below: <span class="citation" data-cites="KingSuamani2018">(<a href="references.html#ref-KingSuamani2018" role="doc-biblioref">King et al. 2018</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Outcome
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">group</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Clear at Year 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Not Clear at Year 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">Three drugs</td>
<td style="text-align: right; width: 10em;">52</td>
<td style="text-align: right; width: 10em;">2</td>
<td style="text-align: right; width: 5em;">54</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em;">Two drugs</td>
<td style="text-align: right; width: 10em;">31</td>
<td style="text-align: right; width: 10em;">24</td>
<td style="text-align: right; width: 5em;">55</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10em;">Two drugs annually</td>
<td style="text-align: right; width: 10em;">42</td>
<td style="text-align: right; width: 10em;">14</td>
<td style="text-align: right; width: 5em;">56</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em;">Total</td>
<td style="text-align: right; width: 10em;">125</td>
<td style="text-align: right; width: 10em;">40</td>
<td style="text-align: right; width: 5em;">165</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>Set up hypotheses for evaluating whether there is any difference in the performance of the treatments, and also check conditions.</p></li>
<li><p>Statistical software was used to run a Chi-square test, which output: <span class="math inline">\(X^2 = 23.7 \quad df = 2 \quad \text{p-value} &lt; 0.0001\)</span>. Use these results to evaluate the hypotheses from part&nbsp;(a), and provide a conclusion in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Shipping holiday gifts.</strong> A local news survey asked 500 randomly sampled Los Angeles residents which shipping carrier they prefer to use for shipping holiday gifts. The table below shows the distribution of responses by age group as well as the expected counts for each cell (shown in italics).</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="6" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Age
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Shipping method
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
18-34
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
35-54
</div></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
55+
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Total
</div></th>
</tr>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 10em;">USPS</td>
<td style="text-align: right; width: 3em;">72</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">81</td>
<td style="text-align: right; width: 3em;">97</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">102</td>
<td style="text-align: right; width: 3em;">76</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">62</td>
<td style="text-align: right; width: 5em;">245</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em;">UPS</td>
<td style="text-align: right; width: 3em;">52</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">53</td>
<td style="text-align: right; width: 3em;">76</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">68</td>
<td style="text-align: right; width: 3em;">34</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">41</td>
<td style="text-align: right; width: 5em;">162</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10em;">FedEx</td>
<td style="text-align: right; width: 3em;">31</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">21</td>
<td style="text-align: right; width: 3em;">24</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">27</td>
<td style="text-align: right; width: 3em;">9</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">16</td>
<td style="text-align: right; width: 5em;">64</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em;">Something else</td>
<td style="text-align: right; width: 3em;">7</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">5</td>
<td style="text-align: right; width: 3em;">6</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">7</td>
<td style="text-align: right; width: 3em;">3</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">4</td>
<td style="text-align: right; width: 5em;">16</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 10em;">Not sure</td>
<td style="text-align: right; width: 3em;">3</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">5</td>
<td style="text-align: right; width: 3em;">6</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">5</td>
<td style="text-align: right; width: 3em;">4</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;">3</td>
<td style="text-align: right; width: 5em;">13</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 10em;">Total</td>
<td style="text-align: right; width: 3em;">165</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;"></td>
<td style="text-align: right; width: 3em;">209</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;"></td>
<td style="text-align: right; width: 3em;">126</td>
<td style="text-align: right; width: 3em; font-style: italic; color: rgba(86, 155, 189, 255) !important;"></td>
<td style="text-align: right; width: 5em;">500</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>State the null and alternative hypotheses for testing for independence of age and preferred shipping method for holiday gifts among Los Angeles residents.</p></li>
<li><p>Are the conditions for inference using a Chi-square test satisfied?</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>Coffee and depression.</strong> Researchers conducted a study investigating the relationship between caffeinated coffee consumption and risk of depression in women. They collected data on 50,739 women free of depression symptoms at the start of the study in the year 1996, and these women were followed through 2006. The researchers used questionnaires to collect data on caffeinated coffee consumption, asked each individual about physician- diagnosed depression, and also asked about the use of antidepressants. The table below shows the distribution of incidences of depression by amount of caffeinated coffee consumption. <span class="citation" data-cites="Lucas:2011">(<a href="references.html#ref-Lucas:2011" role="doc-biblioref">Lucas et al. 2011</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Caffeinated coffee consumption
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Clinical depression</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1 cup / week or fewer</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2-6 cups / week</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1 cups / day</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2-3 cups / day</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">4 cups / day or more</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">Yes</td>
<td style="text-align: right; width: 4em;">670</td>
<td style="text-align: right; width: 4em;">___</td>
<td style="text-align: right; width: 4em;">905</td>
<td style="text-align: right; width: 4em;">564</td>
<td style="text-align: right; width: 4em;">95</td>
<td style="text-align: right; width: 4em;">2,607</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">No</td>
<td style="text-align: right; width: 4em;">11,545</td>
<td style="text-align: right; width: 4em;">6,244</td>
<td style="text-align: right; width: 4em;">16,329</td>
<td style="text-align: right; width: 4em;">11,726</td>
<td style="text-align: right; width: 4em;">2,288</td>
<td style="text-align: right; width: 4em;">48,132</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 5em;">Total</td>
<td style="text-align: right; width: 4em;">12,215</td>
<td style="text-align: right; width: 4em;">6,617</td>
<td style="text-align: right; width: 4em;">17,234</td>
<td style="text-align: right; width: 4em;">12,290</td>
<td style="text-align: right; width: 4em;">2,383</td>
<td style="text-align: right; width: 4em;">50,739</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>What type of test is appropriate for evaluating if there is an association between coffee intake and depression?</p></li>
<li><p>Write the hypotheses for the test you identified in part (a).</p></li>
<li><p>Calculate the overall proportion of women who do and do not suffer from depression.</p></li>
<li><p>Identify the expected count for the empty cell, and calculate the contribution of this cell to the test statistic.</p></li>
<li><p>The test statistic is <span class="math inline">\(\chi^2=20.93\)</span>. What is the p-value?</p></li>
<li><p>What is the conclusion of the hypothesis test?</p></li>
<li><p>One of the authors of this study was quoted on the New York Times as saying it was “too early to recommend that women load up on extra coffee” based on just this study. <span class="citation" data-cites="news:coffeeDepression">(<a href="references.html#ref-news:coffeeDepression" role="doc-biblioref">O’Connor 2011</a>)</span> Do you agree with this statement? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Adolph:1990" class="csl-entry" role="listitem">
Adolph, S. C. 1990. <span>“Influence of Behavioral Thermoregulation on Microhabitat Use by Two <span><em>Sceloporus</em></span> Lizards.”</span> <em>Ecology</em> 71: 315–27.
</div>
<div id="ref-Asbury:2007" class="csl-entry" role="listitem">
Asbury, D. A., and S. C. Adolph. 2007. <span>“Behavioral Plasticity in an Ecological Generalist: Microhabitat Use by Western Fence Lizards.”</span> <em>Evolutionary Ecology Research</em> 9: 801–15.
</div>
<div id="ref-KingSuamani2018" class="csl-entry" role="listitem">
King, C., J. Suamani, N. Sanuku, Y.-C. Cheng, S. Satofan, B. Mancuso, C. W. Goss, et al. 2018. <span>“A Trial of a Triple-Drug Treatment for Lymphatic Filariasis.”</span> <em>New England Journal of Medicine</em> 379: 1801–10. <a href="https://doi.org/10.1056/NEJMoa1706854">https://doi.org/10.1056/NEJMoa1706854</a>.
</div>
<div id="ref-Lucas:2011" class="csl-entry" role="listitem">
Lucas, M., F. Mirzaei, A. Pan, O. I. Okereke, W. C. Willett, E. J. O’Reilly, K. Koenen, and A. Ascherio. 2011. <span>“Coffee, Caffeine, and Risk of Depression Among Women.”</span> <em>Archives of Internal Medicine</em> 171 (17): 1571. <a href="https://doi.org/10.1001/archinternmed.2011.393">https://doi.org/10.1001/archinternmed.2011.393</a>.
</div>
<div id="ref-data:sleepTransport" class="csl-entry" role="listitem">
National Sleep Foundation. 2012. <a href="http://www.openintro.org/redirect.php?go=textbook-trans_workers_sleep_2012">http://www.openintro.org/redirect.php?go=textbook-trans_workers_sleep_2012</a>.
</div>
<div id="ref-news:coffeeDepression" class="csl-entry" role="listitem">
O’Connor, A. 2011. <span>“Coffee Drinking Linked to Less Depression in Women.”</span> <em>New York Times</em>. <a href="http://www.openintro.org/redirect.php?go=textbook-coffee_depression_2011">http://www.openintro.org/redirect.php?go=textbook-coffee_depression_2011</a>.
</div>
<div id="ref-pewclimatechange2021" class="csl-entry" role="listitem">
Pew Research Center. 2021. <span>“How Americans’ Attitudes about Climate Change Differ by Generation, Party and Other Factors, Data Collected April 20 to 29, 2021.”</span> <a href="https://www.openintro.org/go?id=textbook-pew-2021-climate-change">https://www.openintro.org/go?id=textbook-pew-2021-climate-change</a>.
</div>
<div id="ref-Rao:2021" class="csl-entry" role="listitem">
Rao, M., L. Bar, Y. Yu, M. Srinivasan, A. Mukherjea, J. Li, S. Chung, S. Venkatraman, S. Dan, and L. Palaniappan. 2021. <span>“Disaggregating Asian American Cigarette and Alternative Tobacco Product Use: Results from the National Health Interview Survey (NHIS) 2006–2018.”</span> <em>Journal of Racial and Ethnic Health Disparities</em>. <a href="https://doi.org/10.1007/s40615-021-01024-5">https://doi.org/10.1007/s40615-021-01024-5</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>For readers not as old as the authors, an iPod is basically an iPhone without any cellular service, assuming it was one of the later generations. Earlier generations were more basic.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>We would expect <span class="math inline">\((1 - 0.2785) \times 73 = 52.67.\)</span> It is okay that this result, like the result from the Example above, is a fraction.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The expected count for row one / column one is found by multiplying the row one total (234) and column one total (319), then dividing by the table total (699): <span class="math inline">\(\frac{234\times 319}{699} = 106.8.\)</span> Similarly for the second column and the first row: <span class="math inline">\(\frac{234\times 380}{699} = 127.2.\)</span> Row 2: 105.9 and 126.1. Row 3: 106.3 and 126.7.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The <a href="http://openintrostat.github.io/openintro/reference/lizard_habitat.html"><code>lizard_habitat</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./inference-two-props.html" class="pagination-link" aria-label="Inference for comparing two proportions">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference-one-mean.html" class="pagination-link" aria-label="Inference for a single mean">
        <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-tables.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>