# Inferential modeling {#sec-inf-model .unnumbered}

In a previous part, [Regression modeling](https://openintro-ims2.netlify.app/regression-modeling), you learned how to build linear and logistic regression models based on a set of observations.
In a different part, [Foundations of inference](https://openintro-ims2.netlify.app/foundations-of-inference), you learned about the structures that allow us to make inferential claims about a population given a sample of data.
In this part, we develop inferential methods applied to regression models.

-   [Chapter -@sec-inf-model-slr] provides specific details about inference for linear regression models with a single predictor.
-   [Chapter -@sec-inf-model-mlr] provides specific details about inference for linear regression models with multiple predictors.
-   [Chapter -@sec-inf-model-logistic] provides specific details about inference for logistic regression models.
-   [Chapter -@sec-inf-model-applications] includes an application on the Mario Kart case study where the topics from this part of the book on linear regression are fully developed.

We have only scratched the surface in providing information about modeling and related inferential methods.
We hope that the ideas we’ve covered have whet your appetite to learn more higher level modeling.
