<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>17&nbsp; Inference for comparing two proportions – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference-tables.html" rel="next">
<link href="./inference-one-prop.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-709f5aa5aa6a95674750e60a60b86f5a.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-790f3f5e7e2e01ab58e527b05f631cee.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-two-props.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-two-prop-errors" id="toc-sec-two-prop-errors" class="nav-link active" data-scroll-target="#sec-two-prop-errors"><span class="header-section-number">17.1</span> Randomization test for the difference in proportions</a>
  <ul class="collapse">
<li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">17.1.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">17.1.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs-null-statistics" id="toc-observed-statistic-vs-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs-null-statistics"><span class="header-section-number">17.1.3</span> Observed statistic vs null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#sec-two-prop-boot-ci" id="toc-sec-two-prop-boot-ci" class="nav-link" data-scroll-target="#sec-two-prop-boot-ci"><span class="header-section-number">17.2</span> Bootstrap confidence interval for the difference in proportions</a>
  <ul class="collapse">
<li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">17.2.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-difference-in-sample-proportions" id="toc-variability-of-the-difference-in-sample-proportions" class="nav-link" data-scroll-target="#variability-of-the-difference-in-sample-proportions"><span class="header-section-number">17.2.2</span> Variability of the difference in sample proportions</a></li>
  <li><a href="#bootstrap-percentile-vs.-se-confidence-intervals" id="toc-bootstrap-percentile-vs.-se-confidence-intervals" class="nav-link" data-scroll-target="#bootstrap-percentile-vs.-se-confidence-intervals"><span class="header-section-number">17.2.3</span> Bootstrap percentile vs.&nbsp;SE confidence intervals</a></li>
  <li><a href="#what-does-95-mean" id="toc-what-does-95-mean" class="nav-link" data-scroll-target="#what-does-95-mean"><span class="header-section-number">17.2.4</span> What does 95% mean?</a></li>
  </ul>
</li>
  <li>
<a href="#sec-math-2prop" id="toc-sec-math-2prop" class="nav-link" data-scroll-target="#sec-math-2prop"><span class="header-section-number">17.3</span> Mathematical model for the difference in proportions</a>
  <ul class="collapse">
<li><a href="#variability-of-the-difference-between-two-proportions" id="toc-variability-of-the-difference-between-two-proportions" class="nav-link" data-scroll-target="#variability-of-the-difference-between-two-proportions"><span class="header-section-number">17.3.1</span> Variability of the difference between two proportions</a></li>
  <li><a href="#confidence-interval-for-the-difference-between-two-proportions" id="toc-confidence-interval-for-the-difference-between-two-proportions" class="nav-link" data-scroll-target="#confidence-interval-for-the-difference-between-two-proportions"><span class="header-section-number">17.3.2</span> Confidence interval for the difference between two proportions</a></li>
  <li><a href="#sec-test-prop-pool" id="toc-sec-test-prop-pool" class="nav-link" data-scroll-target="#sec-test-prop-pool"><span class="header-section-number">17.3.3</span> Hypothesis test for the difference between two proportions</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp17-review" id="toc-sec-chp17-review" class="nav-link" data-scroll-target="#sec-chp17-review"><span class="header-section-number">17.4</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">17.4.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">17.4.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp17-exercises" id="toc-sec-chp17-exercises" class="nav-link" data-scroll-target="#sec-chp17-exercises"><span class="header-section-number">17.5</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-two-props.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-two-props.html"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-inference-two-props" class="quarto-section-identifier"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>We now extend the methods from <a href="inference-one-prop.html" class="quarto-xref">Chapter&nbsp;<span>16</span></a> to apply confidence intervals and hypothesis tests to differences in population proportions that come from two groups, Group 1 and Group 2: <span class="math inline">\(p_1 - p_2.\)</span></p>
<p>In our investigations, we’ll identify a reasonable point estimate of <span class="math inline">\(p_1 - p_2\)</span> based on the sample, and you may have already guessed its form: <span class="math inline">\(\hat{p}_1 - \hat{p}_2.\)</span> Then we’ll look at the inferential analysis in three different ways: using a randomization test, applying bootstrapping for interval estimates, and, if we verify that the point estimate can be modeled using a normal distribution, we compute the estimate’s standard error, and we apply the mathematical framework.</p>
</div>
<section id="sec-two-prop-errors" class="level2" data-number="17.1"><h2 data-number="17.1" class="anchored" data-anchor-id="sec-two-prop-errors">
<span class="header-section-number">17.1</span> Randomization test for the difference in proportions</h2>
<section id="observed-data" class="level3" data-number="17.1.1"><h3 data-number="17.1.1" class="anchored" data-anchor-id="observed-data">
<span class="header-section-number">17.1.1</span> Observed data</h3>
<p>Let’s take another look at the cardiopulmonary resuscitation (CPR) study we introduced in <a href="foundations-errors.html#sec-two-sided-hypotheses" class="quarto-xref"><span>Section 14.2</span></a>. The experiment consisted of two treatments on patients who underwent CPR for a heart attack and were subsequently admitted to a hospital. Each patient was randomly assigned to either receive a blood thinner (treatment group) or not receive a blood thinner (control group). The outcome variable of interest was whether the patient survived for at least 24 hours. <span class="citation" data-cites="Bottiger:2001">(<a href="references.html#ref-Bottiger:2001" role="doc-biblioref">Böttiger et al. 2001</a>)</span></p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/cpr.html"><code>cpr</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p>The results are summarized in <a href="#tbl-cpr-summary-again" class="quarto-xref">Table&nbsp;<span>17.1</span></a> (which is a replica of <a href="foundations-errors.html#tbl-cpr-summary" class="quarto-xref">Table&nbsp;<span>14.2</span></a>). 11 out of the 50 patients in the control group and 14 out of the 40 patients in the treatment group survived.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-cpr-summary-again" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cpr-summary-again-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17.1: Results for the CPR study. Patients in the treatment group were given a blood thinner, and patients in the control group were not.
</figcaption><div aria-describedby="tbl-cpr-summary-again-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Died</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Survived</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">Control</td>
<td style="text-align: center; width: 7em;">39</td>
<td style="text-align: center; width: 7em;">11</td>
<td style="text-align: center; width: 7em;">50</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">Treatment</td>
<td style="text-align: center; width: 7em;">26</td>
<td style="text-align: center; width: 7em;">14</td>
<td style="text-align: center; width: 7em;">40</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 7em;">Total</td>
<td style="text-align: center; width: 7em;">65</td>
<td style="text-align: center; width: 7em;">25</td>
<td style="text-align: center; width: 7em;">90</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="guidedpractice">
<p>Is this an observational study or an experiment? What implications does the study type have on what can be inferred from the results?<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<p>In this study, a larger proportion of patients who received blood thinner after CPR,<span class="math inline">\(\hat{p}_T = \frac{14}{40} = 0.35,\)</span> survived compared to those who did not receive blood thinner, <span class="math inline">\(\hat{p}_C = \frac{11}{50} = 0.22.\)</span> However, based on these observed proportions alone, we cannot determine whether the difference (<span class="math inline">\(\hat{p}_T - \hat{p}_C = 0.35 - 0.22 = 0.13\)</span>) provides <em>convincing evidence</em> that blood thinner usage after CPR is effective.</p>
<p>As we saw in <a href="foundations-randomization.html" class="quarto-xref">Chapter&nbsp;<span>11</span></a>, we can re-randomize the responses (<code>survived</code> or <code>died</code>) to the treatment conditions assuming the null hypothesis is true and compute possible differences in proportions. The process by which we randomize observations to two groups is summarized and visualized in <a href="foundations-randomization.html#fig-fullrand" class="quarto-xref">Figure&nbsp;<span>11.8</span></a>).</p>
</section><section id="variability-of-the-statistic" class="level3" data-number="17.1.2"><h3 data-number="17.1.2" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">17.1.2</span> Variability of the statistic</h3>
<p><a href="#fig-cpr-rand-dot-plot" class="quarto-xref">Figure&nbsp;<span>17.1</span></a> shows a stacked plot of the differences found from 100 randomization simulations (i.e., repeated iterations as described in <a href="foundations-randomization.html#fig-fullrand" class="quarto-xref">Figure&nbsp;<span>11.8</span></a>, where each dot represents a simulated difference between the infection rates (control rate minus treatment rate).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-cpr-rand-dot-plot" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A stacked dot plot of differences from 100 simulations produced under the independence model $H_0,$ where in these simulations survival is unaffected by the treatment. Twelve of the 100 simulations had a difference of at least 13%, the difference observed in the study. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-cpr-rand-dot-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-props_files/figure-html/fig-cpr-rand-dot-plot-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;17.1: A stacked dot plot of differences from 100 simulations produced under the independence model H_0, where in these simulations survival is unaffected by the treatment. Twelve of the 100 simulations had a difference of at least 13%, the difference observed in the study."><img src="inference-two-props_files/figure-html/fig-cpr-rand-dot-plot-1.png" class="img-fluid figure-img" style="width:90.0%" alt="A stacked dot plot of differences from 100 simulations produced under the independence model $H_0,$ where in these simulations survival is unaffected by the treatment. Twelve of the 100 simulations had a difference of at least 13%, the difference observed in the study. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cpr-rand-dot-plot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.1: A stacked dot plot of differences from 100 simulations produced under the independence model <span class="math inline">\(H_0,\)</span> where in these simulations survival is unaffected by the treatment. Twelve of the 100 simulations had a difference of at least 13%, the difference observed in the study.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="observed-statistic-vs-null-statistics" class="level3" data-number="17.1.3"><h3 data-number="17.1.3" class="anchored" data-anchor-id="observed-statistic-vs-null-statistics">
<span class="header-section-number">17.1.3</span> Observed statistic vs null statistics</h3>
<p>Note that the distribution of these simulated differences is centered around 0. We simulated the differences assuming that the independence model was true, that blood thinners after CPR have no effect on survival. Under the null hypothesis, we expect the difference to be near zero with some random fluctuation, where <em>near</em> is pretty generous in this case since the sample sizes are so small in this study.</p>
<div class="workedexample">
<p>How often would you observe a difference of at least 13% (0.13) according to <a href="#fig-cpr-rand-dot-plot" class="quarto-xref">Figure&nbsp;<span>17.1</span></a>? Is this a rare event?</p>
<hr>
<p>It appears that a difference of at least 13% due to chance alone, if the null hypothesis was true would happen about 12% of the time according to <a href="#fig-cpr-rand-dot-plot" class="quarto-xref">Figure&nbsp;<span>17.1</span></a>. This is not a very rare event.</p>
</div>
<p>The difference of 13% not being a rare event suggests two possible interpretations of the results of the study:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span> Independence model. Blood thinners after CPR have no effect on survival, and we just happened to observe a difference that would only occur on a rare occasion.</li>
<li>
<span class="math inline">\(H_A\)</span> Alternative model. Blood thinners after CPR increase chance of survival, and the difference we observed was actually due to the blood thinners after CPR being effective at increasing the chance of survival, which explains the difference of 13%.</li>
</ul>
<p>Since we determined that the outcome is not that rare (12% chance of observing a difference of 13% or more under the assumption that blood thinners after CPR have no effect on survival), we fail to reject <span class="math inline">\(H_0\)</span>, and conclude that the study results do not provide strong evidence against the independence model. This does not mean that we have proved that blood thinners are not effective, it just means that this study does not provide convincing evidence that they are effective in this setting.</p>
<p>Statistical inference, is built on evaluating how likely such differences are to occur due to chance if in fact the null hypothesis is true. In statistical inference, data scientists evaluate which model is most reasonable given the data. Errors do occur, just like rare events, and we might choose the wrong model. While we do not always choose correctly, statistical inference gives us tools to control and evaluate how often these errors occur.</p>
</section></section><section id="sec-two-prop-boot-ci" class="level2" data-number="17.2"><h2 data-number="17.2" class="anchored" data-anchor-id="sec-two-prop-boot-ci">
<span class="header-section-number">17.2</span> Bootstrap confidence interval for the difference in proportions</h2>
<p>In <a href="#sec-two-prop-errors" class="quarto-xref"><span>Section 17.1</span></a>, we worked with the randomization distribution to understand the distribution of <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> when the null hypothesis <span class="math inline">\(H_0: p_1 - p_2 = 0\)</span> is true. Now, through bootstrapping, we study the variability of <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> without assuming the null hypothesis is true.</p>
<section id="observed-data-1" class="level3" data-number="17.2.1"><h3 data-number="17.2.1" class="anchored" data-anchor-id="observed-data-1">
<span class="header-section-number">17.2.1</span> Observed data</h3>
<p>Reconsider the CPR data from <a href="#sec-two-prop-errors" class="quarto-xref"><span>Section 17.1</span></a> which is provided in <a href="foundations-errors.html#tbl-cpr-summary" class="quarto-xref">Table&nbsp;<span>14.2</span></a>. Again, we use the difference in sample proportions as the observed statistic of interest. Here, the value of the statistic is: <span class="math inline">\(\hat{p}_T - \hat{p}_C = 0.35 - 0.22 = 0.13.\)</span></p>
</section><section id="variability-of-the-difference-in-sample-proportions" class="level3" data-number="17.2.2"><h3 data-number="17.2.2" class="anchored" data-anchor-id="variability-of-the-difference-in-sample-proportions">
<span class="header-section-number">17.2.2</span> Variability of the difference in sample proportions</h3>
<p>The bootstrap method applied to two samples is an extension of the method described in <a href="foundations-bootstrapping.html" class="quarto-xref">Chapter&nbsp;<span>12</span></a>. Now, we have two samples, so each sample estimates the population from which they came. In the CPR setting, the <code>treatment</code> sample estimates the population of all individuals who have gotten (or will get) the treatment; the <code>control</code> sample estimates the population of all individuals who do not get the treatment and are controls. <a href="#fig-boot2proppops" class="quarto-xref">Figure&nbsp;<span>17.2</span></a> extends <a href="foundations-bootstrapping.html#fig-boot1" class="quarto-xref">Figure&nbsp;<span>12.1</span></a> to show the bootstrapping process from two samples simultaneously.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boot2proppops" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Sample 1 is taken from Population 1 (3 colored marbles out of 7); Sample 2 is taken from Population 2 (5 colored marbles out of 9). Each of the two samples is used to create separate infinitely large proxy populations. Proxy population 1 has 3/7 colored marbles; proxy population 2 has 4/9 colored marbles.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boot2proppops-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/boot2proppops.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;17.2: Creating two populations from which to take each of the bootstrap samples."><img src="images/boot2proppops.png" class="img-fluid figure-img" style="width:100.0%" alt="Sample 1 is taken from Population 1 (3 colored marbles out of 7); Sample 2 is taken from Population 2 (5 colored marbles out of 9). Each of the two samples is used to create separate infinitely large proxy populations. Proxy population 1 has 3/7 colored marbles; proxy population 2 has 4/9 colored marbles."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boot2proppops-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.2: Creating two populations from which to take each of the bootstrap samples.
</figcaption></figure>
</div>
</div>
</div>
<p>As before, once the population is estimated, we can randomly resample observations to create bootstrap samples, as seen in <a href="#fig-boot2propresamps" class="quarto-xref">Figure&nbsp;<span>17.3</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boot2propresamps" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Sample 1 is taken from Population 1 (3 colored marbles out of 7); Sample 2 is taken from Population 2 (5 colored marbles out of 9). Each of the two samples is used to create separate infinitely large proxy populations. Proxy population 1 has 3/7 colored marbles; proxy population 2 has 4/9 colored marbles. Resamples are taken from each of the proxy populations. The three resamples from proxy population 1 have 2/7, 4/7 and 5/7 colored marbles, respectively. The three resamples from proxy population 2 have 5/9, 4/9, and 7/9 colored smarbles, respectively.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boot2propresamps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/boot2propresamps.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;17.3: Taking each bootstrap sample from the estimated population."><img src="images/boot2propresamps.png" class="img-fluid figure-img" style="width:100.0%" alt="Sample 1 is taken from Population 1 (3 colored marbles out of 7); Sample 2 is taken from Population 2 (5 colored marbles out of 9). Each of the two samples is used to create separate infinitely large proxy populations. Proxy population 1 has 3/7 colored marbles; proxy population 2 has 4/9 colored marbles. Resamples are taken from each of the proxy populations. The three resamples from proxy population 1 have 2/7, 4/7 and 5/7 colored marbles, respectively. The three resamples from proxy population 2 have 5/9, 4/9, and 7/9 colored smarbles, respectively."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boot2propresamps-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.3: Taking each bootstrap sample from the estimated population.
</figcaption></figure>
</div>
</div>
</div>
<p>The variability of the statistic (the difference in sample proportions) can be calculated by taking one bootstrap resample from Sample 1 and one bootstrap resample from Sample 2 and calculating the difference in the bootstrap proportions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boot2samp2" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The first resamples from each of the two proxy populations are compared. Resample 1 from proxy population 1 has 2/7 colored marbles; resample 1 from proxy population 2 has 5/9 colored marbles. The difference in bootstrap proportions is taken as 2/7 minus 5/9.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boot2samp2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/boot2prop3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;17.4: For example, the first bootstrap resamples from Sample 1 and Sample 2 provide resample proportions of 2/7 and 5/9, respectively."><img src="images/boot2prop3.png" class="img-fluid figure-img" style="width:60.0%" alt="The first resamples from each of the two proxy populations are compared. Resample 1 from proxy population 1 has 2/7 colored marbles; resample 1 from proxy population 2 has 5/9 colored marbles. The difference in bootstrap proportions is taken as 2/7 minus 5/9."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boot2samp2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.4: For example, the first bootstrap resamples from Sample 1 and Sample 2 provide resample proportions of 2/7 and 5/9, respectively.
</figcaption></figure>
</div>
</div>
</div>
<p>As always, the variability of the difference in proportions can only be estimated by repeated simulations, in this case, repeated bootstrap resamples. <a href="#fig-boot2samp2" class="quarto-xref">Figure&nbsp;<span>17.4</span></a> shows multiple bootstrap differences calculated for each of the repeated bootstrap samples.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boot2samp3" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Shown are the two infinitely large proxy populations (created from sample 1 and sample 2). From each proxy population, three resamples are shown. For each pair of resamples, the difference in bootstrap proportions is taken. The first pair of resamples gives a difference in bootstrapped proportions of 2/7 minus 5/9; the second pair of resamples gives a difference in bootstrapped proportions of 4/7 minus 4/9; the last pair of resamples gives a difference in bootstrapped proportions of 5/7 minus 7/9. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boot2samp3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/boot2prop2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;17.5: For each pair of bootstrap samples, we calculate the difference in sample proportions."><img src="images/boot2prop2.png" class="img-fluid figure-img" style="width:100.0%" alt="Shown are the two infinitely large proxy populations (created from sample 1 and sample 2). From each proxy population, three resamples are shown. For each pair of resamples, the difference in bootstrap proportions is taken. The first pair of resamples gives a difference in bootstrapped proportions of 2/7 minus 5/9; the second pair of resamples gives a difference in bootstrapped proportions of 4/7 minus 4/9; the last pair of resamples gives a difference in bootstrapped proportions of 5/7 minus 7/9. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boot2samp3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.5: For each pair of bootstrap samples, we calculate the difference in sample proportions.
</figcaption></figure>
</div>
</div>
</div>
<p>Repeated bootstrap simulations lead to a bootstrap sampling distribution of the statistic of interest, here the difference in sample proportions. <a href="#fig-boot2samp1" class="quarto-xref">Figure&nbsp;<span>17.6</span></a> visualizes the process and <a href="#fig-bootCPR1000" class="quarto-xref">Figure&nbsp;<span>17.7</span></a> shows 1,000 bootstrap differences in proportions for the CPR data. Note that the CPR data includes 40 and 50 people in the respective groups, and the illustrated example includes 7 and 9 people in the two groups. Accordingly, the variability in the distribution of sample proportions is higher for the illustrated example. As you will see in the mathematical models discussed in <a href="#sec-math-2prop" class="quarto-xref"><span>Section 17.3</span></a>, large sample sizes lead to smaller standard errors for a difference in proportions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boot2samp1" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Shown are the two infinitely large proxy populations (created from sample 1 and sample 2). From each proxy population, three resamples are shown. For each pair of resamples, the difference in bootstrap proportions is taken. A dotplot displays many differences in bootstrap proportions. The differences range from roughly -0.6 to +0.3. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boot2samp1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/boot2prop1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;17.6: The differences in each bootstrapped pair of proportions are combined to create the sampling distribution of the differences in proportions."><img src="images/boot2prop1.png" class="img-fluid figure-img" style="width:100.0%" alt="Shown are the two infinitely large proxy populations (created from sample 1 and sample 2). From each proxy population, three resamples are shown. For each pair of resamples, the difference in bootstrap proportions is taken. A dotplot displays many differences in bootstrap proportions. The differences range from roughly -0.6 to +0.3. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boot2samp1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.6: The differences in each bootstrapped pair of proportions are combined to create the sampling distribution of the differences in proportions.
</figcaption></figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootCPR1000" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A histogram of differences in proportions from 1000 bootstrap simulations of the CPR data. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bootCPR1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-props_files/figure-html/fig-bootCPR1000-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;17.7: A histogram of differences in proportions from 1,000 bootstrap simulations of the CPR data. Note that because the CPR data has a larger sample size than the illustrated example, the variability of the difference in proportions is much smaller with the CPR histogram."><img src="inference-two-props_files/figure-html/fig-bootCPR1000-1.png" class="img-fluid figure-img" style="width:90.0%" alt="A histogram of differences in proportions from 1000 bootstrap simulations of the CPR data. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootCPR1000-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.7: A histogram of differences in proportions from 1,000 bootstrap simulations of the CPR data. Note that because the CPR data has a larger sample size than the illustrated example, the variability of the difference in proportions is much smaller with the CPR histogram.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="bootstrap-percentile-vs.-se-confidence-intervals" class="level3" data-number="17.2.3"><h3 data-number="17.2.3" class="anchored" data-anchor-id="bootstrap-percentile-vs.-se-confidence-intervals">
<span class="header-section-number">17.2.3</span> Bootstrap percentile vs.&nbsp;SE confidence intervals</h3>
<p><a href="#fig-bootCPR1000" class="quarto-xref">Figure&nbsp;<span>17.7</span></a> provides an estimate for the variability of the difference in survival proportions from sample to sample. The values in the histogram can be used in two different ways to create a confidence interval for the parameter of interest: <span class="math inline">\(p_1 - p_2\)</span>.</p>
<p>As in <a href="foundations-bootstrapping.html" class="quarto-xref">Chapter&nbsp;<span>12</span></a>, the bootstrap confidence interval can be calculated directly from the bootstrapped differences in <a href="#fig-bootCPR1000" class="quarto-xref">Figure&nbsp;<span>17.7</span></a>. The interval created from the percentiles of the distribution is called the <strong>percentile interval</strong>. Note that here we calculate the 90% confidence interval by finding the <span class="math inline">\(5^{th}\)</span> and <span class="math inline">\(95^{th}\)</span> percentile values from the bootstrapped differences. The bootstrap 5 percentile proportion is -0.032 and the 95 percentile is 0.284. The result is: we are 90% confident that, in the population, the true difference in probability of survival for individuals receiving blood thinners after CPR is between -0.032 lower and 0.284 higher than those who did not receive blood thinners. The interval shows that we do not have much definitive evidence of the effect of blood thinners, one way or another.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootCPR1000CI" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A histogram of differences in proportions from 1000 bootstrap simulations of the CPR data. The 5th and 95th percentiles are shown as vertical lines.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bootCPR1000CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-props_files/figure-html/fig-bootCPR1000CI-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;17.8: The CPR data is bootstrapped 1,000 times. Each simulation creates a sample from the original data where the probability of survival in the treatment group is \hat{p}_{T}  = 14/40 and the probability of survival in the control group is \hat{p}_{C} = 11/50."><img src="inference-two-props_files/figure-html/fig-bootCPR1000CI-1.png" class="img-fluid figure-img" style="width:90.0%" alt="A histogram of differences in proportions from 1000 bootstrap simulations of the CPR data. The 5th and 95th percentiles are shown as vertical lines."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootCPR1000CI-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.8: The CPR data is bootstrapped 1,000 times. Each simulation creates a sample from the original data where the probability of survival in the treatment group is <span class="math inline">\(\hat{p}_{T}  = 14/40\)</span> and the probability of survival in the control group is <span class="math inline">\(\hat{p}_{C} = 11/50.\)</span>
</figcaption></figure>
</div>
</div>
</div>
<p>Alternatively, we can use the variability in the bootstrapped differences to calculate a standard error of the difference. The resulting interval is called the <strong>SE interval</strong>. <a href="#sec-math-2prop" class="quarto-xref"><span>Section 17.3</span></a> details the mathematical model for the standard error of the difference in sample proportions, but the bootstrap distribution typically does an excellent job of estimating the variability of the sampling distribution of the sample statistic.</p>
<p><span class="math display">\[
SE(\hat{p}_T - \hat{p}_C) \approx SE(\hat{p}_{T, boot} - \hat{p}_{C, boot}) = 0.098
\]</span></p>
<p>The variability of the difference in proportions was calculated in R using the <code><a href="https://rdrr.io/r/stats/sd.html">sd()</a></code> function, but any statistical software will calculate the standard deviation of the differences, here, the exact quantity we hope to approximate.</p>
<p>Note that we do not know the true distribution of <span class="math inline">\(\hat{p}_T - \hat{p}_C,\)</span> so we will use a rough approximation to find a confidence interval for <span class="math inline">\(p_T - p_C.\)</span> As seen in the bootstrap histograms, the shape of the distribution is roughly symmetric and bell-shaped. So for a rough approximation, we will apply the 67-95-99.7 rule which tells us that 95% of observed differences should be roughly no farther than 2 SE from the true parameter (difference in proportions). A 95% confidence interval for <span class="math inline">\(p_T - p_C\)</span> is given by:</p>
<p><span class="math display">\[
\hat{p}_T - \hat{p}_C \pm 2 \cdot SE \rightarrow \ \ \ 14/40 - 11/50 \pm 2 \cdot 0.098 \ \ \  \rightarrow \ \ \  (-0.067, 0.327)
\]</span></p>
<p>We are 95% confident that the true value of <span class="math inline">\(p_T - p_C\)</span> is between -0.067 and 0.327. Again, the wide confidence interval that contains zero indicates that the study provides very little evidence about the effectiveness of blood thinners. For other percentages, e.g., a 90% bootstrap SE confidence interval, we will use quantiles given by the standard normal distribution, as seen in <a href="foundations-mathematical.html#sec-normalDist" class="quarto-xref"><span>Section 13.2</span></a> and <a href="foundations-mathematical.html#fig-er6895997" class="quarto-xref">Figure&nbsp;<span>13.8</span></a>.</p>
</section><section id="what-does-95-mean" class="level3" data-number="17.2.4"><h3 data-number="17.2.4" class="anchored" data-anchor-id="what-does-95-mean">
<span class="header-section-number">17.2.4</span> What does 95% mean?</h3>
<p>Recall that the goal of a confidence interval is to find a plausible range of values for a <em>parameter</em> of interest. The estimated statistic is not the value of interest, but it is typically the best guess for the unknown parameter. The confidence level (often 95%) is a number that takes a while to get used to. Surprisingly, the percentage does not describe the dataset at hand, it describes many possible datasets. One way to understand a confidence interval is to think about all the confidence intervals that you have ever made or that you will ever make as a scientist, the confidence level describes <strong>those</strong> intervals.</p>
<p><a href="#fig-ci25ints" class="quarto-xref">Figure&nbsp;<span>17.9</span></a> demonstrates a hypothetical situation in which 25 different studies are performed on the exact same population (with the same goal of estimating the true parameter value of <span class="math inline">\(p_1 - p_2 = 0.47).\)</span> The study at hand represents one point estimate (a dot) and a corresponding interval. It is not possible to know whether the interval at hand is to the right of the unknown true parameter value (the black line) or to the left of that line. It is also impossible to know whether the interval captures the true parameter (is blue) or does not (is red). If we are making 95% intervals, then about 5% of the intervals we create over our lifetime will <em>not</em> capture the parameter of interest (e.g., will be red as in <a href="#fig-ci25ints" class="quarto-xref">Figure&nbsp;<span>17.9</span></a>). What we know is that over our lifetimes as scientists, about 95% of the intervals created and reported on will capture the parameter value of interest: thus the language “95% confident.”</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-ci25ints" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A series of 25 horizontal lines are drawn, representing each of 25 different studies (where a study represents two samples, one from each of population 1 and population 2). Each vertical line starts at the value of the lower bound of the confidence interval and ends at the value of the upper bound of the confidence interval which was created from that particular sample. In the center of the line is a solid dot at the observed difference in proportion of successes for sample 1 minus sample 2. A dashed vertical line runs through the horizontal lines at p = 0.47 (which is the true value of the diffrence in population proportions). 24 of the 25 horizontal lines cross the vertical line at 0.47, but one of the horizontal lines is completely above than 0.47. The line that does not cross 0.47 is colored red because the confidence interval from that particular sample would not have captured the true difference in population proportions. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ci25ints-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-props_files/figure-html/fig-ci25ints-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;17.9: One hypothetical population, parameter value of: p_1 - p_2 = 0.47. Twenty-five different studies all which led to a different point estimate, SE, and confidence interval. The study at hand is one of the horizontal lines (hopefully a blue line!).’"><img src="inference-two-props_files/figure-html/fig-ci25ints-1.png" class="img-fluid figure-img" style="width:85.0%" alt="A series of 25 horizontal lines are drawn, representing each of 25 different studies (where a study represents two samples, one from each of population 1 and population 2). Each vertical line starts at the value of the lower bound of the confidence interval and ends at the value of the upper bound of the confidence interval which was created from that particular sample. In the center of the line is a solid dot at the observed difference in proportion of successes for sample 1 minus sample 2. A dashed vertical line runs through the horizontal lines at p = 0.47 (which is the true value of the diffrence in population proportions). 24 of the 25 horizontal lines cross the vertical line at 0.47, but one of the horizontal lines is completely above than 0.47. The line that does not cross 0.47 is colored red because the confidence interval from that particular sample would not have captured the true difference in population proportions. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ci25ints-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;17.9: One hypothetical population, parameter value of: <span class="math inline">\(p_1 - p_2 = 0.47.\)</span> Twenty-five different studies all which led to a different point estimate, SE, and confidence interval. The study at hand is one of the horizontal lines (hopefully a blue line!).’
</figcaption></figure>
</div>
</div>
</div>
<p>The choice of 95% or 90% or even 99% as a confidence level is admittedly somewhat arbitrary; however, it is related to the logic we used when deciding that a p-value should be declared as “discernible” if it is lower than 0.05 (or 0.10 or 0.01, respectively). Indeed, one can show mathematically, that a 95% confidence interval and a two-sided hypothesis test at a cutoff of 0.05 will provide the same conclusion when the same data and mathematical tools are applied for the analysis. A full derivation of the explicit connection between confidence intervals and hypothesis tests is beyond the scope of this text.</p>
</section></section><section id="sec-math-2prop" class="level2" data-number="17.3"><h2 data-number="17.3" class="anchored" data-anchor-id="sec-math-2prop">
<span class="header-section-number">17.3</span> Mathematical model for the difference in proportions</h2>
<section id="variability-of-the-difference-between-two-proportions" class="level3" data-number="17.3.1"><h3 data-number="17.3.1" class="anchored" data-anchor-id="variability-of-the-difference-between-two-proportions">
<span class="header-section-number">17.3.1</span> Variability of the difference between two proportions</h3>
<p>Like with <span class="math inline">\(\hat{p},\)</span> the difference of two sample proportions <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> can be modeled using a normal distribution when certain conditions are met. First, we require a broader independence condition, and secondly, the success-failure condition must be met by both groups.</p>
<div class="important">
<p><strong>Conditions for the sampling distribution of</strong> <span class="math inline">\(\hat{p}_1 -\hat{p}_2\)</span> <strong>to be normal.</strong></p>
<p>The difference <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> can be modeled using a normal distribution when</p>
<ol type="1">
<li>
<em>Independence</em> (extended). The data are independent within and between the two groups. Generally this is satisfied if the data come from two independent random samples or if the data come from a randomized experiment.</li>
<li>
<em>Success-failure condition.</em> The success-failure condition holds for both groups, where we check successes and failures in each group separately. That is, we should have at least 10 successes and 10 failures in each of the two groups.</li>
</ol>
<p>When these conditions are satisfied, the standard error of <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> is:</p>
<p><span class="math display">\[SE(\hat{p}_1 - \hat{p}_2) = \sqrt{\frac{p_1(1-p_1)}{n_1} + \frac{p_2(1-p_2)}{n_2}}\]</span></p>
<p>where <span class="math inline">\(p_1\)</span> and <span class="math inline">\(p_2\)</span> represent the population proportions, and <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> represent the sample sizes.</p>
<p>Note that in most cases, the standard error is approximated using the observed data:</p>
<p><span class="math display">\[SE(\hat{p}_1 - \hat{p}_2) = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}\]</span></p>
<p>where <span class="math inline">\(\hat{p}_1\)</span> and <span class="math inline">\(\hat{p}_2\)</span> represent the observed sample proportions, and <span class="math inline">\(n_1\)</span> and <span class="math inline">\(n_2\)</span> represent the sample sizes.</p>
</div>
<p>Recall that the margin of error is defined by the standard error. The margin of error for <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> can be directly obtained from <span class="math inline">\(SE(\hat{p}_1 - \hat{p}_2).\)</span></p>
<div class="important">
<p><strong>Margin of error for</strong> <span class="math inline">\(\hat{p}_1 - \hat{p}_2.\)</span></p>
<p>The margin of error is <span class="math inline">\(z^\star \times \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}\)</span> where <span class="math inline">\(z^\star\)</span> is calculated from a specified percentile on the normal distribution.</p>
</div>
<p> </p>
</section><section id="confidence-interval-for-the-difference-between-two-proportions" class="level3" data-number="17.3.2"><h3 data-number="17.3.2" class="anchored" data-anchor-id="confidence-interval-for-the-difference-between-two-proportions">
<span class="header-section-number">17.3.2</span> Confidence interval for the difference between two proportions</h3>
<p> We can apply the generic confidence interval formula for a difference of two proportions, where we use <span class="math inline">\(\hat{p}_1 - \hat{p}_2\)</span> as the point estimate and substitute the <span class="math inline">\(SE\)</span> formula:</p>
<p><span class="math display">\[
\begin{aligned}
\text{point estimate} \ &amp;\pm \  z^{\star} \ \times \ SE \\
(\hat{p}_1 - \hat{p}_2) \ &amp;\pm \ z^{\star} \times \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}
\end{aligned}
\]</span></p>
<div class="important">
<p><strong>Standard error of the difference in two proportions,</strong> <span class="math inline">\(\hat{p}_1 -\hat{p}_2.\)</span></p>
<p>When the conditions for the normal model are are met, the <strong>variability</strong> of the difference in proportions, <span class="math inline">\(\hat{p}_1 -\hat{p}_2,\)</span> is well described by:</p>
<p><span class="math display">\[SE(\hat{p}_1 -\hat{p}_2) = \sqrt{\frac{\hat{p}_1(1-\hat{p}_1)}{n_1} + \frac{\hat{p}_2(1-\hat{p}_2)}{n_2}}\]</span></p>
</div>
<div class="workedexample">
<p>We reconsider the experiment for patients who underwent cardiopulmonary resuscitation (CPR) for a heart attack and were subsequently admitted to a hospital. These patients were randomly divided into a treatment group where they received a blood thinner or the control group where they did not receive a blood thinner. The outcome variable of interest was whether the patients survived for at least 24 hours. The results are shown in <a href="foundations-errors.html#tbl-cpr-summary" class="quarto-xref">Table&nbsp;<span>14.2</span></a>. Check whether we can model the difference in sample proportions using the normal distribution.</p>
<hr>
<p>We first check for independence: since this is a randomized experiment, it seems reasonable to assume that the observations are idependent. Next, we check the success-failure condition for each group. We have at least 10 successes and 10 failures in each experiment arm (11, 14, 39, 26), so this condition is also satisfied. With both conditions satisfied, the difference in sample proportions can be reasonably modeled using a normal distribution for these data.</p>
</div>
<div class="workedexample">
<p>Create and interpret a 90% confidence interval of the difference for the survival rates in the CPR study.</p>
<hr>
<p>We’ll use <span class="math inline">\(p_T\)</span> for the survival rate in the treatment group and <span class="math inline">\(p_C\)</span> for the control group:</p>
<p><span class="math display">\[\hat{p}_{T} - \hat{p}_{C} = \frac{14}{40} - \frac{11}{50}  = 0.35 - 0.22 = 0.13\]</span></p>
<p>We use the standard error formula previously provided. As with the one-sample proportion case, we use the sample estimates of each proportion in the formula in the confidence interval context:</p>
<p><span class="math display">\[SE \approx \sqrt{\frac{0.35 (1 - 0.35)}{40} + \frac{0.22 (1 - 0.22)}{50}}  = 0.095\]</span></p>
<p>For a 90% confidence interval, we use <span class="math inline">\(z^{\star} = 1.65:\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\text{point estimate} \ &amp;\pm \ z^{\star} \ \times \ SE \\
0.13 \ &amp;\pm \ 1.65 \ \times \ 0.095 \\
(-0.027 \ &amp;, \ 0.287)
\end{aligned}
\]</span></p>
<p>We are 90% confident that individuals receiving blood thinners have between a 2.7% less chance of survival to a 28.7% greater chance of survival than those in the control group. Because 0% is contained in the interval, we do not have enough information to say whether blood thinners help or harm heart attack patients who have been admitted after they have undergone CPR.</p>
<p>Note, the problem was set up as 90% to indicate that there was not a need for a high level of confidence (such a 95% or 99%). A lower degree of confidence increases potential for error, but it also produces a more narrow interval.</p>
</div>
<div class="guidedpractice">
<p>A 5-year experiment was conducted to evaluate the effectiveness of fish oils on reducing cardiovascular events, where each subject was randomized into one of two treatment groups <span class="citation" data-cites="Manson:2019">(<a href="references.html#ref-Manson:2019" role="doc-biblioref">Manson et al. 2019</a>)</span>. We’ll consider heart attack outcomes in the patients listed in <a href="#tbl-fish-oil-data" class="quarto-xref">Table&nbsp;<span>17.2</span></a>.</p>
<p>Create a 95% confidence interval for the effect of fish oils on heart attacks for patients who are well-represented by those in the study. Also interpret the interval in the context of the study.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
<div class="cell" data-tbl-pos="H">
<div id="tbl-fish-oil-data" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-fish-oil-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17.2: Results for the study on n-3 fatty acid supplement and related health benefits.
</figcaption><div aria-describedby="tbl-fish-oil-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">heart attack</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">no event</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">fish oil</td>
<td style="text-align: right; width: 7em;">145</td>
<td style="text-align: right; width: 7em;">12788</td>
<td style="text-align: right; width: 7em;">12933</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">placebo</td>
<td style="text-align: right; width: 7em;">200</td>
<td style="text-align: right; width: 7em;">12738</td>
<td style="text-align: right; width: 7em;">12938</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/fish_oil.html"><code>fish_oil_18</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
</section><section id="sec-test-prop-pool" class="level3" data-number="17.3.3"><h3 data-number="17.3.3" class="anchored" data-anchor-id="sec-test-prop-pool">
<span class="header-section-number">17.3.3</span> Hypothesis test for the difference between two proportions</h3>
<p>The details for calculating a SE and for checking technical conditions are very similar to that of confidence intervals. However, when the null hypothesis is that <span class="math inline">\(p_1 - p_2 = 0,\)</span> we use a special proportion called the <strong>pooled proportion</strong> to estimate the SE and to check the success-failure condition.</p>
<div class="important">
<p><strong>Use the pooled proportion when</strong> <span class="math inline">\(H_0\)</span> is <span class="math inline">\(p_1 - p_2 = 0.\)</span></p>
<p>When the null hypothesis is that the proportions are equal, use the pooled proportion <span class="math inline">\((\hat{p}_{\textit{pool}})\)</span> of successes to verify the success-failure condition and estimate the standard error:</p>
<p><span class="math display">\[\hat{p}_{\textit{pool}} = \frac{\text{number of successes}}{\text{number of cases}} = \frac{\hat{p}_1 n_1 + \hat{p}_2 n_2}{n_1 + n_2}\]</span></p>
<p>Here <span class="math inline">\(\hat{p}_1 n_1\)</span> represents the number of successes in sample 1 because <span class="math inline">\(\hat{p}_1 = \frac{\text{number of successes in sample 1}}{n_1}.\)</span></p>
<p>Similarly, <span class="math inline">\(\hat{p}_2 n_2\)</span> represents the number of successes in sample 2.</p>
</div>
<div class="important">
<p><strong>The test statistic for assessing two proportions is a Z.</strong></p>
<p>The Z score is a ratio of how the two sample proportions differ as compared to the expected variability of difference between the proportions.</p>
<p><span class="math display">\[Z = \frac{(\hat{p}_1 - \hat{p}_2) - 0}{\sqrt{\hat{p}_{pool}(1-\hat{p}_{pool}) \bigg(\frac{1}{n_1} + \frac{1}{n_2} \bigg)}}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, Z has a standard normal distribution. See the box below for calculation of the pooled proportion of successes.</p>
<p>Conditions:</p>
<ul>
<li>Independent observations</li>
<li>Large samples: <span class="math inline">\((n_1 p_1 \geq 10\)</span> and <span class="math inline">\(n_1 (1-p_1) \geq 10\)</span> and <span class="math inline">\(n_2 p_2 \geq 10\)</span> and <span class="math inline">\(n_2 (1-p_2) \geq 10)\)</span>
</li>
<li>Check conditions using: <span class="math inline">\((n_1 \hat{p}_{\textit{pool}} \geq 10\)</span> and <span class="math inline">\(n_1 (1-\hat{p}_{\textit{pool}}) \geq 10\)</span> and <span class="math inline">\(n_2 \hat{p}_{\textit{pool}}\geq 10\)</span> and <span class="math inline">\(n_2 (1-\hat{p}_{\textit{pool}}) \geq 10)\)</span>
</li>
</ul>
</div>
<p>A mammogram is an X-ray procedure used to check for breast cancer. Whether mammograms should be used is part of a controversial discussion, and it’s the topic of our next example where we learn about 2-proportion hypothesis tests when <span class="math inline">\(H_0\)</span> is <span class="math inline">\(p_1 - p_2 = 0\)</span> (or equivalently, <span class="math inline">\(p_1 = p_2).\)</span></p>
<p>A 30-year study was conducted with nearly 90,000 participants who identified as female. During a 5-year screening period, each participant was randomized to one of two groups: in the first group, participants received regular mammograms to screen for breast cancer, and in the second group, participants received regular non-mammogram breast cancer exams. No intervention was made during the following 25 years of the study, and we’ll consider death resulting from breast cancer over the full 30-year period. Results from the study are summarized in <a href="#tbl-mammogramStudySummaryTable" class="quarto-xref">Table&nbsp;<span>17.3</span></a>.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/mammogram.html"><code>mammogram</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<p>If mammograms are much more effective than non-mammogram breast cancer exams, then we would expect to see additional deaths from breast cancer in the control group. On the other hand, if mammograms are not as effective as regular breast cancer exams, we would expect to see an increase in breast cancer deaths in the mammogram group.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-mammogramStudySummaryTable" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mammogramStudySummaryTable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17.3: Summary results for breast cancer study.
</figcaption><div aria-describedby="tbl-mammogramStudySummaryTable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Death from breast cancer?
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Treatment</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Yes</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">control</td>
<td style="text-align: right;">505</td>
<td style="text-align: right;">44,405</td>
</tr>
<tr class="even">
<td style="text-align: left;">mammogram</td>
<td style="text-align: right;">500</td>
<td style="text-align: right;">44,425</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="guidedpractice">
<p>Is this study an experiment or an observational study?<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<div class="guidedpractice">
<p>Set up hypotheses to test whether there was a difference in breast cancer deaths in the mammogram and control groups.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</div>
<p>The research question describing mammograms is set up to address specific hypotheses (in contrast to a confidence interval for a parameter). In order to fully take advantage of the hypothesis testing structure, we assess the randomness under the condition that the null hypothesis is true (as we always do for hypothesis testing). Using the data from <a href="#tbl-mammogramStudySummaryTable" class="quarto-xref">Table&nbsp;<span>17.3</span></a>, we will check the conditions for using a normal distribution to analyze the results of the study using a hypothesis test.</p>
<p><span class="math display">\[
\begin{aligned}
\hat{p}_{\textit{pool}}
    &amp;= \frac
        {\text{number of patients who died from breast cancer in the entire study}}
        {\text{number of patients in the entire study}} \\
    &amp;= \frac{500 + 505}{500 + \text{44,425} + 505 + \text{44,405}} \\
    &amp;= 0.0112
\end{aligned}
\]</span></p>
<p>This proportion is an estimate of the breast cancer death rate across the entire study, and it’s our best estimate of the proportions <span class="math inline">\(p_{MGM}\)</span> and <span class="math inline">\(p_{C}\)</span> <em>if the null hypothesis is true that</em> <span class="math inline">\(p_{MGM} = p_{C}.\)</span> We will also use this pooled proportion when computing the standard error.</p>
<div class="workedexample">
<p>Is it reasonable to model the difference in proportions using a normal distribution in this study?</p>
<hr>
<p>Because the patients were randomized, observations can be assumed to be independent, both within each group and between treatment groups. We also must check the success-failure condition for each group. Under the null hypothesis, the proportions <span class="math inline">\(p_{MGM}\)</span> and <span class="math inline">\(p_{C}\)</span> are equal, so we check the success-failure condition with our best estimate of these values under <span class="math inline">\(H_0,\)</span> the pooled proportion from the two samples, <span class="math inline">\(\hat{p}_{\textit{pool}} = 0.0112:\)</span></p>
<p><span class="math display">\[
\begin{aligned}
\hat{p}_{\textit{pool}} \times n_{MGM}
      &amp;= 0.0112 \times \text{44,925} = 503\\
(1 - \hat{p}_{\textit{pool}}) \times n_{MGM}
      &amp;= 0.9888 \times \text{44,925} = \text{44,422} \\
  \hat{p}_{\textit{pool}} \times n_{C}
      &amp;= 0.0112 \times \text{44,910} = 503\\
  (1 - \hat{p}_{\textit{pool}}) \times n_{C}
      &amp;= 0.9888 \times \text{44,910} = \text{44,407}
\end{aligned}
\]</span></p>
<p>The success-failure condition is satisfied since all values are at least 10. With both conditions satisfied, we can safely model the difference in proportions using a normal distribution.</p>
</div>
<p>In the previous example, the pooled proportion was used to check the success-failure condition<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>. In the next example, we see an additional place where the pooled proportion comes into play: the standard error calculation.</p>
<div class="workedexample">
<p>Compute the point estimate of the difference in breast cancer death rates in the two groups, and use the pooled proportion <span class="math inline">\(\hat{p}_{\textit{pool}} = 0.0112\)</span> to calculate the standard error.</p>
<hr>
<p>The point estimate of the difference in breast cancer death rates is</p>
<p><span class="math display">\[
\hat{p}_{MGM} - \hat{p}_{C} = \frac{500}{500 + 44,425} - \frac{505}{505 + 44,405} = 0.01113 - 0.01125 = -0.00012
\]</span></p>
<p>The breast cancer death rate in the mammogram group was 0.012% less than in the control group. Next, the standard error is calculated <em>using the pooled proportion,</em> <span class="math inline">\(\hat{p}_{\textit{pool}}:\)</span></p>
<p><span class="math display">\[SE = \sqrt{\frac{\hat{p}_{\textit{pool}}(1-\hat{p}_{\textit{pool}})}{n_{MGM}} + \frac{\hat{p}_{\textit{pool}}(1-\hat{p}_{\textit{pool}})}{n_{C}}}= 0.00070\]</span></p>
</div>
<div class="workedexample">
<p>Using the point estimate <span class="math inline">\(\hat{p}_{MGM} - \hat{p}_{C} = -0.00012\)</span> and standard error <span class="math inline">\(SE = 0.00070,\)</span> calculate a p-value for the hypothesis test and write a conclusion.</p>
<hr>
<p>We first compute a test statistic and draw a picture:</p>
<p><span class="math display">\[Z = \frac{\text{point estimate} - \text{null value}}{SE} = \frac{-0.00012 - 0}{0.00070} = -0.17\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="inference-two-props_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>The lower tail area is 0.4325, which we double to get the p-value: 0.8650. Because this p-value is larger than 0.05, we do not reject the null hypothesis. That is, the difference in breast cancer death rates is likely to have occurred just by chance, if the null hypothesis is true. Thus, we do not observe benefits or harm from mammograms relative to a regular breast exam.</p>
</div>
<p>Can we conclude that mammograms have no benefits or harm? Here are a few considerations to keep in mind when reviewing the mammogram study as well as any other medical study:</p>
<ul>
<li>We do not reject the null hypothesis, which means we do not have sufficient evidence to conclude that mammograms reduce or increase breast cancer deaths.</li>
<li>If mammograms are helpful or harmful, the data suggest the effect isn’t very large.</li>
<li>Are mammograms more or less expensive than a non-mammogram breast exam? If one option is much more expensive than the other and does not offer clear benefits, then we should lean towards the less expensive option.</li>
<li>The study’s authors also found that mammograms led to over-diagnosis of breast cancer, which means some breast cancers were found (or thought to be found) but that these cancers would not cause symptoms during patients’ lifetimes. That is, something else would kill the patient before breast cancer symptoms appeared. This means some patients may have been treated for breast cancer unnecessarily, and this treatment is another cost to consider. It is also important to recognize that over-diagnosis can cause unnecessary physical or emotional harm to patients.</li>
</ul>
<p>These considerations highlight the complexity around medical care and treatment recommendations. Experts and medical boards who study medical treatments use considerations like those above to provide their best recommendation based on the current evidence.</p>
</section></section><section id="sec-chp17-review" class="level2" data-number="17.4"><h2 data-number="17.4" class="anchored" data-anchor-id="sec-chp17-review">
<span class="header-section-number">17.4</span> Chapter review</h2>
<section id="summary" class="level3" data-number="17.4.1"><h3 data-number="17.4.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">17.4.1</span> Summary</h3>
<p>When the parameter of interest is the difference in population proportions across two groups, randomization tests, bootstrapping, and mathematical modeling can be applied. For confidence intervals, bootstrapping from each group separately will provide a sampling distribution for the difference in sample proportions; the mathematical model shows a similar distributional shape as long as the sample size is large enough to fulfill the success-failure conditions and so that the data are representative of the entire population. Keep in mind that some datasets will produce a confidence interval which does not capture the true parameter, this is the nature of variability! Over your lifetime, about 95% of the confidence intervals you create will capture the parameter of interest, and about 5% won’t. For hypothesis testing, repeated randomization of the explanatory variable creates a null distribution of differences in sample proportions that could have occurred under the null hypothesis. Randomization and the mathematical model will have similar null distributions, as long as the sample size is large enough to fulfill the success-failure conditions.</p>
</section><section id="terms" class="level3" data-number="17.4.2"><h3 data-number="17.4.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">17.4.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-17" class="quarto-xref">Table&nbsp;<span>17.4</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-17" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17.4: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">percentile interval</td>
<td style="text-align: left; width: 12em;">pooled proportion</td>
<td style="text-align: left; width: 12em;">SE interval</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">point estimate</td>
<td style="text-align: left; width: 12em;">SE difference in proportions</td>
<td style="text-align: left; width: 12em;">Z score two proportions</td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp17-exercises" class="level2" data-number="17.5"><h2 data-number="17.5" class="anchored" data-anchor-id="sec-chp17-exercises">
<span class="header-section-number">17.5</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-17" class="quarto-xref">Appendix&nbsp;<span>A.17</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<p><strong>Disaggregating Asian American tobacco use, hypothesis testing.</strong> Understanding cultural differences in tobacco use across different demographic groups can lead to improved health care education and treatment. A recent study disaggregated tobacco use across Asian American ethnic groups including Asian-Indian (n = 4,373), Chinese (n = 4,736), and Filipino (n = 4,912), in comparison to non-Hispanic Whites (n = 275,025). The number of current smokers in each group was reported as Asian-Indian (n = 223), Chinese (n = 279), Filipino (n = 609), and non-Hispanic Whites (n = 50,880). <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span></p>
<p>To determine whether the proportion of Asian-Indian Americans who are current smokers is different from the proportion of Chinese Americans who are smokers, a randomization simulation was performed.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-11-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="inference-two-props_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>In both words and symbols provide the parameter and statistic of interest for this study. Do you know the numerical value of either the parameter or statistic of interest? If so, provide the numerical value.</p></li>
<li><p>The histogram above provides the sampling distribution (under randomization) for <span class="math inline">\(\hat{p}_{Asian-Indian} - \hat{p}_{Chinese}\)</span> under repeated null randomizations (<span class="math inline">\(\hat{p}\)</span> is the proportion in the sample who are current smokers). Estimate the standard error of <span class="math inline">\(\hat{p}_{Asian-Indian} - \hat{p}_{Chinese}\)</span> based on the randomization histogram.</p></li>
<li><p>Consider the hypothesis test to determine if there is a difference in proportion of Asian-Indian Americans as compared to Chinese Americans who are current smokers. Write out the null and alternative hypotheses, estimate a p-value using the randomization histogram, and conclude the test in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="2" type="1">
<li>
<p><strong>Malaria vaccine effectiveness, hypothesis test.</strong> With no currently licensed vaccines to inhibit malaria, good news was welcomed with a recent study reporting long-awaited vaccine success for children in Burkina Faso. With 450 children randomized to either one of two different doses of the malaria vaccine or a control vaccine, 89 of 292 malaria vaccine and 106 out of 147 control vaccine children contracted malaria within 12 months after the treatment. <span class="citation" data-cites="Datoo:2021">(<a href="references.html#ref-Datoo:2021" role="doc-biblioref">Datoo et al. 2021</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="inference-two-props_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>In both words and symbols provide the parameter and statistic of interest for this study. Do you know the numerical value of either the parameter or statisic of interest? If so, provide the numerical value.</p></li>
<li><p>The histogram above provides the sampling distribution (under randomization) for <span class="math inline">\(\hat{p}_{malaria} - \hat{p}_{control}\)</span> under repeated null randomizations (<span class="math inline">\(\hat{p}\)</span> is the proportion of children in the sample who contracted malaria). Estimate the standard error of <span class="math inline">\(\hat{p}_{malaria} - \hat{p}_{control}\)</span> based on the randomization histogram.</p></li>
<li><p>Consider the hypothesis test constructed to show a lower proportion of children contracting malaria on the malaria vaccine as compared to the control vaccine. Write out the null and alternative hypotheses, estimate a p-value using the randomization histogram, and conclude the test in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>Disaggregating Asian American tobacco use, confidence interval.</strong> Based on a study on the degree to which smoking practices differ across ethnic groups. a confidence interval for the difference in current smoking status for Filipino versus Chinese Americans is desired. <span class="citation" data-cites="Rao:2021">(<a href="references.html#ref-Rao:2021" role="doc-biblioref">Rao et al. 2021</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-13-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="inference-two-props_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Consider the bootstrap distribution of difference in sample proportions of current smokers (Filipino Americans minus Chinese Americans) in 1,000 bootstrap repetitions as above. Estimate the standard error of the difference in sample proportions, as seen in the histogram.</p></li>
<li><p>Using the standard error from the bootstrap distribution, find a 95% bootstrap SE confidence interval for the true difference in proportion of current smokers (Filipino Americans minus Chinese Americans) in the population. Interpret the interval in the context of the problem.</p></li>
<li><p>Using the entire bootstrap distribution, find a 95% bootstrap percentile confidence interval for the true difference in proportion of current smokers (Filipino Americans minus Chinese Americans) in the population. Interpret the interval in the context of the problem.</p></li>
</ol>
</li>
<li>
<p><strong>Malaria vaccine effectiveness, confidence interval.</strong> With no currently licensed vaccines to inhibit malaria, good news was welcomed with a recent study reporting long-awaited vaccine success for children in Burkina Faso. With 450 children randomized to either one of two different doses of the malaria vaccine or a control vaccine, 89 of 292 malaria vaccine and 106 out of 147 control vaccine children contracted malaria within 12 months after the treatment. <span class="citation" data-cites="Datoo:2021">(<a href="references.html#ref-Datoo:2021" role="doc-biblioref">Datoo et al. 2021</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-14-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="inference-two-props_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Consider the bootstrap distribution of difference in sample proportions of children who contracted malaria (malaria vaccine minus control vaccine) in 1000 bootstrap repetitions as above. Estimate the standard error of the difference in sample proportions, as seen in the histogram.</p></li>
<li><p>Using the standard error from the bootstrap distribution, find a 95% bootstrap SE confidence interval for the true difference in proportion of children who contract malaria (malaria vaccine minus control vaccine) in the population. Interpret the interval in the context of the problem.</p></li>
<li><p>Using the entire bootstrap distribution, find a 95% bootstrap percentile confidence interval for the true difference in proportion of children who contract malaria (malaria vaccine minus control vaccine) in the population. Interpret the interval in the context of the problem.</p></li>
</ol>
</li>
</ol>
<ol start="5" type="1">
<li>
<p><strong>COVID-19 and degree completion.</strong> A 2021 Gallup poll surveyed 3,941 students pursuing a bachelor’s degree and 2,064 students pursuing an associate degree (students were not randomly selected but were weighted so as to represent a random selection of currently enrolled US college students). The poll found that 51% of the bachelor’s degree students and 44% of associate degree students said that the COVID-19 pandemic will negatively impact their ability to complete the degree. <span class="citation" data-cites="data:gallupcollegeimpact">(<a href="references.html#ref-data:gallupcollegeimpact" role="doc-biblioref">Gallup 2021</a>)</span></p>
<p>Below are two histograms generated with different computational approaches (both use 1,000 repetitions) to research questions which could be asked of these data. One of the histograms can be used to do a randomization test on whether the proportions of bachelor’s and associate students who think the COVID-19 pandemic will negatively impact their ability to complete the degree. The other histogram is a bootstrap distribution used to quantify the difference in the proportions of bachelor’s and associate’s students who feel this way.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="inference-two-props_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Are the center and standard error of the two graphs approximately the same? Explain.</p></li>
<li><p>Write a research question that can be addressed using the histogram generated with computational method A.</p></li>
<li><p>Write a research question that can addressed using the histogram generated with computational method B.</p></li>
</ol>
</li>
<li>
<p><strong>Renewable energy.</strong> A 2021 Gallup poll surveyed 5,447 randomly sampled US adults who are Republican (or Republican leaning) and 7,962 who are Democrats (or Democrat leaning). 31% of Republicans and 81% of Democrats said “government regulations are necessary to encourage businesses and consumers to rely more on renewable energy sources”. <span class="citation" data-cites="data:gallupcollegeimpact">(<a href="references.html#ref-data:gallupcollegeimpact" role="doc-biblioref">Gallup 2021</a>)</span></p>
<p>Below are two histograms generated with different computational approaches (both use 1,000 repetitions) to research questions which could be asked of these data. One of the histograms can be used to do a randomization test on whether the proportions of Republicans and Democrats who think government regulations are necessary to encourage businesses and consumers to rely more on renewable energy sources are different. The other histogram is a bootstrap distribution used to quantify the difference in the proportions of Republicans and Democrats who agree with this statement.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="inference-two-props_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Are the center and standard error of the two graphs approximately the same? Explain.</p></li>
<li><p>Write a research question that can addressed using the histogram generated with computational method A.</p></li>
<li><p>Write a research question that can addressed using the histogram generated with computational method B.</p></li>
</ol>
</li>
</ol>
<ol start="7" type="1">
<li>
<p><strong>HIV in sub-Saharan Africa.</strong> In July 2008 the US National Institutes of Health announced that it was stopping a clinical study early because of unexpected results. The study population consisted of HIV-infected women in sub-Saharan Africa who had been given single dose Nevaripine (a treatment for HIV) while giving birth, to prevent transmission of HIV to the infant. The study was a randomized comparison of continued treatment of a woman (after successful childbirth) with Nevaripine vs Lopinavir, a second drug used to treat HIV. 240 women participated in the study; 120 were randomized to each of the two treatments. Twenty-four weeks after starting the study treatment, each woman was tested to determine if the HIV infection was becoming worse (an outcome called <em>virologic failure</em>). Twenty-six of the 120 women treated with Nevaripine experienced virologic failure, while 10 of the 120 women treated with the other drug experienced virologic failure. <span class="citation" data-cites="Lockman:2007">(<a href="references.html#ref-Lockman:2007" role="doc-biblioref">Lockman et al. 2007</a>)</span></p>
<ol type="a">
<li><p>Create a two-way table presenting the results of this study.</p></li>
<li><p>State appropriate hypotheses to test for difference in virologic failure rates between treatment groups.</p></li>
<li><p>Complete the hypothesis test and state an appropriate conclusion. (Reminder: Verify any necessary conditions for the test.)</p></li>
</ol>
</li>
</ol>
<ol start="8" type="1">
<li>
<p><strong>Supercommuters.</strong> The fraction of workers who are considered “supercommuters”, because they commute more than 90 minutes to get to work, varies by state. Suppose the 1% of Nebraska residents and 6% of New York residents are supercommuters. Now suppose that we plan a study to survey 1000 people from each state, and we will compute the sample proportions <span class="math inline">\(\hat{p}_{NE}\)</span> for Nebraska and <span class="math inline">\(\hat{p}_{NY}\)</span> for New York.</p>
<ol type="a">
<li><p>What is the associated mean and standard deviation of <span class="math inline">\(\hat{p}_{NE}\)</span> in repeated samples of size 1000?</p></li>
<li><p>What is the associated mean and standard deviation of <span class="math inline">\(\hat{p}_{NY}\)</span> in repeated samples of size 1000?</p></li>
<li><p>Calculate and interpret the mean and standard deviation associated with the difference in sample proportions for the two groups, <span class="math inline">\(\hat{p}_{NY} - \hat{p}_{NE}\)</span> in repeated samples of 1000 in each group.</p></li>
<li><p>How are the standard deviations from parts&nbsp;(a), (b), and&nbsp;(c) related?</p></li>
</ol>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>National Health Plan.</strong> A Kaiser Family Foundation poll for US adults in 2019 found that 79% of Democrats, 55% of Independents, and 24% of Republicans supported a generic “National Health Plan”. There were 347 Democrats, 298 Republicans, and 617 Independents surveyed. 79% of 347 Democrats and 55% of 617 Independents support a National Health Plan. <span class="citation" data-cites="data:KFF2019nathealthplan">(<a href="references.html#ref-data:KFF2019nathealthplan" role="doc-biblioref">Kaiser Family Foundation 2019</a>)</span></p>
<ol type="a">
<li><p>Calculate a 95% confidence interval for the difference between the proportion of Democrats and Independents who support a National Health Plan <span class="math inline">\((p_{D} - p_{I})\)</span>, and interpret it in this context. We have already checked conditions for you.</p></li>
<li><p>True or false: If we had picked a random Democrat and a random Independent at the time of this poll, it is more likely that the Democrat would support the National Health Plan than the Independent.</p></li>
</ol>
</li>
</ol>
<ol start="10" type="1">
<li>
<strong>Sleep deprivation, CA vs.&nbsp;OR, confidence interval.</strong> According to a report on sleep deprivation by the Centers for Disease Control and Prevention, the proportion of California residents who reported insufficient rest or sleep during each of the preceding 30 days is 8.0%, while this proportion is 8.8% for Oregon residents. These data are based on simple random samples of 11,545 California and 4,691 Oregon residents. Calculate a 95% confidence interval for the difference between the proportions of Californians and Oregonians who are sleep deprived and interpret it in context of the data. <span class="citation" data-cites="data:sleepCAandOR">(<a href="references.html#ref-data:sleepCAandOR" role="doc-biblioref">CDC 2008</a>)</span>
</li>
</ol>
<ol start="11" type="1">
<li>
<p><strong>Gender pay gap in medicine.</strong> A study examined the average pay for men and women entering the workforce as doctors for 21 different positions. <span class="citation" data-cites="LoSassoMedicineGenderPayGap">(<a href="references.html#ref-LoSassoMedicineGenderPayGap" role="doc-biblioref">Lo Sasso et al. 2011</a>)</span></p>
<ol type="a">
<li><p>If each gender was equally paid, then we would expect about half of those positions to have men paid more than women and women would be paid more than men in the other half of positions. Write appropriate hypotheses to test this scenario.</p></li>
<li><p>Men were, on average, paid more in 19 of those 21 positions. Complete a hypothesis test using your hypotheses from part&nbsp;(a).</p></li>
</ol>
</li>
</ol>
<ol start="12" type="1">
<li>
<p><strong>Sleep deprivation, CA vs.&nbsp;OR, hypothesis test.</strong> A CDC report on sleep deprivation rates shows that the proportion of California residents who reported insufficient rest or sleep during each of the preceding 30 days is 8.0%, while this proportion is 8.8% for Oregon residents. These data are based on simple random samples of 11,545 California and 4,691 Oregon residents.</p>
<ol type="a">
<li><p>Conduct a hypothesis test to determine if these data provide strong evidence that the rate of sleep deprivation is different for the two states. (Reminder: Check conditions)</p></li>
<li><p>It is possible the conclusion of the test in part (a) is incorrect. If this is the case, what type of error was made?</p></li>
</ol>
</li>
</ol>
<ol start="13" type="1">
<li>
<p><strong>Is yawning contagious?</strong> An experiment conducted by the MythBusters, a science entertainment TV program on the Discovery Channel, tested if a person can be subconsciously influenced into yawning if another person near them yawns. 50 people were randomly assigned to two groups: 34 to a group where a person near them yawned (treatment) and 16 to a group where there wasn’t a person yawning near them (control). The visualization below displays how many participants yawned in each group.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-17-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="inference-two-props_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Suppose we are interested in estimating the difference in yawning rates between the control and treatment groups using a confidence interval. Explain why we cannot construct such an interval using the normal approximation. What might go wrong if we constructed the confidence interval despite this problem?</p>
</li>
</ol>
<ol start="14" type="1">
<li>
<p><strong>Heart transplant success.</strong> The Stanford University Heart Transplant Study was conducted to determine whether an experimental heart transplant program increased lifespan. Each patient entering the program was officially designated a heart transplant candidate, meaning that he was gravely ill and might benefit from a new heart. Patients were randomly assigned into treatment and control groups. Patients in the treatment group received a transplant, and those in the control group did not. The visualization below displays how many patients survived and died in each group.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <span class="citation" data-cites="Turnbull+Brown+Hu:1974">(<a href="references.html#ref-Turnbull+Brown+Hu:1974" role="doc-biblioref">Turnbull, Brown, and Hu 1974</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-props_files/figure-html/unnamed-chunk-18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18"><img src="inference-two-props_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Suppose we are interested in estimating the difference in survival rate between the control and treatment groups using a confidence interval. Explain why we cannot construct such an interval using the normal approximation. What might go wrong if we constructed the confidence interval despite this problem?</p>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Government shutdown.</strong> The United States federal government shutdown of 2018–2019 occurred from December 22, 2018 until January 25, 2019, a span of 35 days. A&nbsp;Survey USA poll of 614 randomly sampled Americans during this time period reported that 48% of those who make less than $40,000 per year and 55% of those who make $40,000 or more per year said the government shutdown has not at all affected them personally. A&nbsp;95% confidence interval for <span class="math inline">\((p_\text{$&lt;$40K} - p_\text{$\ge$40K})\)</span>, where <span class="math inline">\(p\)</span> is the proportion of those who said the government shutdown has not at all affected them personally, is (-0.16, 0.02). Based on this information, determine if the following statements are true or false, and explain your reasoning if you identify the statement as false. <span class="citation" data-cites="data:govtshuthown">(<a href="references.html#ref-data:govtshuthown" role="doc-biblioref">Survey USA 2019</a>)</span></p>
<ol type="a">
<li><p>At the 5% discernibility level, the data provide convincing evidence of a real difference in the proportion who are not affected personally between Americans who make less than $40,000 annually and Americans who make $40,000 annually.</p></li>
<li><p>We are 95% confident that 16% more to 2% fewer Americans who make less than $40,000 per year are not at all personally affected by the government shutdown compared to those who make $40,000 or more per year.</p></li>
<li><p>A 90% confidence interval for <span class="math inline">\((p_\text{$&lt;$40K} - p_\text{$\ge$40K})\)</span> would be wider than the <span class="math inline">\((-0.16, 0.02)\)</span> interval.</p></li>
<li><p>A 95% confidence interval for <span class="math inline">\((p_\text{$\ge$40K} - p_\text{$&lt;$40K})\)</span> is (-0.02, 0.16).</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>Online harassment.</strong> A Pew Research poll asked US adults aged 18-29 and 30-49 whether they have personally experienced harassment online. A 95% confidence interval for the difference between the proportions of 18-29 year-olds and 30-49 year-olds who have personally experienced harassment online <span class="math inline">\((p_{18-29} - p_{30-49})\)</span> was calculated to be (0.115, 0.185). Based on this information, determine if the following statements are true or false, and explain your reasoning for each statement you identify as false. <span class="citation" data-cites="onlineharassment2021">(<a href="references.html#ref-onlineharassment2021" role="doc-biblioref">Pew Research Center 2021</a>)</span></p>
<ol type="a">
<li><p>We are 95% confident that the true proportion of 18-29 year-olds who have personally experienced harassment online is 11.5% to 18.5% lower than the true proportion of 30-49 year-olds who have personally experienced harassment online.</p></li>
<li><p>We are 95% confident that the true proportion of 18-29 year-olds who have personally experienced harassment online is 11.5% to 18.5% higher than the true proportion of 30-49 year-olds who have personally experienced harassment online.</p></li>
<li><p>95% of random samples will produce 95% confidence intervals that include the true difference between the population proportions of 18-29 year-olds and 30-49 year-olds who have personally experienced harassment online.</p></li>
<li><p>We can conclude that there is a discernible difference between the proportions of 18-29 year-olds and 30-49 year-olds who have personally experienced harassment online is too large to plausibly be due to chance, if in fact there is no difference between the two proportions.</p></li>
<li><p>The 90% confidence interval for <span class="math inline">\((p_{18-29} - p_{30-49})\)</span> cannot be calculated with only the information given in this exercise.</p></li>
</ol>
</li>
</ol>
<ol start="17" type="1">
<li>
<p><strong>Decision errors and comparing proportions I.</strong> In the following research studies, conclusions were made based on the data provided. It is always possible that the analysis conclusion could be wrong, although we will almost never actually know if an error has been made or not. For each study conclusion, specify which of a Type I or Type II error could have been made, and state the error in the context of the problem.</p>
<ol type="a">
<li><p>The malaria vaccine was seen to be effective at lowering the rate of contracting malaria (when compared to the control vaccine).</p></li>
<li><p>In the US population, Asian-Indian Americans and Chinese Americans are not observed to have different proportions of current smokers.</p></li>
<li><p>There is no evidence to claim a difference in the proportion of Americans who are not affected personally by a government shutdown when comparing Americans who make less than $40,000 annually and Americans who make $40,000 annually.</p></li>
</ol>
</li>
</ol>
<ol start="18" type="1">
<li>
<p><strong>Decision errors and comparing proportions II.</strong> In the following research studies, conclusions were made based on the data provided. It is always possible that the analysis conclusion could be wrong, although we will almost never actually know if an error has been made or not. For each study conclusion, specify which of a Type I or Type II error could have been made, and state the error in the context of the problem.</p>
<ol type="a">
<li><p>Of registered voters in California, the proportion who report not knowing enough to voice an opinion on whether they support off shore drilling is different across those who have a college degree and those who do not.</p></li>
<li><p>In comparing Californians and Oregonians, there is no evidence to support a difference in the proportion of each who are sleep deprived.</p></li>
</ol>
</li>
</ol>
<ol start="19" type="1">
<li>
<strong>Active learning.</strong> A teacher wanting to increase the active learning component of her course is concerned about student reactions to changes she is planning to make. She conducts a survey in her class, asking students whether they believe more active learning in the classroom (hands on exercises) instead of traditional lecture will helps improve their learning. She does this at the beginning and end of the semester and wants to evaluate whether students’ opinions have changed over the semester. Can she used the methods we learned in this chapter for this analysis? Explain your reasoning.</li>
</ol>
<ol start="20" type="1">
<li>
<strong>An apple a day keeps the doctor away.</strong> A physical education teacher at a high school wanting to increase awareness on issues of nutrition and health asked her students at the beginning of the semester whether they believed the expression “an apple a day keeps the doctor away”. 40% of the students responded yes. Throughout the semester she started each class with a discussion of a study highlighting positive effects of eating more fruits and vegetables. She conducted the same apple-a-day survey at the end of the semester, and this time 60% of the students responded yes. Can she used a two-proportion method from this section for this analysis? Explain your reasoning.</li>
</ol>
<ol start="21" type="1">
<li>
<p><strong>Malaria vaccine effectiveness, effect size.</strong> A randomized controlled trial on malaria vaccine effectiveness randomly assigned 450 children intro either one of two different doses of the malaria vaccine or a control vaccine. 89 of 292 malaria vaccine and 106 out of 147 control vaccine children contracted malaria within 12 months after the treatment. <span class="citation" data-cites="Datoo:2021">(<a href="references.html#ref-Datoo:2021" role="doc-biblioref">Datoo et al. 2021</a>)</span></p>
<p>Recall that in order to reject the null hypothesis that the two vaccines (malaria and control) are equivalent, we’d need the sample proportion to be about 2 standard errors below the hypothesized value of zero.</p>
<p>Say that the true difference (in the population) is given as <span class="math inline">\(\delta,\)</span> the sample sizes are the same in both groups <span class="math inline">\((n_{malaria} = n_{control}),\)</span> and the true proportion who contract malaria on the control vaccine is <span class="math inline">\(p_{control} = 0.7.\)</span> If you ran your own study (in the future), how likely is it that you would get a difference in sample proportions that was sufficiently far from zero that you could reject under each of the conditions below. (<em>Hint:</em> Use the mathematical model.)</p>
<ol type="a">
<li><p><span class="math inline">\(\delta = -0.1\)</span> and <span class="math inline">\(n_{malaria} = n_{control} = 20\)</span></p></li>
<li><p><span class="math inline">\(\delta = -0.4\)</span> and <span class="math inline">\(n_{malaria} = n_{control} = 20\)</span></p></li>
<li><p><span class="math inline">\(\delta = -0.1\)</span> and <span class="math inline">\(n_{malaria} = n_{control} = 100\)</span></p></li>
<li><p><span class="math inline">\(\delta = -0.4\)</span> and <span class="math inline">\(n_{malaria} = n_{control} = 100\)</span></p></li>
<li><p>What can you conclude about values of <span class="math inline">\(\delta\)</span> and the sample size?</p></li>
</ol>
</li>
</ol>
<ol start="22" type="1">
<li>
<p><strong>Diabetes and unemployment.</strong> A Gallup poll surveyed Americans about their employment status and whether they have diabetes. The survey results indicate that 1.5% of the 47,774 employed (full or part time) and 2.5% of the 5,855 unemployed 18-29 year-olds have diabetes. <span class="citation" data-cites="data:employmentDiabetes">(<a href="references.html#ref-data:employmentDiabetes" role="doc-biblioref">Gallup 2012</a>)</span></p>
<ol type="a">
<li><p>Create a two-way table presenting the results of this study.</p></li>
<li><p>State appropriate hypotheses to test for difference in proportions of diabetes between employed and unemployed Americans.</p></li>
<li><p>The sample difference is about 1%. If we completed the hypothesis test, we would find that the p-value is very small (about 0), meaning the difference is statistically discernible. Use this result to explain the difference between statistically discernible and practically important findings.</p></li>
</ol>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Bottiger:2001" class="csl-entry" role="listitem">
Böttiger, B. W., C. Bode, S. Kern, A. Gries, R. Gust, R. Glätzer, H. Bauer, J. Motsch, and E. Martin. 2001. <span>“Efficacy and Safety of Thrombolytic Therapy After Initially Unsuccessful Cardiopulmonary Resuscitation: A Prospective Clinical Trial.”</span> <em>The Lancet</em> 357 (9268): 1583–85.
</div>
<div id="ref-data:sleepCAandOR" class="csl-entry" role="listitem">
CDC. 2008. <span>“Perceived Insufficient Rest or Sleep Among Adults – United States, 2008.”</span> <a href="http://www.openintro.org/redirect.php?go=textbook-Perceived_Insufficient_Rest_or_Sleep_Among_Adults">http://www.openintro.org/redirect.php?go=textbook-Perceived_Insufficient_Rest_or_Sleep_Among_Adults</a>.
</div>
<div id="ref-Datoo:2021" class="csl-entry" role="listitem">
Datoo, M. S., M. H. Natama, A. Somé, O. Traoré, T. Rouamba, D. Bellamy, P. Yameogo, et al. 2021. <span>“High Efficacy of a Low Dose Candidate Malaria Vaccine, R21 in 1 Adjuvant Matrix-m<span class="math inline">\(^{TM}\)</span>, with Seasonal Administration to Children in Burkina Faso.”</span> <em>The Lancet</em>. <a href="https://doi.org/10.1016/S0140-6736(21)00943-0">https://doi.org/10.1016/S0140-6736(21)00943-0</a>.
</div>
<div id="ref-data:employmentDiabetes" class="csl-entry" role="listitem">
Gallup. 2012. <a href="http://www.openintro.org/redirect.php?go=textbook-employed_americans_in_better_health_2012">http://www.openintro.org/redirect.php?go=textbook-employed_americans_in_better_health_2012</a>.
</div>
<div id="ref-data:gallupcollegeimpact" class="csl-entry" role="listitem">
Gallup. 2021. <span>“Half of College Students Say COVID-19 May Impact Completion.”</span> <a href="https://www.openintro.org/go?id=textbook-gallup-2021-covid-college-impact">https://www.openintro.org/go?id=textbook-gallup-2021-covid-college-impact</a>.
</div>
<div id="ref-data:KFF2019nathealthplan" class="csl-entry" role="listitem">
Kaiser Family Foundation. 2019. <a href="https://www.openintro.org/go?id=textbook-kff-2019-expand-aca-coverage">https://www.openintro.org/go?id=textbook-kff-2019-expand-aca-coverage</a>.
</div>
<div id="ref-LoSassoMedicineGenderPayGap" class="csl-entry" role="listitem">
Lo Sasso, A. T., M. R. Richards, C. F. Chou, and S. E. Gerber. 2011. <span>“The $16,819 Pay Gap for Newly Trained Physicians: The Unexplained Trend of Men Earning More Than Women.”</span> <em>Health Affairs</em> 30 (2). <a href="https://doi.org/10.1377/hlthaff.2010.0597">https://doi.org/10.1377/hlthaff.2010.0597</a>.
</div>
<div id="ref-Lockman:2007" class="csl-entry" role="listitem">
Lockman, S., R. L. Shapiro, L. M. Smeaton, C. Wester, I. Thior, L. Stevens, F. Chand, et al. 2007. <span>“Response to Antiretroviral Therapy After a Single, Peripartum Dose of Nevirapine.”</span> <em>New England Journal of Medicine</em> 356 (2): 135–47. <a href="https://doi.org/10.1056/NEJMoa062876">https://doi.org/10.1056/NEJMoa062876</a>.
</div>
<div id="ref-Manson:2019" class="csl-entry" role="listitem">
Manson, J. E., N. R. Cook, I-M. Lee, W. Christen, S. S. Bassuk, S. Mora, H. Gibson, et al. 2019. <span>“Marine n-3 Fatty Acids and Prevention of Cardiovascular Disease and Cancer.”</span> <em>New England Journal of Medicine</em> 380 (1): 23–32. <a href="https://doi.org/10.1056/NEJMoa1811403">https://doi.org/10.1056/NEJMoa1811403</a>.
</div>
<div id="ref-onlineharassment2021" class="csl-entry" role="listitem">
Pew Research Center. 2021. <span>“The State of Online Harassment, Data Collected September 8 - 13, 2020.”</span> <a href="https://www.openintro.org/go?id=textbook-pew-2021-online-harassment">https://www.openintro.org/go?id=textbook-pew-2021-online-harassment</a>.
</div>
<div id="ref-Rao:2021" class="csl-entry" role="listitem">
Rao, M., L. Bar, Y. Yu, M. Srinivasan, A. Mukherjea, J. Li, S. Chung, S. Venkatraman, S. Dan, and L. Palaniappan. 2021. <span>“Disaggregating Asian American Cigarette and Alternative Tobacco Product Use: Results from the National Health Interview Survey (NHIS) 2006–2018.”</span> <em>Journal of Racial and Ethnic Health Disparities</em>. <a href="https://doi.org/10.1007/s40615-021-01024-5">https://doi.org/10.1007/s40615-021-01024-5</a>.
</div>
<div id="ref-data:govtshuthown" class="csl-entry" role="listitem">
Survey USA. 2019. <a href="http://www.openintro.org/redirect.php?go=textbook-SurveyUSA_24568">http://www.openintro.org/redirect.php?go=textbook-SurveyUSA_24568</a>.
</div>
<div id="ref-Turnbull+Brown+Hu:1974" class="csl-entry" role="listitem">
Turnbull, B., B. Brown, and M. Hu. 1974. <span>“Survivorship of Heart Transplant Data.”</span> <em>Journal of the American Statistical Association</em> 69: 74–80. <a href="https://doi.org/10.1080/01621459.1974.10480130">https://doi.org/10.1080/01621459.1974.10480130</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p>The study is an experiment, as patients were randomly assigned an experiment group. Since this is an experiment, the results can be used to evaluate a causal relationship between blood thinner use after CPR and whether patients survived.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Because the patients were randomized, the subjects are independent, both within and between the two groups. The success-failure condition is also met for both groups as all counts are at least 10. This satisfies the conditions necessary to model the difference in proportions using a normal distribution. Compute the sample proportions <span class="math inline">\((\hat{p}_{\text{fish oil}} = 0.0112,\)</span> <span class="math inline">\(\hat{p}_{\text{placebo}} = 0.0155),\)</span> point estimate of the difference <span class="math inline">\((0.0112 - 0.0155 = -0.0043),\)</span> and standard error <span class="math inline">\(SE = \sqrt{\frac{0.0112 \times 0.9888}{12933} + \frac{0.0155 \times 0.9845}{12938}},\)</span> <span class="math inline">\(SE = 0.00145.\)</span> Next, plug the values into the general formula for a confidence interval, where we’ll use a 95% confidence level with <span class="math inline">\(z^{\star} = 1.96:\)</span> <span class="math inline">\(-0.0043 \pm 1.96 \times 0.00145 = (-0.0071, -0.0015).\)</span> We are 95% confident that fish oils decreases heart attacks by 0.15 to 0.71 percentage points (off of a baseline of about 1.55%) over a 5-year period for subjects who are similar to those in the study. Because the interval is entirely below 0, and the treatment was randomly assigned the data provide strong evidence that fish oil supplements reduce heart attacks in patients like those in the study.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>This is an experiment. Patients were randomized to receive mammograms or a standard breast cancer exam. We will be able to make causal conclusions based on this study.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p><span class="math inline">\(H_0:\)</span> the breast cancer death rate for patients screened using mammograms is the same as the breast cancer death rate for patients in the control, <span class="math inline">\(p_{MGM} - p_{C} = 0.\)</span> <span class="math inline">\(H_A:\)</span> the breast cancer death rate for patients screened using mammograms is different than the breast cancer death rate for patients in the control, <span class="math inline">\(p_{MGM} - p_{C} \neq 0.\)</span><a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>For an example of a two-proportion hypothesis test that does not require the success-failure condition to be met, see <a href="#sec-two-prop-errors" class="quarto-xref"><span>Section 17.1</span></a>.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>The <a href="http://openintrostat.github.io/openintro/reference/yawn.html"><code>yawn</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The <a href="http://openintrostat.github.io/openintro/reference/heart_transplant.html"><code>heart_transplant</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./inference-one-prop.html" class="pagination-link" aria-label="Inference for a single proportion">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference-tables.html" class="pagination-link" aria-label="Inference for two-way tables">
        <span class="nav-page-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-two-props.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>