<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="author" content="Mine Çetinkaya-Rundel and Johanna Hardin">
<title>20&nbsp; Inference for comparing two independent means – Introduction to Modern Statistics (2e)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./inference-paired-means.html" rel="next">
<link href="./inference-one-mean.html" rel="prev">
<link href="./images/openintro.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-709f5aa5aa6a95674750e60a60b86f5a.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bf77a05ce6ba3f5649b1c5bec9928afc.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-790f3f5e7e2e01ab58e527b05f631cee.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-41ebc7e69ef0285b0c3541b9cc726a5c.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script async="" src="https://hypothes.is/embed.js"></script><script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script><script src="site_libs/kePrint-0.0.1/kePrint.js"></script><link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<link href="site_libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet">
<script src="site_libs/bsTable-3.3.7/bootstrapTable.js"></script><script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
</head>
<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-two-means.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="./index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Introduction to Modern Statistics (2e)</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/openintrostat/ims/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome to IMS2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Authors</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./introduction-to-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-hello.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Hello data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Study design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Applications: Data</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./exploratory-data-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exploratory data analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-categorical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Exploring categorical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-numerical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Exploring numerical data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./explore-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Applications: Explore</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./regression-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regression modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Applications: Model</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./foundations-of-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Foundations of inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-randomization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Hypothesis testing with randomization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-bootstrapping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Confidence intervals with bootstrapping</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-mathematical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Inference with mathematical models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-errors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Decision Errors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./foundations-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Applications: Foundations</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./statistical-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistical inference</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-prop.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Inference for a single proportion</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-props.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Inference for comparing two proportions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-tables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Inference for two-way tables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-one-mean.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-two-means.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-paired-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-many-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Inference for comparing many means</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Applications: Infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./inferential-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Inferential modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-slr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Inference for linear regression with a single predictor</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-mlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Inference for linear regression with multiple predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Inference for logistic regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inf-model-applications.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Applications: Model and infer</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Exercise solutions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">References</span></span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-rand2mean" id="toc-sec-rand2mean" class="nav-link active" data-scroll-target="#sec-rand2mean"><span class="header-section-number">20.1</span> Randomization test for the difference in means</a>
  <ul class="collapse">
<li><a href="#observed-data" id="toc-observed-data" class="nav-link" data-scroll-target="#observed-data"><span class="header-section-number">20.1.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic" id="toc-variability-of-the-statistic" class="nav-link" data-scroll-target="#variability-of-the-statistic"><span class="header-section-number">20.1.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics" id="toc-observed-statistic-vs.-null-statistics" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics"><span class="header-section-number">20.1.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#bootstrap-confidence-interval-for-the-difference-in-means" id="toc-bootstrap-confidence-interval-for-the-difference-in-means" class="nav-link" data-scroll-target="#bootstrap-confidence-interval-for-the-difference-in-means"><span class="header-section-number">20.2</span> Bootstrap confidence interval for the difference in means</a>
  <ul class="collapse">
<li><a href="#observed-data-1" id="toc-observed-data-1" class="nav-link" data-scroll-target="#observed-data-1"><span class="header-section-number">20.2.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-1" id="toc-variability-of-the-statistic-1" class="nav-link" data-scroll-target="#variability-of-the-statistic-1"><span class="header-section-number">20.2.2</span> Variability of the statistic</a></li>
  </ul>
</li>
  <li>
<a href="#sec-math2samp" id="toc-sec-math2samp" class="nav-link" data-scroll-target="#sec-math2samp"><span class="header-section-number">20.3</span> Mathematical model for testing the difference in means</a>
  <ul class="collapse">
<li><a href="#observed-data-2" id="toc-observed-data-2" class="nav-link" data-scroll-target="#observed-data-2"><span class="header-section-number">20.3.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-2" id="toc-variability-of-the-statistic-2" class="nav-link" data-scroll-target="#variability-of-the-statistic-2"><span class="header-section-number">20.3.2</span> Variability of the statistic</a></li>
  <li><a href="#observed-statistic-vs.-null-statistics-1" id="toc-observed-statistic-vs.-null-statistics-1" class="nav-link" data-scroll-target="#observed-statistic-vs.-null-statistics-1"><span class="header-section-number">20.3.3</span> Observed statistic vs.&nbsp;null statistics</a></li>
  </ul>
</li>
  <li>
<a href="#mathematical-model-for-estimating-the-difference-in-means" id="toc-mathematical-model-for-estimating-the-difference-in-means" class="nav-link" data-scroll-target="#mathematical-model-for-estimating-the-difference-in-means"><span class="header-section-number">20.4</span> Mathematical model for estimating the difference in means</a>
  <ul class="collapse">
<li><a href="#observed-data-3" id="toc-observed-data-3" class="nav-link" data-scroll-target="#observed-data-3"><span class="header-section-number">20.4.1</span> Observed data</a></li>
  <li><a href="#variability-of-the-statistic-3" id="toc-variability-of-the-statistic-3" class="nav-link" data-scroll-target="#variability-of-the-statistic-3"><span class="header-section-number">20.4.2</span> Variability of the statistic</a></li>
  </ul>
</li>
  <li>
<a href="#sec-chp20-review" id="toc-sec-chp20-review" class="nav-link" data-scroll-target="#sec-chp20-review"><span class="header-section-number">20.5</span> Chapter review</a>
  <ul class="collapse">
<li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary"><span class="header-section-number">20.5.1</span> Summary</a></li>
  <li><a href="#terms" id="toc-terms" class="nav-link" data-scroll-target="#terms"><span class="header-section-number">20.5.2</span> Terms</a></li>
  </ul>
</li>
  <li><a href="#sec-chp20-exercises" id="toc-sec-chp20-exercises" class="nav-link" data-scroll-target="#sec-chp20-exercises"><span class="header-section-number">20.6</span> Exercises</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-two-means.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./statistical-inference.html">Statistical inference</a></li><li class="breadcrumb-item"><a href="./inference-two-means.html"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></a></li></ol></nav><div class="quarto-title">
<h1 class="title"><span id="sec-inference-two-means" class="quarto-section-identifier"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Inference for comparing two independent means</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><div class="chapterintro">
<p>We now extend the methods from <a href="inference-one-mean.html" class="quarto-xref">Chapter&nbsp;<span>19</span></a> to apply confidence intervals and hypothesis tests to differences in population means that come from two groups, Group 1 and Group 2: <span class="math inline">\(\mu_1 - \mu_2.\)</span></p>
<p>In our investigations, we’ll identify a reasonable point estimate of <span class="math inline">\(\mu_1 - \mu_2\)</span> based on the sample, and you may have already guessed its form: <span class="math inline">\(\bar{x}_1 - \bar{x}_2.\)</span> Then we’ll look at the inferential analysis in three different ways: using a randomization test, applying bootstrapping for interval estimates, and, if we verify that the point estimate can be modeled using a normal distribution, we compute the estimate’s standard error and apply the mathematical framework.</p>
</div>
<p>In this section we consider a difference in two population means, <span class="math inline">\(\mu_1 - \mu_2,\)</span> under the condition that the data are not paired. Just as with a single sample, we identify conditions to ensure we can use the <span class="math inline">\(t\)</span>-distribution with a point estimate of the difference, <span class="math inline">\(\bar{x}_1 - \bar{x}_2,\)</span> and a new standard error formula.</p>
<p>The details for working through inferential problems in the two independent means setting are strikingly similar to those applied to the two independent proportions setting. We first cover a randomization test where the observations are shuffled under the assumption that the null hypothesis is true. Then we bootstrap the data (with no imposed null hypothesis) to create a confidence interval for the true difference in population means, <span class="math inline">\(\mu_1 - \mu_2.\)</span> The mathematical model, here the <span class="math inline">\(t\)</span>-distribution, is able to describe both the randomization test and the bootstrapping as long as the conditions are met.</p>
<p>The inferential tools are applied to three different data contexts: determining whether stem cells can improve heart function, exploring the relationship between pregnant women’s smoking habits and birth weights of newborns, and exploring whether there is convincing evidence that one variation of an exam is harder than another variation. This section is motivated by questions like “Is there convincing evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who do not smoke?”</p>
<section id="sec-rand2mean" class="level2" data-number="20.1"><h2 data-number="20.1" class="anchored" data-anchor-id="sec-rand2mean">
<span class="header-section-number">20.1</span> Randomization test for the difference in means</h2>
<p>An instructor decided to run two slight variations of the same exam. Prior to passing out the exams, they shuffled the exams together to ensure each student received a random version. Anticipating complaints from students who took Version B, they would like to evaluate whether the difference observed in the groups is so large that it provides convincing evidence that Version B was more difficult (on average) than Version A.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/classdata.html"><code>classdata</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<section id="observed-data" class="level3" data-number="20.1.1"><h3 data-number="20.1.1" class="anchored" data-anchor-id="observed-data">
<span class="header-section-number">20.1.1</span> Observed data</h3>
<p>Summary statistics for how students performed on these two exams are shown in <a href="#tbl-summaryStatsForTwoVersionsOfExams" class="quarto-xref">Table&nbsp;<span>20.1</span></a> and plotted in <a href="#fig-boxplotTwoVersionsOfExams" class="quarto-xref">Figure&nbsp;<span>20.1</span></a>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-summaryStatsForTwoVersionsOfExams" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summaryStatsForTwoVersionsOfExams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.1: Summary statistics of scores for each exam version.
</figcaption><div aria-describedby="tbl-summaryStatsForTwoVersionsOfExams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Min</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Max</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center; width: 5em;">A</td>
<td style="text-align: center; width: 5em;">58</td>
<td style="text-align: center; width: 5em;">75.1</td>
<td style="text-align: center; width: 5em;">13.9</td>
<td style="text-align: center; width: 5em;">44</td>
<td style="text-align: center;">100</td>
</tr>
<tr class="even">
<td style="text-align: center; width: 5em;">B</td>
<td style="text-align: center; width: 5em;">55</td>
<td style="text-align: center; width: 5em;">72.0</td>
<td style="text-align: center; width: 5em;">13.8</td>
<td style="text-align: center; width: 5em;">38</td>
<td style="text-align: center;">100</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplotTwoVersionsOfExams" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Box plot of exam score broken down by version of exam.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-boxplotTwoVersionsOfExams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-boxplotTwoVersionsOfExams-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;20.1: Exam scores for students given one of two different exams."><img src="inference-two-means_files/figure-html/fig-boxplotTwoVersionsOfExams-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Box plot of exam score broken down by version of exam."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-boxplotTwoVersionsOfExams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.1: Exam scores for students given one of two different exams.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Construct hypotheses to evaluate whether the observed difference in sample means, <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1,\)</span> is likely to have happened due to chance, if the null hypothesis is true. We will later evaluate these hypotheses using <span class="math inline">\(\alpha = 0.01.\)</span><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
</div>
<div class="guidedpractice">
<p>Before moving on to evaluate the hypotheses in the previous Guided Practice, let’s think carefully about the dataset. Are the observations across the two groups independent? Are there any concerns about outliers?<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</div>
</section><section id="variability-of-the-statistic" class="level3" data-number="20.1.2"><h3 data-number="20.1.2" class="anchored" data-anchor-id="variability-of-the-statistic">
<span class="header-section-number">20.1.2</span> Variability of the statistic</h3>
<p>In <a href="foundations-randomization.html" class="quarto-xref"><span>Chapter 11</span></a>, the variability of the statistic (previously: <span class="math inline">\(\hat{p}_1 - \hat{p}_2)\)</span> was visualized after shuffling the observations across the two treatment groups many times. The shuffling process implements the null hypothesis model (that there is no effect of the treatment). In the exam example, the null hypothesis is that exam A and exam B are equally difficult, so the average scores across the two tests should be the same. If the exams were equally difficult, <em>due to natural variability</em>, we would sometimes expect students to do slightly better on exam A <span class="math inline">\((\bar{x}_A &gt; \bar{x}_B)\)</span> and sometimes expect students to do slightly better on exam B <span class="math inline">\((\bar{x}_B &gt; \bar{x}_A).\)</span> The question at hand is: does <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span> indicate that exam A is easier than exam B.</p>
<p><a href="#fig-rand2means" class="quarto-xref">Figure&nbsp;<span>20.2</span></a> shows the process of randomizing the exam to the observed exam scores. If the null hypothesis is true, then the score on each exam should represent the true student ability on that material. It shouldn’t matter whether they were given exam A or exam B. By reallocating which student got which exam, we are able to understand how the difference in average exam scores changes due only to natural variability. There is only one iteration of the randomization process in <a href="#fig-rand2means" class="quarto-xref">Figure&nbsp;<span>20.2</span></a>, leading to one simulated difference in average scores.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rand2means" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four panels representing four different orientations of a toy dataset of 9 exam scores. The first panel provides the observed data; 4 of the exams were version A and the average score was 77.25; 5 of the exams were version B and the average score was 75.8, a difference of 1.45. The second panel shows the shuffled reassignment of the exam versions (4 of the scores are randomly reassigned to A, 5 of the scores are randomly reassigned to B). The third panel shows which score is connected with which new reassigned version of the exam. And the fourth panel sorts the exams so that version A exams are together and version B exams are together. In the randomly reassigned versions, the average score for version A is 74.25 and the average score for version B is 78.2, a difference  of -3.95. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-rand2means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/rand2means.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;20.2: The version of the test (A or B) is randomly allocated to the test scores, under the null assumption that the tests are equally difficult."><img src="images/rand2means.png" class="img-fluid figure-img" style="width:75.0%" alt="Four panels representing four different orientations of a toy dataset of 9 exam scores. The first panel provides the observed data; 4 of the exams were version A and the average score was 77.25; 5 of the exams were version B and the average score was 75.8, a difference of 1.45. The second panel shows the shuffled reassignment of the exam versions (4 of the scores are randomly reassigned to A, 5 of the scores are randomly reassigned to B). The third panel shows which score is connected with which new reassigned version of the exam. And the fourth panel sorts the exams so that version A exams are together and version B exams are together. In the randomly reassigned versions, the average score for version A is 74.25 and the average score for version B is 78.2, a difference  of -3.95. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rand2means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.2: The version of the test (A or B) is randomly allocated to the test scores, under the null assumption that the tests are equally difficult.
</figcaption></figure>
</div>
</div>
</div>
<p>Building on <a href="#fig-rand2means" class="quarto-xref">Figure&nbsp;<span>20.2</span></a>, <a href="#fig-randexams" class="quarto-xref">Figure&nbsp;<span>20.3</span></a> shows the values of the simulated statistics <span class="math inline">\(\bar{x}_{1, sim} - \bar{x}_{2, sim}\)</span> over 1,000 random simulations. We see that, just by chance, the difference in scores can range anywhere from -10 points to +10 points.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-randexams" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-randexams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-randexams-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;20.3: Histogram of differences in means, calculated from 1,000 different randomizations of the exam types."><img src="inference-two-means_files/figure-html/fig-randexams-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-randexams-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.3: Histogram of differences in means, calculated from 1,000 different randomizations of the exam types.
</figcaption></figure>
</div>
</div>
</div>
</section><section id="observed-statistic-vs.-null-statistics" class="level3" data-number="20.1.3"><h3 data-number="20.1.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics">
<span class="header-section-number">20.1.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<p>The goal of the randomization test is to assess the observed data, here the statistic of interest is <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1.\)</span> The randomization distribution allows us to identify whether a difference of 3.1 points is more than one would expect by natural variability of the scores if the two tests were equally difficult. By plotting the value of 3.1 on <a href="#fig-randexamspval" class="quarto-xref">Figure&nbsp;<span>20.4</span></a>, we can measure how different or similar 3.1 is to the randomized differences which were generated under the null hypothesis.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-randexamspval" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-randexamspval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-randexamspval-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;20.4: Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value."><img src="inference-two-means_files/figure-html/fig-randexamspval-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-randexamspval-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.4: Histogram of differences in means, calculated from 1,000 different randomizations of the exam types. The observed difference of 3.1 points is plotted as a vertical line, and the area more extreme than 3.1 is shaded to represent the p-value.
</figcaption></figure>
</div>
</div>
</div>
<div class="workedexample">
<p>Approximate the p-value depicted in <a href="#fig-randexamspval" class="quarto-xref">Figure&nbsp;<span>20.4</span></a>, and provide a conclusion in the context of the case study.</p>
<hr>
<p>Using software, we can find the number of shuffled differences in means that are less than the observed difference (of 3.14) is 900 (out of 1,000 randomizations). So 10% of the simulations are larger than the observed difference. To get the p-value, we double the proportion of randomized differences which are larger than the observed difference, p-value = 0.2.</p>
<p>Previously, we specified that we would use <span class="math inline">\(\alpha = 0.01.\)</span> Since the p-value is larger than <span class="math inline">\(\alpha,\)</span> we do not reject the null hypothesis. That is, the data do not convincingly show that one exam version is more difficult than the other, and the teacher should not be convinced that they should add points to the Version B exam scores.</p>
</div>
<p>The large p-value and consistency of <span class="math inline">\(\bar{x}_A - \bar{x}_B=3.1\)</span> with the randomized differences leads us to <em>not reject the null hypothesis</em>. Said differently, there is no evidence to think that one of the tests is easier than the other. One might be inclined to conclude that the tests have the same level of difficulty, but that conclusion would be wrong. The hypothesis testing framework is set up only to reject a null claim, it is not set up to validate a null claim. As we concluded, the data are consistent with exams A and B being equally difficult, but the data are also consistent with exam A being 3.1 points “easier” than exam B. The data are not able to adjudicate on whether the exams are equally hard or whether one of them is slightly easier. Indeed, conclusions where the null hypothesis is not rejected often seem unsatisfactory. However, in this case, the teacher and class are probably all relieved that there is no evidence to demonstrate that one of the exams is more difficult than the other.</p>
</section></section><section id="bootstrap-confidence-interval-for-the-difference-in-means" class="level2" data-number="20.2"><h2 data-number="20.2" class="anchored" data-anchor-id="bootstrap-confidence-interval-for-the-difference-in-means">
<span class="header-section-number">20.2</span> Bootstrap confidence interval for the difference in means</h2>
<p></p>
<p>Before providing a full example working through a bootstrap analysis on actual data, we return to the fictional Awesome Auto example as a way to visualize the two sample bootstrap setting. Consider an expanded scenario where the research question centers on comparing the average price of a car at one Awesome Auto franchise (Group 1) to the average price of a car at a different Awesome Auto franchise (Group 2). The process of bootstrapping can be applied to <em>each</em> Group separately, and the differences of means recalculated each time. <a href="#fig-bootmeans2means" class="quarto-xref">Figure&nbsp;<span>20.5</span></a> visually describes the bootstrap process when interest is in a statistic computed on two separate samples. The analysis proceeds as in the one sample case, but now the (single) statistic of interest is the <em>difference in sample means</em>. That is, a bootstrap resample is done on each of the groups separately, but the results are combined to have a single bootstrapped difference in means. Repetition will produce <span class="math inline">\(k\)</span> bootstrapped differences in means, and the histogram will describe the natural sampling variability associated with the difference in means.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootmeans2means" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Samples are shown as separately coming from two independent, large, unknown populations. Directly from each of the two observed samples, bootstrap resamples can be taken (with replacement). Bootstrap resample 1 from sample 1 is compared to bootstrap resample 1 from sample 2 by comparing the difference in bootstrapped averages. A histogram of differences in bootstrapped averages displays the differences ranging from roughly -20000 dollars to +10000 dollars. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bootmeans2means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/bootmeans2means.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;20.5: For the two group comparison, the bootstrap resampling is done separately on each group, but the statistic is calculated as a difference. The set of k differences is then analyzed as the statistic of interest with conclusions drawn on the parameter of interest."><img src="images/bootmeans2means.png" class="img-fluid figure-img" style="width:80.0%" alt="Samples are shown as separately coming from two independent, large, unknown populations. Directly from each of the two observed samples, bootstrap resamples can be taken (with replacement). Bootstrap resample 1 from sample 1 is compared to bootstrap resample 1 from sample 2 by comparing the difference in bootstrapped averages. A histogram of differences in bootstrapped averages displays the differences ranging from roughly -20000 dollars to +10000 dollars. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootmeans2means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.5: For the two group comparison, the bootstrap resampling is done separately on each group, but the statistic is calculated as a difference. The set of k differences is then analyzed as the statistic of interest with conclusions drawn on the parameter of interest.
</figcaption></figure>
</div>
</div>
</div>
<p>In the following sections, we leave the fictional setting of Awesome Auto and apply the bootstrap method to actual datasets investigating whether embryonic stem cells help improve heart function and later to investigate characteristics of births. Note that the fictional setting allowed us to visualize the bootstrap method because we had samples of size five. The visualization was important in understanding how the bootstrap method works. However, the bootstrap relies heavily on the sample being an outstanding proxy for the population, and five observations are almost never enough to truly represent the nuances of a full population. To that end, we apply bootstrap methods with much larger sample sizes, as seen in the 1000 random samples provided in the births data.</p>
<section id="observed-data-1" class="level3" data-number="20.2.1"><h3 data-number="20.2.1" class="anchored" data-anchor-id="observed-data-1">
<span class="header-section-number">20.2.1</span> Observed data</h3>
<p>Does treatment using embryonic stem cells (ESCs) help improve heart function following a heart attack? <a href="#tbl-statsSheepEscStudy" class="quarto-xref">Table&nbsp;<span>20.2</span></a> contains summary statistics for an experiment to test ESCs in sheep that had a heart attack. Each of these sheep was randomly assigned to the ESC or control group, and the change in their hearts’ pumping capacity was measured in the study. <span class="citation" data-cites="Menard:2005">(<a href="references.html#ref-Menard:2005" role="doc-biblioref">Ménard et al. 2005</a>)</span> <a href="#fig-stem-cell-histograms" class="quarto-xref">Figure&nbsp;<span>20.8</span></a> provides histograms of the two datasets. A positive value corresponds to increased pumping capacity, which generally suggests a stronger recovery. Our goal will be to identify a 95% confidence interval for the effect of ESCs on the change in heart pumping capacity relative to the control group.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/stem_cell.html"><code>stem_cell</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<div class="cell" data-tbl-pos="H">
<div id="tbl-statsSheepEscStudy" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-statsSheepEscStudy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.2: Summary statistics of the embryonic stem cell study.
</figcaption><div aria-describedby="tbl-statsSheepEscStudy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em;">ESC</td>
<td style="text-align: center; width: 6em;">9</td>
<td style="text-align: center; width: 6em;">3.50</td>
<td style="text-align: center; width: 6em;">5.17</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em;">Control</td>
<td style="text-align: center; width: 6em;">9</td>
<td style="text-align: center; width: 6em;">-4.33</td>
<td style="text-align: center; width: 6em;">2.76</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The point estimate of the difference in the heart pumping variable is straightforward to find: it is the difference in the sample means.</p>
<p><span class="math display">\[\bar{x}_{esc} - \bar{x}_{control}\   =\ 3.50 - (-4.33)\   =\ 7.83\]</span></p>
</section><section id="variability-of-the-statistic-1" class="level3" data-number="20.2.2"><h3 data-number="20.2.2" class="anchored" data-anchor-id="variability-of-the-statistic-1">
<span class="header-section-number">20.2.2</span> Variability of the statistic</h3>
<p>As we saw in <a href="inference-two-props.html#sec-two-prop-boot-ci" class="quarto-xref"><span>Section 17.2</span></a>, we will use bootstrapping to estimate the variability associated with the difference in sample means when taking repeated samples. In a method akin to two proportions, a <em>separate</em> sample is taken with replacement from each group (here ESCs and control), the sample means are calculated, and their difference is taken. The entire process is repeated multiple times to produce a bootstrap distribution of the difference in sample means (<em>without</em> the null hypothesis assumption).</p>
<p><a href="#fig-bootexamsci" class="quarto-xref">Figure&nbsp;<span>20.6</span></a> displays the variability of the differences in means with the 90% percentile and SE confidence intevals super imposed.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bootexamsci" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histogram of differences in means after 1,000 bootstrap samples from each of the two groups. The observed difference is plotted as a black vertical line at 7.83. The blue dashed and red dotted lines provide the bootstrap percentile and boostrap SE confidence intervals, respectively, for the difference in true population means.">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bootexamsci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-bootexamsci-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;20.6: Histogram of differences in means after 1,000 bootstrap samples from each of the two groups. The observed difference is plotted as a black vertical line at 7.83. The blue dashed and red dotted lines provide the bootstrap percentile and bootstrap SE confidence intervals, respectively, for the difference in true population means."><img src="inference-two-means_files/figure-html/fig-bootexamsci-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histogram of differences in means after 1,000 bootstrap samples from each of the two groups. The observed difference is plotted as a black vertical line at 7.83. The blue dashed and red dotted lines provide the bootstrap percentile and boostrap SE confidence intervals, respectively, for the difference in true population means."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bootexamsci-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.6: Histogram of differences in means after 1,000 bootstrap samples from each of the two groups. The observed difference is plotted as a black vertical line at 7.83. The blue dashed and red dotted lines provide the bootstrap percentile and bootstrap SE confidence intervals, respectively, for the difference in true population means.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>Using the histogram of bootstrapped difference in means, estimate the standard error of the differences in sample means, <span class="math inline">\(\bar{x}_{ESC} - \bar{x}_{Control}.\)</span><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
</div>
<div class="workedexample">
<p>Choose one of the bootstrap confidence intervals for the true difference in average pumping capacity, <span class="math inline">\(\mu_{ESC} - \mu_{Control}.\)</span> Does the interval show that there is a difference across the two treatments?</p>
<hr>
<p>Because neither of the 90% intervals (either percentile or SE) above overlap zero (note that zero is never one of the bootstrapped differences so 95% and 99% intervals would have given the same conclusion!), we conclude that the ESC treatment is substantially better with respect to heart pumping capacity than the control.</p>
<p>Because the study is a randomized controlled experiment, we can conclude that it is the treatment (ESC) which is causing the change in pumping capacity.</p>
</div>
</section></section><section id="sec-math2samp" class="level2" data-number="20.3"><h2 data-number="20.3" class="anchored" data-anchor-id="sec-math2samp">
<span class="header-section-number">20.3</span> Mathematical model for testing the difference in means</h2>
<p>Every year, the US releases to the public a large dataset containing information on births recorded in the country. This dataset has been of interest to medical researchers who are studying the relation between habits and practices of expectant mothers and the birth of their children. We will work with a random sample of 1,000 cases from the dataset released in 2014.</p>
<div class="data">
<p>The <a href="http://openintrostat.github.io/openintro/reference/births14.html"><code>births14</code></a> data can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.</p>
</div>
<section id="observed-data-2" class="level3" data-number="20.3.1"><h3 data-number="20.3.1" class="anchored" data-anchor-id="observed-data-2">
<span class="header-section-number">20.3.1</span> Observed data</h3>
<p>Four cases from this dataset are represented in <a href="#tbl-babySmokeDF" class="quarto-xref">Table&nbsp;<span>20.3</span></a>. We are particularly interested in two variables: <code>weight</code> and <code>smoke</code>. The <code>weight</code> variable represents the weights of the newborns and the <code>smoke</code> variable describes which mothers smoked during pregnancy.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-babySmokeDF" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-babySmokeDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.3: Four cases from the <code>births14</code> dataset. The empty cells indicate missing data.
</figcaption><div aria-describedby="tbl-babySmokeDF-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">fage</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">mage</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">weeks</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">visits</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">gained</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">weight</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">habit</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">34</td>
<td style="text-align: center;">34</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">14</td>
<td style="text-align: left;">28</td>
<td style="text-align: center;">6.96</td>
<td style="text-align: center;">male</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
<tr class="even">
<td style="text-align: center;">36</td>
<td style="text-align: center;">31</td>
<td style="text-align: center;">41</td>
<td style="text-align: center;">12</td>
<td style="text-align: left;">41</td>
<td style="text-align: center;">8.86</td>
<td style="text-align: center;">female</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
<tr class="odd">
<td style="text-align: center;">37</td>
<td style="text-align: center;">36</td>
<td style="text-align: center;">37</td>
<td style="text-align: center;">10</td>
<td style="text-align: left;">28</td>
<td style="text-align: center;">7.51</td>
<td style="text-align: center;">female</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
<tr class="even">
<td style="text-align: center;"></td>
<td style="text-align: center;">16</td>
<td style="text-align: center;">38</td>
<td style="text-align: center;"></td>
<td style="text-align: left;">29</td>
<td style="text-align: center;">6.19</td>
<td style="text-align: center;">male</td>
<td style="text-align: left;">nonsmoker</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We would like to know, is there convincing evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who do not smoke? We will use data from this sample to try to answer this question.</p>
<div class="workedexample">
<p>Set up appropriate hypotheses to evaluate whether there is a relationship between a mother smoking and average birth weight.</p>
<hr>
<p>The null hypothesis represents the case of no difference between the groups.</p>
<ul>
<li>
<span class="math inline">\(H_0:\)</span> There is no difference in average birth weight for newborns from mothers who did and did not smoke. In statistical notation: <span class="math inline">\(\mu_{n} - \mu_{s} = 0,\)</span> where <span class="math inline">\(\mu_{n}\)</span> represents non-smoking mothers and <span class="math inline">\(\mu_s\)</span> represents mothers who smoked.</li>
<li>
<span class="math inline">\(H_A:\)</span> There is some difference in average newborn weights from mothers who did and did not smoke <span class="math inline">\((\mu_{n} - \mu_{s} \neq 0).\)</span>
</li>
</ul>
</div>
<p><a href="#tbl-births14-summary-stats" class="quarto-xref">Table&nbsp;<span>20.4</span></a> displays sample statistics from the data. We can see that the average birth weight of babies born to smoker moms is lower than those born to nonsmoker moms.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-births14-summary-stats" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-births14-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.4: Summary statistics for the <code>births14</code> dataset.
</figcaption><div aria-describedby="tbl-births14-summary-stats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Habit</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 7em;">nonsmoker</td>
<td style="text-align: center; width: 7em;">867</td>
<td style="text-align: center; width: 7em;">7.27</td>
<td style="text-align: center; width: 7em;">1.23</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 7em;">smoker</td>
<td style="text-align: center; width: 7em;">114</td>
<td style="text-align: center; width: 7em;">6.68</td>
<td style="text-align: center; width: 7em;">1.60</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section><section id="variability-of-the-statistic-2" class="level3" data-number="20.3.2"><h3 data-number="20.3.2" class="anchored" data-anchor-id="variability-of-the-statistic-2">
<span class="header-section-number">20.3.2</span> Variability of the statistic</h3>
<p>We check the two conditions necessary to model the difference in sample means using the <span class="math inline">\(t\)</span>-distribution.</p>
<ul>
<li>Because the data come from a simple random sample, the observations are independent, both within and between samples.</li>
<li>With both groups over 30 observations, we inspect the data in <a href="#fig-babySmokePlotOfTwoGroupsToExamineSkew" class="quarto-xref">Figure&nbsp;<span>20.7</span></a> for any particularly extreme outliers and find none.</li>
</ul>
<p>Since both conditions are satisfied, the difference in sample means may be modeled using a <span class="math inline">\(t\)</span>-distribution.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-babySmokePlotOfTwoGroupsToExamineSkew" class="quarto-float quarto-figure quarto-figure-center anchored" alt="The left panel represents birth weights for infants whose mothers smoked during pregnancy. The right panel represents the birth weights for infants whose mothers who did not smoke during pregnancy. ">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-babySmokePlotOfTwoGroupsToExamineSkew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-babySmokePlotOfTwoGroupsToExamineSkew-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;20.7: The left panel represents birth weights for infants whose mothers smoked during pregnancy. The right panel represents the birth weights for infants whose mothers who did not smoke during pregnancy."><img src="inference-two-means_files/figure-html/fig-babySmokePlotOfTwoGroupsToExamineSkew-1.png" class="img-fluid figure-img" style="width:100.0%" alt="The left panel represents birth weights for infants whose mothers smoked during pregnancy. The right panel represents the birth weights for infants whose mothers who did not smoke during pregnancy. "></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-babySmokePlotOfTwoGroupsToExamineSkew-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.7: The left panel represents birth weights for infants whose mothers smoked during pregnancy. The right panel represents the birth weights for infants whose mothers who did not smoke during pregnancy.
</figcaption></figure>
</div>
</div>
</div>
<div class="guidedpractice">
<p>The summary statistics in <a href="#tbl-births14-summary-stats" class="quarto-xref">Table&nbsp;<span>20.4</span></a> may be useful for this Guided Practice. What is the point estimate of the population difference, <span class="math inline">\(\mu_{n} - \mu_{s}\)</span>?<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
</div>
</section><section id="observed-statistic-vs.-null-statistics-1" class="level3" data-number="20.3.3"><h3 data-number="20.3.3" class="anchored" data-anchor-id="observed-statistic-vs.-null-statistics-1">
<span class="header-section-number">20.3.3</span> Observed statistic vs.&nbsp;null statistics</h3>
<div class="important">
<p><strong>The test statistic for comparing two means is a T.</strong></p>
<p> </p>
<p>The T score is a ratio of how the groups differ as compared to how the observations within a group vary.</p>
<p><span class="math display">\[T = \frac{(\bar{x}_1 - \bar{x}_2) - 0}{\sqrt{s_1^2/n_1 + s_2^2/n_2}}\]</span></p>
<p>When the null hypothesis is true and the conditions are met, T has a t-distribution with <span class="math inline">\(df = min(n_1 - 1, n_2 -1).\)</span></p>
<p>Conditions:</p>
<ul>
<li>Independent observations within and between groups.</li>
<li>Large samples and no extreme outliers.</li>
</ul>
</div>
<div class="guidedpractice">
<p>Compute the standard error of the point estimate for the average difference between the weights of babies born to nonsmoker and smoker mothers.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
</div>
<div class="workedexample">
<p>Complete the hypothesis test started in the previous Example and Guided Practice on <code>births14</code> dataset and research question. Use a discernibility level of <span class="math inline">\(\alpha=0.05.\)</span> For reference, <span class="math inline">\(\bar{x}_{n} - \bar{x}_{s} = 0.59,\)</span> <span class="math inline">\(SE = 0.16,\)</span> and the sample sizes were <span class="math inline">\(n_n = 867\)</span> and <span class="math inline">\(n_s = 114.\)</span></p>
<hr>
<p>We can find the test statistic for this test using the previous information:</p>
<p><span class="math display">\[T = \frac{\ 0.59 - 0\ }{0.16} = 3.69\]</span></p>
<p>We find the single tail area using software. We’ll use the smaller of <span class="math inline">\(n_n - 1 = 866\)</span> and <span class="math inline">\(n_s - 1 = 113\)</span> as the degrees of freedom: <span class="math inline">\(df = 113.\)</span> The one tail area is roughly 0.00017; doubling this value gives the two-tail area and p-value, 0.00034.</p>
<p>The p-value is smaller than the discernibility level, 0.05, so we reject the null hypothesis. The data provide statistically discernible evidence of a difference in the average weights of babies born to mothers who smoked during pregnancy and those who did not.</p>
</div>
<p>This result is likely not surprising. We all know that smoking is bad for you and you’ve probably also heard that smoking during pregnancy is not just bad for the mother but also for the baby as well. In fact, some in the tobacco industry actually had the audacity to tout that as a <em>benefit</em> of smoking:</p>
<blockquote class="blockquote">
<p><em>It’s true. The babies born from women who smoke are smaller, but they’re just as healthy as the babies born from women who do not smoke. And some women would prefer having smaller babies.</em> - Joseph Cullman, Philip Morris’ Chairman of the Board on CBS’ <em>Face the Nation</em>, Jan 3, 1971</p>
</blockquote>
<p>Furthermore, health differences between babies born to mothers who smoke and those who do not are not limited to weight differences.<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a></p>
<p>A small note on the power of the independent t-test (recall the discussion of power in <a href="foundations-errors.html#sec-pow" class="quarto-xref"><span>Section 14.4</span></a>). It turns out that the independent t-test given here is often less powerful than the paired t-test discussed in <a href="inference-paired-means.html#sec-mathpaired" class="quarto-xref"><span>Section 21.3</span></a>. That said, depending on how the data are collected, we don’t always have a mechanism for pairing the data and reducing the inherent variability across observations.</p>
</section></section><section id="mathematical-model-for-estimating-the-difference-in-means" class="level2" data-number="20.4"><h2 data-number="20.4" class="anchored" data-anchor-id="mathematical-model-for-estimating-the-difference-in-means">
<span class="header-section-number">20.4</span> Mathematical model for estimating the difference in means</h2>
<section id="observed-data-3" class="level3" data-number="20.4.1"><h3 data-number="20.4.1" class="anchored" data-anchor-id="observed-data-3">
<span class="header-section-number">20.4.1</span> Observed data</h3>
<p>As with hypothesis testing, for the question of whether we can model the difference using a <span class="math inline">\(t\)</span>-distribution, we’ll need to check new conditions. Like the 2-proportion cases, we will require a more robust version of independence so we are confident the two groups are also independent. Secondly, we also check for normality in each group separately, which in practice is a check for outliers.</p>
<p></p>
<div class="important">
<p><strong>Using the</strong> <span class="math inline">\(t\)</span><strong>-distribution for a difference in means.</strong></p>
<p>The <span class="math inline">\(t\)</span>-distribution can be used for inference when working with the standardized difference of two means if</p>
<ul>
<li>
<em>Independence</em> (extended). The data are independent within and between the two groups, e.g., the data come from independent random samples or from a randomized experiment.</li>
<li>
<em>Normality</em>. We check the outliers for each group separately.</li>
</ul>
<p>The standard error may be computed as </p>
<p><span class="math display">\[SE = \sqrt{\frac{\sigma_1^2}{n_1} + \frac{\sigma_2^2}{n_2}}\]</span></p>
<p>The official formula for the degrees of freedom is quite complex and is generally computed using software, so instead you may use the smaller of <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> for the degrees of freedom if software isn’t readily available.</p>
</div>
<p>Recall that the margin of error is defined by the standard error. The margin of error for <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span> can be directly obtained from <span class="math inline">\(SE(\bar{x}_1 - \bar{x}_2).\)</span></p>
<div class="important">
<p><strong>Margin of error for</strong> <span class="math inline">\(\bar{x}_1 - \bar{x}_2.\)</span></p>
<p>The margin of error is <span class="math inline">\(t^\star_{df} \times \sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\)</span> where <span class="math inline">\(t^\star_{df}\)</span> is calculated from a specified percentile on the t-distribution with <em>df</em> degrees of freedom.</p>
</div>
</section><section id="variability-of-the-statistic-3" class="level3" data-number="20.4.2"><h3 data-number="20.4.2" class="anchored" data-anchor-id="variability-of-the-statistic-3">
<span class="header-section-number">20.4.2</span> Variability of the statistic</h3>
<p></p>
<div class="workedexample">
<p>Can the <span class="math inline">\(t\)</span>-distribution be used to make inference using the point estimate, <span class="math inline">\(\bar{x}_{esc} - \bar{x}_{control} = 7.83\)</span>?</p>
<hr>
<p>First, we check for independence. Because the sheep were randomized into the groups, independence within and between groups is satisfied.</p>
<p><a href="#fig-stem-cell-histograms" class="quarto-xref">Figure&nbsp;<span>20.8</span></a> does not reveal any clear outliers in either group. (The ESC group does look a bit more variable, but this is not the same as having clear outliers.)</p>
<p>With both conditions met, we can use the <span class="math inline">\(t\)</span>-distribution to model the difference of sample means.</p>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stem-cell-histograms" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Histograms for the difference in heart pumping function after a heart attack for both the treatment group (ESC, which received the embryonic stem cell treatment) and the control group (which did not receive the treatment).">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-stem-cell-histograms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="inference-two-means_files/figure-html/fig-stem-cell-histograms-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;20.8: Histograms for the difference in heart pumping function after a heart attack for both the treatment group (ESC, which received the embryonic stem cell treatment) and the control group (which did not receive the treatment)."><img src="inference-two-means_files/figure-html/fig-stem-cell-histograms-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Histograms for the difference in heart pumping function after a heart attack for both the treatment group (ESC, which received the embryonic stem cell treatment) and the control group (which did not receive the treatment)."></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stem-cell-histograms-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;20.8: Histograms for the difference in heart pumping function after a heart attack for both the treatment group (ESC, which received the embryonic stem cell treatment) and the control group (which did not receive the treatment).
</figcaption></figure>
</div>
</div>
</div>
<p>Generally, we use statistical software to find the appropriate degrees of freedom, or if software isn’t available, we can use the smaller of <span class="math inline">\(n_1 - 1\)</span> and <span class="math inline">\(n_2 - 1\)</span> for the degrees of freedom, e.g., if using a <span class="math inline">\(t\)</span>-table to find tail areas. For transparency in the Examples and Guided Practice, we’ll use the latter approach for finding <span class="math inline">\(df\)</span>; in the case of the ESC example, this means we’ll use <span class="math inline">\(df = 8.\)</span></p>
<div class="workedexample">
<p>Calculate a 95% confidence interval for the effect of ESCs on the change in heart pumping capacity of sheep after they’ve suffered a heart attack.</p>
<hr>
<p>We will use the sample difference and the standard error that we computed earlier:</p>
<p><span class="math display">\[
\begin{aligned}
\bar{x}_{esc} - \bar{x}_{control} &amp;= 7.83 \\
SE &amp;= \sqrt{\frac{5.17^2}{9} + \frac{2.76^2}{9}} = 1.95
\end{aligned}
\]</span></p>
<p>Using <span class="math inline">\(df = 8,\)</span> we can identify the critical value of <span class="math inline">\(t^{\star}_{8} = 2.31\)</span> for a 95% confidence interval. Finally, we can enter the values into the confidence interval formula:</p>
<p><span class="math display">\[
\begin{aligned}
\text{point estimate} \ &amp;\pm\ t^{\star} \times SE \\
7.83 \ &amp;\pm\ 2.31\times 1.95 \\
(3.32 \ &amp;, \ 12.34)
\end{aligned}
\]</span></p>
<p>We are 95% confident that the heart pumping function in sheep that received embryonic stem cells is between 3.32% and 12.34% higher than for sheep that did not receive the stem cell treatment.</p>
</div>
</section></section><section id="sec-chp20-review" class="level2" data-number="20.5"><h2 data-number="20.5" class="anchored" data-anchor-id="sec-chp20-review">
<span class="header-section-number">20.5</span> Chapter review</h2>
<section id="summary" class="level3" data-number="20.5.1"><h3 data-number="20.5.1" class="anchored" data-anchor-id="summary">
<span class="header-section-number">20.5.1</span> Summary</h3>
<p>In this chapter we extended the single mean inferential methods to questions of differences in means. You may have seen parallels from the chapters that extended a single proportion (<a href="inference-one-prop.html" class="quarto-xref">Chapter&nbsp;<span>16</span></a>) to differences in proportions (<a href="inference-two-props.html" class="quarto-xref">Chapter&nbsp;<span>17</span></a>). When considering differences in sample means (indeed, when considering many quantitative statistics), we use the t-distribution to describe the sampling distribution of the T score (the standardized difference in sample means). Ideas of confidence level and type of error which might occur from a hypothesis test conclusion are similar to those seen in other chapters (see <a href="foundations-errors.html" class="quarto-xref">Chapter&nbsp;<span>14</span></a>).</p>
</section><section id="terms" class="level3" data-number="20.5.2"><h3 data-number="20.5.2" class="anchored" data-anchor-id="terms">
<span class="header-section-number">20.5.2</span> Terms</h3>
<p>The terms introduced in this chapter are presented in <a href="#tbl-terms-chp-20" class="quarto-xref">Table&nbsp;<span>20.5</span></a>. If you’re not sure what some of these terms mean, we recommend you go back in the text and review their definitions. You should be able to easily spot them as <strong>bolded text</strong>.</p>
<div class="cell" data-tbl-pos="H">
<div id="tbl-terms-chp-20" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-pos="H">
<figure class="quarto-float quarto-float-tbl figure"><figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-terms-chp-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;20.5: Terms introduced in this chapter.
</figcaption><div aria-describedby="tbl-terms-chp-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table table-striped table-condensed do-not-create-environment cell caption-top table-sm small"><tbody>
<tr class="odd">
<td style="text-align: left; width: 12em;">difference in means</td>
<td style="text-align: left; width: 12em;">SE difference in means</td>
<td style="text-align: left; width: 12em;">t-CI</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 12em;">point estimate</td>
<td style="text-align: left; width: 12em;">T score</td>
<td style="text-align: left; width: 12em;">t-test</td>
</tr>
</tbody></table>
</div>
</div>
</figure>
</div>
</div>
</section></section><section id="sec-chp20-exercises" class="level2" data-number="20.6"><h2 data-number="20.6" class="anchored" data-anchor-id="sec-chp20-exercises">
<span class="header-section-number">20.6</span> Exercises</h2>
<p>Answers to odd-numbered exercises can be found in <a href="exercise-solutions.html#sec-exercise-solutions-20" class="quarto-xref">Appendix&nbsp;<span>A.20</span></a>.</p>
<div class="exercises">
<ol type="1">
<li>
<p><strong>Experimental baker.</strong> A baker working on perfecting their bagel recipe is experimenting with active dry (AD) and instant (I) yeast. They bake a dozen bagels with each type of yeast and score each bagel on a scale of 1 to 10 on how well the bagels rise. They come up with the following set of hypotheses for evaluating whether there is a difference in the average rise of bagels baked with active dry and instant yeast. What is wrong with the hypotheses as stated?</p>
<p><span class="math display">\[H_0: \bar{x}_{AD} \leq \bar{x}_{I} \quad \quad H_A: \bar{x}_{AD} &gt; \bar{x}_{I}\]</span></p>
</li>
</ol>
<ol start="2" type="1">
<li>
<strong>Fill in the blanks.</strong> We use a ___ to evaluate if data provide convincing evidence of a difference between two population means and we use a ___ to estimate this difference.</li>
</ol>
<ol start="3" type="1">
<li>
<p><strong>Diamonds, randomization test.</strong> The prices of diamonds go up as the carat weight increases, but the increase is not smooth. For example, the difference between the size of a 0.99 carat diamond and a 1 carat diamond is undetectable to the naked human eye, but the price of a 1 carat diamond tends to be much higher than the price of a 0.99 carat diamond. We have two random samples of diamonds: 23 0.99 carat diamonds and 23 1 carat diamonds. In order to be able to compare equivalent units, we first divide the price for each diamond by 100 times its weight in carats. That is, for a 0.99 carat diamond, we divide the price by 99 and for a 1 carat diamond, we divide it by 100. Then, we randomize the carat weight to the price values in order simulate the null distribution of differences in average prices of 0.99 carat and 1 carat diamonds. The null distribution (with 1,000 randomized differences) is shown below and depicts the distribution of differences in sample means (of price per carat) if there really was no difference in the population from which these diamonds came.<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a> <span class="citation" data-cites="ggplot2">(<a href="references.html#ref-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-means_files/figure-html/unnamed-chunk-7-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="inference-two-means_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<p>Using the randomization distribution, conduct a hypothesis test to evaluate if there is a difference between the prices per carat of diamonds that weigh 0.99 carats and diamonds that weigh 1 carat. Make sure to state your hypotheses clearly and interpret your results in context of the data. <span class="citation" data-cites="ggplot2">(<a href="references.html#ref-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span></p>
</li>
</ol>
<ol start="4" type="1">
<li>
<p><strong>Lizards running, randomization test.</strong> In order to assess physiological characteristics of common lizards, data on top speeds (in m/sec) measured on a laboratory race track for two species of lizards: Western fence lizard (Sceloporus occidentalis) and Sagebrush lizard (Sceloporus graciosus). The original observed difference in lizard speeds is <span class="math inline">\(\bar{x}_{Western fence} - \bar{x}_{Sagebrush} = 0.7 \mbox{m/sec}.\)</span> The histogram below shows the distribution of average differences when speed has been randomly allocated across lizard species 1,000 times. Using the randomization distribution, conduct a hypothesis test to evaluate if there is a difference between the average speed of the Western fence lizard as compared to the Sagebrush lizard. Make sure to state your hypotheses clearly and interpret your results in context of the data.<a href="#fn8" class="footnote-ref" id="fnref8" role="doc-noteref"><sup>8</sup></a> <span class="citation" data-cites="Adolph:1987">(<a href="references.html#ref-Adolph:1987" role="doc-biblioref">Adolph 1987</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-means_files/figure-html/unnamed-chunk-8-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="inference-two-means_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
</li>
</ol>
<ol start="5" type="1">
<li>
<p><strong>Diamonds, bootstrap interval.</strong> We have data on two random samples of diamonds: 23 0.99 carat diamonds and 23 1 carat diamonds. Provided below is a histogram of bootstrap differences in means of price per carat of diamonds that weigh 0.99 carats and diamonds that weigh 1 carat. <span class="citation" data-cites="ggplot2">(<a href="references.html#ref-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-means_files/figure-html/unnamed-chunk-9-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11"><img src="inference-two-means_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap distribution, create a (rough) 95% bootstrap percentile confidence interval for the true population difference in prices per carat of diamonds that weigh 0.99 carats and 1 carat.</p></li>
<li><p>Using the bootstrap distribution, create a (rough) 95% bootstrap SE confidence interval for the true population difference in prices per carat of diamonds that weigh 0.99 carats and 1 carat. Note that the standard error of the bootstrap distribution is 4.64.</p></li>
</ol>
</li>
</ol>
<ol start="6" type="1">
<li>
<p><strong>Lizards running, bootstrap interval.</strong> We have data on top speeds (in m/sec) measured on a laboratory race track for two species of lizards: Western fence lizard (Sceloporus occidentalis) and Sagebrush lizard (Sceloporus graciosus). The bootstrap distribution below describes the variability of difference in means captured from 1,000 bootstrap samples of the lizard data. <span class="citation" data-cites="Adolph:1987">(<a href="references.html#ref-Adolph:1987" role="doc-biblioref">Adolph 1987</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure"><p><a href="inference-two-means_files/figure-html/unnamed-chunk-10-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12"><img src="inference-two-means_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" style="width:90.0%"></a></p>
</figure>
</div>
</div>
</div>
<ol type="a">
<li><p>Using the bootstrap distribution, create a (rough) 90% percentile bootrap confidence interval for the true population difference in average speed of the Western fence lizard as compared with Sagebrush lizard.</p></li>
<li><p>Using the bootstrap distribution, create a (rough) 90% bootstrap SE confidence interval for the true population difference in average speed of the Western fence lizard as compared with Sagebrush lizard.</p></li>
</ol>
</li>
</ol>
<ol start="7" type="1">
<li>
<strong>Weight loss.</strong> You are reading an article in which the researchers have created a 95% confidence interval for the difference in average weight loss for two diets. They are 95% confident that the true difference in average weight loss over 6 months for the two diets is somewhere between (1 lb, 25 lbs). The authors claim that, “therefore diet A (<span class="math inline">\(\bar{x}_A\)</span> = 20 lbs average loss) results in a much larger average weight loss as compared to diet B (<span class="math inline">\(\bar{x}_B\)</span> = 7 lbs average loss).” Comment on the authors’ claim.</li>
</ol>
<ol start="8" type="1">
<li>
<p><strong>Possible randomized means.</strong> Data were collected on data from two groups (A and B). There were 3 measurements taken on Group A and two measurements in Group B.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Group</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Measurement 1</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Measurement 2</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Measurement 3</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">B</td>
<td style="text-align: center;">7</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If the data are (repeatedly) randomly allocated across the two conditions, provide the following: (1) the values which are assigned to group A, (2) the values which are assigned to group B, and (3) the difference in averages <span class="math inline">\((\bar{x}_A - \bar{x}_B)\)</span> for each of the following:</p>
<ol type="a">
<li><p>When the randomized difference in averages is as large as possible.</p></li>
<li><p>When the randomized difference in averages is as small as possible (a big in magnitude negative number).</p></li>
<li><p>When the randomized difference in averages is as close to zero as possible.</p></li>
<li><p>When the observed values are randomly assigned to the two groups, to which of the previous parts would you expect the difference in means to fall closest? Explain your reasoning.</p></li>
</ol>
</li>
</ol>
<ol start="9" type="1">
<li>
<p><strong>Diamonds, mathematical test.</strong> We have data on two random samples of diamonds: one with diamonds that weigh 0.99 carats and one with diamonds that weigh 1 carat. Each sample has 23 diamonds. Sample statistics for the price per carat of diamonds in each sample are provided below. Conduct a hypothesis test using a mathematical model to evaluate if there is a difference between the prices per carat of diamonds that weigh 0.99 carats and diamonds that weigh 1 carat Make sure to state your hypotheses clearly, check relevant conditions, and interpret your results in context of the data. <span class="citation" data-cites="ggplot2">(<a href="references.html#ref-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span></p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 5em;">0.99 carats</td>
<td style="text-align: center; width: 3em;">$44.51</td>
<td style="text-align: center; width: 3em;">$13.32</td>
<td style="text-align: center; width: 2em;">23</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 5em;">1 carat</td>
<td style="text-align: center; width: 3em;">$57.20</td>
<td style="text-align: center; width: 3em;">$18.19</td>
<td style="text-align: center; width: 2em;">23</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inference-two-means_files/figure-html/unnamed-chunk-12-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13"><img src="inference-two-means_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid"></a></p>
</div>
</div>
</div>
</li>
</ol>
<ol start="10" type="1">
<li><p><strong>A/B testing.</strong> A/B testing is a user experience research methodology where two variants of a page are shown to users at random. A company wants to evaluate whether users will spend more time, on average, on Page A or Page B using an A/B test. Two user experience designers at the company, Lucie and Müge, are tasked with conducting the analysis of the data collected. They agree on how the null hypothesis should be set: on average, users spend the same amount of time on Page A and Page B. Lucie believes that Page B will provide a better experience for users and hence wants to use a one-tailed test, Müge believes that a two-tailed test would be a better choice. Which designer do you agree with, and why?</p></li>
<li>
<p><strong>Diamonds, mathematical interval.</strong> We have data on two random samples of diamonds: one with diamonds that weigh 0.99 carats and one with diamonds that weigh 1 carat. Each sample has 23 diamonds. Sample statistics for the price per carat of diamonds in each sample are provided below. Assuming that the conditions for conducting inference using a mathematical model are satisfied, construct a 95% confidence interval for the true population difference in prices per carat of diamonds that weigh 0.99 carats and 1 carat. <span class="citation" data-cites="ggplot2">(<a href="references.html#ref-ggplot2" role="doc-biblioref">Wickham 2016</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 6em;">0.99 carats</td>
<td style="text-align: center; width: 6em;">$44.51</td>
<td style="text-align: center; width: 6em;">$13.32</td>
<td style="text-align: center; width: 6em;">23</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 6em;">1 carat</td>
<td style="text-align: center; width: 6em;">$57.20</td>
<td style="text-align: center; width: 6em;">$18.19</td>
<td style="text-align: center; width: 6em;">23</td>
</tr>
</tbody>
</table>
</div>
</div>
</li>
</ol>
<ol start="12" type="1">
<li>
<p><strong>True / False: comparing means.</strong> Determine if the following statements are true or false, and explain your reasoning for statements you identify as false.</p>
<ol type="a">
<li><p>As the degrees of freedom increases, the <span class="math inline">\(t\)</span>-distribution approaches normality.</p></li>
<li><p>If a 95% confidence interval for the difference between two population means contains 0, a 99% confidence interval calculated based on the same two samples will also contain 0.</p></li>
<li><p>If a 95% confidence interval for the difference between two population means contains 0, a 90% confidence interval calculated based on the same two samples will also contain 0.</p></li>
</ol>
</li>
<li>
<p><strong>Difference of means.</strong> We collect two random samples from two different populations In each part below, consider the sample means <span class="math inline">\(\bar{x}_1\)</span> and <span class="math inline">\(\bar{x}_2\)</span> that we might observe from these two samples.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Standard deviation</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Sample size</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Population 1</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">50</td>
</tr>
<tr class="even">
<td style="text-align: left;">Population 2</td>
<td style="text-align: center;">20</td>
<td style="text-align: center;">10</td>
<td style="text-align: center;">30</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="a">
<li><p>What is the associated mean and standard deviation of <span class="math inline">\(\bar{x}_1\)</span>?</p></li>
<li><p>What is the associated mean and standard deviation of <span class="math inline">\(\bar{x}_2\)</span>?</p></li>
<li><p>Calculate and interpret the mean and standard deviation associated with the difference in sample means for the two groups, <span class="math inline">\(\bar{x}_2 - \bar{x}_1\)</span>.</p></li>
<li><p>How are the standard deviations from parts (a), (b), and (c) related?</p></li>
</ol>
</li>
</ol>
<ol start="14" type="1">
<li>
<strong>Mindfulness intervention for nurses.</strong> In order to address extremely challenging and stressful situations for intensive care unit nurses, researchers ran a mindfulness-based intervention (MBI) study on 60 nurses working in three hospitals in El-Beheira, Egypt. The participants were randomly allocated to one of the two groups: the treatment group (MBI) received 8 MBI sessions and the control group received no intervention. The nurses’ emotional exhaustion was measured using 9 items from a questionnaire of the Maslach Burnout Inventory-Human Services Survey for Medical Personnel; the questions are recorded on a Likert scale where 0 indicated “Never” and 6 indicates “Every day”. Nurses in the treatment group had an emotional exhaustion score of 15.47, with a standard deviation of 4.44, and nurses in the control group had an emotional exhaustion score of 32.43, with a standard deviation of 8.87. Do these data provide convincing evidence that the emotional exhaustion decrease is different for the patients in the treatment group compared to the control group? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Othman:2023">(<a href="references.html#ref-Othman:2023" role="doc-biblioref">Othman, Hassan, and Mohamed 2023</a>)</span>
</li>
</ol>
<ol start="15" type="1">
<li>
<p><strong>Chicken diet: horsebean vs.&nbsp;linseed.</strong> Chicken farming is a multi-billion dollar industry, and any methods that increase the growth rate of young chicks can reduce consumer costs while increasing company profits, possibly by millions of dollars. An experiment was conducted to measure and compare the effectiveness of various feed supplements on the growth rate of chickens. Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. In this exercise we consider chicks that were fed horsebean and linseed. Below are some summary statistics from this dataset along with box plots showing the distribution of weights by feed type.<a href="#fn9" class="footnote-ref" id="fnref9" role="doc-noteref"><sup>9</sup></a> <span class="citation" data-cites="data:chickwts">(<a href="references.html#ref-data:chickwts" role="doc-biblioref">McNeil 1977</a>)</span></p>
<div class="cell quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Horsebean</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Linseed</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">160.2</td>
<td style="text-align: right;">218.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">SD</td>
<td style="text-align: right;">38.6</td>
<td style="text-align: right;">52.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: right;">10.0</td>
<td style="text-align: right;">12.0</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><a href="inference-two-means_files/figure-html/unnamed-chunk-15-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14"><img src="inference-two-means_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid"></a></p>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: center;">
<p><a href="inference-two-means_files/figure-html/unnamed-chunk-15-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15"><img src="inference-two-means_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid"></a></p>
</div>
</div>
</div>
<ol type="a">
<li><p>Describe the distributions of weights of chickens that were fed horsebean and linseed.</p></li>
<li><p>Do these data provide strong evidence that the average weights of chickens that were fed linseed and horsebean are different? Use a 5% discernibility level.</p></li>
<li><p>What type of error might we have committed? Explain.</p></li>
<li><p>Would your conclusion change if we used <span class="math inline">\(\alpha = 0.01\)</span>?</p></li>
</ol>
</li>
</ol>
<ol start="16" type="1">
<li>
<p><strong>Fuel efficiency in the city.</strong> Each year the US Environmental Protection Agency (EPA) releases fuel economy data on cars manufactured in that year. Below are summary statistics on fuel efficiency (in miles/gallon) from random samples of cars with manual and automatic transmissions manufactured in 2021. Do these data provide strong evidence of a difference between the average fuel efficiency of cars with manual and automatic transmissions in terms of their average city mileage?<a href="#fn10" class="footnote-ref" id="fnref10" role="doc-noteref"><sup>10</sup></a> <span class="citation" data-cites="data:epa2021">(<a href="references.html#ref-data:epa2021" role="doc-biblioref">US DOE EPA 2021</a>)</span></p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">CITY</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Automatic</td>
<td style="text-align: center;">17.4</td>
<td style="text-align: center;">3.44</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manual</td>
<td style="text-align: center;">22.7</td>
<td style="text-align: center;">4.58</td>
<td style="text-align: center;">25</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inference-two-means_files/figure-html/unnamed-chunk-16-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16"><img src="inference-two-means_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid"></a></p>
</div>
</div>
</div>
</li>
</ol>
<ol start="17" type="1">
<li>
<p><strong>Chicken diet: casein vs.&nbsp;soybean.</strong> Casein is a common weight gain supplement for humans. Does it have an effect on chickens? An experiment was conducted to measure and compare the effectiveness of various feed supplements on the growth rate of chickens. Newly hatched chicks were randomly allocated into six groups, and each group was given a different feed supplement. In this exercise we consider chicks that were fed casein and soybean. Assume that the conditions for conducting inference using mathematical models are met, and using the data provided below, test the hypothesis that the average weight of chickens that were fed casein is different than the average weight of chickens that were fed soybean. If your hypothesis test yields a statistically discernible result, discuss whether the higher average weight of chickens can be attributed to the casein diet. <span class="citation" data-cites="data:chickwts">(<a href="references.html#ref-data:chickwts" role="doc-biblioref">McNeil 1977</a>)</span></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Feed type</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">casein</td>
<td style="text-align: center;">323.58</td>
<td style="text-align: center;">64.43</td>
<td style="text-align: center;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">soybean</td>
<td style="text-align: center;">246.43</td>
<td style="text-align: center;">54.13</td>
<td style="text-align: center;">14</td>
</tr>
</tbody>
</table>
</div>
</div>
</li>
</ol>
<ol start="18" type="1">
<li>
<p><strong>Fuel efficiency on the highway.</strong> Each year the US Environmental Protection Agency (EPA) releases fuel economy data on cars manufactured in that year. Below are summary statistics on fuel efficiency (in miles/gallon) from random samples of cars with manual and automatic transmissions manufactured in 2021. Do these data provide strong evidence of a difference between the average fuel efficiency of cars with manual and automatic transmissions in terms of their average highway mileage? <span class="citation" data-cites="data:epa2021">(<a href="references.html#ref-data:epa2021" role="doc-biblioref">US DOE EPA 2021</a>)</span></p>
<div class="cell quarto-layout-panel" data-layout-ncol="2">
<div class="quarto-layout-row">
<table class="table table-striped table-condensed caption-top table-sm small">
<thead><tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">HIGHWAY</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Mean</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">n</th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Automatic</td>
<td style="text-align: center;">23.7</td>
<td style="text-align: center;">3.90</td>
<td style="text-align: center;">25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manual</td>
<td style="text-align: center;">30.9</td>
<td style="text-align: center;">5.13</td>
<td style="text-align: center;">25</td>
</tr>
</tbody>
</table>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><a href="inference-two-means_files/figure-html/unnamed-chunk-18-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17"><img src="inference-two-means_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid"></a></p>
</div>
</div>
</div>
</li>
</ol>
<ol start="19" type="1">
<li>
<strong>Gaming, distracted eating, and intake.</strong> A group of researchers who are interested in the possible effects of distracting stimuli during eating, such as an increase or decrease in the amount of food consumption, monitored food intake for a group of 44 patients who were randomized into two equal groups. The treatment group ate lunch while playing solitaire, and the control group ate lunch without any added distractions. Patients in the treatment group ate 52.1 grams of biscuits, with a standard deviation of 45.1 grams, and patients in the control group ate 27.1 grams of biscuits, with a standard deviation of 26.4 grams. Do these data provide convincing evidence that the average food intake (measured in amount of biscuits consumed) is different for the patients in the treatment group compared to the control group? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Oldham:2011">(<a href="references.html#ref-Oldham:2011" role="doc-biblioref">Oldham-Cooper et al. 2011</a>)</span>
</li>
</ol>
<ol start="20" type="1">
<li>
<strong>Gaming, distracted eating, and recall.</strong> A group of researchers who are interested in the possible effects of distracting stimuli during eating, such as an increase or decrease in the amount of food consumption, monitored food intake for a group of 44 patients who were randomized into two equal groups. The 22 patients in the treatment group who ate their lunch while playing solitaire were asked to do a serial-order recall of the food lunch items they ate. The average number of items recalled by the patients in this group was 4. 9, with a standard deviation of 1.8. The average number of items recalled by the patients in the control group (no distraction) was 6.1, with a standard deviation of 1.8. Do these data provide strong evidence that the average numbers of food items recalled by the patients in the treatment and control groups are different? Assume that conditions for conducting inference using mathematical models are satisfied. <span class="citation" data-cites="Oldham:2011">(<a href="references.html#ref-Oldham:2011" role="doc-biblioref">Oldham-Cooper et al. 2011</a>)</span>
</li>
</ol>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-Adolph:1987" class="csl-entry" role="listitem">
Adolph, S. C. 1987. <span>“Physiological and Behavioral Ecology of the Lizards <span><em>Sceloporus Occidentalis</em></span> and <span><em>Sceloporus Graciosus</em></span>.”</span> PhD thesis, University of Washington, Seattle, Washington.
</div>
<div id="ref-data:chickwts" class="csl-entry" role="listitem">
McNeil, D. R. 1977. <span>“Interactive Data Analysis: A Practical Primer.”</span>
</div>
<div id="ref-Menard:2005" class="csl-entry" role="listitem">
Ménard, C., A. A. Hagège, O. Agbulut, M. Barro, M. C. Morichetti, C. Brasselet, A. Bel, et al. 2005. <span>“Transplantation of Cardiac-Committed Mouse Embryonic Stem Cells to Infarcted Sheep Myocardium: A Preclinical Study.”</span> <em>The Lancet</em> 366 (9490): 1005–12.
</div>
<div id="ref-Oldham:2011" class="csl-entry" role="listitem">
Oldham-Cooper, R. E., C. A. Hardman, C. E. Nicoll, P. J. Rogers, and J. M. Brunstrom. 2011. <span>“Playing a Computer Game During Lunch Affects Fullness, Memory for Lunch, and Later Snack Intake.”</span> <em>The American Journal of Clinical Nutrition</em> 93 (2): 308. <a href="https://doi.org/10.3945/ajcn.110.004580">https://doi.org/10.3945/ajcn.110.004580</a>.
</div>
<div id="ref-Othman:2023" class="csl-entry" role="listitem">
Othman, S., N. Hassan, and A. Mohamed. 2023. <span>“Effectiveness of Mindfulness-Based Interventions on Burnout and Self-Compassion Among Critical Care Nurses Caring for Patients with COVID-19: A Quasi-Experimental Study.”</span> <em>BMC Nursing</em> 22: 35.
</div>
<div id="ref-data:epa2021" class="csl-entry" role="listitem">
US DOE EPA. 2021. <span>“<span>Fuel Economy, 2021 Data File</span>.”</span> <a href="https://www.openintro.org/go?id=textbook-fueleconomy-2021">https://www.openintro.org/go?id=textbook-fueleconomy-2021</a>.
</div>
<div id="ref-ggplot2" class="csl-entry" role="listitem">
Wickham, H. 2016. <em><span class="nocase">ggplot2</span>: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
</div>
</section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1"><p><span class="math inline">\(H_0:\)</span> the exams are equally difficult, on average. <span class="math inline">\(\mu_A - \mu_B = 0.\)</span> <span class="math inline">\(H_A:\)</span> one exam was more difficult than the other, on average. <span class="math inline">\(\mu_A - \mu_B \neq 0.\)</span><a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Since the exams were shuffled, the “treatment” in this case was randomly assigned, so independence within and between groups is satisfied. The summary statistics suggest the data are roughly symmetric about the mean, and the min/max values do not suggest any outliers of concern.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The point estimate of the population difference (<span class="math inline">\(\bar{x}_{ESC} - \bar{x}_{Control}\)</span>) is 7.83.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The point estimate of the population difference (<span class="math inline">\(\bar{x}_{n} - \bar{x}_{s}\)</span>) is 0.59.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p><span class="math inline">\(SE(\bar{x}_{n} - \bar{x}_{s}) = \sqrt{s^2_{n}/ n_{n} + s^2_{s}/n_{s}} = \sqrt{1.23^2/867 + 1.60^2/114} = 0.16\)</span><a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>You can watch an episode of John Oliver on <a href="youtu.be/6UsHHOCH4q8"><em>Last Week Tonight</em></a> to explore the present day offenses of the tobacco industry. Please be aware that there is some adult language.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>The <a href="https://ggplot2.tidyverse.org/reference/diamonds.html"><code>diamonds</code></a> data used in this exercise can be found in the <a href="http://ggplot2.tidyverse.org/"><strong>ggplot2</strong></a> R package.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn8"><p>The <a href="http://openintrostat.github.io/openintro/reference/lizard_run.html"><code>lizard_run</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref8" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn9"><p>The <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/chickwts.html"><code>chickwts</code></a> data used in this exercise can be found in the <a href="https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/00Index.html"><strong>datasets</strong></a> R package.<a href="#fnref9" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn10"><p>The <a href="http://openintrostat.github.io/openintro/reference/epa2021.html"><code>epa2021</code></a> data used in this exercise can be found in the <a href="http://openintrostat.github.io/openintro"><strong>openintro</strong></a> R package.<a href="#fnref10" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./inference-one-mean.html" class="pagination-link" aria-label="Inference for a single mean">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Inference for a single mean</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./inference-paired-means.html" class="pagination-link" aria-label="Inference for comparing paired means">
        <span class="nav-page-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Inference for comparing paired means</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
<p>This is IMS2e!</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/openintrostat/ims/edit/main/inference-two-means.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/openintrostat/ims/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer><script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>


</body></html>