# Introduction to data {.unnumbered}

The first part of the book will introduce you to data, their properties, how they are collected, and the structure of the design used for the study.
Different data and settings lead to different **types** of conclusions, so you'll always want to keep in mind the data provenance, especially as you move on to modeling and inference.

-   In [Chapter -@sec-data-hello] you'll be introduced to tidy data, an important structure for describing, visualizing, and analyzing data.

-   In [Chapter -@sec-data-design] the focus is on study design.
    In particular, the critical distinction between random sampling and randomization is made.

-   [Chapter -@sec-data-applications] includes an application on the Paralympics case study where the topics from the Introduction to data part of the book are fully developed.

We recommend you come back to review this foundational part after you cover each new part in the textbook.
In particular, it is worthwhile to consider @fig-randsampValloc in all of the inferential settings you cover.
Each dataset you analyze will have a slightly different context which will require thoughtful consideration of the appropriate conclusions.
