# Regression modeling {#sec-model .unnumbered}

Among the most ubiquitous methods used to model a response variable given one or more predictor variables is regression. Linear regression is most commonly used when the response variable is numeric (and even better, continuous); logistic regression is used when the response variable is binary.

- In [Chapter -@sec-model-slr] you are introduced to finding a best fit line using a least squares method. Additionally, the correlation and coefficient of determination are presented as a way to describe the strength of the linear model.
- In [Chapter -@sec-model-mlr] the linear model is expanded to include multiple predictor variables in a single model. We discuss the benefits as well as the pitfalls that can arise when using multiple predictors.
- In [Chapter -@sec-model-logistic] the response variable is constrained to be binary which changes the entire structure and produces the logistic regression model. The similarities between the regression models (namely, linear combinations of the predictors) are presented. Additionally, you see that the logistic regression predictions are now probabilities.
- [Chapter -@sec-model-application] includes an application on the Houses for sale case study where the topics from this part of the book are fully developed.

Later on in the textbook, in the [Inferential modeling](https://openintro-ims2.netlify.app/inferential-modeling) part, we will consider how a regression model built on a sample may or may not describe a particular population of interest.