# Statistical inference {#sec-inference .unnumbered}

While the previous part of the textbook, [Foundations of inference](https://openintro-ims2.netlify.app/foundations-of-inference), introduces the core of statistical inference, this part provides details for applying statistical inference in particular settings.
Understanding the specific nuances given for different inferential methods can be helpful in communicating the resulting analyses.

-   [Chapter -@sec-inference-one-prop] provides specific details about inference for a single proportion.

-   [Chapter -@sec-inference-two-props] provides specific details about inference for comparing two proportions.

-   [Chapter -@sec-inference-tables] provides specific details about inference for two-way tables.

-   [Chapter -@sec-inference-one-mean] provides specific details about inference for a single mean.

-   [Chapter -@sec-inference-two-means] provides specific details about inference for comparing two independent means.

-   [Chapter -@sec-inference-paired-means] provides specific details about inference for comparing paired means.

-   [Chapter -@sec-inference-many-means] provides specific details about inference for comparing many means.

-   [Chapter -@sec-inference-applications] includes an application on the Redundant adjectives case study where the topics from this part of the book on means are fully developed.

After working through the details in this part, you should have a good sense for how inferential methods are similar and different when applied to different data structures.
Additionally, you should be able to apply both computational methods as well as mathematical techniques to the inference problem at hand.
