1.  **True / False.** 
Determine if the following statements are true or false. 
If false, explain why.

    a.  A correlation coefficient of -0.90 indicates a stronger linear relationship than a correlation of 0.5.

    b.  Correlation is a measure of the association between any two variables.

1.  **Trees.** 
The scatterplots below show the relationship between height, diameter, and volume of timber in 31 felled black cherry trees. 
The diameter of the tree is measured 4.5 feet above the ground.^[The data used in this exercise can be found in the **datasets** package: [`trees`](https://stat.ethz.ch/R-manual/R-devel/library/datasets/html/trees.html).]

    ```{r}
    library(ggplot2)
    library(openintro)
    library(patchwork)
    
    p_1 <- ggplot(datasets::trees, aes(x = Height, y = Volume)) +
      geom_point(color = COL["blue","full"]) +
      theme_minimal() +
      labs(x = "Height (feet)", y = "Volume (cubic feet)")
    
    p_2 <- ggplot(datasets::trees, aes(x = Girth, y = Volume)) +
      geom_point(color = COL["blue","full"]) +
      theme_minimal() +
      labs(x = "Diameter (inches)", y = "Volume (cubic feet)")
    
    p_1 + p_2
    ```

    a.  Describe the relationship between volume and height of these trees.

    b.  Describe the relationship between volume and diameter of these trees.

    c.  Suppose you have height and diameter measurements for another black cherry tree. Which of these variables would be preferable to use to predict the volume of timber in this tree using a simple linear regression model? Explain your reasoning.
