1. \(a) Two-way table is shown below. (b-i) $E_{row_1, col_1} = \frac{(row~1~total)\times(col~1~total)}{table~total} = 35$. This is lower than the observed value. (b-ii) $E_{row_2, col_2} = \frac{(row~2~total)\times(col~2~total)}{table~total} = 115$. This is lower than the observed value.

    ```{r}
    library(tidyverse)
    library(kableExtra)
    
    tribble(
      ~Treatment, ~Yes, ~No, ~Total,
      "Patch + support group", 40, 110, 150,
      "Only patch", 30, 120, 150,
      "Total", 70, 230, 300
    ) %>%
      kbl(linesep = "", booktabs = TRUE, align = "lrrr") %>%
      kable_styling(bootstrap_options = c("striped", "condensed"), 
                    latex_options = "HOLD_position", 
                    full_width = FALSE) %>%
      column_spec(1, width = "10em") %>%
      column_spec(2:4, width = "5em") %>%
      add_header_above(c(" " = 1, "Quit" = 2, " " = 1))
    ```
\addtocounter{enumi}{1}

1. \(a) Sun = 0.343, Partial = 0.325, Shade = 0.331. (b) For each, the numbers are listed in the order sun, partial, and shade: Desert (40,9, 38,7, 39.4), Mountain (36.7, 34.8, 35.5), Valley (36.4, 34.5, 35.1). (c) Yes. (d) We can't evaluate the association without a formal test.
\addtocounter{enumi}{1}

1. The original dataset will have a higher Chi-squared statistic than the randomized dataset.
\addtocounter{enumi}{1}

1. \(a) The two variables are independent. (b) The randomized Chi-squared values range from zero to approximately 15. (c) The null hypothesis is that the variables are independent; the alternative hypothesis is that the variables are associated. The p-value is extremely small. The habitat provides information about the likelihood of being in the different sunshine states.
\addtocounter{enumi}{1}

1. \(a) The two variables are independent. (b) The randomized Chi-squared values range from zero to approximately 25. (c) The null hypothesis is that the variables are independent; the alternative hypothesis is that the variables are associated. The p-value is around 0. There is convincing evidence to claim that site and sunlight preference are associated. (d) With larger sample sizes, the power (the probability of rejecting $H_0$ when $H_A$ is true) is higher.
\addtocounter{enumi}{1}

1. \(a) False. The Chi-square distribution has one parameter called degrees of freedom. (b) True. (c) True. (d) False. As the degrees of freedom increases, the shape of the Chi-square distribution becomes more symmetric.
\addtocounter{enumi}{1}

1. The hypotheses are $H_0:$ Sleep levels and profession are independent. $H_A:$ Sleep levels and profession are associated. The observations are independent and the sample sizes are large enough to conduct a Chi-square test of independence. The Chi-square statistic is 1 with 2 degrees of freedom. The p-value is 0.6. Since the p-value is high (default to alpha = 0.05), we fail to reject $H_0$. The data do not provide convincing evidence of an association between sleep levels and profession.
\addtocounter{enumi}{1}

1. \(a) $H_0$: The age of Los Angeles residents is independent of shipping carrier preference variable. $H_A$: The age of Los Angeles residents is associated with the shipping carrier preference variable. (b) The conditions are not satisfied since some expected counts are below 5.
\addtocounter{enumi}{1}
