1. \(a) Positive association: mammals with longer gestation periods tend to live longer as well. (b) Association would still be positive. (c) No, they are not independent. See part (a).
\addtocounter{enumi}{1}

1. The graph below shows a ramp up period. There may also be a period of exponential growth at the start before the size of the petri dish becomes a factor in slowing growth.

    ```{r out.width="30%"}
    set.seed(2406)
    par(mar = c(1.5, 1.5, 0.5, 0.5), mgp = c(0.3, 0.7, 0),  mfrow = c(1,1), cex.lab = 1.5)
    curve(-1*dexp(x, rate = 4), lwd = 2,
          xlab = "time", ylab = "number of bacteria cells", axes = FALSE)
    box()
    ```
\addtocounter{enumi}{1}

1. \(a) Decrease: the new score is smaller than the mean of the 24 previous scores. (b) Calculate a weighted mean. Use a weight of 24 for the old mean and 1 for the new mean: $(24\times 74 + 1\times64)/(24+1) = 73.6$. (c) The new score is more than 1 standard deviation away from the previous mean, so increase.
\addtocounter{enumi}{1}

1. Any 10 employees whose average number of days off is between the minimum and the mean number of days off for the entire workforce at this plant.
\addtocounter{enumi}{1}

1. \(a) Dist B has a higher mean since $20 > 13$, and a higher standard deviation  since 20 is further from the rest of the data than 13. (b) Dist A has a higher mean since $-20 > -40$, and Dist B has a higher standard deviation since -40 is farther away from the rest of the data than -20. (c) Dist B has a higher mean since all values in this Dist Are higher than those in Dist A, but both distribution have the same standard deviation  since they are equally variable around their respective means. (d) Both distributions have the same mean since they're both centered at 300, but  Dist B has a higher standard deviation since the observations are farther from the mean than in Dist A.
\addtocounter{enumi}{1}

1. \(a) About 30. (b) Since the distribution is right skewed the mean is higher than the median. (c) Q1: between 15 and 20, Q3: between 35 and 40, IQR: about 20. (d) Values that are considered to be unusually low or high lie more than 1.5$\times$IQR away from the quartiles. Upper fence: Q3 + 1.5 $\times$ IQR = $37.5 + 1.5 \times 20 = 67.5$; Lower fence: Q1 - 1.5 $\times$ IQR = $17.5 + 1.5 \times 20 =  -12.5$; The lowest AQI recorded is not lower than 5 and the highest AQI recorded is not higher than 65, which are both within the fences. Therefore none of the days in this sample would be considered to have an unusually low or high AQI.
\addtocounter{enumi}{1}

1. The histogram shows that the distribution is bimodal, which is not apparent in the box plot. The box plot makes it easy to identify more precise values of observations outside of the whiskers.
\addtocounter{enumi}{1}

1. \(a) Right skewed, there is a natural boundary at 0 and only a few people have many pets. Center: median, variability: IQR. (b) Right skewed, there is a natural boundary at 0 and only a few people live a very long distance from work. Center: median, variability: IQR. (c) Symmetric. Center: mean, variability: standard deviation. (d) Left skewed. Center: median, variability: IQR. (e) Left skewed. Center: median, variability: IQR.
\addtocounter{enumi}{1}

1. No, we would expect this distribution to be right skewed. There are two reasons for this: there is a natural boundary at 0 (it is not possible to watch less than 0 hours of TV) and the standard deviation of the distribution is very large compared to the mean.
\addtocounter{enumi}{1}

1. No, the outliers are likely the maximum and the minimum of the distribution so a statistic based on these values cannot be robust to outliers.
\addtocounter{enumi}{1}

1. The 75th percentile is 82.5, so 5 students will get an A. Also, by definition 25% of students will be above the 75th percentile.
\addtocounter{enumi}{1}

1. \(a) If $\frac{\bar{x}}{median} = 1$, then $\bar{x} = median$. This is most likely to be the case for symmetric distributions. (b) If $\frac{\bar{x}}{median} < 1$, then $\bar{x} < median$. This is most likely to be the case for left skewed distributions, since the mean is affected (and pulled down) by the lower values more so than the median. (c) If $\frac{\bar{x}}{median} > 1$, then $\bar{x} > median$. This is most likely to be the case for right skewed distributions, since the mean is affected (and pulled up) by the higher values more so than the median.
\addtocounter{enumi}{1}

1. \(a) The distribution of percentage of population that is Hispanic is extremely right skewed with majority of counties with less than 10% Hispanic residents. However, there are a few counties that have more than 90% Hispanic population. It might be preferable to, in certain analyses, to use the log-transformed values since this distribution is much less skewed. (b) The map reveals that counties with higher proportions of Hispanic residents are clustered along the Southwest border, all of New Mexico, a large swath of Southwest Texas, the bottom two-thirds of California, and in Southern Florida. In the map all counties with more than 40% of Hispanic residents are indicated by the darker shading, so it is impossible to discern how high Hispanic percentages go. The histogram reveals that there are counties with over 90% Hispanic residents. The histogram is also useful for estimating measures of center and spread. (c) Both visualizations are useful, but if we could only examine one, we should examine the map since it explicitly ties geographic data to each county's percentage.
\addtocounter{enumi}{1}
