1.  **Air pollution and birth outcomes, scope of inference.**
Researchers collected data to examine the relationship between air pollutants and preterm births in Southern California. 
During the study air pollution levels were measured by air quality monitoring stations. 
Length of gestation data were collected on 143,196 births between the years 1989 and 1993, and air pollution exposure during gestation was calculated for each birth. [@Ritz+Yu+Chapa+Fruin:2000]

    a.  Identify the population of interest and the sample in this study.

    b.  Comment on whether or not the results of the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.

1.  **Cheaters, scope of inference.**
Researchers studying the relationship between honesty, age and self-control conducted an experiment on 160 children between the ages of 5 and 15. 
The researchers asked each child to toss a fair coin in private and to record the outcome (white or black) on a paper sheet, and said they would only reward children who report white. 
Half the students were explicitly told not to cheat and the others were not given any explicit instructions. Differences were observed in the cheating rates in the instruction and no instruction groups, as well as some differences across children's characteristics within each group. [@Bucciol:2011]

    a.  Identify the population of interest and the sample in this study.

    b.  Comment on whether or not the results of the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.

1.  **Buteyko method, scope of inference.**
The Buteyko method is a shallow breathing technique developed by Konstantin Buteyko, a Russian doctor, in 1952. Anecdotal evidence suggests that the Buteyko method can reduce asthma symptoms and improve quality of life. 
In a scientific study to determine the effectiveness of this method, 600 asthma patients aged 18-69 who relied on medication for asthma treatment were recruited and randomly assigned to two groups: one practiced the Buteyko method and the other did not. 
Those in the Buteyko group experienced, on average, a significant reduction in asthma symptoms and an improvement in quality of life. [@McDowan:2003]

    a.  Identify the population of interest and the sample in this study.

    2.  Comment on whether or not the results of the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.

1.  **Stealers, scope of inference.** 
In a study of the relationship between socio-economic class and unethical behavior, 129 University of California undergraduates at Berkeley were asked to identify themselves as having low or high social-class by comparing themselves to others with the most (least) money, most (least) education, and most (least) respected jobs. 
They were also presented with a jar of individually wrapped candies and informed that the candies were for children in a nearby laboratory, but that they could take some if they wanted. 
After completing some unrelated tasks, participants reported the number of candies they had taken. 
It was found that those who were identified as upper-class took more candy than others. [@Piff:2012]

    a.  Identify the population of interest and the sample in this study.

    b.  Comment on whether or not the results of the study can be generalized to the population, and if the findings of the study can be used to establish causal relationships.

1.  **Relaxing after work.** 
The General Social Survey asked the question, *"After an average work day, about how many hours do you have to relax or pursue activities that you enjoy?"* to a random sample of 1,155 Americans. 
The average relaxing time was found to be 1.65 hours. 
Determine which of the following is an observation, a variable, a sample statistic (value calculated based on the observed sample), or a population parameter.^[The data used in this exercise comes from the [General Social Survey, 2018](https://www.openintro.org/go?id=textbook-gss-data&referrer=ims0_html).]

    a.  An American in the sample.

    b.  Number of hours spent relaxing after an average work day.

    c.  1.65.

    d.  Average number of hours all Americans spend relaxing after an average work day.

1.  **Cats on YouTube.** 
Suppose you want to estimate the percentage of videos on YouTube that are cat videos. 
It is impossible for you to watch all videos on YouTube so you use a random video picker to select 1000 videos for you. 
You find that 2% of these videos are cat videos. 
Determine which of the following is an observation, a variable, a sample statistic (value calculated based on the observed sample), or a population parameter.

    a.  Percentage of all videos on YouTube that are cat videos.

    b.  2%.

    c.  A video in your sample.

    d.  Whether or not a video is a cat video.

1.  **Course satisfaction across sections.** 
A large college class has 160 students. 
All 160 students attend the lectures together, but the students are divided into 4 groups, each of 40 students, for lab sections administered by different teaching assistants. 
The professor wants to conduct a survey about how satisfied the students are with the course, and he believes that the lab section a student is in might affect the student's overall satisfaction with the course.

    a.  What type of study is this?

    b.  Suggest a sampling strategy for carrying out this study.

1.  **Housing proposal across dorms.** 
On a large college campus first-year students and sophomores live in dorms located on the eastern part of the campus and juniors and seniors live in dorms located on the western part of the campus. 
Suppose you want to collect student opinions on a new housing structure the college administration is proposing and you want to make sure your survey equally represents opinions from students from all years.

    a.  What type of study is this?

    b.  Suggest a sampling strategy for carrying out this study.

1.  **Internet use and life expectancy.** 
The following scatterplot was created as part of a study evaluating the relationship between estimated life expectancy at birth (as of 2014) and percentage of internet users (as of 2009) in 208 countries for which such data were available.^[The data used in this exercise can be found in the **openintro** package: [`cia_factbook`](http://openintrostat.github.io/openintro/reference/cia_factbook.html).]
    
    ```{r echo=FALSE, message=FALSE, warning=FALSE}
    library(openintro)
    library(tidyverse)
    library(scales)
    
    ggplot(data = cia_factbook,
           aes(y = life_exp_at_birth,
               x = internet_users/population)) +
        geom_point(color = COL["blue", "full"], alpha = 0.8) +
        scale_x_continuous(
            labels = label_percent(scale = 100),
            limits = c(0, 1)) +
        labs(
            x = "Percent internet users",
            y = "Life expectancy",
            title = "Life expectancy vs. percent internet users", 
            subtitle = "Data from 2014 from the CIA Factbook"
        ) +
        theme_minimal()
    ```

    a.  Describe the relationship between life expectancy and percentage of internet users.

    b.  What type of study is this?

    c.  State a possible confounding variable that might explain this relationship and describe its potential effect.

1.  **Stressed out.** 
A study that surveyed a random sample of otherwise healthy high school students found that they are more likely to get muscle cramps when they are stressed. 
The study also noted that students drink more coffee and sleep less when they are stressed.

    a.  What type of study is this?

    b.  Can this study be used to conclude a causal relationship between increased stress and muscle cramps?

    c.  State possible confounding variables that might explain the observed relationship between increased stress and muscle cramps.

1.  **Evaluate sampling methods.** 
A university wants to determine what fraction of its undergraduate student body support a new $25 annual fee to improve the student union. 
For each proposed method below, indicate whether the method is reasonable or not.

    a.  Survey a simple random sample of 500 students.

    b.  Stratify students by their field of study, then sample 10% of students from each stratum.

    c.  Cluster students by their ages (e.g. 18 years old in one cluster, 19 years old in one cluster, etc.), then randomly sample three clusters and survey all students in those clusters.

1.  **Random digit dialing.** 
The Gallup Poll uses a procedure called random digit dialing, which creates phone numbers based on a list of all area codes in America in conjunction with the associated number of residential households in each area code. 
Give a possible reason the Gallup Poll chooses to use random digit dialing instead of picking phone numbers from the phone book.

1.  **Haters are gonna hate, study confirms.** 
A study published in the *Journal of Personality and Social Psychology* asked a group of 200 randomly sampled men and women to evaluate how they felt about various subjects, such as camping, health care, architecture, taxidermy, crossword puzzles, and Japan in order to measure their attitude towards mostly independent stimuli. 
Then, they presented the participants with information about a new product: a microwave oven. 
This microwave oven does not exist, but the participants didn't know this, and were given three positive and three negative fake reviews. 
People who reacted positively to the subjects on the dispositional attitude measurement also tended to react positively to the microwave oven, and those who reacted negatively tended to react negatively to it. 
Researchers concluded that *"some people tend to like things, whereas others tend to dislike things, and a more thorough understanding of this tendency will lead to a more thorough understanding of the psychology of attitudes."* [@Hepler:2013]

    a.  What are the cases?

    b.  What is (are) the response variable(s) in this study?

    c.  What is (are) the explanatory variable(s) in this study?

    d.  Does the study employ random sampling?

    e.  Is this an observational study or an experiment? Explain your reasoning.

    f.  Can we establish a causal link between the explanatory and response variables?

    g.  Can the results of the study be generalized to the population at large?

1.  **Family size.** 
Suppose we want to estimate household size, where a *"household"* is defined as people living together in the same dwelling, and sharing living accommodations. 
If we select students at random at an elementary school and ask them what their family size is, will this be a good measure of household size? 
Or will our average be biased? 
If so, will it overestimate or underestimate the true value?

1.  **Sampling strategies.** 
A statistics student who is curious about the relationship between the amount of time students spend on social networking sites and their performance at school decides to conduct a survey. 
Various research strategies for collecting data are described below. In each, name the sampling method proposed and any bias you might expect.

    a.  They randomly sample 40 students from the study's population, give them the survey, ask them to fill it out and bring it back the next day.

    b.  They give out the survey only to their friends, making sure each one of them fills out the survey.

    c.  They post a link to an online survey on Facebook and ask their friends to fill out the survey.

    d.  They randomly sample 5 classes and asks a random sample of students from those classes to fill out the survey.

1.  **Reading the paper.** 
Below are excerpts from two articles published in the *NY Times*:

    a.  An article titled *Risks: Smokers Found More Prone to Dementia* states the following. Based on this study, can we conclude that smoking causes dementia later in life? Explain your reasoning. [@news:smokingDementia]

    > "Researchers analyzed data from 23,123 health plan members who participated in a voluntary exam and health behavior survey from 1978 to 1985, when they were 50-60 years old. 23 years later, about 25% of the group had dementia, including 1,136 with Alzheimer's disease and 416 with vascular dementia. After adjusting for other factors, the researchers concluded that pack-a-day smokers were 37% more likely than nonsmokers to develop dementia, and the risks went up with increased smoking; 44% for one to two packs a day; and twice the risk for more than two packs."

    b.  Another article titled *The School Bully Is Sleepy* states the following. A friend of yours who read the article says, *"The study shows that sleep disorders lead to bullying in school children."* Is this statement justified? If not, how best can you describe the conclusion that can be drawn from this study? [@news:bullySleep]

    > "The University of Michigan study, collected survey data from parents on each child's sleep habits and asked both parents and teachers to assess behavioral concerns. About a third of the students studied were identified by parents or teachers as having problems with disruptive behavior or bullying. The researchers found that children who had behavioral issues and those who were identified as bullies were twice as likely to have shown symptoms of sleep disorders."

        
